Special case attempt, redeem, redeemWith in IO and SyncIO
typelevel/cats-effect pull request #1069
Opened 2020-08-09 19:07 UTC by vasilmkd

Resolves #1055.

I checked the bytecode, we still keep the `tableswitch`. I have included the files as proof.
[iobytecode.txt](https://github.com/typelevel/cats-effect/files/5048251/iobytecode.txt)
[synciobytecode.txt](https://github.com/typelevel/cats-effect/files/5048252/synciobytecode.txt)

2020-08-09 22:33 UTC, djspiewak commented
I think it's more important to check the timing. :-) The bytecode will remain tableswitch, but hotspot starts emitting less efficient assembly *for* `tableswitch` at some point.

2020-08-09 22:44 UTC, vasilmkd commented
No worries, I got it.

2020-08-10 05:12 UTC, RaasAhsan commented
I'm certain there will be a performance boost for the special cases, but the question is by how much. And does it hurt performance for the other combinators? I'd like to balance both of those with the growing sizes of the run-loop and the surface area for bugs. I'm reminded by how `guaranteeCase` is special cased in CE2 but exhibits different behavior than if it were implemented in terms of `bracketCase`.

2020-08-10 08:35 UTC, vasilmkd commented
Before:
```
Benchmark                         (size)   Mode  Cnt       Score      Error  Units
AsyncBenchmark.async                 100  thrpt   20   17306.762 ±  129.089  ops/s
AsyncBenchmark.bracket               100  thrpt   20   45306.318 ±  335.720  ops/s
AsyncBenchmark.cancelable            100  thrpt   20   17082.783 ±  385.100  ops/s
AsyncBenchmark.race                  100  thrpt   20    5786.621 ±  184.385  ops/s
AsyncBenchmark.racePair              100  thrpt   20    2471.910 ±   26.048  ops/s
AsyncBenchmark.start                 100  thrpt   20    4156.749 ±  459.760  ops/s
AsyncBenchmark.uncancelable          100  thrpt   20  212709.165 ± 3573.030  ops/s
AttemptBenchmark.errorRaised       10000  thrpt   20    1132.792 ±   20.359  ops/s
AttemptBenchmark.happyPath         10000  thrpt   20    1548.067 ±   58.161  ops/s
DeepBindBenchmark.async            10000  thrpt   20     301.051 ±    9.440  ops/s
DeepBindBenchmark.delay            10000  thrpt   20    3538.446 ±   19.084  ops/s
DeepBindBenchmark.pure             10000  thrpt   20    4284.279 ±   13.700  ops/s
HandleErrorBenchmark.errorRaised   10000  thrpt   20    1945.265 ±    1.895  ops/s
HandleErrorBenchmark.happyPath     10000  thrpt   20    2647.295 ±   18.309  ops/s
MapCallsBenchmark.batch120           N/A  thrpt   20    5546.021 ±  132.684  ops/s
MapCallsBenchmark.batch30            N/A  thrpt   20    3629.625 ±    8.017  ops/s
MapCallsBenchmark.one                N/A  thrpt   20     271.221 ±    1.839  ops/s
MapStreamBenchmark.batch120          N/A  thrpt   20    3764.633 ±   69.979  ops/s
MapStreamBenchmark.batch30           N/A  thrpt   20    1376.310 ±   55.688  ops/s
MapStreamBenchmark.one               N/A  thrpt   20    1483.375 ±   65.414  ops/s
ShallowBindBenchmark.async         10000  thrpt   20     246.260 ±    8.463  ops/s
ShallowBindBenchmark.delay         10000  thrpt   20    3997.139 ±    5.801  ops/s
ShallowBindBenchmark.pure          10000  thrpt   20    4784.682 ±    3.613  ops/s
```

2020-08-10 15:58 UTC, djspiewak commented
> I'm certain there will be a performance boost for the special cases, but the question is by how much. And does it hurt performance for the other combinators? I'd like to balance both of those with the growing sizes of the run-loop and the surface area for bugs. I'm reminded by how guaranteeCase is special cased in CE2 but exhibits different behavior than if it were implemented in terms of bracketCase.

Apparently I completely misread the HotSpot information, and the 17 threshold (which is now 8 in Java 1.8) is the threshold at which the *more* efficient assembly is generated. Below that threshold, it's a chain of conditional jumps; *above* the threshold, it's an array table. So in other words, the only thing we really need to worry about are cache hits on the indirection, which implies that the soft threshold (in terms of number of IO cases) is probably closer to 32 or 64.

None of this invalidates your second point about surface area. I think we really need to ask what cases are *worthwhile* to specialize in terms of runloop complexity. `attempt` seems worth it to me, since it's basically everywhere, but I've never actually seen `redeemWith` in the wild. Maybe that's just selection bias. I think it's at least worth examining the question though. Remember that a lot of these trivially derived combinators (like `redeemWith`) don't actually have law-based tests, meaning that we won't necessarily catch bugs without adding dedicated tests of our own.

2020-08-10 16:00 UTC, vasilmkd commented
For full up to date information:
https://github.com/openjdk/jdk/search?q=MinJumpTableSize&unscoped_q=MinJumpTableSize

This constant seems to be architecture specific.

2020-08-10 16:01 UTC, vasilmkd commented
I saw `redeem` and `redeemWith` specialized in CE2, that's why I included them.

2020-08-10 16:04 UTC, Avasil commented
> attempt seems worth it to me, since it's basically everywhere, but I've never actually seen redeemWith in the wild. Maybe that's just selection bias.

I've seen the opposite and `attempt` is rarely used alone - usually, it is followed with `map` or `flatMap` which is `redeem`. Using `transform(With)` is a good practice with `Future` too. And `redeem` is basically a `fold`.

If I were to choose, I'd implement `redeem` "natively" and use it in `attempt` implementation.

2020-08-10 16:08 UTC, vasilmkd commented
I agree, the `Throwable => Either[Throwable, Any]` and `Any => Either[Throwable, Any]` (`Left(_)` and `Right(_)`) can even be preallocated.

2020-08-10 21:28 UTC, vasilmkd commented
Running benchmarks.

2020-08-11 03:12 UTC, djspiewak requested changes
Okay I'm provisionally alright with overriding these. :-) Particularly since we know we aren't going to fall off a cliff in terms of tableswitch evaluation performance. The runloop complexity is something we really do need to be mindful of, but these are important functions.

2020-08-11 03:12 UTC, djspiewak commented on core/jvm/src/main/java/cats/effect/SyncIOConstants.java
> +}
Minor nit: the other Java source file is formatted with two-space indentation and we may as well be consistent. :-)

2020-08-11 03:12 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    override def redeem[A, B](fa: IO[A])(recover: Throwable => B, f: A => B): IO[B] =
Shouldn't we also override `redeemWith`?

2020-08-11 03:12 UTC, djspiewak commented on core/shared/src/test/scala/cats/effect/IOSpec.scala
> +    }
I think it would be worth adding a scalacheck test. Something like:

```scala
in ticked { implicit ticker =>
  forAll { (ioa: IO[Int], f: Int => IO[Int], e: Throwable => IO[Int]) =>
    ioa.attempt.flatMap(_.bitraverse(f, e)) === ioa.redeemWith(f, e)
  }
}
```

And maybe something similar for `redeem` and `attempt`. Just because I don't trust unit tests on this sort of thing. :-D

2020-08-11 03:12 UTC, djspiewak commented on core/shared/src/test/scala/cats/effect/SyncIOSpec.scala
> +    }
Similarly property tests here.

2020-08-11 03:12 UTC, djspiewak commented on testkit/shared/src/main/scala/cats/effect/testkit/Generators.scala
> +      "redeem" -> genRedeem[Int, A](deeper)
I don't think it's worth adding these to the abstract generators. Not every implementation will override them the way that we do. If we really want these, we can add them for `IO`/`SyncIO` explicitly in `Runners`

2020-08-11 03:12 UTC, djspiewak commented on testkit/shared/src/main/scala/cats/effect/testkit/Generators.scala
> +    } yield F.redeemWith(fa)(recover, bind)
Similarly here: not worth adding these.

2020-08-11 08:42 UTC, vasilmkd commented on core/jvm/src/main/java/cats/effect/SyncIOConstants.java
> +}
Sorry, this was auto formatted.

2020-08-11 08:46 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    override def redeem[A, B](fa: IO[A])(recover: Throwable => B, f: A => B): IO[B] =
Good catch.

2020-08-11 09:59 UTC, vasilmkd commented on core/shared/src/test/scala/cats/effect/IOSpec.scala
> +    }
Done.

2020-08-11 09:59 UTC, vasilmkd commented on testkit/shared/src/main/scala/cats/effect/testkit/Generators.scala
> +      "redeem" -> genRedeem[Int, A](deeper)
Done.

2020-08-11 09:59 UTC, vasilmkd commented on core/shared/src/test/scala/cats/effect/SyncIOSpec.scala
> +    }
Done.

2020-08-11 09:59 UTC, vasilmkd commented on testkit/shared/src/main/scala/cats/effect/testkit/Generators.scala
> +    } yield F.redeemWith(fa)(recover, bind)
Removed.

2020-08-11 14:49 UTC, djspiewak approved these changes
Looks good to me! Any thoughts, @RaasAhsan? I'm still very convincible on the runloop complexity point. :-)

2020-08-11 14:52 UTC, vasilmkd commented
What is the most complex thing about the runloop in your opinion? I'd like to tackle it. Not in this PR obviously.

2020-08-11 15:16 UTC, djspiewak commented
> What is the most complex thing about the runloop in your opinion? I'd like to tackle it. Not in this PR obviously.

I actually think the runloop is quite nice now, but it's still a comparatively difficult thing to see through in terms of the encoding. Adding and maintaining functionality in the runloop is pretty objectively harder than adding and maintaining it in "purity land" at a higher level, which is a long-winded way of saying that every time we add a primitive algebraic case to `IO`, we increase the complexity of the runloop and we should be careful around that.

Particularly since your recent changes, I feel pretty good about the way the runloop works. There is *always* room for improvement, but I guess what I'm saying is that I don't feel anything is particularly acute right now. :-) The "runloop complexity point" was mostly just a general first-principles concern stemming from increased surface area of functionality.

2020-08-11 17:43 UTC, RaasAhsan commented
I'm still not entirely convinced that we need all 3 of these to be primitive. `redeemWith` is the least common denominator for `redeem` and `attempt`, so some benchmarks where the latter two are implemented in terms of `redeemWith` would shine some light on where the performance boost is coming from. `attempt` does see gains, but I have a feeling most of it is coming from its encoding with one continuation rather than two, but `redeem` and `redeemWith` enjoy the same benefit. There aren't any benchmarks for those yet so I can't really tell how impactful it is.

On runloop complexity, I completely agree that it's in a great spot right now, especially with all the refactoring and cleanup that's been done, and we should try to keep it that way. Every new constructor adds code to the runloop, and it being the impure beast that it is, we have to mentally track how every block of code interacts with another. I'd like to leverage FP principles as much as possible unless there's a solid justification for not doing so.

2020-08-11 17:50 UTC, vasilmkd commented
I'll add the benchmarks.

2020-08-11 18:14 UTC, djspiewak commented
> I'd like to leverage FP principles as much as possible unless there's a solid justification for not doing so.

There's also an element of dogfooding here: if the performance isn't good enough for us to allow derived operations to be implemented *in terms of* other operations, then shouldn't we correct that problem? Users don't have the option of making things primitive when the performance isn't good enough, so the performance *should be* good enough that derived combinators are acceptably fast.

Definitely seeing some comparative benchmarks would be helpful!

2020-08-11 18:15 UTC, vasilmkd commented
They'll be in a separate PR though, I need to first implement the combinators on IO. I'll probably split this one. Working on it.

2020-08-12 18:36 UTC, vasilmkd commented
Please take a look at the benchmark results in #1075. I hope they are clear enough to make a decision on how to continue here.

2020-08-14 02:06 UTC, djspiewak approved these changes

2020-08-14 02:06 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  private[effect] final case class OnCancel[+A](ioa: IO[A], fin: IO[Unit]) extends IO[A] {
Oh lol

2020-08-14 02:06 UTC, merged