Add Poll
typelevel/cats-effect pull request #1074
Opened 2020-08-11 18:20 UTC by vasilmkd

Resolves #1064.

2020-08-11 22:32 UTC, djspiewak requested changes
Very nice! Minor request but otherwise good to go

2020-08-11 22:32 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/concurrent.scala
> +trait Poll[F[_]] extends (F ~> F)
Can you move this to its own file? Arguably `Fiber` should be moved as well, and then **concurrent.scala** can be capitalized to **Concurrent.scala**.

2020-08-11 22:57 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/concurrent.scala
> +trait Poll[F[_]] extends (F ~> F)
Finally! 😆

2020-08-12 00:18 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/concurrent.scala
>  trait Concurrent[F[_], E] extends MonadError[F, E] {
Super-minor thing, but would you mind renaming this file to upper-case?

2020-08-12 00:20 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/concurrent.scala
>  trait Concurrent[F[_], E] extends MonadError[F, E] {
I swear I did. Git failed me. Fixing.

2020-08-12 00:36 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/concurrent.scala
>  trait Concurrent[F[_], E] extends MonadError[F, E] {
`git mv` to the rescue.

2020-08-12 02:13 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/concurrent.scala
>  trait Concurrent[F[_], E] extends MonadError[F, E] {
Yeah Mac and Windows are terrible for that kind of thing :-/

2020-08-12 02:13 UTC, merged