Resolve directory-package inconsistency in cats.effect.kernel.syntax
typelevel/cats-effect pull request #1078
Opened 2020-08-12 10:59 UTC by nikiforo

Syntax objects are placed in cats-effects/kernel/shared/src/main/scala/cats/effect/kernel/syntax/ directory.

The path should corresponds to `cats.effect.kernel.syntax` package, but instead `package cats.effect.syntax` is used.

2020-08-12 14:50 UTC, djspiewak requested changes
I quite like this change! And I do think this is better, but I think we should add a forwarder in the `cats.effect` package object, so that people can still import `cats.effect.syntax` and `cats.effect.implicits` and such. Also I believe that `instances` needs the same treatment!

2020-08-13 14:39 UTC, djspiewak requested changes
Closer! I think this still isn't quite right, sorry. :-(

So what I *think* we should have is the following:

- [x] All the syntax and instances should be defined under the `cats.effect.kernel` package
- [ ] `cats.effect.kernel.implicits`, `cats.effect.kernel.instances`, and `cats.effect.kernel.syntax` should all exist in the **kernel** project
- [ ] `cats.effect.implicits`, `cats.effect.instances`, and `cats.effect.syntax` should *also* exist, but in the **core** package. They should be defined as objects extending the appropriate `kernel` things, which gives us the binary-compatible flexibility to add **core**-specific syntax/instances/etc down the line

Sorry for being unclear!

2020-08-14 11:10 UTC, nikiforo commented
Wow! Thanks a lot for such a thorough explanation!

Do we still need a `package object syntax` under `cats.effect.kernel` package? It's used in `SyntaxSpec` so I assume that it should be preserved.

2020-08-14 14:14 UTC, djspiewak commented
> Do we still need a package object syntax under cats.effect.kernel package? It's used in SyntaxSpec so I assume that it should be preserved.

Yep! I believe we do still need that. We probably also need a similar one in the `cats.effect` package.

2020-08-14 17:19 UTC, djspiewak requested changes
Almost there! There are some unnecessary identity forwarder traits in **core** now. I think removing those and having the objects directly inherit from the **kernel** versions is the right thing to do.

Basically what I'm thinking here is that it's very unlikely that **core** would want to introduce new syntax or instances for (say) `Temporal`. However, it's very possible that **core** may want to introduce new syntax or instances for **core**-specific things (like `IO`), and we need everything that's in **kernel** to be *forwarded* along to **core**, so that means we need the objects to inherit from the **kernel** traits, but we don't need **core**-specific variants of the **kernel** traits. Does that make some sense?

Sorry I'm doing a bad job of explaining this. This is a really great change! Really great. :-)

2020-08-14 17:19 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/instances/ConcurrentInstances.scala
> +trait ConcurrentInstances extends kernel.instances.ConcurrentInstances
I don't think we actually need `ConcurrentInstances` to be mirrored here, though that's an interesting thought. We might add *other* instances, but basically the `all` and `concurrent` in `cats.effect.instances` can just directly refer to `kernel.instances.ConcurrentInstances`

2020-08-14 17:19 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/instances/AllInstances.scala
> +trait AllInstances extends ConcurrentInstances
I think this can just directly extend `kernel.instances.ConcurrentInstances`, since we won't be adding new instances for `Concurrent` specifically in **core**

2020-08-14 17:19 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/syntax/AllSyntax.scala
> +    with EffectSyntax
I think these should just extend the `kernel.syntax.*` traits, since we aren't adding new (e.g.) `AsyncSyntax` that is specific to **core**, but we might add new syntax for other things.

2020-08-14 17:19 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/syntax/AsyncSyntax.scala
> +trait AsyncSyntax extends kernel.syntax.AsyncSyntax
Much like `ConcurrentInstances`, I don't think this is necessary here.

2020-08-14 17:19 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/syntax/package.scala
> +  object effect extends EffectSyntax
These should all just extend `kernel.syntax.*`

2020-08-14 20:22 UTC, nikiforo commented
Great thanks for the patience :-)

2020-08-14 20:41 UTC, djspiewak approved these changes
Outstanding! Thank you!

2020-08-14 20:41 UTC, merged