Add fork join benchmark
typelevel/cats-effect pull request #1095
Opened 2020-08-18 14:16 UTC by vasilmkd

Setting up a benchmark for #1025.

2020-08-18 14:58 UTC, djspiewak approved these changes

2020-08-18 15:45 UTC, vasilmkd commented
```
Benchmark                               (size)   Mode  Cnt  Score   Error    Units
ForkJoinBenchmark.async                1000000  thrpt   20  0.969 ± 0.019  ops/min
ForkJoinBenchmark.asyncTooManyThreads  1000000  thrpt   20  1.069 ± 0.043  ops/min
```

2020-08-18 17:34 UTC, djspiewak commented
> ops/min

LOL!

2020-08-18 17:43 UTC, vasilmkd commented
Yeah, it's pretty huge. I set it to minutes, otherwise the nominal value is too low and hard to compare.

2020-08-19 00:00 UTC, djspiewak reviewed
Okay so this is proof positive that we want to go in this direction. :-)

I left some thoughts on the general architecture but I left the code alone for now. It looks really really good. I think if it's *possible* for us to move the divergence point up into `IORuntime`, we'll gain a lot more VM-specific control over it, but if we can't do that… we'll find a way to make it work I'm sure. :-)

Let's do this.

2020-08-19 00:00 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +          // println("WTF")
😂

2020-08-19 00:00 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +  private[effect] var queue: WorkQueue = _
So I really firmly believe that what we should actually do here is keep the `ExecutionContext`, but add an *additional* var here which is the `IOExecutionContext` or `WorkStealingPool` or whatever it is. Actually just having hte `WorkQueue` alone is maybe enough. Not sure. Need to read more.

Anyway, this will be `null` most of the time, but we do an `isInstanceOf[WorkStealingPool]` in the constructor and also in `EvalOn` below to populate it. Then we have one bit of branching in `cede` (and similar) which first tries the `WorkStealingPool`, and then falls back to the `ExecutionContext` if it has to. This should pipeline optimize quite well since it'll be the common case.

I could be wrong that this is ideal, btw :-)

Anyway, what this *allows* us to do is isolate this to just `IORuntime` on the JVM. So we don't have to worry about ScalaJS or `TestContext` or custom `IORuntime`s, and instead just make `WorkStealingPool` the default executor on the JVM.

2020-08-19 00:00 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/CircularBuffer.scala
> +private final class CircularBuffer(private[this] val logSize: Int) {
Very nice

2020-08-19 00:00 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/WorkQueue.scala
> +    val t = top.get()
Random thought for future: I wish we could get away without this memory barrier.

2020-08-19 00:00 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +        Thread.`yield`()
LOL

2020-08-19 00:07 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/unsafe/CircularBuffer.scala
> +private final class CircularBuffer(private[this] val logSize: Int) {
I will definitely add the correct attributions. This is an implementation of the pseudo code found here:
https://www.dre.vanderbilt.edu/~schmidt/PDF/work-stealing-dequeue.pdf

2020-08-19 00:09 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +          // println("WTF")
This alone is a 2x improvement.

2020-08-19 00:13 UTC, vasilmkd commented
The initial results are in:
```
Benchmark                 (size)   Mode  Cnt  Score   Error    Units
ForkJoinBenchmark.async  1000000  thrpt   20  5.208 ± 0.188  ops/min
```

2020-08-19 00:15 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/unsafe/CircularBuffer.scala
> +private final class CircularBuffer(private[this] val logSize: Int) {
I like this, going to change the `traceBufferSize` to use that, eliminates a ton of edge cases

2020-08-19 00:23 UTC, RaasAhsan commented
This is looking awesome, great work! I'm going to take a closer look when I get the chance

2020-08-19 22:24 UTC, vasilmkd commented
After the simple parking of fibers:
```
Benchmark                               (size)   Mode  Cnt  Score   Error    Units
ForkJoinBenchmark.async                1000000  thrpt   20  4.653 ± 0.134  ops/min
ForkJoinBenchmark.asyncTooManyThreads  1000000  thrpt   20  5.114 ± 0.183  ops/min
```

The 256 thread benchmark is now under control and shows encouraging performance.

2020-08-20 11:02 UTC, vasilmkd commented
Full benchmark results:
```
Benchmark                          (size)   Mode  Cnt       Score      Error    Units
AsyncBenchmark.async                  100  thrpt   20   16063.131 ±   91.230    ops/s
AsyncBenchmark.bracket                100  thrpt   20   45519.524 ±  298.862    ops/s
AsyncBenchmark.cancelable             100  thrpt   20   16283.249 ±  208.644    ops/s
AsyncBenchmark.race                   100  thrpt   20    2550.818 ±   19.127    ops/s
AsyncBenchmark.racePair               100  thrpt   20    5078.696 ±   62.834    ops/s
AsyncBenchmark.start                  100  thrpt   20    2395.364 ±    9.273    ops/s
AsyncBenchmark.uncancelable           100  thrpt   20  214740.299 ± 4927.649    ops/s
AttemptBenchmark.errorRaised        10000  thrpt   20    1653.779 ±   16.853    ops/s
AttemptBenchmark.happyPath          10000  thrpt   20    2353.118 ±    4.356    ops/s
DeepBindBenchmark.delay             10000  thrpt   20    3671.460 ±   22.995    ops/s
DeepBindBenchmark.pure              10000  thrpt   20    4431.950 ±   65.021    ops/s
ForkJoinBenchmark.async           1000000  thrpt   20       4.746 ±    0.159  ops/min
HandleErrorBenchmark.errorRaised    10000  thrpt   20    1957.198 ±    3.165    ops/s
HandleErrorBenchmark.happyPath      10000  thrpt   20    2597.567 ±    8.190    ops/s
MapCallsBenchmark.batch120            N/A  thrpt   20    5773.317 ±  177.136    ops/s
MapCallsBenchmark.batch30             N/A  thrpt   20    3742.733 ±    5.323    ops/s
MapCallsBenchmark.one                 N/A  thrpt   20     249.812 ±    1.368    ops/s
MapStreamBenchmark.batch120           N/A  thrpt   20    3811.856 ±    8.332    ops/s
MapStreamBenchmark.batch30            N/A  thrpt   20    1355.331 ±   35.905    ops/s
MapStreamBenchmark.one                N/A  thrpt   20    1425.313 ±    3.810    ops/s
RedeemBenchmark.errorRaised         10000  thrpt   20    1205.340 ±   86.063    ops/s
RedeemBenchmark.happyPath           10000  thrpt   20    1515.032 ±   14.920    ops/s
RedeemWithBenchmark.errorRaised     10000  thrpt   20    1639.424 ±  103.909    ops/s
RedeemWithBenchmark.happyPath       10000  thrpt   20    2106.245 ±    2.189    ops/s
ShallowBindBenchmark.delay          10000  thrpt   20    3980.231 ±   11.426    ops/s
ShallowBindBenchmark.pure           10000  thrpt   20    4548.748 ±  160.515    ops/s
```

2020-08-20 20:17 UTC, djspiewak requested changes

2020-08-20 20:17 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +  private[this] val size = Runtime.getRuntime().availableProcessors()
Shouldn't this be passed in as a parameter? That would allow us to continue testing the "too many threads" case in the benchmark.

2020-08-20 20:17 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +    val runtime = IORuntime(this, blocking, scheduler, () => ())
Shouldn't we allocate this just once and hold onto it? Or even better, we could actually be passed it during construction as a lazy parameter.

2020-08-20 20:17 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +    println(cause)
This should at least be `cause.printStackTrace()`

2020-08-20 20:17 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +        pool.park(this)
There's a race condition here:

1. All other workers are busy
2. This worker attempts to steal and fails
3. A new task comes in on the external queue (this can't happen with the local queue)
4. The pool puts it into the external queue without awakening any workers (since none are parked)
5. This worker parks itself

The external task will remain outstanding until some other worker wakes up. Maybe that's okay, since the cost of making all of this atomic would be very high.

2020-08-20 20:17 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +    val _ = externalQueue.offer(fiber)
This won't actually wake up any workers. If a new task comes in and all the workers are parked, it will *never* be seen. I believe this should be `executeFiber(fiber)` instead.

2020-08-20 20:17 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +    val fiber = IO.delay(runnable.run()).unsafeRunFiber(true)(_ => ())(runtime)
```suggestion
    val fiber = IO(runnable.run()).unsafeRunFiber(true)(_.fold(reportFailure(_), _ => ())(runtime)
```

Any uncaught exceptions need to be reported.

2020-08-20 20:17 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
> +    (threadPool, { () => () })
I think `WorkStealingThreadPool` needs a `shutdown()` method which interrupts and disposes of the workers.

2020-08-20 20:17 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +private final class WorkStealingThreadPool(
This type is leaked publicly via the `workStealing` method of the `IORuntime` object. I think it makes a lot more sense to keep this private, so I would rather remove `IORuntimeCompanion#workStealing` and just call `new IORuntime` directly.

2020-08-20 20:17 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    IO.EvalOn(this, IOExecutionContext.wrap(ec))
I would prefer we do this wrapping in `IOFiber`. It would avoid the need to *unwrap* in `IO#to` below.

2020-08-20 20:17 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/WorkQueue.scala
> +    bottom += 1
NB this is the only consistent write barrier associated with `reschedule`

2020-08-20 20:17 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/WorkQueue.scala
> +  }
I honestly can't decide if this hack is worth it. The only benchmarks in which we *don't* want to shift are ones which don't touch `cede` or `async`, and if we're not touching `cede` or `async`, then we don't need the sentinel in the first place and `null` should suffice.

2020-08-20 20:17 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +    }
We should think carefully about the fairness implications of this scan. I'm guessing it's fine, but we need to sit down and puzzle it through.

2020-08-20 20:17 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +    blocking: ExecutionContext
Instead, we can have `self0: => IORuntime` along with an instance `var self: IORuntime = _`. Then, in `execute`, we populate `self` with `self0` if `self == null`. This goes along with another change in `IORuntimeCompanion`.

2020-08-20 20:17 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
>        () => ())
```suggestion
    lazy val back: IORuntime = new IORuntime(
      createDefaultComputeExecutionContext(back)._1,
      blocking,
      scheduler,
      () => ())
    
    back
```

2020-08-20 20:17 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
> +    (threadPool, { () => () })
```suggestion
      self: => IORuntime): (WorkStealingThreadPool, () => Unit) = {
    val threadPool = new WorkStealingThreadPool(self)
    (threadPool, { () => () })
```

2020-08-20 20:17 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/WorkQueue.scala
> +  def push(fiber: IOFiber[_]): Unit = {
So, I'm *almost* 100% positive that it's safe to call `push` from whatever threads we want, so long as we don't call multiple `push`es *simultaneously*. As long as we guarantee synchronicity, it's fine.

2020-08-20 21:43 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +  private[this] val size = Runtime.getRuntime().availableProcessors()
Done.

2020-08-20 21:44 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +    println(cause)
Thanks, I have no idea what to put here.

2020-08-20 21:44 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +    val runtime = IORuntime(this, blocking, scheduler, () => ())
Done.

2020-08-20 21:48 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +    val _ = externalQueue.offer(fiber)
Definitely. I had this change, but somehow I lost it. Good catch.

2020-08-20 21:50 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +    val fiber = IO.delay(runnable.run()).unsafeRunFiber(true)(_ => ())(runtime)
Thanks.

2020-08-20 21:59 UTC, vasilmkd commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
> +    (threadPool, { () => () })
Done.

2020-08-20 22:00 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +        pool.park(this)
I guess we'll be leaving this as is for now?

2020-08-20 22:00 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +private final class WorkStealingThreadPool(
Done.

2020-08-20 22:02 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    IO.EvalOn(this, IOExecutionContext.wrap(ec))
That's nicer, I agree.

2020-08-20 22:04 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/unsafe/WorkQueue.scala
> +  }
Removed. We'll be going for automatic shifting and no shifting only in synchronous benchmarks.

2020-08-20 22:04 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +    }
Agreed, I really don't like this.

2020-08-20 22:07 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +    blocking: ExecutionContext
Does a `lazy val self: IORuntime = self0` work?

2020-08-21 08:06 UTC, Avasil commented on core/shared/src/main/scala/cats/effect/unsafe/WorkQueue.scala
> +    val t = top.get()
Noob question: 
How do you guys reason about memory barriers? Is it intuition or is there any good tool for it? I suspect that you're not looking at assembly :D

2020-08-21 08:08 UTC, Avasil commented on core/shared/src/main/scala/cats/effect/unsafe/WorkQueue.scala
> +    bottom += 1
Q: Are volatile writes ensuring that all operations above (buffer changes) are visible?

2020-08-21 13:25 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/WorkQueue.scala
> +    bottom += 1
They do so long as the volatile in question (bottom) is read before the buffer is. But more relevantly, note that steal is the only function called from another thread. The buffer is read and pushed otherwise entirely locally.

2020-08-22 02:33 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/unsafe/CircularBuffer.scala
> +  private[unsafe] val buffer: Array[IOFiber[_]] = new Array[IOFiber[_]](1 << logSize)
We can replace `1 << logSize` with `size`, moving `size` before this to avoid the forward reference.

Another cool trick we can exploit: since we know the buffer size is a power of 2, then `forall n. n % powerOf2 = n & (powerOf2 - 1)`. We can define `val mask = size - 1` and replace instances `index % size` with `index & mask`, which requires fewer ALU instructions to compute.

2020-08-22 02:33 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/unsafe/CircularBuffer.scala
> +  private[unsafe] val buffer: Array[IOFiber[_]] = new Array[IOFiber[_]](1 << logSize)
Also, can we confirm that accesses to `buffer` aren't protected by a memory barrier? I know for a fact that fields declared object-private aren't, but I'm not sure about regular private or package-private fields.

Regular private scope is also more restrictive here but still allows other instances of the class to access the field.

2020-08-22 02:33 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/unsafe/WorkQueue.scala
> +      else fiber
We can just do the buffer get if the CAS operation succeeds

2020-08-22 02:33 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/unsafe/WorkQueue.scala
> +  @volatile private[this] var buffer: CircularBuffer = new CircularBuffer(
I need to think about this more, but I believe we can make `buffer` non-volatile. All assignments to the `buffer` variable occur *before* a write to `bottom`, and all reads from the `buffer` variable occur *after* a read from `bottom`, so a happens-before relationship is established.

2020-08-22 02:33 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +      val index = (from + i + 1) % threadCount
This might be immaterial, but it took me a bit to realize this is the same as `if (index != from)`

2020-08-22 02:33 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +  private[this] def stealFromLocalWorkQueue(): IOFiber[_] =
IMO `stealFromLocalWorkQueue` and `stealFromExternalQueue` don't really sound like stealing

2020-08-22 09:26 UTC, vasilmkd commented
@RaasAhsan thanks for the review. I will address all of these issues, they are really great finds. But first of all, I'd like to arrive at a better implementation for the `WorkerThread` run loop because the current one is really detrimental to `start` performance. The implementation is currently too simple.

2020-08-22 17:31 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/unsafe/WorkQueue.scala
> +      else fiber
Done.

2020-08-24 02:14 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +      val index = (from + i + 1) % threadCount
Still pretty concerned about doing a linear scan here.

2020-08-27 21:14 UTC, closed without merging