Simplify Async node
typelevel/cats-effect pull request #1165
Opened 2020-09-07 15:24 UTC by SystemFw

2020-09-07 15:46 UTC, djspiewak reviewed
Initial thoughts. I'll stare at the state machine a bit more. Off-hand, it doesn't look like it has enough states to actually work. Need to ponder.

2020-09-07 15:46 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  private[effect] final case class Cont[A]() extends IO[(IO[A], (Either[Throwable, A] => Unit))] {
Should be an `object`. Also I would have expected this to outright replace `Async`.

2020-09-07 15:46 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +          // all over the place in the runloop.
I hope you're not planning on deleting this…

2020-09-07 15:46 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +            // should I do any checks on the old finalisation state like in async?
The only reason those checks exist is to solve the case where `async` is used *in a finalizer*. When an async callback is fired on a canceled fiber, we generally want to just eat the callback so we don't fork the runloop, but if we're in the process of evaluating finalizers, we *don't* want to eat the callback.

2020-09-07 15:46 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +              if (resume("callback")) { // is this necessary to publish writes?
Yes, but also it's necessary to grab the runloop ownership. `suspend`/`resume` are sort of like a runloop semaphore protocol. They're responsible for ensuring that, if someone is running the fiber, there is only *one* such someone.

In this case, what you're doing here is reanimating evaluation of a `get`, so there was a suspension (when the `get` was hit) and now you're bringing it back up again.

2020-09-07 15:46 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +              if (!shouldFinalize()) {
There's probably something awkward here w.r.t. `get` within an `onCancel`.

2020-09-07 15:46 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    if(str.nonEmpty) println(s"resume called by $str on fiber $name, suspended ${suspended.get}")
FYI, `str != ""` is a lot faster. `str.length > 0` might be faster-still.

2020-09-07 16:43 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  private[effect] final case class Cont[A]() extends IO[(IO[A], (Either[Throwable, A] => Unit))] {
oh sorry, this is just wip. It will replace `Async` once it's done, but I'm keeping both for now so that I can use `start/sleep` in tests and retain a touch of sanity.

2020-09-07 16:44 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +          // all over the place in the runloop.
ahahah I was actually not sure if useful for other people or not. But yeah I'm thinking that in the worst case scenario of this PR going nowhere, I'll still commit some of the comments.

2020-09-07 16:44 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +            // should I do any checks on the old finalisation state like in async?
> the case where async is used in a finalizer

I have to say that this didn't even remotely crosses my mind, thanks

2020-09-07 16:45 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    if(str.nonEmpty) println(s"resume called by $str on fiber $name, suspended ${suspended.get}")
that's useful thanks, so far I haven't yet hit a case where the slow string check cause the races to disappear,  but it's bound to happen at some point I guess

2020-09-07 16:47 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +              if (resume("callback")) { // is this necessary to publish writes?
> . suspend/resume are sort of like a runloop semaphore protocol. They're responsible for ensuring that, if someone is running the fiber, there is only one such someone.

This bit I did get in general, although it breaks with `.get.start` as we've discussed. The reason I added the comment there though is that it seemed to me that `ContState` was going to be enough for that, although that's probably wrong

2020-09-07 16:49 UTC, SystemFw commented
> I'll stare at the state machine a bit more. Off-hand, it doesn't look like it has enough states to actually work. Need to ponder.

Please do. Also this construction does not push anything on `conts`, which feels dodgy (but the `async` protocol with respect to `conts` cannot be used here)

2020-09-07 20:10 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +              if (resume("callback")) { // is this necessary to publish writes?
I'm worried about things like this:

```scala
promise[A] flatMap { p =>
  p.get.start >> p.get.start
}
```

Like… good luck. You really would need `CallbackQueue` in order to do anything with the above. This is part of why I like the `CPST` approach better, if it works out the way it *seems* like it should.

2020-09-07 20:11 UTC, djspiewak commented
> Also this construction does not push anything on conts, which feels dodgy (but the async protocol with respect to conts cannot be used here)

That's actually expected. The only reason `Async` pushes something to `conts` is the fact that it has a *body* (the contents of the `async` block). Of course, `promise` doesn't, so you have no continuations to juggle.

2020-09-11 14:16 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +        case _ : IO.Get[_] => sys.error("impossible")
I'm not sure that it is. This is probably similar to the `Unmask` situation

2020-09-11 19:17 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IO.scala
> +        case _ : IO.Get[_] => sys.error("impossible")
yeah actually I think we have a problem here

2020-09-11 19:19 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IO.scala
> +        case _ : IO.Get[_] => sys.error("impossible")
`cont.flatMap(_.get).to[F]` would probably crash, and it's not like `Unmask` either, because in that case we can express the operation as `poll`, I'm not sure we have an equivalent operation in any typeclass here, and putting `get` in `Async` is pretty weird since it's a standalone method, but an internal node which is a by-product of evaluating `Cont`.

2020-09-11 19:20 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +        case _ : IO.Get[_] => sys.error("impossible")
I think the solution is similar to `Unmask`: you have to get the `get` from the delegate's CPS.

2020-09-11 19:21 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IO.scala
> +        case _ : IO.Get[_] => sys.error("impossible")
mm ok. I'll leave it for now and get back to it once I harden the external encoding

2020-09-11 19:23 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +        case _ : IO.Get[_] => sys.error("impossible")
> cont.flatMap(_.get).to[F] would probably crash, and it's not like Unmask either, because in that case we can express the operation as poll, I'm not sure we have an equivalent operation in any typeclass here, and putting get in Async is pretty weird since it's a standalone method, but an internal node which is a by-product of evaluating Cont.

You're going to get it *from* the `cont` though. You're starting by interpreting `IO.Cont` to `F`, which you do by calling `F.cont`, which gives you a `get: F[A]`. Take that `get` and stuff it into *another* `IO` node and pass that to the `Cont` function. So you don't have to worry about ever seeing `IO.Get`, but you *will* see your fancy `Get` node that carries the `get: F[A]` value, similar to what we do with `poll` and `Unmask`.

2020-09-13 18:28 UTC, kubukoz commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
>          case 12 =>
Just wondering, can these be replaced with final vals? Wouldn't they be inlined at compile time?

2020-09-13 18:30 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
>          case 12 =>
Nope! There are bugs in scalac related to this stuff. Generally-speaking, you can't get a `tableswitch` to generate if you use vals; you need to actually inline the constants manually.

2020-09-13 18:30 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
>          case 12 =>
(also, curiously, `@inline` appears to *sometimes* fix this issue, but not always; this is, to my knowledge, the only practically visible impact of that annotation)

2020-09-13 18:55 UTC, kubukoz commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
>          case 12 =>
eh. Thanks ;)

2020-09-20 18:52 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +          }
I believe this is the origin of the canceled `never` deadlock: you aren't checking `canceled` here. The issue is the fact that cancelation could come in *during* the interpretation of this node, which means the canceler would fail to get the runloop and would thus suspend. Meanwhile, you go through this logic, never check cancelation, and just… suspend, meaning that no one runs the cancelation and things hang forever.

2020-09-20 19:31 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +          }
ah, I see.
Sounds like the answer to:
> // async has a conditional suspend, why?

and in retrospect, there is this comment in the relevant method too:
>     // race condition check: we may have been cancelled before we suspended

2020-09-20 20:51 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +              } // else println("something wrong")
Here's your deadlock. The callback is `resume`ing the fiber, and it *does* need to finalize, but it doesn't have the ability to do so (here it just drops things on the floor). The scenario happens in the following case:

1. `get` suspends
2. The callback is fired and we pass through the `resume` barrier
3. Some other fiber cancels the `get`, and `cancel` cannot `resume`
4. The above block is hit, meaning that we have detected that we need to finalize, but no one ran the finalizers *for* us (and they can't, since we own the runloop), so we just die.

`Async` has quite a lot of complex conditional double-checking to avoid this particular scenario. :-)

2020-09-20 21:08 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +          }
This fixed it

2020-09-20 21:09 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +              } // else println("something wrong")
After adding some tracing, deadlock doesn't happen on a winning callback path, it seems

2020-09-20 21:14 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +            }
It's actually here, it hits the (invisible) `else`

2020-09-20 21:35 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +              } // else println("something wrong")
Ok I fixed the deadlock, which was a similar case but in `get`. This specific path isn't stressed by any tests, but I think you're right, basically on line 644 you need `else cancel`

2020-09-22 11:51 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +            // should I do any checks on the old finalisation state like in async?
does this check apply to the callback in promise as well then?

2020-09-22 12:13 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +            // should I do any checks on the old finalisation state like in async?
it appears to not be needed: removing it when using `Async` makes a test consistently fail, and that same test consistently passes when using `Cont/promise`

2020-09-22 14:34 UTC, SystemFw commented on kernel/shared/src/main/scala/cats/effect/kernel/Deferred.scala
>              }
I'm using `async` as we've agreed here, just wanted to double check we are ok with the extra allocations

2020-09-22 16:10 UTC, djspiewak commented on core/js/src/main/scala/cats/effect/IOFiberConstants.scala
> +  // TODO reassign tags after AsyncK removal
FYI the tag reassignment is quite important. :-) `tableswitch` with consecutive values is treated differently by HotSpot than non-consecutive ones.

2020-09-22 16:11 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Deferred.scala
>              }
I think we can loop back and rework it if we decide that's worthwhile. There are definitely performance advantage to working with `cont` directly, but they might disappear when we fiddle with the API to be safer.

2020-09-22 17:55 UTC, SystemFw commented on kernel/shared/src/main/scala/cats/effect/kernel/Deferred.scala
>              }
yeah fair enough. The side-effects in the old usage are a lot scarier imho now that `async` is not primitive, there are a lot more layers from there to execution

2020-09-22 17:56 UTC, SystemFw commented on core/js/src/main/scala/cats/effect/IOFiberConstants.scala
> +  // TODO reassign tags after AsyncK removal
oh wow. Btw once I get there, I really want to also cluster the operations differently, so switching order in `IOFiber` and `IO`. This might be annoying for people hacking on it so I'll check on gitter before starting, but I do think it will make `IOFiber` easier to digest.

2020-09-24 06:36 UTC, RaasAhsan reviewed
This is looking awesome, and much easier to understand!

2020-09-24 06:36 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +              suspended.compareAndSet(false, true)
We were talking about this on Gitter earlier, but to reiterate why this was done (and to jog my memory about it). A CAS has the effect of both a volatile read and write, and so the non-volatile invariant extends here as well. Specifically, we want to observe the most up-to-date value of `cancelled`.

Additionally, this CAS should *always* succeed because the runloop is owned by the current thread.

2020-09-24 06:36 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +              if (!shouldFinalize()) {
If we're running finalizers, that means `asyncCancel` was invoked at some point, which masks the runloop. If we're masked, `shouldFinalize()` evaluates to `false`, so we would proceed with `asyncContinue` in this case. In general, once we start finalization, subsequent calls to `shouldFinalize()` will always return `false`.

2020-09-24 06:36 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +            if (state.compareAndSet(ContStateInitial, ContStateWaiting)) {
extra indentation here?

2020-09-24 06:36 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +        case 22 =>
1. What is the effect of sequencing the same `get` multiple times? 
2. Do several invocations of `cont` interact with each other as expected with various interleavings of `get` and `resume`? 

I think its worth having test cases for these but feel free to open a follow up issue :)

2020-09-24 06:36 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +            def stateLoop(): Unit = {
I was expecting otherwise, but it's interesting that this `stateLoop` stayed mostly intact from the old `Async`. I think that goes to say that old finalizer registration mechanism was just a more specific variant of what we have now

2020-09-24 07:58 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +              suspended.compareAndSet(false, true)
I'm going to expand that comment a bit to include some of this

2020-09-24 08:01 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +        case 22 =>
1. Should be idempotent
2. I don't know, and this is worth checking to make sure there are no weird interactions. On one hand the number of interleavings is reduced by not being able to `start` `get`, but on the other I expect it to be fully possible to misuse this to deadlock (in a way that we cannot prevent). But still, worth checking that in sane usage we aren't messing up the runloop somehow

2020-09-24 15:08 UTC, djspiewak commented
I find it interesting that you seem to dislike line comments :-)

2020-09-24 15:10 UTC, SystemFw commented
> I find it interesting that you seem to dislike line comments :-)

I don't really. In this case I disliked having the debug println that I need to glance over interwoven with the stuff I need to read. So I started by adding `// LOG` to those lines, and then I moved to this commit. Not sure if I like the result or not (interlude: this is part of why I like working with granular commits and really avoid squashing on merge)

2020-09-24 17:03 UTC, djspiewak commented
> (interlude: this is part of why I like working with granular commits and really avoid squashing on merge)

Hard agree

2020-09-28 15:10 UTC, SystemFw commented on kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala
> +private[kernel] final class DefaultCont[F[_], A](implicit F: Async[F]) {
Interesting question is how to test this

2020-09-28 15:46 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala
> +private[kernel] final class DefaultCont[F[_], A](implicit F: Async[F]) {
Maybe create an identity transformer which sits on top of `IO` but delegates to `IO`'s `async` rather than its `cont`?

2020-09-28 18:16 UTC, SystemFw commented on kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala
> +private[kernel] final class DefaultCont[F[_], A](implicit F: Async[F]) {
and then run the entire IOSpec over that? that's fair enough, although ultimately it's still running on top of `IOCont`, which `IO.async` sits on top of

2020-09-28 23:18 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala
> +private[kernel] final class DefaultCont[F[_], A](implicit F: Async[F]) {
Yeah, but if we trust `IOCont`, then we trust its derived `async`

2020-10-02 09:20 UTC, RaasAhsan reviewed
reviewed half of it, going to look at the rest tomorrow

2020-10-02 09:20 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IO.scala
> +   * please use `start`, `async` or `Deferred` instead,
Should we recommend `background` here instead

2020-10-02 09:20 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +  /* masks encoding: initMask => no masks, ++ => push, -- => pop */
is this supposed to be somewhere else

2020-10-02 09:20 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> -                if (finalizing == wasFinalizing) {
This check was rather crucial: if a fiber is suspended in an asynchronous boundary and gets cancelled, the canceller will acquire the runloop and finalize. If one of the finalizers are asynchronous, the canceller enters an asynchronous boundary. At this point, if the callback from the *original* async completes, it's going to be able to acquire runloop, and try to apply the continuation on top of the stack to the result, which ultimately throws an exception.

If this isn't necessary anymore, we can remove the `finalizing` instance variable.

2020-10-02 09:20 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +              IO(state.compareAndSet(ContStateWaiting, ContStateInitial)).void
ooh, this is a really good catch

2020-10-02 09:20 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    /* full memory barrier to publish masks */
I wrote this but it's wrong BTW, it's just a write barrier. 

Also, the reason this was added in: with the old `Async` state machine, after `Async` registered a finalizer and suspended, somebody else could `cancel` before the callback can acquire the runloop. In that scenario, the callback perpetually loops since the canceller owns the runloop now and masks before finalizing. 

After cancellation and finalizations completes, we reset `masks` which signals to the callback loop that the current fiber is both cancelled and completely unmasked, so somebody else handled cancellation. So the `!shouldFinalize()` check in `loop` fails, which terminates it

2020-10-02 09:20 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +   4 possible cases for callback and cancellation:
I added this in awhile back, I think i came to the conclusion that this is wrong or just incomplete. But this behavior is better described by your new comments now :)

2020-10-02 09:25 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +  /* masks encoding: initMask => no masks, ++ => push, -- => pop */
It was there before my changes as well. Not quite sure where to put it, it's a general point, which affects `childMask`, `initMask`, `masks`, `case 9` and `case 10` in the runloop (that's a candidate spot), `isUnmasked`, etc

2020-10-02 09:28 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> -                if (finalizing == wasFinalizing) {
I need to think more about whether this is still needed or not. Please do the same :)
The reason I removed it is that with the old `async`, removing the check causes a test to consistently fail, and with `cont` (without the check), the same test consistently succeeds
https://github.com/typelevel/cats-effect/pull/1165#discussion_r492684017

2020-10-02 09:28 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> -                if (finalizing == wasFinalizing) {
If/when we all agree it's not needed, I'll go ahead and remove `finalizing`, thanks for pointing that out

2020-10-02 09:29 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +              IO(state.compareAndSet(ContStateWaiting, ContStateInitial)).void
The solution here was surprisingly simple, I had gone down a really complicated avenue of double checking AtomicReferences before realising I could use `IO` itself and `onCancel`. This is the solution to "`get` within an `onCancel`" bug, ftr.

2020-10-02 09:32 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    /* full memory barrier to publish masks */
What should I do here? Delete the full memory barrier comment for sure. Should I also add your comment above? is it still needed?

2020-10-02 09:32 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +   4 possible cases for callback and cancellation:
Will delete then, cheers

2020-10-02 09:32 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IO.scala
> +   * please use `start`, `async` or `Deferred` instead,
yeah I will mention it there

2020-10-02 21:09 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +   * please use `start`, `async` or `Deferred` instead,
Also oxford comma please :-)

2020-10-02 21:27 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> -                if (finalizing == wasFinalizing) {
`"run the continuation of an async finalizer within async"` in `IOSpec` proves that this isn't necessary any longer, though it isn't immediately obvious to me *why* it is no longer necessary.

2020-10-02 22:10 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IO.scala
> +   * please use `start`, `async` or `Deferred` instead,
I actually love Oxford commas

2020-10-02 22:11 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> -                if (finalizing == wasFinalizing) {
>  though it isn't immediately obvious to me why it is no longer necessary.

Exactly :)

2020-10-02 23:56 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +   * please use `start`, `async` or `Deferred` instead,
They make lists so much less ambiguous

2020-10-03 08:27 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    /* full memory barrier to publish masks */
Yeah, I believe it's still needed, I just wanted to make sure you and others are aware of why it's being done because it's not entirely clear (I had to spend 15 minutes recalling). Here's the race it fixes to be more clear:
1. Fiber A starts the `Cont` action.
2. Fiber A invokes `Cont.get`, which sets the `AtomicReference` to `ContStateWaiting`.
3. Before Fiber A suspends, the `Cont` action invokes the callback, and sets the `AtomicReference` to `ContStateResult`, and moves to `loop` to acquire the runloop, but it can't yet because fiber A hasn't suspended yet.
4. Fiber A suspends.
5. Fiber B cancels fiber A. Before the callback manages to acquire the runloop, B acquires the runloop, masks and completes finalization. At this point, assume we're not unmasking or publishing that state via `suspended`.
6. The callback for the `Cont` action is stuck in an infinite loop: it can't reacquire the runloop since it will never be released again, and the `!shouldFinalize()` will always pass because we're still masked.

So, by resetting `masks` and publishing that state, we can force that `!shouldFinalize` check to fail, which lets `loop` end.

2020-10-03 08:36 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    /* full memory barrier to publish masks */
Fantastic, I'll see if I can work that in a comment somewhere

2020-10-03 08:53 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> -                if (finalizing == wasFinalizing) {
IIRC this was definitely a racey behavior that I observed for some test case over millions of invocations. So, I think there are two possible races here, one of which the finalizer on `Get` actually fixes:
1. Fiber A starts the `Cont` action.
2. Fiber A invokes `get`, suspending the runloop.
3. Fiber B cancels A, so it acquires A's runloop and starts finalization. The first finalizer is *guaranteed* to be the one registered over `Get`! So this resets the `AtomicReference` back to the `Initial` state.
4. B encounters an async finalizer for A, so it suspends the runloop. We will never encounter an async finalizer before the one over `Get`.
5. The callback from step 1 completes. It sees the `Initial` state so transitions to `Result` and exits out.

Here's an example of a race that it doesn't fix:
1. Fiber A starts the `Cont` action.
2. Fiber A calls `Get`, setting the `AtomicReference` to `Waiting`.
3. Before A suspends the runloop, the callback from step 1 completes. It sees the `Waiting` state, transitions to `Result`, and then tries to acquire the runloop in `loop`, which it can't at this point, so it loops.
4. A suspends the runloop.
5. Fiber B cancels A, acquiring the runloop. It begins finalization. The first finalizer resets the `AtomicReference` to `Initial`, as described above.
6. B encounters an async finalizer for A, so it suspends.
7. The callback from step 1 reacquires the runloop in `loop`. `!shouldFinalize()` evaluates to true because we are masked, so it moves onto `asyncContinue` which is where everything starts to break down.

I think that's right, but please double check that :D I wonder if there's a more obvious way to represent and compare against this fiber state, but it's not immediately obvious to me yet

2020-10-03 14:32 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> -                if (finalizing == wasFinalizing) {
I believe this is correct. It's a much more subtle and harder to hit case than the original one, but I believe the analysis is accurate that we don't handle it without checking that we're in the same finalization state as when we started.

As a note, we only need two finalization states because finalizers themselves are not cancelable. So we can only generate this scenario at a single level.

2020-10-03 18:21 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Cont.scala
> +      G: MonadCancel[G, Throwable]): (Either[Throwable, A] => Unit, G[A], F ~> G) => G[A]
Why not:

```scala
  def apply[G[_]](
      resume: Either[Throwable, A] => Unit,
      get: G[A],
      lift: F ~> G)(
      implicit G: MonadCancel[G, Throwable]): G[A]
```

More names and easier syntax at call sites.

2020-10-03 18:22 UTC, SystemFw commented on kernel/shared/src/main/scala/cats/effect/kernel/Cont.scala
> +      G: MonadCancel[G, Throwable]): (Either[Throwable, A] => Unit, G[A], F ~> G) => G[A]
> More names and easier syntax at call sites.

That's what I used to have, but actually the call site with that is _so_ much uglier

2020-10-03 18:23 UTC, SystemFw commented on kernel/shared/src/main/scala/cats/effect/kernel/Cont.scala
> +      G: MonadCancel[G, Throwable]): (Either[Throwable, A] => Unit, G[A], F ~> G) => G[A]
https://github.com/typelevel/cats-effect/pull/1165/commits/d2d23a2513cdb53b0ac573e132ae53c7e9c520c1#diff-8d42a1f7ffbea3d266c76d171c65d92c

have a look, note how many type signatures we can omit

2020-10-03 18:24 UTC, SystemFw commented on kernel/shared/src/main/scala/cats/effect/kernel/Cont.scala
> +      G: MonadCancel[G, Throwable]): (Either[Throwable, A] => Unit, G[A], F ~> G) => G[A]
Also I think the higher-rank type is clearer this way, although probably the only one who'll ever notice is me :P

2020-10-03 18:26 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Cont.scala
> +      G: MonadCancel[G, Throwable]): (Either[Throwable, A] => Unit, G[A], F ~> G) => G[A]
Ah I see what you mean. Okay that's fair.

And yeah, I do think the higher-rank is clearer. That's actually the very first thing I noticed. :-) Had to stare at it a while to convince myself that it was actually okay to do what I was proposing. We can leave it as-is then.

2020-10-03 22:30 UTC, djspiewak requested changes

2020-10-03 22:30 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +  def defaultCont[F[_]: Async, A](body: Cont[F, A]): F[A] =
If we make this `protected`, will subclasses of the companion trait be able to see it? That would be ideal, imo.

2020-10-03 22:30 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala
> +  def cont[F[_]: Async, A](body: Cont[F, A]): F[A] =
IMO it actually would be nicer to just inline this into `Async.defaultCont`. The types here don't serve any purpose other than redirecting the implementation to another file.

2020-10-04 08:24 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +                if (finalizing == wasFinalizing.get()) {
I *think* this looks good to me, will keep on thinking about it. Here's an alternative state coordination mechanism that makes somewhat more sense to me:
1. Renaming `wasFinalizing` to `waiting`. The purpose of this variable is to communicate to the callback whether the fiber is ready to resume from *this* callback specifically.
2. Add an extra statement to the `Get` finalizer that sets `waiting` to false.
3. Replace this conditional with `waiting.get()`. This basically indicates that the runloop suspended with the intention if waiting on this fiber. 
4. We can remove the `finalizing` field member.

If it's actually correct, I think this mechanism is slightly easier to understand, since it's completely independent of finalization. It's "if the runloop is waiting on me, then I can proceed" rather than "if the current runloop finalization state is the same as the state of whoever is currently waiting".

2020-10-04 08:27 UTC, RaasAhsan commented on core/shared/src/test/scala/cats/effect/ContSpec.scala
> +    val test = io.flatMap(r => IO(r mustEqual 42))
I think it would be nice to have tests that involve multiple `cont` calls with different orderings of `resume`/`get`. Let me know if I should just do it, would be a good opportunity to play around with this :)

2020-10-04 08:46 UTC, RaasAhsan commented on kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala
> +            def loop(): Unit =
`@tailrec` here just to be safe ?

2020-10-04 08:46 UTC, RaasAhsan commented on kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala
> +    def loop(): Unit =
`tailrec` here as well

2020-10-04 09:26 UTC, SystemFw commented on core/shared/src/test/scala/cats/effect/ContSpec.scala
> +    val test = io.flatMap(r => IO(r mustEqual 42))
Go for it

2020-10-04 09:33 UTC, SystemFw commented on kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala
> +            def loop(): Unit =
solved in the next commit, for some reason the diff doesn't show it

2020-10-04 09:38 UTC, SystemFw commented on kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala
> +  def cont[F[_]: Async, A](body: Cont[F, A]): F[A] =
yeah ok will do that

2020-10-04 11:41 UTC, SystemFw commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +  def defaultCont[F[_]: Async, A](body: Cont[F, A]): F[A] =
```
trait A
object A {
  protected def a = 1
}

trait B extends A {
  def b = A.a
}

method a in object A cannot be accessed in object A
[error]  Access to protected method a not permitted because
[error]  enclosing trait B is not a subclass of
[error]  object A where target is defined
[error]   def b = A.a
```

2020-10-04 11:41 UTC, SystemFw commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +  def defaultCont[F[_]: Async, A](body: Cont[F, A]): F[A] =
> method a in object A cannot be accessed in object A

it would be a good scala trivia to ask what code can generate this error lol

2020-10-04 14:26 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +                if (finalizing == wasFinalizing.get()) {
I find the solution in the PR (and the one in the old async) a bit opaque.
I think I prefer the direction with the `id` of the suspension, which acts as a sort of epoch number, because I think the specific problem is more accurately described as "we don't want a callback of a previous epoch to resume the runloop in a new epoch", with an orthogonal statement that says "a change of epoch happens during finalisation, in the presence of an async finaliser reusing the same `cont`"

2020-10-04 17:19 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +                if (finalizing == wasFinalizing.get()) {
I think that @RaasAhsan's proposed solution is even *better* than the epoch number, actually, since we only need an epoch bit and his solution achieves it while removing the extra state from `IOFiber` itself. I really like that, but I think we should implement it in a follow-up PR.

The solution currently on the branch is definitely opaque, I just want to get this landed in a functional form so that we can unblock everything else. :-D

2020-10-04 17:20 UTC, SystemFw commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +                if (finalizing == wasFinalizing.get()) {
I'm fixing the conflicts as we speak, let's get it merged and then @RaasAhsan can add his solution and the additional tests in a follow up

2020-10-04 18:16 UTC, merged