Gen hierarchy renaming
typelevel/cats-effect pull request #1192
Opened 2020-09-15 00:08 UTC by RaasAhsan

- [x] Prefix `Concurrent`, `Temporal` and `Spawn` type classes with `Gen`
- [x] Remove `Throw` suffix from `ConcurrentThrow`, `TemporalThrow` and `SpawnThrow`
- [x] Add type alias `MonadThrow[F]` to `MonadError[F, Throwable]`

Made a best effort to remain as consistent as possible, let me know if I missed anything.

2020-09-15 12:38 UTC, mpilquist commented
Looks great. One thing I noticed when converting FS2 to use this PR is that I really miss `Concurrent[F]` syntax for summoning an implicit instance.

2020-09-15 14:12 UTC, djspiewak requested changes
👍 looks really good! Just some minor changes.

2020-09-15 14:12 UTC, djspiewak commented on concurrent/shared/src/main/scala/cats/effect/concurrent/Semaphore.scala
> +      implicit F: GenSpawn[F, Throwable])
`Spawn[F]`

2020-09-15 14:12 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/instances/package.scala
> +  object concurrent extends kernel.instances.GenSpawnInstances
This should probably be `object spawn`

2020-09-15 14:12 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/package.scala
> +  type Temporal[F[_]] = cekernel.Temporal[F]
We should also do value-level forwarders, so that we can use the summoning syntax. IMO, `val Spawn = GenSpawn` is sufficient

2020-09-15 14:12 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/syntax/package.scala
> +  object spawn extends kernel.syntax.GenSpawnSyntax
We should add `concurrent` here

2020-09-15 14:12 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +trait Async[F[_]] extends AsyncPlatform[F] with Sync[F] with GenTemporal[F, Throwable] {
`Temporal`

2020-09-15 14:12 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Fiber.scala
> +  def joinAndEmbed(onCancel: F[A])(implicit F: GenSpawn[F, E]): F[A] =
We can loosen this to `MonadCancel`

2020-09-15 14:12 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/package.scala
> +  type Concurrent[F[_]] = GenConcurrent[F, Throwable]
Needs value-level forwarders

2020-09-15 14:12 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/syntax/GenTemporalSyntax.scala
> +      implicit F: GenTemporal[F, _ >: TimeoutException]): F[A] =
Let's just make this `Temporal`

2020-09-15 14:12 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/syntax/package.scala
> +  object temporal extends GenTemporalSyntax
We need to add `concurrent`

2020-09-16 03:46 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/syntax/package.scala
> +  object spawn extends kernel.syntax.GenSpawnSyntax
We don't have any `Concurrent` syntax enrichment yet

2020-09-16 03:49 UTC, RaasAhsan commented on kernel/shared/src/main/scala/cats/effect/kernel/syntax/package.scala
> +  object temporal extends GenTemporalSyntax
No syntax for `Concurrent` yet

2020-09-16 15:04 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/syntax/package.scala
> +  object spawn extends kernel.syntax.GenSpawnSyntax
That's true, I just wanted to create a place for it.

2020-09-16 15:05 UTC, merged

2020-09-16 15:49 UTC, mpilquist commented
@djspiewak Can we get a release of this one?

2020-09-16 16:20 UTC, djspiewak commented
For posterity, already done: `3.0-c54025b`