Add Console
typelevel/cats-effect pull request #1197
Opened 2020-09-16 16:53 UTC by vasilmkd

We can iterate on this. I definitely couldn't please everyone. Could also serve as a place to continue the discussion.

Special thanks to @gvolpe for `console4cats`.

2020-09-16 22:47 UTC, vasilmkd commented on concurrent/shared/src/main/scala/cats/effect/concurrent/Console.scala
> +    new SyncConsole[F](in, err, out)
I just adapted this code from `console4cats`, however I do think that we can provide a better user experience by creating it, I dare say in a `Resource`, which could then be used to close the readers and the streams at the end.

2020-09-20 06:00 UTC, djspiewak requested changes
I think we should probably add @gvolpe to the list of developers (is he already in there? is anybody? I haven't checked) in recognition of the fact that we're basically slurping his library directly into Cats Effect. :-)

2020-09-20 06:00 UTC, djspiewak commented on concurrent/shared/src/main/scala/cats/effect/concurrent/Console.scala
> +  def apply[F[_]](implicit C: Console[F]): C.type = C
So the more I think about it, the more I'm convinced that this really shouldn't be a final tagless encoding. I think the `Console[F]` trait itself is fine, but I don't think it should *ever* be passed implicitly. It just doesn't make sense and there are so many drawbacks to it.

2020-09-20 06:00 UTC, djspiewak commented on concurrent/shared/src/main/scala/cats/effect/concurrent/SyncConsole.scala
> +    Sync[F].delay(in.readLine())
This should definitely be in `blocking` instead of `delay`, and probably in `interruptible`.

2020-09-20 06:00 UTC, djspiewak commented on concurrent/shared/src/main/scala/cats/effect/concurrent/SyncConsole.scala
> +    Sync[F].delay(err.println(a.show))
All of these should definitely be in `blocking` or possibly `interruptible`.

2020-09-20 06:00 UTC, djspiewak commented on concurrent/shared/src/test/scala/cats/effect/concurrent/SyntaxSpec.scala
> +    Console.stdio[F]
IMO this doesn't need to be in the syntax spec

2020-09-20 06:00 UTC, djspiewak commented on concurrent/shared/src/test/scala/cats/effect/concurrent/SyntaxSpec.scala
> +    Console[F]
…same here

2020-09-20 16:04 UTC, vasilmkd commented on concurrent/shared/src/main/scala/cats/effect/concurrent/SyncConsole.scala
> +    Sync[F].delay(in.readLine())
Yes, sorry, this PR needs more polish. I only opened it to have something that others can comment on with context and possibly see what works and what doesn't.

2020-09-20 16:05 UTC, vasilmkd commented on concurrent/shared/src/main/scala/cats/effect/concurrent/Console.scala
> +  def apply[F[_]](implicit C: Console[F]): C.type = C
Do you maybe have more concrete suggestions on how to proceed from here? Thanks.

2020-09-20 16:06 UTC, vasilmkd commented
What is a list of developers?

2020-09-20 18:19 UTC, djspiewak commented on concurrent/shared/src/main/scala/cats/effect/concurrent/Console.scala
> +  def apply[F[_]](implicit C: Console[F]): C.type = C
I would remove all the things that involve `implicit Console[F]`. Basically just distilling it down to a type that is passed explicitly.

2020-09-20 18:19 UTC, djspiewak commented
> What is a list of developers? I will gladly add him.

2020-09-20 18:20 UTC, mpilquist commented on concurrent/shared/src/main/scala/cats/effect/concurrent/Console.scala
> +  def apply[F[_]](implicit C: Console[F]): C.type = C
I’m not sure about this. I’d likely take Console as an implicit argument in fs2 and in apps.

2020-09-20 19:08 UTC, djspiewak commented on concurrent/shared/src/main/scala/cats/effect/concurrent/Console.scala
> +  def apply[F[_]](implicit C: Console[F]): C.type = C
It's stateful though. Among other things, remember that it's impossible to get an `implicit` value generated by a `for`-comprehension step without using better-monadic-for. Which like… obviously you can do (in Scala 2), but isn't that a decent red flag? What's wrong with passing it explicitly?

2020-09-20 19:11 UTC, mpilquist commented on concurrent/shared/src/main/scala/cats/effect/concurrent/Console.scala
> +  def apply[F[_]](implicit C: Console[F]): C.type = C
Why is it stateful?

Passing it manually is harder and more ceremonious than just taking a Sync constraint. This should be at least as easy as using Sync directly.

2020-09-20 19:51 UTC, djspiewak commented on concurrent/shared/src/main/scala/cats/effect/concurrent/Console.scala
> +  def apply[F[_]](implicit C: Console[F]): C.type = C
> Why is it stateful?
>
> Passing it manually […]

If it's not stateful, then why are you passing it at all? Just take a `Sync` constraint.

The state is the fact that it can be constructed to point at different input/output streams, and those streams might not actually be alive anymore. If there were only one global instance pointing to stdout/stderr/stdin, then the whole thing is actually really easy and doesn't need to be passed at all, implicitly or otherwise. If it's anything *other* than that, then passing it implicitly is dangerous and *constructing* the implicit in a scoped fashion is dodgy.

2020-09-20 19:55 UTC, mpilquist commented on concurrent/shared/src/main/scala/cats/effect/concurrent/Console.scala
> +  def apply[F[_]](implicit C: Console[F]): C.type = C
Ah, yes, let’s get rid of ability to customize streams.

2020-09-20 19:56 UTC, djspiewak commented on concurrent/shared/src/main/scala/cats/effect/concurrent/Console.scala
> +  def apply[F[_]](implicit C: Console[F]): C.type = C
I'm actually okay with that. :-) If we do that then this API becomes very very simple indeed.

2020-09-21 00:31 UTC, vasilmkd commented
It seems that the header (typelevel licence) that was automatically updated deleted my original reference to `console4cats`. I just now noticed that and I have fixed it.

2020-09-22 16:08 UTC, djspiewak requested changes
I'm still thinking about the "override the streams" case…

2020-09-22 16:08 UTC, djspiewak commented on build.sbt
> +)
Since we're adding this now, let's go ahead and get others in here as well. `git shortlog -s` tells me the following:

```
     5  Ben Plommer
     5  Chris Davenport
   478  Daniel Spiewak
    67  Fabio Labella
     1  Gavin Bisesi
     1  Guillaume Martres
    18  Jakub Kozłowski
    13  Michael Pilquist
     1  Michał Gibowski
     4  Oleg Pyzhcov
    86  Raas Ahsan
   135  Tim Spence
    62  Vasil Vasilev
    12  anikiforov
     5  mpilquist
```

Which, btw, gives us a pretty good idea who rebases with squashing and who doesn't. :-D

Off-hand, and in addition to what you have here:

- Fabio
- Jakob
- Michael
- Raas
- Tim
- Vasil
- Ben

I think the other changes have been relatively small in scope, but that's a subjective call with no clear answer. Feel free to disagree! I'm not fussed much about this either way.

2020-09-22 16:08 UTC, djspiewak commented on concurrent/shared/src/main/scala/cats/effect/concurrent/Console.scala
> +  final class ApplyBuilders[F[_]](val F: Sync[F]) extends AnyVal {
I would just change this to `Console[F]`. That seems more idiomatic to me, anyway. Basically, the `Console` *class* would exist solely to be a holder for the `F` type and its constraints.

2020-09-22 16:08 UTC, djspiewak commented on concurrent/shared/src/main/scala/cats/effect/concurrent/Console.scala
> +    Sync[F].blocking(scala.Console.in.readLine())
This should be `interruptible(false)` rather than `blocking`. I think the rest are good though.

2020-09-22 16:08 UTC, djspiewak commented on concurrent/shared/src/main/scala/cats/effect/concurrent/Console.scala
> +      Console.printlnError(a)(F, S)
If the `F: Sync[F]` above is made `implicit`, then you don't need to pass any of these explicitly.

2020-09-22 16:08 UTC, djspiewak commented on concurrent/shared/src/main/scala/cats/effect/concurrent/Console.scala
> +   *   Console[F].println("Hello") <-> Console.println[F, String]("Hello")
IMO, and this is a bit of a bikeshed, but I don't think we need to support both variants of the API. Let's just be a little more prescriptive:

- `Console[F].print("Hello")`
- `Console[F].println("Hello")`
- `Console[F].readLine`
- `Console[F].printErr("Hello")` (I like the shorter `Err`, but that's just my opinion)
- `Console[F].printlnErr("Hello")` (I like the shorter `Err`, but that's just my opinion)

2020-09-22 17:45 UTC, kubukoz commented on concurrent/shared/src/main/scala/cats/effect/concurrent/Console.scala
> + * Effect type agnostic `Console` with common methods to write to and read from the standard console.
I would mention that it's supposed to be used for simple console output exclusively, and anything more complex like logging should be done via a custom algebra (e.g. Logger from log4cats).

2020-09-22 18:28 UTC, vasilmkd commented on build.sbt
> +)
Since this is now a task that requires compiling a list of people's names, GitHub accounts and Twitter handles, I'm going to do that in a separate issue/PR. Let's focus this current one on `Console`.

2020-09-22 18:37 UTC, vasilmkd commented on concurrent/shared/src/main/scala/cats/effect/concurrent/Console.scala
> +      Console.printlnError(a)(F, S)
Unfortunately that doesn't work with value classes. 😕

2020-09-22 22:50 UTC, djspiewak commented on concurrent/shared/src/main/scala/cats/effect/concurrent/Console.scala
> +      Console.printlnError(a)(F, S)
I wouldn't bother making it a value class. That probably doesn't buy very much in this instance.

2020-09-23 19:56 UTC, djspiewak commented
So on the subject of `setErr` and such… Also taking into account @kubukoz's excellent points…

I think that we should roll our own `readLine`. It's going to be a little annoying because we actually need to deal with `\n` vs `\r\n` and such, but it's not the end of the world. We can't reuse `BufferedReader` because that will result in missing some input depending on buffer quantization.

As for `println` and `print` and such, I think we just need to re-access them on each read:

```scala
def println[A: Show](a: A): F[Unit] = {
  val str = a.show
  F.blocking(System.out.println(str))
}
```

…and with that, we should support the setters.

2020-10-04 19:20 UTC, closed without merging