Add documentation page on testing with cats-effect
typelevel/cats-effect pull request #1216
Opened 2020-09-20 17:34 UTC by Daenyth

Addressing #1214

2020-09-20 20:17 UTC, RaasAhsan commented on site/src/main/mdoc/testing/index.md
> +Relatively few libraries support cats-effect directly at this time. However, most (if not all) popular testing frameworks have libraries offering some level of integration
The new Cats Effect documentation site is going to include some of this as well (https://github.com/typelevel/cats-effect/blob/docs/website/pages/en/ecosystem.js#L48), but it's probably worth including here as well

2020-09-21 03:49 UTC, djspiewak requested changes
This is *amazing*. Just a couple quick notes

2020-09-21 03:49 UTC, djspiewak commented on site/src/main/mdoc/testing/index.md
> +- [cats-effect-testing](https://github.com/djspiewak/cats-effect-testing)
I think cats-effect-testing actually doesn't support `A => F[Assertion]` properties, does it? I may be derping.

2020-09-21 03:49 UTC, djspiewak commented on site/src/main/mdoc/testing/index.md
> +When possible, use `TestContext` as your `ExecutionContext`, `ContextShift`, and `Timer`. This is generally the case if your code uses `Timer` and `Clock` to perform time-related operations, and does
I'm actually not sure I agree with this. `TestContext` can mask a lot of subtle bugs. It's appropriate for some things, not for others.

2020-09-21 17:22 UTC, Daenyth commented on site/src/main/mdoc/testing/index.md
> +- [cats-effect-testing](https://github.com/djspiewak/cats-effect-testing)
The docs suggest that it does; https://github.com/djspiewak/cats-effect-testing#scalatest-scalacheck

```
  "My IO Code" - {

    "works with effect-full property-based testing" in {
      forAll { (l1: List[Int], l2: List[Int]) =>
        IO.delay(l1.size + l2.size shouldBe (l1 ::: l2).size)
      }
    }
```

I think from skimming the code it doesn't support *true async* properties (so, probably won't work on scala.js)

2020-09-21 17:28 UTC, Daenyth commented on site/src/main/mdoc/testing/index.md
> +When possible, use `TestContext` as your `ExecutionContext`, `ContextShift`, and `Timer`. This is generally the case if your code uses `Timer` and `Clock` to perform time-related operations, and does
Hmm, ok. I can revise the wording here. I do want to point people at it - I think it's under-advertised

Do you have a suggestion I could use for new wording?

2020-09-23 20:13 UTC, djspiewak commented on site/src/main/mdoc/testing/index.md
> +- [cats-effect-testing](https://github.com/djspiewak/cats-effect-testing)
Ooooooooh I get why this is working. Okay this is a fair bullet point then. But yeah, it's not going to work on scala.js. :-)

2020-09-23 20:16 UTC, djspiewak commented on site/src/main/mdoc/testing/index.md
> +When possible, use `TestContext` as your `ExecutionContext`, `ContextShift`, and `Timer`. This is generally the case if your code uses `Timer` and `Clock` to perform time-related operations, and does
Maybe something like this?

```markdown
In many test cases, `TestContext` should be used as an `ExecutionContext`, `ContextShift`, and `Timer`. This gives you very precise control over the sequencing and scheduling of evaluation, making it possible to deterministically replicate certain race conditions or even identify timing-related bugs without having to rely on non-deterministic thread ordering. `TestContext` also gives you control over *time* (as exposed by `Timer` and `Clock`), which makes it easy to write unit tests for time-related semantics without having to rely on `sleep`s or other hacks.

Be warned though that `TestContext` is a very artificial environment, and it can in turn mask bugs that a realistic executor would uncover. The most comprehensive test suites will often use a balance of each.
```

2020-09-25 13:08 UTC, keynmol commented on site/src/main/mdoc/testing/index.md
> +For test frameworks that use imperative "hook"-style methods (such as scalatest's `BeforeAndAfterAll` mixin), you can use [`allocated`](https://typelevel.org/cats-effect/api/cats/effect/Resource.html
Worth adding here weaver's resources as an alternative? As I think all the other frameworks use hook style

2020-09-27 10:17 UTC, keynmol approved these changes

2020-09-28 22:13 UTC, merged