Implement embed directly in Outcome
typelevel/cats-effect pull request #1234
Opened 2020-09-23 18:59 UTC by vasilmkd

Resolves #1232.

2020-09-23 20:08 UTC, djspiewak requested changes

2020-09-23 20:08 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Fiber.scala
> +  def joinAndEmbed(onCancel: => F[A])(implicit F: MonadCancel[F, E]): F[A] =
Why by-name?

2020-09-23 20:08 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/GenSpawn.scala
> +    backgroundAndEmbed(fa)(never)
Discussion: is it worth having this, or should we just rely on people mapping over the contents? Like, `background(fa).evalMap(_.embedNever)` doesn't seem too onerous.

2020-09-23 20:08 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Outcome.scala
> +  def embed(onCancel: => F[A])(implicit F: MonadCancel[F, E]): F[A] =
Why by-name?

2020-09-23 22:43 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/Fiber.scala
> +  def joinAndEmbed(onCancel: => F[A])(implicit F: MonadCancel[F, E]): F[A] =
`Outcome#fold` takes a by-name parameter. I would think the `onCancel` does not need to be fully built if that path is not taken? Is that a wrong assumption?

2020-09-23 23:22 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Fiber.scala
> +  def joinAndEmbed(onCancel: => F[A])(implicit F: MonadCancel[F, E]): F[A] =
That's definitely a correct assumption. I think my thought on the `fold` signature is the fact that it's more general, and critically, people might recurse through it (think: just like `whenM` and `>>`). I can't really see people making `joinAndEmbed` the branch point in a conditional recursion, but maybe I'm wrong on that one.

2020-09-23 23:31 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/Fiber.scala
> +  def joinAndEmbed(onCancel: => F[A])(implicit F: MonadCancel[F, E]): F[A] =
I'll revert to strict.

2020-09-24 15:57 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/GenSpawn.scala
> +    backgroundAndEmbed(fa)(never)
I'm not a fan of the names, but I do like the simmetry with `join`.

2020-09-25 16:33 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/Outcome.scala
> +  def embed(onCancel: => F[A])(implicit F: MonadCancel[F, E]): F[A] =
Reverted.

2020-09-25 16:33 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/GenSpawn.scala
> +    backgroundAndEmbed(fa)(never)
I removed these methods.

2020-09-25 16:33 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/Fiber.scala
> +  def joinAndEmbed(onCancel: => F[A])(implicit F: MonadCancel[F, E]): F[A] =
Reverted.

2020-09-25 17:47 UTC, djspiewak commented
🎉

2020-09-25 17:47 UTC, merged