MonadCancel scaladoc
typelevel/cats-effect pull request #1239
Opened 2020-09-25 06:48 UTC by RaasAhsan

First PR for scaladoc-ing the hierarchy. I didn't bother including examples for now

2020-09-25 06:51 UTC, RaasAhsan commented on kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
> +/**
Any way to limit the line width here? I'd hate to make sure every line falls below 80 on my own, would be nice if that was automated by a formatter

2020-09-25 06:52 UTC, RaasAhsan commented on kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
> +  /**
Most of the `bracket` ones are kind of copy-and-paste, not sure if this is the best way to deal with combinators with a ton of variants

2020-09-25 06:56 UTC, RaasAhsan commented on kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
> +/**
Following CE2, I sort of tried to cover the class from a high-level, leaving examples and more explanation to the site documentation. maybe there should be less detail here though

2020-09-25 06:59 UTC, RaasAhsan commented on kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
> -  // produces an effect which is already canceled (and doesn't introduce an async boundary)
I think it's reasonable for an implementation to use an async boundary here if they want

2020-09-25 12:33 UTC, mpilquist approved these changes

2020-09-25 17:44 UTC, djspiewak requested changes
Really really nice

2020-09-25 17:44 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
> + * and finalization. [[MonadCancel]] instances must provide an instance for
Editorial nits:

- We usually use "typeclass" instead of "type class" just to distinguish from the OO thing
- "A typeclass **that**", but "monads **which**" (since the monads are non-specific)
- "masking," (I like the oxford comma since it creates fewer ambiguities in conjoined lists)

2020-09-25 17:44 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
> + *      be reversed.
IMO it's worth adding another sentence here noting the contrast with `handleError`, which allows you to "catch" an error and then continue normally, whereas there is no way to "catch" cancelation.

2020-09-25 17:44 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
> + * terminated. [[MonadCancel]] exposes a means of self-cancellation, where a fiber
I think it's worth clarifying here something like the following:

> In this context, "fiber" means "a chain of effects bound together by `flatMap`". So, `fa.flatMap(a => f(a)).flatMap(b => g(b))` is a fiber (or, more likely, one part of a longer fiber).

2020-09-25 17:44 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
> + *      can be cancelled by external parties. This can be likened to asynchronous exception throwing.
> This can be likened to asynchronous exception throwing.

Is this a helpful piece of information for non-Haskell developers?

2020-09-25 17:44 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
> + * evaluation of that effect, the registered finalizer is guaranteed to be invoked before terminating.
Is it worth mentioning here that finalizers are invoked in nested order, with the inner-most finalizers running first? We could just put that on the `onCancel` doc.

2020-09-25 17:44 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
> +   * Masks cancellation while evaluating an effect, offering the ability to
I like how you introduce the masking terminology without explicitly introducing it. That's really nice.

2020-09-25 17:44 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
> +   * in the opposite order of registration.
Rather than saying "opposite order" I would say something like "innermost-first". We want to get people in the habit of thinking about their program semantics lexically, since those are the semantics we've very strictly enforced across the entire calculus.

2020-09-25 17:44 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
> +   * `onError`, and [[MonadCancel!.onCancel onCancel]].
Note to self: we need to get doclinks setup for cats and stuff.

2020-09-25 17:44 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
> +   * `onError`, and [[MonadCancel!.onCancel onCancel]].
Still `flatTap`.

2020-09-25 17:44 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
> +   * A pattern for interacting with effectful lifecycles.
I love that you're identifying `bracket` as a "pattern". That's perfect.

Do you think it's worth calling out that this is just implemented in terms of `uncancelable` and `onCancel` and friends? Specifically saying something like, if you need more customized bracketing behavior, you may want to use `uncancelable` and `onCancel` directly. Not sure.

2020-09-26 04:31 UTC, RaasAhsan commented on kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
> + *      can be cancelled by external parties. This can be likened to asynchronous exception throwing.
good point

2020-09-26 04:41 UTC, RaasAhsan commented on kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
> + * terminated. [[MonadCancel]] exposes a means of self-cancellation, where a fiber
It actually felt a bit weird to talk about fibers in the context of `MonadCancel` since there is no notion of starting one, but I'll try to fit this in somewhere

2020-09-26 05:52 UTC, RaasAhsan commented on laws/shared/src/main/scala/cats/effect/laws/MonadCancelLaws.scala
> +  def uncancelableFinalizers[A](fin: F[Unit]) =
Added these two new laws, let me know if they even make sense and/or can be minimized more

2020-09-26 12:28 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
> +/**
> Any way to limit the line width here? I'd hate to make sure every line falls below 80 on my own, would be nice if that was automated by a formatter

Not automatically. I usually add a visual ruler guideline in the editor and make sure to follow it manually.

2020-09-28 15:54 UTC, djspiewak commented on laws/shared/src/main/scala/cats/effect/laws/MonadCancelLaws.scala
> +    F.onCancel(F.canceled, F.canceled >> fin) <-> F.onCancel(F.canceled, fin)
I would phrase this a little differently:

```scala
F.onCancel(fa, F.uncancelable(_ => fin)) <-> F.onCancel(fa, fin)
```

Comes down to the same thing, but is a bit more general of a formulation.

2020-09-29 01:40 UTC, merged