Add Semaphore#permit returning Resource
typelevel/cats-effect pull request #1281
Opened 2020-10-07 17:32 UTC by bplommer

Depends on #1280.

This adds an `Applicative` constraint to `imapK` but I can't see that being a problem.

2020-10-07 18:00 UTC, vasilmkd commented on core/shared/src/test/scala/cats/effect/std/SemaphoreSpec.scala
> +          res must beEqualTo(1: Long)
Instead of `(1: Long)` you can write `1L`.

2020-10-07 19:41 UTC, bplommer commented on core/shared/src/test/scala/cats/effect/std/SemaphoreSpec.scala
> +          res must beEqualTo(1: Long)
Sure - I've changed it in the other places in that file too.

2020-10-07 20:10 UTC, vasilmkd commented on core/shared/src/test/scala/cats/effect/std/SemaphoreSpec.scala
> +          res must beEqualTo(1: Long)
It was mostly a nit and knowledge sharing, no worries 😄

2020-10-10 07:41 UTC, bplommer commented
It just occurred to me that if we remove `withPermit` then `imapK` can become `mapK`.

2020-10-10 10:14 UTC, vasilmkd commented
I am really hesitant about removing `withPermit`.

2020-10-10 15:06 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/Semaphore.scala
> +      Resource.make(acquireNInternal(1))(_.release).evalMap(_.await)
Doesn't this have the cancelation issue? (i.e. isn't acquisition here uncancelable?)

2020-10-10 15:10 UTC, SystemFw commented on std/shared/src/main/scala/cats/effect/std/Semaphore.scala
> +      Resource.make(acquireNInternal(1))(_.release).evalMap(_.await)
`acquireNInternal` is Mike's idea of using `F[(F[A], F[Unit]]`, which solves the issues by splitting the state manipulation, which needs restoring but not interruption, from the waiting (which needs interruption but no restoring). It's so general than ZIO actually went with that `F[(F[A], F[Unit])]` for their Resource encoding, but it comes at the cost of having to complicate Semaphore's implementation.

2020-10-10 15:18 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/Semaphore.scala
> +      Resource.make(acquireNInternal(1))(_.release).evalMap(_.await)
Ahhh! Okay then, so `permit` works correctly, which makes me suspect that we simply don't need `withPermit` anymore, right?

2020-10-10 15:19 UTC, SystemFw commented on std/shared/src/main/scala/cats/effect/std/Semaphore.scala
> +      Resource.make(acquireNInternal(1))(_.release).evalMap(_.await)
`withPermit` can be replaced with `permit.use`, yes. The argument now is fully about weighting the `mapK` point in another discussion, with breaking code for users (there is precedent for this type of change in http4s client, which I have an argument for)

2020-10-10 19:12 UTC, bplommer commented on std/shared/src/main/scala/cats/effect/std/Semaphore.scala
> +      Resource.make(acquireNInternal(1))(_.release).evalMap(_.await)
We can also keep `withPermit` as a derived method defined in terms of `permit` - so it will only break user code if a `Resource.Bracket` instance isn't available.

2020-10-10 19:53 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/Semaphore.scala
> +      Resource.make(acquireNInternal(1))(_.release).evalMap(_.await)
I'm in favor of just removing `withPermit` entirely and going with `mapK` instead of `imapK`. Now is the time to clean stuff up. :-D

2020-10-11 02:30 UTC, djspiewak requested changes

2020-10-11 02:30 UTC, djspiewak commented on core/shared/src/test/scala/cats/effect/std/SemaphoreSpec.scala
> +    "permit.use does not leak fibers or permits upon cancelation" in real {
I think this test is redundant now, right?

2020-10-11 07:34 UTC, bplommer commented on core/shared/src/test/scala/cats/effect/std/SemaphoreSpec.scala
> +    "permit.use does not leak fibers or permits upon cancelation" in real {
Why yes, yes it is 🤦‍♂️

2020-10-11 07:48 UTC, bplommer commented
Unrelated test failure:

```
[info]     timeout should
[info]       + succeed
[info]       + cancel a loop
Error:        x invoke finalizers on timed out things
Error:         the value is false (file:///home/runner/work/cats-effect/cats-effect/core/js/target/scala-2.13/cats-effect-test-fastopt.js:35155)
...
Error:  Failed tests:
Error:  	cats.effect.IOSpec
```

2020-10-11 17:27 UTC, djspiewak commented
My bad. Tracking in #1297

2020-10-11 17:29 UTC, bplommer commented
Should we add backport this to CE2 and deprecate `permit` there to help with the transition?

2020-10-11 19:50 UTC, djspiewak commented
I think that would be very worthwhile. Anything we can do to ease the transition is good.

2020-10-11 19:50 UTC, merged

2020-10-11 23:50 UTC, bplommer commented
On second thought, that wouldn't work - with CE2 `Resource` that would require adding new constraints to `imapK`, and we can't remove those constraints from `Resource` without breaking changes.