Add some quality of life utilities
typelevel/cats-effect pull request #1318
Opened 2020-10-17 00:22 UTC by kubukoz

Just some things I wish existed.

2020-10-17 05:12 UTC, RaasAhsan commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +    makeCase(Applicative[F].unit)((_, exit) => release(exit))
There's an `OnFinalizeCase` constructor in the Resource algebra now, should this call out to that, on a empty resource i'm guessing?

2020-10-17 05:12 UTC, RaasAhsan commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +   * Preserves interruptibility of `release`.
`release` is uncancelable by law

2020-10-17 17:31 UTC, kubukoz commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +   * Preserves interruptibility of `release`.
I was following the scaladoc from `liftF`, but I can remove it if it sounds redundant

2020-10-17 17:38 UTC, kubukoz commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +    makeCase(Applicative[F].unit)((_, exit) => release(exit))
Sure, I can reuse that

2020-10-17 19:14 UTC, djspiewak reviewed
Also I think the build failures are legitimate

2020-10-17 19:14 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +    productR(sleep(time))(fa)
Something that might be nice here: invert the order of the two parameters, since the sleep happens before the effect.

2020-10-17 19:14 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +  def useK[G[x] >: F[x]: Resource.Bracket, B >: A]: Kleisli[G, B, *] ~> G =
I think `useKleisliK` would be more consistent

2020-10-17 19:14 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +    use(usage.run)
Now that I think about it, this is a really good idea!

2020-10-17 19:14 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +  def used[G[x] >: F[x]](implicit G: Resource.Bracket[G]): G[Unit] = use(_ => G.unit)
IMO, `use_` would be a more consistent name (think: `traverse` vs `traverse_`).

2020-10-17 19:14 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/syntax/ResourceSyntax.scala
> +  def liftToResource: Resource[F, A] = Resource.liftF(wrapped)
`toResource` maybe?

2020-10-17 19:14 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  val stub: IO[Nothing] = raiseError(new NotImplementedError("This IO is not implemented"))
Should either be a `def` or should use the `private[this] val _stub` pattern we have elsewhere. Public `val`s on objects are *usually* less efficient than `def`s are because of the memory barriers.

2020-10-17 19:17 UTC, kubukoz commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +    productR(sleep(time))(fa)
I don't know, this matches the order you'd call it in on an effect: `print(...).delayBy(10.seconds)` (it's also how the method on IO is defined)

2020-10-17 19:17 UTC, kubukoz commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +    use(usage.run)
It reminds me of `modifyState` in Ref :)

2020-10-17 19:18 UTC, kubukoz commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +  def used[G[x] >: F[x]](implicit G: Resource.Bracket[G]): G[Unit] = use(_ => G.unit)
fair, although I can speak from experience that people don't like yet another usecase of the underscore symbol...

2020-10-17 19:19 UTC, kubukoz commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  val stub: IO[Nothing] = raiseError(new NotImplementedError("This IO is not implemented"))
ok, will change

2020-10-17 19:26 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +  def used[G[x] >: F[x]](implicit G: Resource.Bracket[G]): G[Unit] = use(_ => G.unit)
lol fair

2020-10-17 19:39 UTC, kubukoz commented
I would make sure this is squashed before merging 😅

2020-10-17 21:53 UTC, djspiewak commented
> I would make sure this is squashed when merging

Nah. :-D

2020-10-17 21:54 UTC, djspiewak requested changes

2020-10-17 21:54 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  def stub: IO[Nothing] = _stub
Just realized something interesting: this is going to throw a constant exception with a useless stack trace. We probably should do something like this:

```suggestion
  def stub: IO[Nothing] = {
    val t = new NotImplementedError("this IO is not implemented"))
    raiseError(t)
  }
```

2020-10-17 22:34 UTC, kubukoz commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  def stub: IO[Nothing] = _stub
yeah, I guess this isn't meant to be used in production code so we should rather focus on "experience" things like stack traces than perf.

btw. why the change to lowercase `this`? :D

2020-10-17 23:36 UTC, kubukoz commented
I was expecting it to be whitespace (formatting), but no! It was actually a paren.

2020-10-18 16:19 UTC, kubukoz commented
I think that'd be it for now... Unless there's anything else that needs attention here?

2020-10-18 19:45 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  def stub: IO[Nothing] = _stub
> btw. why the change to lowercase this? :D

IIRC, in most cases, exceptions have lower-case messages

2020-10-18 19:46 UTC, merged

2020-10-18 21:29 UTC, bwiercinski commented on kernel/shared/src/main/scala/cats/effect/kernel/syntax/ResourceSyntax.scala
> +  def toResource: Resource[F, A] = Resource.liftF(wrapped)
`to` is used when you transforming something eg.: `toList`, `toMap`, `toNel`, `toLong`, `toString`

where in `as` you changing the representation of the same thing: `asInstanceOf`, `asLeft`, `asRight`

`asResource`?


ps: my theory doesn't match with `Functor::as`