Run CI on Windows and macOS
typelevel/cats-effect pull request #1321
Opened 2020-10-17 19:08 UTC by vasilmkd

Heavily WIP.

2020-10-20 23:13 UTC, djspiewak requested changes

2020-10-20 23:13 UTC, djspiewak commented on build.sbt
> +    cond = Some("matrix.ci == 'ciJVM' && matrix.os == 'ubuntu-latest'")),
```suggestion
    cond = Some("matrix.ci == 'ciJVM' && matrix.os == PrimaryOS")),
```

2020-10-20 23:13 UTC, djspiewak commented on build.sbt
> +    cond = Some("matrix.ci == 'ciJS' && matrix.os == 'ubuntu-latest'")))
```suggestion
    cond = Some("matrix.ci == 'ciJS' && matrix.os == PrimaryOS")))
```

2020-10-20 23:13 UTC, djspiewak commented on core/jvm/src/test/scala/cats/effect/IOAppSpec.scala
> +      if (System.getProperty("os.name").contains("Windows")) {
Older versions of windows don't use capitalization. This is rather annoying. The workaround:

```suggestion
      if (System.getProperty("os.name").toLowerCase.contains("windows")) {
```

2020-10-20 23:13 UTC, djspiewak commented on core/jvm/src/test/scala/cats/effect/IOAppSpec.scala
> +        ok
```suggestion
        skipped
```

This is a bit more accurate

2020-10-21 07:02 UTC, vasilmkd commented on core/jvm/src/test/scala/cats/effect/IOAppSpec.scala
> +        ok
Skipped doesn't compile as it is not a `MatchResult`...

2020-10-21 07:05 UTC, vasilmkd commented on build.sbt
> +    cond = Some("matrix.ci == 'ciJVM' && matrix.os == 'ubuntu-latest'")),
Done.

2020-10-21 07:05 UTC, vasilmkd commented on core/jvm/src/test/scala/cats/effect/IOAppSpec.scala
> +      if (System.getProperty("os.name").contains("Windows")) {
Done.

2020-10-23 01:36 UTC, djspiewak commented on core/jvm/src/test/scala/cats/effect/IOAppSpec.scala
> +        ok
Welp. Apparently it's `Skipped()`

2020-10-23 17:55 UTC, vasilmkd commented on core/jvm/src/test/scala/cats/effect/IOAppSpec.scala
> +        ok
Also not, that's the same type 😆

2020-10-24 15:52 UTC, djspiewak commented on core/jvm/src/test/scala/cats/effect/IOAppSpec.scala
> +        ok
Okay apparently I don't know specs very well. I'll fiddle with it later :-P

2020-10-24 15:52 UTC, merged

2020-10-24 16:11 UTC, vasilmkd commented on core/jvm/src/test/scala/cats/effect/IOAppSpec.scala
> +        ok
Does anyone? 😄