Add cancellation state machine to Dispatcher
typelevel/cats-effect pull request #1333
Opened 2020-10-19 03:03 UTC by RaasAhsan

This PR fixes two bugs:
1. The one described in #1332 where the unsafe cancel token can return before finalization completes.
2. A benign race where a fiber cancel is called twice when the cancel token was only called once

Fixes #1332

2020-10-19 03:04 UTC, RaasAhsan commented on std/shared/src/main/scala/cats/effect/std/Dispatcher.scala
> -       * We know we never need structural equality on this type. We do, however,
I checked out the javadocs again and `AtomicReference` only performs referential equality to begin with. You can verify with this snippet:
```scala
@ val initialState = (2, 3)
initialState: (Int, Int) = (2, 3)

@ val state = new AtomicReference(initialState)
state: AtomicReference[(Int, Int)] = (2,3)

@ state.compareAndSet((2, 3), (5, 6))
res3: Boolean = false
```

2020-10-20 23:04 UTC, djspiewak requested changes

2020-10-20 23:04 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/Dispatcher.scala
> +import scala.util.Failure
Random stupid preference:

```suggestion
import scala.util.{Failure, Success}
```

2020-10-20 23:04 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/Dispatcher.scala
> -       * We know we never need structural equality on this type. We do, however,
That makes it so much simpler! I did spend some time thinking about this and honestly wondered *how* it could be doing structural equality while keeping things atomic. I had a mental note to decompile the ASM and find out, but I guess it's easier if we just test it and find out that I was wrong. :-P

2020-10-20 23:04 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/Dispatcher.scala
> +    final case class CancelledNoToken(promise: Promise[Unit]) extends CancelState
```suggestion
    final case class CanceledNoToken(promise: Promise[Unit]) extends CancelState
```

Just to be consistent with `F.canceled`

2020-10-20 23:04 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/Dispatcher.scala
> +                    import scala.concurrent.ExecutionContext.Implicits.global
IMO we would be better off using the parasitic executor, but it doesn't exist on Scala 2.12. I'm very leery about the consequences of introducing a random reference to the global pool here. At the *very* least, this could cause it to allocate threads, which otherwise won't happen at all in a well-behaved CE application.

Can we just capture the `ExecutionContext` in the scope using `F.executionContext`?

2020-10-20 23:12 UTC, RaasAhsan commented on std/shared/src/main/scala/cats/effect/std/Dispatcher.scala
> +                    import scala.concurrent.ExecutionContext.Implicits.global
good call, and we only need to capture a reference to it once at the very beginning

2020-10-20 23:49 UTC, merged