Auto yielding
typelevel/cats-effect pull request #1340
Opened 2020-10-19 21:41 UTC by TimWSpence

Auto-yield by inserting in `IO.cede` every specified numbere of iterations. The default is to check for cancellation every 512 iterations of the runloop and to auto-yield every 1024 but this is configurable in the `IORuntime`.

The behaviour of `global` is to check for the system properties `cats.effect.cancellation.check.threshold` and `cats.effect.auto.yield.threshold.multiplier` but to default to 512 and 2 respectively. The auto-yield threshold is the product of these.

2020-10-20 00:12 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    startEC: ExecutionContext,
Should we just start passing in the `IORuntime` into the constructor and adding `private[this]` fields for stuff inside it?

2020-10-20 00:12 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +      runLoop(IO.cede >> _cur0, nextIteration)
So this is actually a `FlatMap(IO.cede, _ => _cur0`, I think there is a case where we're inserting two `cede`s?

Assume that `iterationThreshold` = `autoYieldThreshold` = 512. Let's say that in the current execution, `nextIteration` is 512, so we auto-yield here, and continue the runloop. When we evaluate the `FlatMap`, `iteration` will be 512 so `nextIteration` will be 513, and we run the `FlatMap`. On the _next_ loop, `iteration` will be 513, so `nextIteration` will be 0, so we add insert another `cede`. Am I running through that correctly?

2020-10-20 00:30 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    startEC: ExecutionContext,
There are also other good reasons to do this

2020-10-20 07:26 UTC, TimWSpence commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +      runLoop(IO.cede >> _cur0, nextIteration)
Good spot!! 👍

2020-10-20 10:13 UTC, TimWSpence commented
Also if anyone can tell me why git diff has lost its mind on `IOFiber` I would be very grateful :) The indentation changes are expected but not the rest

2020-10-20 22:57 UTC, djspiewak requested changes

2020-10-20 22:57 UTC, djspiewak commented on core/jvm/src/test/scala/cats/effect/IOPlatformSpecification.scala
> +        run.evalOn(ec).map { res => res mustEqual true }
Should `.guarantee(IO(ec.shutdown()))` on this. Also, `res mustEqual true` can be `res must beTrue` for nicer messages, and also is a side effect and should be wrapped in `IO(...)`

2020-10-20 22:57 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +  private[this] val iterationThreshold = autoYieldThreshold
We do need to check the performance implications of this. I think it would be worth running the benchmarks with this setup, then try swapping in a hard-coded integer value and see how different the results are. *Hopefully* the difference will be negligable.

2020-10-20 22:57 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +      runLoop(IO.cede >> _cur0, nextIteration)
I also think this will be a lot easier (and cheaper!!) if we explicitly manipulate the continuation stack and `reschedule` the same as the implementation of `Cede`. We could probably extract that as common code in some tiny function somewhere without any performance impact.

2020-10-20 22:57 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntime.scala
> +)
Minor preference:

```suggestion
    val autoYieldThreshold: Int)
```

2020-10-20 22:57 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntime.scala
> +      )
```suggestion
        autoYieldThreshold)
```

2020-10-21 08:42 UTC, TimWSpence commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +  private[this] val iterationThreshold = autoYieldThreshold
You mean because it's not a constant and hence can't be inlined? I had wondered about this...

2020-10-23 01:16 UTC, djspiewak commented
I'm going to merge this so we can unblock M2, but we should follow-up on a) getting the benchmarks running, b) testing the relative performance impact of this whole change, and c) testing the relative performance impact of the way we're encoding the tuning parameters.

2020-10-23 01:23 UTC, djspiewak commented
I'm going to merge this to unblock M2, but we need to follow up on the remaining issues:

- Can improve performance of the autoyield by adding a special new `K` type rather than reusing `FlatMapK`. This special new type would avoid the `Function1` allocation
- Have to fix the benchmarks
- Test the relative performance impact of this change (relative to having it off)
- Test the relative performance impact of this constant encoding, rather than some alternative one where the JVM knows that the constants are always the same value forever and thus can inline more aggressively (like with `IOFiberConstants`)

2020-10-23 01:23 UTC, merged