Exit on fatal error
typelevel/cats-effect pull request #1349
Opened 2020-10-22 10:08 UTC by vasilmkd

Implement proper fatal error handling in the work stealing pool.

Fixes #1327.

2020-10-23 01:34 UTC, djspiewak requested changes

2020-10-23 01:34 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +        fiber.errorCb(Left(t))
Oh! This is much nicer than what I was thinking of. The problem though is that we may have multiple separate fiber chains running on the same pool. Specifically, if someone is doing `unsafeRunSync()` multiple times against the same `IORuntime`. I think I'm kind of okay with all-but-one of them deadlocking though.

2020-10-23 01:34 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +        System.exit(1)
IMO we shouldn't exit. Let's allow the downstream callback to do that. However, we *should* completely shut down the pool.

2020-10-23 01:34 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    val errorCb: Left[Throwable, Nothing] => Unit
This is just `Throwable => Unit`. Also should be `private[effect] val`. This is actually pretty important because we can't really allocate reliably after an OOM.

2020-10-23 01:34 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +      cb
The wrapping in `Left` should be here, IMO, and in some cases (e.g. `unsafeRunSync()`) we can avoid it altogether by slightly revising the signature of `unsafeRunFiber` (to take a `Throwable => Unit` and an `A => Unit` instead of a single one with `Either`).

2020-10-23 06:57 UTC, RaasAhsan commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +      case t: Throwable =>
This is catching all throwables (rather than just fatal `Error`s); is there another `try`/`catch` inside `fiber.run()` that catches nonfatal exceptions?

2020-10-23 06:57 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    val errorCb: Left[Throwable, Nothing] => Unit
Eventually it's going to be lifted into a `Left` anyways though, since that's the signature of `cb`. It seems kind of futile to catch these fatal errors :P

2020-10-23 06:57 UTC, RaasAhsan commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +        System.exit(1)
What are the behaviors of the default `Executors` with respect to fatal errors? I'm a bit in favor of keeping consistent with that behavior unless there's a really good reason not to

2020-10-23 07:06 UTC, vasilmkd commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +      case t: Throwable =>
Yes, the `IOFiber` runloop catches non fatal errors.

2020-10-23 07:11 UTC, vasilmkd commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +        System.exit(1)
Downstream callback may not exit the VM, think about `unsafeRunSync()` from anywhere. You're right coupled with your previous comment about only one fiber chain being notified, this solution doesn't cut it.

2020-10-23 07:12 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    val errorCb: Left[Throwable, Nothing] => Unit
We must do _something_, currently a fatal error crashes a carrier thread from the work stealing thread pool and the program continues as if nothing happened. Feel free to try it.

2020-10-23 14:12 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    val errorCb: Left[Throwable, Nothing] => Unit
> Eventually it's going to be lifted into a Left anyways though, since that's the signature of cb. It seems kind of futile to catch these fatal errors :P

Doesn't have to be. We can avoid the lifting for `unsafeRunSync` for example.

2020-10-23 14:12 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +      case t: Throwable =>
There also isn't a particularly clean "catch only fatal errors" mechanism, much less one I would trust when the VM is on fire because of one. Catching `Throwable` also has the advantage that we sweep up `InterruptedException`, which is currently incorrectly handled.

2020-10-25 00:40 UTC, vasilmkd commented
This is now basically a different PR, but I guess it could be useful to keep the old comments.

I have used the following `IOApp` for testing, let me know if the results are satisfying.
```scala
/*
 * Copyright 2020 Typelevel
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cats.effect

import scala.concurrent.duration._

object CatsEffectApp extends IOApp.Simple {
  def run: IO[Unit] =
    for {
      _ <- IO.sleep(10.seconds)
      _ <- IO[Unit](throw new OutOfMemoryError("Boom!"))
    } yield ()
}
```

Console output:
<img width="668" alt="Screen Shot 2020-10-25 at 02 10 22" src="https://user-images.githubusercontent.com/7115459/97096335-010ef000-166b-11eb-9e41-55f0afa9124a.png">

JDK Mission Control screenshot during execution:
<img width="932" alt="Screen Shot 2020-10-25 at 02 34 24" src="https://user-images.githubusercontent.com/7115459/97096345-1a17a100-166b-11eb-9c8c-66f80552211e.png">

JDK Mission Control screenshot after execution:
<img width="932" alt="Screen Shot 2020-10-25 at 02 34 49" src="https://user-images.githubusercontent.com/7115459/97096349-2bf94400-166b-11eb-9dfb-9a36327b3934.png">

Activity Monitor screenshot after execution (no spinning threads):
<img width="826" alt="Screen Shot 2020-10-25 at 02 39 02" src="https://user-images.githubusercontent.com/7115459/97096358-492e1280-166b-11eb-9793-97168996563d.png">

Resolves #1327.
Resolves #1355.

2020-10-25 00:42 UTC, vasilmkd commented
I also apologize in advance for implementing another questionable concurrent data structure.

2020-10-25 00:43 UTC, vasilmkd commented
Special thanks to @djspiewak, I would not have been able to come close to this solution without your help.

2020-10-25 02:14 UTC, djspiewak commented
> unsafeRunSync() operations are fairly rare in practice, so they don't need high performance concurrency.

Exactly this. I think locking is actually okay here.

2020-10-25 02:23 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +      IO(runnable.run()).unsafeRunFiber(reportFailure, _ => ())(self)
Amusingly, I completely forgot this was a source of unsafe running…

2020-10-25 02:23 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +          t => {
Very minor nit: I generally prefer `{ t =>` rather than `t => {` (since the former syntax works with paren-less function calls while the latter syntax does not)

2020-10-25 02:23 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +        runtime.internalShutdown()
I think we have to shut down the runtime *before* we notify the callbacks, otherwise one could sneak in as we're notifying.

2020-10-25 02:23 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntime.scala
> +    private[effect] val compute: ExecutionContext,
I think that @SystemFw wanted these to be public. `blocking` is the one that really needs to be private; technically the other two can be public without a problem, I think.

2020-10-25 02:23 UTC, djspiewak commented on core/jvm/src/test/scala/cats/effect/IOAppSpec.scala
> +        _ <- IO(IO(throw new OutOfMemoryError("Boom!")).start.void.unsafeRunSync())
This test is probably more interesting if you add a few more lines like `_ <- IO(IO.never.unsafeRunSync()).start` to this for-comprehension.

2020-10-25 09:16 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntime.scala
> +    private[effect] val compute: ExecutionContext,
Oh wow, I have made it exactly opposite to what's needed here https://github.com/typelevel/cats-effect/issues/1298, my bad...

2020-10-25 09:32 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/IO.scala
> +          t => {
Unwanted syntax gone.

2020-10-25 09:35 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntime.scala
> +    private[effect] val compute: ExecutionContext,
Done.

2020-10-25 11:31 UTC, vasilmkd commented on core/jvm/src/test/scala/cats/effect/IOAppSpec.scala
> +        _ <- IO(IO(throw new OutOfMemoryError("Boom!")).start.void.unsafeRunSync())
Done.

2020-10-25 11:31 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +        runtime.internalShutdown()
Done. I made sure to handle interruption coming from the shutdown, hopefully this is how it should be done. Please check again.

2020-10-25 14:10 UTC, djspiewak approved these changes

2020-10-25 14:10 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> -    workerThreads.foreach(_.join())
Out of curiosity, what are the implications of removing this joining?

2020-10-25 14:31 UTC, vasilmkd commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> -    workerThreads.foreach(_.join())
If attempted from inside the pool, from a worker thread, it will try to join itself and deadlock.

2020-10-26 16:25 UTC, merged