On jvm IOApp clean exit, optionally print non-daemon threads
typelevel/cats-effect pull request #1379
Opened 2020-11-02 17:27 UTC by Daenyth

Debugging when a jvm is being held open due to non-daemon threads is a royal
pain. Try to help users here (who might not even know this can happen) by
giving the option to debug, which we can put into a FAQ entry

I opted for making it configurable here since this isn't a problem for most
people, and there's no reason to slow down the shutdown for it unless debugging

2020-11-02 20:53 UTC, mpilquist requested changes

2020-11-02 20:53 UTC, mpilquist commented on core/jvm/src/main/scala/cats/effect/internals/IOAppPlatform.scala
> +        logNonDaemonThreads()
I think this logging should occur periodically -- e.g., maybe every 10s after completion of the main fiber, with the first log occurring after 10s, not immediately.

2020-11-02 20:53 UTC, mpilquist commented on core/jvm/src/main/scala/cats/effect/internals/IOAppPlatform.scala
> +      if (Option(System.getProperty("cats.effect.logNonDaemonThreadsOnExit")).exists(_.equalsIgnoreCase("true")))
I'd rather default this to on -- it's a common gotcha and folks won't know to enable it without looking in FAQ or getting directed via chat.

2020-11-02 20:53 UTC, mpilquist commented on core/jvm/src/main/scala/cats/effect/internals/IOAppPlatform.scala
> +    println("IOApp Debug: Checking for non-daemon Threads prior to exit")
Minor thing but I'd rather create 1 multi-line string and then make one call to print to standard error.

2020-11-02 20:53 UTC, mpilquist commented on core/jvm/src/main/scala/cats/effect/internals/IOAppPlatform.scala
> +      println(" - (no non-daemon threads running)")
No need to print at all if there are no active threads.

2020-11-02 22:21 UTC, arosien commented on core/jvm/src/main/scala/cats/effect/internals/IOAppPlatform.scala
> +        logNonDaemonThreads()
OTOH you don't want to introduce a 10s delay just to end the program.

2020-11-02 22:28 UTC, mpilquist commented on core/jvm/src/main/scala/cats/effect/internals/IOAppPlatform.scala
> +        logNonDaemonThreads()
Right, start a daemon thread that has a `while(true) { Thread.sleep(10000L); logActiveThreads() }`

2020-11-05 21:44 UTC, Daenyth commented on core/jvm/src/main/scala/cats/effect/internals/IOAppPlatform.scala
> +        logNonDaemonThreads()
Oh that's clever. I can see about doing that.

2020-11-05 21:45 UTC, Daenyth commented
@mpilquist Thanks for the feedback. I'll try to get that cleaned up this weekend. Feel free to poke me if I don't ;)

2020-11-12 21:28 UTC, mpilquist approved these changes

2020-11-12 22:07 UTC, Daenyth commented
The re-push was just the fix the "missing headers" CI failure. No changes aside from that

2020-11-13 14:08 UTC, Daenyth commented
- Fixed the sleep time being 1sec; made it 10.
- How do I do java collection compat across 2.12+2.13? It looks like collections-compat isn't in scope. Should I add it?

 https://github.com/typelevel/cats-effect/runs/1393002433#step:14:40

2020-11-13 15:40 UTC, Daenyth commented
I fixed the collections-compat part.

I think this should be ready for merge now.

I don't think it's a blocker, but I'm wondering how I could possibly write a unit test for this kind of behavior, though. It seems very hard to do. Any suggestions?

2020-11-14 03:10 UTC, merged

2020-11-14 03:13 UTC, djspiewak commented
Merged; thank you!

I don't think it needs unit testing. Probably possible, definitely annoying, limited value. :-)