Add helper for the equivalent of java.time.Instant.now
typelevel/cats-effect pull request #1382
Opened 2020-11-03 22:45 UTC by jatcwang

2020-11-06 00:01 UTC, vasilmkd requested changes
This is an idea, could we have a single name, e.g. `now` for all of these effects, but they all return a platform specific type (`Instant` on the JVM and `js.Date` on Scala.js)?

cc @djspiewak

2020-11-06 00:01 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/SyncIOCompanionPlatform.scala
> +    syncForSyncIO.map(syncForSyncIO.realTime)(d => new js.Date(d.toMillis.toDouble))
`realTime` is defined on the `SyncIO` companion object and `map` on `SyncIO`, so you should be able to rewrite this as `realTime.map(d => new js.Date(d.toMillis.toDouble))`.

2020-11-06 00:01 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/SyncIOCompanionPlatform.scala
> +private[effect] trait SyncIOCompanionPlatform { this: SyncIO.type =>
Use `abstract class` instead of `trait` to match the other platform specific mixins.

2020-11-06 00:01 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/SyncIOCompanionPlatform.scala
> +import scalajs.js
Nitpicking, we usually have imports separated by a line from the package definition.

2020-11-06 00:01 UTC, vasilmkd commented on core/jvm/src/main/scala/cats/effect/SyncIOCompanionPlatform.scala
> +    syncForSyncIO.map(syncForSyncIO.realTime)(d => Instant.ofEpochMilli(d.toMillis))
`realTime.map(...)`

2020-11-06 00:01 UTC, vasilmkd commented on core/jvm/src/main/scala/cats/effect/SyncIOCompanionPlatform.scala
> +private[effect] trait SyncIOCompanionPlatform { this: SyncIO.type =>
`abstract class` instead of `trait`.

2020-11-06 00:01 UTC, vasilmkd commented on kernel/jvm/src/main/scala/cats/effect/kernel/ClockPlatform.scala
> +  def instantNow: F[java.time.Instant] =
No need for fully qualified `java.time.Instant`, just `Instant`.

2020-11-06 00:03 UTC, vasilmkd commented
@jatcwang There were some GitHub Actions changes in the meantime, please rebase your changes onto the current `series/3.x` or merge it in your branch to be able to pass the CI. :)

2020-11-06 08:50 UTC, jatcwang commented on core/js/src/main/scala/cats/effect/SyncIOCompanionPlatform.scala
> +private[effect] trait SyncIOCompanionPlatform { this: SyncIO.type =>
Do you know what that's done since a trait would suffice? I tried abstract class first and was running into compile errors (since it needs to be the first after `extends`)

2020-11-06 23:34 UTC, jatcwang reviewed
@vasilmkd thanks for the review. Regarding `now` returning different type in different context: I'm not sure it feels a bit weird that you can type the same code and end up with a different type

2020-11-06 23:34 UTC, jatcwang commented on core/js/src/main/scala/cats/effect/SyncIOCompanionPlatform.scala
> +import scalajs.js
nw changed

2020-11-06 23:34 UTC, jatcwang commented on core/jvm/src/main/scala/cats/effect/SyncIOCompanionPlatform.scala
> +    syncForSyncIO.map(syncForSyncIO.realTime)(d => Instant.ofEpochMilli(d.toMillis))
done

2020-11-06 23:34 UTC, jatcwang commented on kernel/jvm/src/main/scala/cats/effect/kernel/ClockPlatform.scala
> +  def instantNow: F[java.time.Instant] =
oops removed

2020-11-06 23:34 UTC, jatcwang commented on core/js/src/main/scala/cats/effect/SyncIOCompanionPlatform.scala
> +    syncForSyncIO.map(syncForSyncIO.realTime)(d => new js.Date(d.toMillis.toDouble))
fixed

2020-11-07 00:14 UTC, vasilmkd commented
This code is already platform specific (not portable and you cannot abstract over it) so there is no way to get different behavior/type by using the same code on different platforms. It was just an idea anyway. Congratulations on your first contribution. We'll get this merged soon enough, let's hear more suggestions on the naming.

2020-11-14 04:00 UTC, djspiewak requested changes

2020-11-14 04:00 UTC, djspiewak commented on core/js/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +  def jsDateNow: IO[js.Date] = asyncForIO.jsDateNow
I would say a better name for this would be `realTimeDate`

2020-11-14 04:00 UTC, djspiewak commented on core/js/src/main/scala/cats/effect/SyncIOCompanionPlatform.scala
> +  final def jsDateNow: SyncIO[js.Date] = realTime.map(d => new js.Date(d.toMillis.toDouble))
Ditto `realTimeDate`

2020-11-14 04:00 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +  def instantNow: IO[Instant] = asyncForIO.instantNow
I would say `realTimeInstant` here.

2020-11-14 04:00 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/SyncIOCompanionPlatform.scala
> +  final def now: SyncIO[Instant] = realTime.map(d => Instant.ofEpochMilli(d.toMillis))
Also `realTimeInstant`

2020-11-14 04:00 UTC, djspiewak commented on kernel/js/src/main/scala/cats/effect/kernel/ClockPlatform.scala
> +  def jsDateNow: F[js.Date] = self.map(self.realTime)(d => new js.Date(d.toMillis.toDouble))
`realTimeDate`

2020-11-14 04:00 UTC, djspiewak commented on kernel/jvm/src/main/scala/cats/effect/kernel/ClockPlatform.scala
> +  def instantNow: F[Instant] = {
`realTimeInstant`

2020-11-14 04:00 UTC, djspiewak commented on kernel/jvm/src/main/scala/cats/effect/kernel/ClockPlatform.scala
> +    self.map(self.realTime)(d => Instant.ofEpochMilli(d.toMillis))
Here's an interesting problem: if `Clock` no longer extends `Applicative`, then we can't actually do this!

2020-11-14 04:06 UTC, djspiewak commented
I really like where this is going! Also it's very much in line with ce2, which I believe has `realTimeInstant` or something like that.

2020-11-14 17:25 UTC, jatcwang commented on core/js/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +  def jsDateNow: IO[js.Date] = asyncForIO.jsDateNow
changed.

2020-11-14 17:25 UTC, jatcwang commented on core/js/src/main/scala/cats/effect/SyncIOCompanionPlatform.scala
> +  final def jsDateNow: SyncIO[js.Date] = realTime.map(d => new js.Date(d.toMillis.toDouble))
changed.

2020-11-14 17:25 UTC, jatcwang commented on core/jvm/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +  def instantNow: IO[Instant] = asyncForIO.instantNow
changed.

2020-11-14 17:26 UTC, jatcwang commented on core/jvm/src/main/scala/cats/effect/SyncIOCompanionPlatform.scala
> +  final def now: SyncIO[Instant] = realTime.map(d => Instant.ofEpochMilli(d.toMillis))
changed.

2020-11-14 17:26 UTC, jatcwang commented on kernel/js/src/main/scala/cats/effect/kernel/ClockPlatform.scala
> +  def jsDateNow: F[js.Date] = self.map(self.realTime)(d => new js.Date(d.toMillis.toDouble))
changed.

2020-11-14 17:26 UTC, jatcwang commented on kernel/jvm/src/main/scala/cats/effect/kernel/ClockPlatform.scala
> +  def instantNow: F[Instant] = {
changed.

2020-11-14 17:31 UTC, jatcwang commented on kernel/jvm/src/main/scala/cats/effect/kernel/ClockPlatform.scala
> +    self.map(self.realTime)(d => Instant.ofEpochMilli(d.toMillis))
Yeah I think I saw the conversation :sweat_smile: Makes sense to remove the constraint but will have to require an applicative instance for the def? I think that's fine in practical usage, though it's a bit weird as it leaks the implementation.

2020-11-14 17:37 UTC, jatcwang commented
@djspiewak It was called instantNow :sweat_smile: but I think the common realTime* prefix is good for discoverability.

@vasilmkd thanks for the review. I have yet to make the change for trait -> abstract class as suggested as I'm keen on understanding why we're not using trait (Ensure a linear inheritance chain?)

2020-11-15 03:26 UTC, djspiewak commented
> I'm keen on understanding why we're not using trait (Ensure a linear inheritance chain?)

Two reasons, historically! First, class inheritance on the JVM is much faster than interface inheritance. Second, prior to the changes in Scala 2.12, traits imposed significantly more severe binary compatibility constraints than abstract classes. For example, it was impossible to add a new method *implementation* in a super-trait without breaking binary compatibility, whereas abstract classes do not have this issue since they didn't require forwarders in the subtypes. This problem is now resolved, though some other subtleties remain.

In general, you should prefer abstract classes over traits unless there's a strong reason to use traits.

2020-11-16 21:20 UTC, jatcwang commented
Thanks for the info Daniel. TIL.

I switched to abstract class but now we're getting issues from the likes of `clockForEitherT`. 

```
[error] kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala:118:18: illegal inheritance; superclass Object
[error]  is not a subclass of the superclass ClockPlatform
[error]  of the mixin trait OptionTClock
[error]       with Clock.OptionTClock[F] {             
```

So I think I can change  OptionTClock to be `abstract class` but that'll have a cascading effect since e.g. `OptionTTemporal` mixes in `Clock.OptionTClock` (we'll in turn need to change OptionTTemporal to be an abstract class and shuffle it around for any class that extends it).
I think this was the original reason why I didn't use abstract class. If you think it'll work I will give it a go - just want to double check before I jump into the black hole :)

2020-11-16 22:32 UTC, djspiewak commented
LOL I would just go back to the `trait`. I don't think anyone wants to diagnose those kinds of compile errors.

2020-11-16 23:21 UTC, ritschwumm commented on core/js/src/main/scala/cats/effect/SyncIOCompanionPlatform.scala
> +    syncForSyncIO.map(syncForSyncIO.realTime)(d => new js.Date(d.toMillis.toDouble))
is this behaving sensible for dates outside the JS date range as mentioned here https://github.com/scala-js/scala-js/issues/4131 ?

2020-11-16 23:22 UTC, ritschwumm commented on core/js/src/main/scala/cats/effect/SyncIOCompanionPlatform.scala
> +  final def realTimeDate: SyncIO[js.Date] = realTime.map(d => new js.Date(d.toMillis.toDouble))
is this behaving sensibly for dates outside the JS date range as mentioned here https://github.com/scala-js/scala-js/issues/4131 ?

2020-11-17 20:18 UTC, jatcwang commented on core/js/src/main/scala/cats/effect/SyncIOCompanionPlatform.scala
> +  final def realTimeDate: SyncIO[js.Date] = realTime.map(d => new js.Date(d.toMillis.toDouble))
It'll behave just like how js Date would behave ("Invalid Date"). The issue you linked is about the behaviour of java.util.Date#getTime which isn't what we're dealing with here.

2020-11-18 22:51 UTC, djspiewak requested changes
Looks like just one last thing and this is ready! :tada:

2020-11-18 22:51 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/SyncIOCompanionPlatform.scala
> +  final def now: SyncIO[Instant] = realTime.map(d => Instant.ofEpochMilli(d.toMillis))
Was this one missed?

2020-11-18 23:51 UTC, jatcwang commented on core/jvm/src/main/scala/cats/effect/SyncIOCompanionPlatform.scala
> +  final def now: SyncIO[Instant] = realTime.map(d => Instant.ofEpochMilli(d.toMillis))
Sorry this one fell out of of the rename train. Fixed now.

2020-11-19 00:33 UTC, merged