On Windows run only latest stable Scala
typelevel/cats-effect pull request #1401
Opened 2020-11-09 21:10 UTC by vasilmkd

2020-11-09 21:23 UTC, djspiewak commented on build.sbt
> +  }
Isn't it easier to do this as a matrix inclusion?

2020-11-09 21:32 UTC, vasilmkd commented on build.sbt
> +  }
TIL.

2020-11-09 21:49 UTC, vasilmkd commented on build.sbt
> +  }
A little help please:
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-including-new-combinations

results in:
```java.lang.RuntimeException: inclusion key `os` was present in matrix, but value `windows-latest` was not in List(ubuntu-latest)```

2020-11-11 17:06 UTC, djspiewak requested changes

2020-11-11 17:06 UTC, djspiewak commented on build.sbt
> +)
The trick here is you have to include *all* keys. So you probably want the following:

```suggestion
ThisBuild / githubWorkflowBuildMatrixInclusions += MatrixInclude(
  Map("scala" -> Scala213, "java" -> PrimaryJava, "ci" -> "ciJVM"),
  Map("os" -> Windows)
)
```

2020-11-11 22:29 UTC, merged