Countdown latch for std
typelevel/cats-effect pull request #1404
Opened 2020-11-10 10:14 UTC by TimWSpence

2020-11-10 10:25 UTC, SystemFw reviewed
Looks good, small comments here and there

2020-11-10 10:25 UTC, SystemFw commented on core/shared/src/test/scala/cats/effect/std/CountDownLatchSpec.scala
> +  sequential
why are these `sequential`?

2020-11-10 10:25 UTC, SystemFw commented on std/shared/src/main/scala/cats/effect/std/CountDownLatch.scala
> +      }.flatten
let's make this `uncancelable`

2020-11-10 10:25 UTC, SystemFw commented on std/shared/src/main/scala/cats/effect/std/CountDownLatch.scala
> + * until n latches are released
Worth adding a comment about this being one-shot (in slightly less concise terms :) )

2020-11-10 11:26 UTC, TimWSpence commented on core/shared/src/test/scala/cats/effect/std/CountDownLatchSpec.scala
> +  sequential
Because I copied the header from `QueueSpec` 😂 I'm not actually sure why it needs `sequential` either?

2020-11-10 11:26 UTC, TimWSpence commented on std/shared/src/main/scala/cats/effect/std/CountDownLatch.scala
> + * until n latches are released
Yep, good call 👍

2020-11-10 11:28 UTC, SystemFw commented on core/shared/src/test/scala/cats/effect/std/CountDownLatchSpec.scala
> +  sequential
yeah I would remove it unless someone else has a reason for it. I vaguely recall one place where it was actually needed, but then I think it spread through copy-paste

2020-11-10 11:29 UTC, TimWSpence commented on std/shared/src/main/scala/cats/effect/std/CountDownLatch.scala
> +      }.flatten
Oh good point! Just to check my understanding: if we observed cancellation after `modify` and before `flatten` then we would have transitioned to the `Done` state without ever unblocking the fibers by completing the `signal`?

2020-11-10 11:30 UTC, SystemFw commented on std/shared/src/main/scala/cats/effect/std/CountDownLatch.scala
> +      }.flatten
exactly. You can solve it by adding an `onCancel` that checks the state yada-yada, but because `complete` is not a long-lived operation, it's overwhelmingly better to just make the whole thing `uncancelable` (since `modify` is already uncancelable anyway)

2020-11-14 03:18 UTC, djspiewak commented on core/shared/src/test/scala/cats/effect/std/CountDownLatchSpec.scala
> +  sequential
Only the laws tests need `sequential`. Everything else can be in parallel for maximum speeds. :-)

2020-11-14 03:20 UTC, djspiewak requested changes
Minor comment but otherwise good!

2020-11-14 03:20 UTC, djspiewak commented on core/shared/src/test/scala/cats/effect/std/CountDownLatchSpec.scala
> +    s"$name - raise an exception when constructed with negative initial latches" in real {
`name should {` :-)

2020-11-18 23:10 UTC, merged