Add `backgroundOn` and `startOn` combinators.
typelevel/cats-effect pull request #1632
Opened 2021-01-29 17:17 UTC by Wosin

This PR introduces new combinators `backgroundOn` and `startOn` as described in https://github.com/typelevel/cats-effect/issues/1613.

Not sure if we need any additional tests, if so I will be happy to add them.

2021-01-30 17:28 UTC, djspiewak requested changes
Nice! Just a few changes but this looks very good

2021-01-30 17:28 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +
These don't actually have to be abstract, since they have a trivial definition in terms of `evalOn` and such. In fact, if you do that, then you can remove all of the transformer-specific implementations below

2021-01-30 17:28 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +
Like this. All of these can go away if we give `startOn`/`backgroundOn` a default concrete implementation.

2021-01-30 17:28 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +
Also here

2021-01-30 17:28 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +
I think we actually don't need to override these, because the implementation is directly identical to what we would have in `IO`-proper.

2021-01-30 17:28 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +  def startOn[A](fa: F[A], ec: ExecutionContext): F[Fiber[F, Throwable, A]]
Also, can you add these to the `AsyncOps` type so that they're available using infix syntax? (e.g. `fa.startOn(ec)`)

2021-01-30 22:17 UTC, djspiewak commented
I had another thought! I think we should do `.start.evalOn(ec)` for the implementation, rather than `.evalOn(ec).start`. The scenario I'm thinking of here is if we imagine that the *outer* EC is resource-constrained in some way, shifting to the new one before `start`ing and then shifting back is going to yield more intuitive results than the other way around, since it gets the scheduling work onto the new pool.

2021-02-01 23:32 UTC, Wosin commented
Sure, but I assume we should do exactly the same for `backgroundOn` am I right here ??

2021-02-02 06:24 UTC, djspiewak commented
> Sure, but I assume we should do exactly the same for backgroundOn am I right here ??

Yep!

2021-02-03 00:26 UTC, Wosin commented
I will be happy to rebase the commits since I've created quite a lotte of them.

2021-02-06 04:40 UTC, djspiewak requested changes
Hey! Sorry for my tardiness. It's been a week. :-) Some slight adjustments and I think this is good to go!

2021-02-06 04:40 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    background.map(f => f.evalOn(ec))
Ah! This is subtle but actually wrong. It will take the current `IO[A]` and run it *on the current pool* and then run the `join` on the specified pool. I believe you want the following.

```suggestion
    evalOn(ec).background
```

2021-02-06 04:40 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +    background(fa).map(f => evalOn(f, ec))
Same problem as above!

```suggestion
    background(evalOn(f, ec))
```

2021-02-06 04:40 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/syntax/AsyncSyntax.scala
> +    Async[F].backgroundOn(wrapped, ec)
:+1:

2021-02-07 18:45 UTC, kubukoz commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  def startOn(ec: ExecutionContext): IO[FiberIO[A @uncheckedVariance]] = start.evalOn(ec)
This would probably need a similar change to what Daniel mentioned below:

```suggestion
  def startOn(ec: ExecutionContext): IO[FiberIO[A @uncheckedVariance]] = evalOn(ec).start
```

2021-02-07 18:47 UTC, kubukoz commented
> I had another thought! I think we should do .start.evalOn(ec) for the implementation, rather than .evalOn(ec).start. The scenario I'm thinking of here is if we imagine that the outer EC is resource-constrained in some way, shifting to the new one before starting and then shifting back is going to yield more intuitive results than the other way around, since it gets the scheduling work onto the new pool.

Now I'm lost :D in `backgroundOn`, you suggested to do `evalOn` first, then do `background` on that?

2021-02-07 19:05 UTC, djspiewak commented
Oh crap I think I inverted it. The first suggestion was right. My background thing was wrong. I'll review more carefully today to disambiguate

2021-02-11 18:20 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +    background(fa).map(f => evalOn(f, ec))
Correction, I think this is a more accurate suggestion:

```suggestion
    Resource.make(evalOn(start, ec))(_.cancel).map(_.join)
```

Basically I don't think there's a way to reuse the implementation of `background` itself because of the inversion problem.

2021-02-11 18:21 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    background.map(f => f.evalOn(ec))
A more accurate suggestion:

```suggestion
    Resource.make(start.evalOn(ec))(_.cancel).map(_.join)
```

2021-02-11 23:56 UTC, kubukoz commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  def startOn(ec: ExecutionContext): IO[FiberIO[A @uncheckedVariance]] = start.evalOn(ec)
ignore ;)

2021-02-14 21:19 UTC, Wosin commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    background.map(f => f.evalOn(ec))
Okay, sounds cool. Will fix.

2021-02-16 01:42 UTC, kubukoz approved these changes

2021-02-17 06:54 UTC, merged

2021-02-17 06:54 UTC, djspiewak commented
Thank you!