feat: timed syntax for GenTemporal
typelevel/cats-effect pull request #1677
Opened 2021-02-11 19:56 UTC by patseev

Addresses this issue:
https://github.com/typelevel/cats-effect/issues/1672

2021-02-11 20:36 UTC, djspiewak requested changes
This is fantastic. Just the one small change about `monotonic` vs `realTime`, and additionally I think it can be moved up to `Clock` since it doesn't rely on `sleep` or anything concurrent.

2021-02-11 20:36 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +    map3(realTime, fa, realTime)((startTime, a, endTime) => (endTime.minus(startTime), a))
Close! We *definitely* want to use `monotonic` here. For starters, it's much faster and higher resolution than `realTime`, but additionally it doesn't suffer from re-sync issues. If someone changes the system time between `startTime` and `endTime`, for example, the result here will be inaccurate. `monotonic` doesn't have that problem

```suggestion
    map3(monotonic, fa, monotonic)((startTime, a, endTime) => (endTime.minus(startTime), a))
```

Also given that we're doing this with `Applicative`, I *think* it can just be on `Clock` instead!

2021-02-11 21:19 UTC, patseev commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +    map3(realTime, fa, realTime)((startTime, a, endTime) => (endTime.minus(startTime), a))
Done! Thank you for your feedback

2021-02-11 21:20 UTC, patseev commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +    map3(realTime, fa, realTime)((startTime, a, endTime) => (endTime.minus(startTime), a))
Appears I broke something, I'll check a bit later

2021-02-11 21:25 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +    map3(realTime, fa, realTime)((startTime, a, endTime) => (endTime.minus(startTime), a))
You just need to do `scalafmtAll` in `sbt`.

2021-02-11 23:54 UTC, kubukoz requested changes

2021-02-11 23:54 UTC, kubukoz commented on kernel/shared/src/main/scala/cats/effect/kernel/syntax/ClockSyntax.scala
> +}
minor: I'd suggest adding a newline here (POSIX-compliant files have that, it helps in printing etc.)

2021-02-11 23:54 UTC, kubukoz commented on kernel/shared/src/main/scala/cats/effect/kernel/syntax/ClockSyntax.scala
> +  implicit def clockOps[F[_], A, E](wrapped: F[A])(implicit F: Clock[F]): ClockOps[F, A] =
This constraint seems unused to me - we require another Clock at the callsite of `timed`. I would remove this one and keep the one on the method. If you saw this somewhere else in CE, please update these ones as well! (or create an issue to do so before 3.0 final) :)

2021-02-12 00:45 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/syntax/ClockSyntax.scala
> +  implicit def clockOps[F[_], A, E](wrapped: F[A])(implicit F: Clock[F]): ClockOps[F, A] =
The constraint is redundant *but* it makes the type inference better. Cats uses the same pattern.

2021-02-12 01:09 UTC, kubukoz commented on kernel/shared/src/main/scala/cats/effect/kernel/syntax/ClockSyntax.scala
> +  implicit def clockOps[F[_], A, E](wrapped: F[A])(implicit F: Clock[F]): ClockOps[F, A] =
hmm. It also makes the extension methods less visible in IDEs, but I'll defer to you

2021-02-12 07:41 UTC, patseev commented
Made all requested changes. 
@djspiewak @kubukoz should I target 2.x with the same utils?
I suppose I won't be able to put it into Clock because there's no applicative there, but I could create similar `ClockSyntax` with implicit requirement of `Applicative` to make it work. What do you think?

2021-02-12 11:37 UTC, kubukoz commented
I would like to see that, but I'm not sure we should do that...

2021-02-12 11:38 UTC, joroKr21 commented on kernel/shared/src/main/scala/cats/effect/kernel/syntax/ClockSyntax.scala
> +  implicit def clockOps[F[_], A, E](wrapped: F[A]): ClockOps[F, A] =
Unused type parameter
```suggestion
  implicit def clockOps[F[_], A](wrapped: F[A]): ClockOps[F, A] =
```

2021-02-12 11:39 UTC, patseev commented on kernel/shared/src/main/scala/cats/effect/kernel/syntax/ClockSyntax.scala
> +  implicit def clockOps[F[_], A, E](wrapped: F[A]): ClockOps[F, A] =
thank you! missed it

2021-02-12 11:39 UTC, joroKr21 commented on kernel/shared/src/main/scala/cats/effect/kernel/syntax/ClockSyntax.scala
> +  implicit def clockOps[F[_], A, E](wrapped: F[A])(implicit F: Clock[F]): ClockOps[F, A] =
It makes sense if you want to infer the type of `E` from the typeclass instance but here it's not used.

2021-02-13 03:17 UTC, kubukoz approved these changes
I think we got it! @djspiewak I think your concerns were addressed, but feel free to blame me if anything is still missing

2021-02-13 03:17 UTC, merged