Use MonadError instead of assertions in Random
typelevel/cats-effect pull request #1720
Opened 2021-02-21 18:25 UTC by patseev

Related issue: https://github.com/typelevel/cats-effect/issues/1719

2021-02-21 22:41 UTC, vasilmkd approved these changes

2021-02-21 23:52 UTC, RaasAhsan requested changes

2021-02-21 23:52 UTC, RaasAhsan commented on std/shared/src/main/scala/cats/effect/std/Random.scala
> +      new IllegalArgumentException(errorMessage).raiseError[F, Unit].unlessA(condition)
There is a bit of a subtlety with `raiseError` syntax in conjunction with `MonadError[F, Throwable]`. In particular, that exception is always going to be allocated and force the population of a stack trace regardless of whether `condition` is true or not, which can be quite expensive. I think we should conditionally allocate the exception via a regular `if` statement, or the monadic `ifM` combinator

2021-02-22 06:03 UTC, patseev commented on std/shared/src/main/scala/cats/effect/std/Random.scala
> +      new IllegalArgumentException(errorMessage).raiseError[F, Unit].unlessA(condition)
Fixed. TY for the remark!

2021-02-27 05:12 UTC, djspiewak commented
Thank you!

2021-02-27 05:12 UTC, merged