Implement UUIDGen capability trait.
typelevel/cats-effect pull request #1772
Opened 2021-03-09 23:59 UTC by Wosin

This PR implements UUIDGen capability trait as discussed in https://github.com/typelevel/cats-effect/issues/1741.

2021-03-10 00:00 UTC, vasilmkd commented
Make sure to run `compile` in `sbt`, it will generate the needed license header. 😄

2021-03-10 00:06 UTC, vasilmkd commented
I guess you're going to have to run `scalafmtAll` in `sbt` as well. While we're at it, do you mind adding a basic scaladoc to this file? You can look at the other modules in `cats/effect/std` for inspiration.

2021-03-10 01:06 UTC, Wosin commented
> I guess you're going to have to run `scalafmtAll` in `sbt` as well. While we're at it, do you mind adding a basic scaladoc to this file? You can look at the other modules in `cats/effect/std` for inspiration.

Yeah, something actually went wrong with my git, so it was left in some weird half-state :<

2021-03-14 07:30 UTC, catostrophe commented on std/shared/src/main/scala/cats/effect/std/UUIDGen.scala
> +  def randomUUID[F[_]: Sync]: F[UUID] = Sync[F].delay(UUID.randomUUID())
These 2 methods should require `F[_] : UUIDGen` bound.

And the companion object should have:
```scala
implicit def fromSync[F[_] : Sync]: UUIDGen[F] = ???
```

2021-03-14 07:31 UTC, catostrophe commented on std/shared/src/main/scala/cats/effect/std/UUIDGen.scala
> +}
Can we also add this to the companion?
```scala
  def randomString[F[_]: Functor: UUIDGen]: F[String] = randomUUID[F].map(_.toString)
```

2021-03-14 09:16 UTC, catostrophe commented on std/shared/src/main/scala/cats/effect/std/UUIDGen.scala
> +  def fromString(uuidString: String): F[UUID]
This trait is a UUID _generator_. Does this method reflect the purpose of the trait? And if so, why is there no method for making a UUID from a byte array?

2021-03-14 09:20 UTC, catostrophe commented on std/shared/src/main/scala/cats/effect/std/UUIDGen.scala
> +  def fromString(uuidString: String): F[UUID]
So maybe we should rename the trait and add some methods?

I also don't like the `Gen` suffix because it's used in `kernel` (yet, as a prefix) for generic type classes like `GenConcurrent`

2021-03-14 18:36 UTC, Wosin commented on std/shared/src/main/scala/cats/effect/std/UUIDGen.scala
> +}
Sure, sounds reasonable.

2021-03-14 21:59 UTC, Wosin commented on std/shared/src/main/scala/cats/effect/std/UUIDGen.scala
> +  def fromString(uuidString: String): F[UUID]
Yeah, I was kinda basing on https://github.com/davenverse/fuuid here. I had an idea to implement the byte array version too, but decided to skip it for now.

IMHO, if we are doing this it should cover all basic use-cases so I think including at least a `fromString` would be a good idea, but happy to discuss this  :)

2021-03-21 23:21 UTC, djspiewak requested changes

2021-03-21 23:21 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/UUIDGen.scala
> +  def fromString(uuidString: String): F[UUID]
I tend to think this is a bit out of scope. At the very least, I would have expected it to return `Option[UUID]`.

2021-03-22 14:40 UTC, Wosin commented on std/shared/src/main/scala/cats/effect/std/UUIDGen.scala
> +  def fromString(uuidString: String): F[UUID]
Ok, will drop it and stick to `random` and `randomString`

2021-03-22 21:12 UTC, Wosin commented on std/shared/src/main/scala/cats/effect/std/UUIDGen.scala
> +  def randomUUID[F[_]: Sync]: F[UUID] = Sync[F].delay(UUID.randomUUID())
Hey, is that what You meant ? I think I didn't fully understand what You meant .

2021-03-25 07:57 UTC, catostrophe commented on std/shared/src/main/scala/cats/effect/std/UUIDGen.scala
> +  def randomString: F[String]
I meant that the trait would have only `def randomUUID: F[UUID]`.
While `randomString` would be a method on the object.

Like:
```scala
object UUIDGen {
  def apply[F[_]](implicit ev: UUIDGen[F]): UUIDGen[F] = ev

  implicit def fromSync[F[_]: Sync]: UUIDGen[F] = new UUIDGen[F] {
    override def randomUUID: F[UUID] = Sync[F].delay(UUID.randomUUID())
  }

  def randomUUID[F[_]: UUIDGen]: F[UUID] = UUIDGen[F].randomUUID
  def randomString[F[_]: UUIDGen: Functor]: F[UUID] = randomUUID[F].map(_.toString)
}
```

Or we can just forget about it at all :)

2021-03-28 14:41 UTC, Wosin commented on std/shared/src/main/scala/cats/effect/std/UUIDGen.scala
> +  def randomString: F[String]
Cool, done!

2021-05-14 18:55 UTC, mpilquist commented
Where does this one stand?

2021-07-07 20:23 UTC, merged