Port align instance for IO and SyncIO from CE2
typelevel/cats-effect pull request #1775
Opened 2021-03-10 11:45 UTC by alexandrustana

This PR aims to fix #1726

2021-03-13 22:22 UTC, djspiewak requested changes
Some minor comments, but otherwise looks very good!

2021-03-13 22:22 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  implicit val alignForIO: Align[IO] =
It's worth following the pattern we have elsewhere: define `alignForIO` to be a `def` which delegates to `private[this] val _alignForIO`. I realize it's a bit arcane, but this actually produces performance benefits because it avoids the memory barriers associated with `val` on `object`.

2021-03-13 22:22 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  protected class IOAlign extends Align[IO] {
Why `protected`?

2021-03-13 22:22 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/SyncIO.scala
> +  protected class SyncIOAlign extends Align[SyncIO] {
Same comments as with `IO`

2021-03-15 13:20 UTC, alexandrustana commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  implicit val alignForIO: Align[IO] =
Ok, I'll switch to this implementation then.
Thanks for the tip :)

2021-03-15 13:21 UTC, alexandrustana commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  protected class IOAlign extends Align[IO] {
While adding `alignForIO` I've used `semigroupKForIO` as a reference. Didn't really thought it through when choosing the access specifier.

2021-03-15 14:56 UTC, djspiewak commented
🎉

2021-03-15 14:56 UTC, merged