Document the design of Async#cont
typelevel/cats-effect pull request #1807
Opened 2021-03-22 10:18 UTC by TimWSpence

2021-03-22 11:03 UTC, SystemFw commented on docs/typeclasses/async.md
> +```
you probably want to introduce `uncancelable` here first

2021-03-22 11:06 UTC, SystemFw commented on docs/typeclasses/async.md
> +to call concurrent operations such as `get.start`. We therefore need to employ
yeah this is hard to explain, but essentially the reason is that `get` represents "the rest of the runloop", which don't want to be resumed concurrently from multiple places

2021-03-22 11:08 UTC, TimWSpence commented on docs/typeclasses/async.md
> +```
Yep thanks 👍 Just copied this from Gitter without thinking too much about it 😂 Although I did also consider removing `uncancelable` from both implementations as it's pretty irrelevant to what we're actually discussing here (could leave a note to say that we're ignoring cancellation). What do you think?

2021-03-22 14:45 UTC, djspiewak requested changes
Looks really really nice! A couple changes but otherwise this is awesome

2021-03-22 14:45 UTC, djspiewak commented on docs/typeclasses/async.md
> +  def async[A](k: (Either[Throwable, A] => Unit) => F[Option[F[Unit]]]): F[A] = {
Random open curly? :-)

2021-03-22 14:45 UTC, djspiewak commented on docs/typeclasses/async.md
> +def asyncRightIsSequencedPure[A](a: A, fu: F[Unit]) =
Needs indentation

2021-03-22 14:45 UTC, djspiewak commented on docs/typeclasses/async.md
> +A possible solution would be to un-CPS the computation by defining
Maybe link `CPS` to the [Wikipedia description](https://en.wikipedia.org/wiki/Continuation-passing_style)?

2021-03-22 15:37 UTC, catostrophe commented on docs/typeclasses/async.md
> +delegrate.pure(None)`) that we are forced to discard when mapping to something
~delegrate~ delegate

2021-03-22 15:43 UTC, TimWSpence commented on docs/typeclasses/async.md
> +  def async[A](k: (Either[Throwable, A] => Unit) => F[Option[F[Unit]]]): F[A] = {
🤦 thanks!

2021-03-26 17:24 UTC, TimWSpence commented
@djspiewak I _believe_ I've addressed all your comments. Apologies if I've missed any!

2021-03-28 19:04 UTC, merged