Add Random materializers for monad transformers
typelevel/cats-effect pull request #1850
Opened 2021-03-29 17:43 UTC by alexandrustana

This closes #1834

2021-04-10 18:11 UTC, djspiewak requested changes
This is great! Just a couple super-minor changes. I'm thinking that the mima compatibility failures are spurious? Need to look at them a little closer and could use a second set of eyes.

2021-04-10 18:11 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/Random.scala
> +    Random[F].mapK(StateT.liftK)
This should probably be `IndexedStateT` just to be slightly more general

2021-04-10 18:11 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/Random.scala
> +  implicit def catsReaderWriterStateTRandom[
Also `Indexed`, ideally

2021-04-10 19:58 UTC, wemrysi commented
@djspiewak I agree the mima issues are spurious, looks like the PR branch is based on a `main` pre #1854.

2021-04-12 05:41 UTC, alexandrustana commented
@wemrysi you are right it's before #1854. I'll get the fix in when applying the requested changes

2021-04-12 07:04 UTC, alexandrustana commented on std/shared/src/main/scala/cats/effect/std/Random.scala
> +  implicit def catsReaderWriterStateTRandom[
I wasn't aware of the Indexed version, should be ok now 🙂

2021-04-20 04:29 UTC, merged