add three methods to Outcome for easy testing
typelevel/cats-effect pull request #1903
Opened 2021-04-13 05:50 UTC by davidabrahams

When writing unit-tests on Fibers, I wrote an extension method to allow myself to write:

```
assert(fiber.isCancelled)
```

rather than pattern-matching every time. I thought others might find this useful too!

Let me know if anyone has thoughts on the method names here. I wasn't sure about `isSuccess` vs `wasSuccessful` vs `isSucceeded`, etc, so happy to change this.

2021-04-13 21:40 UTC, kubukoz commented
Mild :-1: as you can use `fold` with relatively little code (`fold(false, _=>false, _=>true)` for example), and this increases the API surface, but if others think it'd be good to have it, I'm okay with it :)

2021-04-14 02:17 UTC, davidabrahams commented
Fair enough! I found this useful, but I'm happy to keep this out of the cats-effect library to reduce surface area

2021-04-26 17:55 UTC, djspiewak requested changes
I agree that this is easily accomplished via `fold`, but I have no objection to the convenience functions!

2021-04-26 17:55 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Outcome.scala
> +  def isCancelled: Boolean = this match {
Minor note: We generally using the single `l` spelling consistently throughout the library. Also another thing to think about: this is a past-tense conjugation while the other two methods are present-tense. `isCancel` would probably be more consistent. Alternatively, given that the conjugation of the ADT cases themselves is past-tense, perhaps it would be better to have `isSucceeded`, `isErrored`, and `isCanceled`?

2021-07-07 17:10 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Outcome.scala
> +  def isCancelled: Boolean = this match {
```suggestion
  def isCanceled: Boolean = this match {
```

2021-07-07 18:28 UTC, merged