Polymorphic AsyncAwait implementation
typelevel/cats-effect pull request #1924
Opened 2021-04-22 21:01 UTC by Baccata

This preliminary work adds an async/await implementation based off the now built-in mechanism in the Scala 2 compiler.

The grittiest details of the implementation are borrowed from :

* https://github.com/scala/scala/pull/8816
* https://github.com/retronym/monad-ui/tree/master/src/main/scala/monadui
* https://github.com/scala/scala-async

Due to the reliance on Dispatcher#unsafeRunSync, the implementation currently only works on JVM.

Error propagation / cancellation seems to behave as it should.

NB : despite it compiling, using this with OptionT/EitherT/IorT is currently unsafe, for two reasons:

* what seems to be a bug in the MonadCancel instance tied to those Error-able types: See https://gitter.im/typelevel/cats-effect-dev?at=60818cf4ae90f3684098c042
* The fact that calling `unsafeRunSync` is `F[A] => A`, which obviously
doesn't work for types that have an error channel that isn't accounted for by the CE typeclasses. 

Fixes https://github.com/typelevel/cats-effect/issues/1907

2021-04-22 21:02 UTC, Baccata commented on tests/jvm/src/test/scala-2/cats/effect/std/AsyncAwaitSpec.scala
> +    import IOAsyncAwait.{await => ioAwait, _}
`await` collides with something in FutureMatchers.

2021-04-22 21:17 UTC, Baccata commented on std/jvm/src/main/scala-2/AsyncAwait.scala
> +      c: whitebox.Context
might be able to use blackbox instead. Maybe, maybe not, I don't know anymore...  Space-time infinites aren't they just the reflection of our inner emotional stirs ? Do I even exist ?

2021-04-22 21:31 UTC, Baccata commented
I haven't added a syntax object for IO in the main scope yet. If someone could make an executive decision over where to put things and what to call them, that'd be great.

2021-04-23 17:32 UTC, vasilmkd commented
Since we're all very new to this, may I suggest that we mark this as experimental and iterate on this for a couple of versions without promising source or binary compatibility. Who knows, we may end up improving on some of the constraints. Hats off to @Baccata  for the effort. I'm interested to look into this in more depth, I've never dabbled with macros before.

2021-04-23 22:14 UTC, djspiewak commented
> Since we're all very new to this, may I suggest that we mark this as experimental and iterate on this for a couple of versions without promising source or binary compatibility. Who knows, we may end up improving on some of the constraints. Hats off to @Baccata for the effort. I'm interested to look into this in more depth, I've never dabbled with macros before.

I agree with this. It's worth noting though that we basically already have a built-in "experimental" flag on all of this, since none of it is accessible without using the `-Xasync` flag on `scalac`. So overall I think we're okay. :-)

2021-04-23 22:28 UTC, djspiewak commented on std/jvm/src/main/scala-2/AsyncAwait.scala
> +      c: whitebox.Context
Pretty sure blackbox would work. Whitebox is fine though. There really isn't any harm

2021-04-24 04:53 UTC, joroKr21 commented on std/jvm/src/main/scala-2/AsyncAwait.scala
> +      c: whitebox.Context
Blackbox compiles faster 😄

2021-04-24 10:04 UTC, Baccata commented
@vasilmkd, @djspiewak, my latest commits on this introduce a construct (that I named `DispatchCloak`, feel free to propose an alternative) that solves the following problems : 

* prevent reliance on `unsafeRunSync` for javascript interop (btw, why doesn't the build reference `shared/scala-2` as an `unmanagedSourceDirectory` ? Should I add it manually ?) 
* allows to account for side-error-channels (which as far as I know is the reason why successful outcomes expose an `F[A]`), by encoding these channels as ad-hoc, path-dependant Throwable classes (hence the "cloak" name). In the bigger picture, this would theoretically allow for `Dispatcher#unsafeRunSync` to be called safely (ie without hanging) on monad transformer stacks that have such error channels. I was thinking it felt a bit ad-hoc at first, but it does embrace the same "Throwable is the de-facto channel" paradigm as Dispatcher does.

2021-04-24 10:11 UTC, Baccata commented on std/shared/src/main/scala/cats/effect/std/DispatchCloak.scala
> +  implicit def cloakForOptionT[F[_]: Spawn: DispatchCloak]: DispatchCloak[OptionT[F, *]] =
Just added this instance as an example for starters. Obviously similar things would have to be provided for EitherT/IorT ... 

Though in the case of IorT maybe it'd be better to prevent the use altogether: I'm not sure how partial successes should transit through this tbh ...

2021-04-24 10:29 UTC, vasilmkd commented
Just to confirm, you're still currently hitting the problems with transformers that we became aware of a couple days ago right? I just want to make sure this is not somehow hiding those or relying on behavior that will be changed/fixed in the next version.

2021-04-24 10:30 UTC, Baccata commented on std/shared/src/main/scala/cats/effect/std/DispatchCloak.scala
> +  def cloak[A](fa: F[A]): F[Either[Throwable, A]]
This is meant to be called only on whatever's contained by Outcome.Succeeded, when asynchrony and concurrency have been accounted for. Ought to make it protected.

2021-04-24 10:32 UTC, Baccata commented on tests/jvm/src/test/scala-2/cats/effect/std/AsyncAwaitSpec.scala
> +  "Nested OptionT AsyncAwait" should {
These tests showcase that an arbitrary number of OptionT layers do not get mis-interpreted by async/await when one of the layers yields a None.

2021-04-24 11:13 UTC, Baccata commented
> Just to confirm, you're still currently hitting the problems with transformers that we became aware of a couple days ago right? I just want to make sure this is not somehow hiding those or relying on behavior that will be changed/fixed in the next version.

Let's put it this way : the "DispatchCloak" construct is solving two problems by applying a solution which coincidentally prevents the problematic codepath (the one we became aware of) from being exercised. 

So even when the MonadCancel#bracketFull implementation is fixed for monad transformers, this solution (or something similar) would still have to be applied, in order to : 
* avoid reliance on Dispatcher#unsafeRunSync which doesn't exist in javascript world 
* communicate non-Throwable errors through the async/await dispatcher-loop (the scala one, not the CE one), because that loops relies on what is analogous to F[A] => A. 

In other words, the fixing of MonadCancel#bracketFull would not have been enough to prevent async/await from hanging when it encounters `OptionT.none` or `EitherT.left`

2021-04-24 11:14 UTC, vasilmkd commented
I'm very very happy with this outcome.

2021-04-24 11:32 UTC, Baccata commented
> I'm very very happy with this outcome.

Wait, actually I'm very dumb 🤦 see [https://github.com/typelevel/cats-effect/pull/1924/files#diff-016206623196eb9e6fecfff5dd3ef0fe4826caddd10791f7bc316012c812c366R44-R49]. Yeah it'll need to be rewritten in terms of Deferred + guarantee ...

2021-04-24 11:34 UTC, Baccata commented on std/shared/src/main/scala/cats/effect/std/DispatchCloak.scala
> +    fa.start.flatMap(_.join).flatMap {
This needs to be amended as soon as bracketFull is fixed for monad transformers

2021-04-24 12:56 UTC, vasilmkd commented
We'll fix the issue, that's definitely a priority for the next release.

2021-04-24 18:36 UTC, djspiewak commented
Spent some time thinking about this today. Do you think it would be better to just define this for `IO` for the time being? I'm pretty leery about `DispatchCloak`, but at the same time, just deadlocking whenever someone uses a transformer with alternative zeros is… undesirable.

I'm interested in @retronym's perspective on this. It seems that the current `-Xasync` mechanism is just not capable of handling any monadic context more complicated than errors and callbacks (which, staring at the API, is actually kind of obvious). It should be possible to get this kind of functionality, but it would require a more complex state machine which no longer makes assumptions about the kinds of state which needs to be threaded between `await`s.

2021-04-24 22:05 UTC, Baccata commented
>  Do you think it would be better to just define this for IO for the time being 

Considering it works for Kleisli / WriterT, I think it'd be silly not to provide the feature for a combination of those types. Or to prevent other IO implementations from tapping into this mechanism. 

>  It should be possible to get this kind of functionality, but it would require a more complex state machine which no longer makes assumptions about the kinds of state which needs to be threaded between awaits. 

TBH, the state machine makes few assumptions. The problem can be summarised as this : "how do you generically decide whether a computation has been successful, according to all its monadic effects ?" Outside of the `-XAsync` mechanism, CE3 does suffer from not having a solution to this very problem : following program will happily compile and hang forever. 

```scala 
import cats.effect.IOApp
import cats.effect.IO
import cats.data.OptionT
import cats.effect.kernel.Sync
import cats.effect.std.Dispatcher

object Main extends IOApp.Simple {

  type Foo[A] = OptionT[IO, A]

  def run = {
    IO.println("Hello") >>
      Dispatcher[Foo].use { dispatcher =>
        Sync[Foo].delay(dispatcher.unsafeRunSync(OptionT.none[IO, Int]))
      }.value >> IO.println("Goodbye")
  }
}
```

> I'm pretty leery about DispatchCloak 

In the case of Async/Await, a more elegant encoding of could be applied: The call to CE's `async_` could be made against `Either[F[A], A]` instead of `A`, so the CE callback would be `Either[Throwable, Either[F[A], A]] => Unit`, following the steps of Outcome, and that might be more acceptable than trying to encode stuff in terms of Throwable. However, a typeclass-like construct will still be needed to encode the `F[A] => F[Either[F[A], A]]`. 

The value of encoding things in terms of Throwable (even if the current DispatchCloak construct could do with polishing) is that it offers a start of solution for the very present problem showcased in the snippet above. Throwables are ubiquitous in all runtimes Scala combines against, and a lot of libraries people are gonna use Dispatcher to interop with will likely propagate throwables. 

### To summarise, the possible solution, as I see them are : 

1. Hardcode cats.effect.IO. It's the solution that I'd fine the most disappointing. 
2. Come up with a no-method marker typeclass ("awaitable" or whatever) that'd encode the fact that a type can be safely used through things like async/await and `Dispatcher#unsafeRunSync` 
3. Encode side-error-channels with Throwable types (current state of the PR at the time of writing this), which might be meh but would allow to make Dispatcher#unsafeRunSync work for EitherT/OptionT. 
4. Come up with a `F[A] => F[Either[F[A], A]]` typeclass which encodes the notion of "can I continue in the monadic sequence ?" (I guess it's conceptually similar to Free#resume now that I think about it), that'd solve the problem for Async/Await, but does not offer a solution to `Dispatcher#unsafeRunSync`... Or would it ?

2021-04-25 08:49 UTC, Baccata commented
> Considering it works for [...] WriterT 

That was a stretch, my bad. It does work for Kleisli, but in the case of WriterT, the logs get lost through the async/await through each callback. I'm gonna try out something to address it (in a less ad-hoc fashion than the DispatchCloak thing).

2021-04-25 10:20 UTC, Baccata commented
@djspiewak, I've nuked the "DispatchCloak" in favour of a much less ad-hoc "Resume" construct that allows for decomposing a monadic computation into its potential product and coproduct components. 

Using a mutable variable in the async/await state machine (which I presume is thread-safe since the dispatch loop requires the FSM to hold a mutable integer, but it'd be good to have  @retronym's confirmation), the intermediate monadic results can be stored when the async/await loop retrieves the value to fulfil the current "await", and re-composed with the effect unpacked by the next "await" call. 

The CE `async_` call is now performed against `F[A]`, following's the design of Outcome, to account for any monadic effects unknown to the CE typeclasses (as well as potential self-cancellation of await blocks)

2021-04-25 16:04 UTC, Baccata commented on std/shared/src/main/scala/cats/effect/std/Resume.scala
> +  def resume[A](fa: F[A]): F[Either[F[A], (F[Unit], A)]]
I guess we can kinda formulate a "law" (which requires dispatcher), which would roughly be : 

```scala
delay(dispatcher.unsafeRunSync(resume(fa))).flatMap {
  case Left(fa) => fa 
  case Right((funit, a)) => funit.as(a)  
} <-> fa
```

Running the effect through the dispatcher serves as a way to check that all coproduct/product components have been accounted for, by checking that : 

1. the unsafeRun doesn't hang (which would indicate a "unhandled" coproduct member). Yes, it's terrible 😸  
2. the `F[Unit]` has tracked all the product effects, as they would have been forgotten when crossing the unsafe bridge.

2021-04-25 16:07 UTC, Baccata commented on std/jvm/src/main/scala-2/AsyncAwait.scala
> +        recordedEffect = newEffect
I need to inline some comments there.

2021-05-23 20:56 UTC, djspiewak commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      }
So I spent a ton of time thinking about this, and it occurs to me that we *should* be able to get this same kind of "peak into the control layer" effect by using `guaranteeCase`. In particular, the `Succeeded` case should contain the `F[A]` even when that `F[A]` is some coproduct case. Unfortunately, this is precisely what *isn't* working right now because of the `bracketCase` issue. I *think* if I fix that issue, then we don't need `Resume` here anymore.

2021-05-24 22:15 UTC, Baccata commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      }
>  I think if I fix that issue, then we don't need Resume here anymore.

I don't think that'll suffice, unfortunately, but I'd be really happy to be proven wrong though. One thing that the structural interface (which `XAsync` works with) requires is the implementation of the `tryGet` method, which, if you squint really hard, is akin to `F[A] => Either[Stop, A]` (the Stop is signalled by returning `this` ... ). 

For any await block, the state machine will call this `tryGet` method to unpack the value from whatever structure you elect to work with, and substitutes the await block with that value. So the structure you choose needs to contain enough information to decide whether to signal to the state machine whether it should stop, or continue. 

So as far as I'm aware, `XAsync` cannot be implemented in a polymorphic manner without some abstraction letting you decide whether your `F[A]` actually "contains" the `A`. Fixing `guaranteeCase` will not give us that, it will however mean that `resume` could be called later than it currently is.

2021-05-25 00:41 UTC, retronym commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      }
I'm not across the particular context of this PR but wanted to mention that the structural interface of async does support using an identity type alias as the "Either" type.

This makes sense if the Future-ish data type + dispatcher are responsible for propagating failures to dependant tasks.  That isn't the case with Scala Futures, but is true in some other task abstractions, e.g.:

```
trait NodeStateMachine extends AsyncStateMachine[Node[AnyRef], AnyRef] with (AnyRef => Unit) {
  def node: Node[AnyRef]
  private[this] var state$async: Int = 0

  protected def state: Int = state$async

  protected def state_=(s: Int): Unit = state$async = s

  final def apply(tr$async: R[AnyRef]): Unit = fsm(tr$async)
  def fsm(tr$async: R[AnyRef]): Unit

  type F[A] = Node[A]
  type R[A] = A

  // Adapter methods
  protected def completeFailure(t: Throwable): Unit = throw new UnsupportedOperationException()

  protected def completeSuccess(value: AnyRef): Unit = node.completeWithValue(value)

  protected def onComplete(f: F[AnyRef]): Unit = f.onComplete(this)

  protected def getCompleted(f: F[AnyRef]): R[AnyRef] = f.getCompleted

  protected def tryGet(tr: R[AnyRef]): tr.type = tr
}

sealed class Node[T] {
  private[this] val ec: Executor = Node.DefaultThreadPool
  private[this] final val result: CompletableFuture[T @uncheckedVariance] = new CompletableFuture()

  def address: NodeAddress[T] = NodeAddress.NoAddress

  protected def runAsync(f: () => Unit): Unit = {
    val childContext = NodeContext.childContext(this)
    CompletableFuture.runAsync ({ () =>
      NodeContext.pushContext(childContext)
      try f()
      catch {
        case t: Throwable =>
          completeWithFailure(t)
      } finally NodeContext.popContext()
    }, ec)
  }
  def onComplete[U](f: T => U): Unit = {
    val childContext = NodeContext.childContext(this)
    result.whenCompleteAsync((t: T, throwable: Throwable) => {
      NodeContext.pushContext(childContext)
      try {
        if (throwable != null) {
          completeWithFailure(throwable)
        } else {
          f(t)
        }
      } catch {
        case t: Throwable =>
          completeWithFailure(t)
      } finally NodeContext.popContext()
    }, ec)
  }

  def completeWithValue(t: T): Unit = result.complete(t)
  def completeWithFailure(t: Throwable): Unit = {
    result.completeExceptionally(t)
    var context = NodeContext.current()
    while (context ne RootContext) {
      context.node.completeWithFailureDirect(t)
      context = context.parent
    }
  }
  ...

```

2021-05-25 01:52 UTC, djspiewak commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      }
> Fixing guaranteeCase will not give us that, it will however mean that resume could be called later than it currently is.

It might if we cheat. So some things we can hang our hat on:

- `guaranteeCase` will run regardless of whether or not we "contain" the `A`. For example, an `OptionT.empty` will result in a `Succeeded` with `None`. This is what the `bracketCase` fix buys us
- We can peak into the result that's *inside* the `Succeeded` by `flatMap` and `Dispatcher`
- The result, in practice, is going to be determined by `F.pure` for some `F`, meaning that we can safely `unsafeRunSync` on it. 😈 
- This means that we can figure out whether or not there's an `A` by simply `flatMap`ping with something that captures that `A` and re-`pure`s it into `F` in a local `var`
- If the `var` isn't populated by the `unsafeRunSync`, then we know we're in a coproduct case, so we populate a *different* `var` with… exactly the `F[A]` we just ran. Then short-circuit the whole rest of the expression and return it, casted to the appropriate type

I'm pretty sure this works in all cases that the control layer solution (`Resume`) would have worked in.

2021-05-25 08:22 UTC, Baccata commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      }
> F.pure for some F, meaning that we can safely unsafeRunSync on it 

That is not quite accurate?Ffunnily enough, that's what I was doing in the first iteration. 

> If the var isn't populated by the unsafeRunSync, then we know we're in a coproduct case

What you seem to forget is that the behaviour of running unsafeRunSync when you're in the coproduct case is non-termination ... what you suggest would be possible if there was a flavour of `unsafeRun` that returned `Either[F[A], A]` or something, which is exactly what I've tried to achieve with `Resume`. 

Here's a repro of such non-termination. 

```scala
import cats.effect.IOApp
import cats.effect.IO
import cats.effect.std._
import cats.data.OptionT
import cats.effect.kernel.Sync

object Main extends IOApp.Simple {

  type Foo[A] = OptionT[IO, A]

  // this could be returned in the success case of `guaranteeCase`
  val prog: Foo[Int] = OptionT[IO, Int](IO.pure(None))

  def run: IO[Unit] = {
    val dispatched =
      Dispatcher[Foo].use(d => Sync[Foo].delay(d.unsafeRunSync(prog))).value

    dispatched >> IO.println("completed")
  }
}
```

2021-05-25 18:40 UTC, djspiewak commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      }
> What you seem to forget is that the behaviour of running unsafeRunSync when you're in the coproduct case is non-termination ... what you suggest would be possible if there was a flavour of unsafeRun that returned Either[F[A], A] or something, which is partially what I've tried to achieve with Resume.

Yeah, I did forget that. Trying to think about how to emulate this.

Fundamentally, I don't want to just create a `MonadControlLayer`, which is basically what `Resume` is (with all the attendant power and problems), but by the same token it's hard to see what might be an alternative here. Being forced (by the DSL state machine) to extract out either a `Throwable` or an `A` and absolutely nothing else is *really* constraining.

2021-05-25 20:08 UTC, Baccata commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      }
I certainly appreciate how tricky this is 😞 . I'd personally be fine with nuking the Resume/MonadControlLayer in favour of mutable variables if Dispatcher offered methods that guaranteed termination. 

Regardless of Async/Await, the non terminating behaviour of Dispatcher does feel like a pitfall people will fall for, and that maintainers should have an answer for

2021-05-25 22:32 UTC, djspiewak commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      }
Agree. It's more than a bit weird.

2021-05-26 18:38 UTC, djspiewak commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      }
```scala
val fa: F[A] = ???

var result: Option[Either[F[A], A]] = None
fa.flatTap(a => Sync[F].delay { result = Some(Right(a)) }) guaranteeCase {
  case Succeeded(fa) =>
    result = result.orElse(Some(Left(fa))

  case Errored(e) => ???
  case Canceled() => ???
}
```

Okay I didn't have time to flesh out the error cases, but hopefully this is clear. `result` is guaranteed to get a value. You can also rewrite this into an async fashion by putting a little `Boolean` mutable guard to prevent double-population between `flatTap` and `guaranteeCase`. Tldr though this should solve the deadlock problem.

2021-05-26 19:45 UTC, Baccata commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      }
It might work :) . I'll try it out when guaranteeCase is fixed for transformers. Is there an open issue for that btw ?

2021-05-27 13:37 UTC, djspiewak commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      }
I think there isn't an open issue yet. Would you mind opening one if you have the example immediately at hand? I'm drowning in a couple branches right now.

2021-05-28 07:47 UTC, Baccata commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      }
https://github.com/typelevel/cats-effect/issues/2013

2021-05-28 08:36 UTC, Baccata commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      }
@djspiewak the mutation trick works 👍 , and the guaranteeCase fix isn't blocking this (I think forking a fiber before dispatch is still desirable to avoid the non-termination problem, though in the case of unsafeRunAndForget I do not know whether a thread would end up being monopolised in the background).

2021-05-29 02:49 UTC, djspiewak requested changes
Giving a more proper review now that we're in the home stretch! I'm really excited about this, tbh.

2021-05-29 02:49 UTC, djspiewak commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +  type Callback[F[_]] = Either[Throwable, CallbackTarget[F]] => Unit
Does this have to be public?

2021-05-29 02:49 UTC, djspiewak commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +  type AwaitOutcome[F[_]] = Either[F[AnyRef], (F[Unit], AnyRef)]
Ditto above

2021-05-29 02:49 UTC, djspiewak commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +class AsyncAwaitDsl[F[_]](implicit F: Async[F]) {
We should add some scaladoc being like "uh, this is really really unstable, only works on Scala 2.x, and will likely change and/or be deprecated in the future"

2021-05-29 02:49 UTC, djspiewak commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +/*
Minor thing, but can we rename this file in lower-case to reflect the fact that it contains multiple top-level members? Like `asyncAwait.scala`.

2021-05-29 02:49 UTC, djspiewak commented on tests/shared/src/test/scala-2/cats/effect/std/AsyncAwaitSpec.scala
> +    import IOAsyncAwait.{await => ioAwait, _}
Given that we're whitebox macroing here, I wonder if it's possible to have an API which *doesn't* require this kind of "dsl partial application" pattern. I'm totally fine going with this for now, especially since we aren't guaranteeing compatibility, but it feels possible.

2021-05-29 02:49 UTC, djspiewak commented on tests/shared/src/test/scala-2/cats/effect/std/AsyncAwaitSpec.scala
> +      val program = async(ioAwait(io))
Should we have a test for `async(throw Boom)` as well?

2021-05-29 02:49 UTC, djspiewak commented on tests/shared/src/test/scala-2/cats/effect/std/AsyncAwaitSpec.scala
> +        _ <- async { ioAwait(IO.sleep(100.millis) *> ref.update(_ + 1)) }
What if we got a little fancier?

```suggestion
        _ <- async {
          ioAwait(IO.never)
          ioAwait(ref.update(_ + 1))
        }
```

This should also make the test more deterministic.

2021-05-29 02:49 UTC, djspiewak commented on tests/shared/src/test/scala-2/cats/effect/std/AsyncAwaitSpec.scala
> +        after <- IO(x must beEqualTo(1))
Also worth testing this sequenced a *second* time, ensuring that `x must beEqualTo(2)` afterward.

2021-05-29 02:49 UTC, djspiewak commented on tests/shared/src/test/scala-2/cats/effect/std/AsyncAwaitSpec.scala
> +      } yield before && after
```suggestion
      } yield ok
```

You already did the assertion.

2021-05-29 02:49 UTC, djspiewak commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      (summary *> f).flatTap(r => F.delay{awaitedValue = Some(r)}).start.flatMap(_.join).flatMap {
It actually surprises me that scalafmt gives this line a pass.

```suggestion
      (summary *> f).flatTap(r => F.delay { awaitedValue = Some(r) }).start.flatMap(_.join).flatMap {
```

Also, why is the `.start.flatMap(_.join)` necessary? Why not just `guaranteeCase`? (is this just working around #2013?) At the very least we should use `uncancelable` to ensure the `Fiber` doesn't leak.

2021-05-29 02:49 UTC, djspiewak commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +  }
```suggestion
  protected def completeSuccess(value: AnyRef): Unit =
    callback(Right(F.as(summary, value)))
```

2021-05-29 02:50 UTC, djspiewak commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      }
Fibers are forked regardless when you do an `unsafeRun` of any sort on `Dispatcher`, so the secondary forking is unneeded. I do see how it's working around the bracket issue though.

2021-05-29 07:46 UTC, Baccata commented on tests/shared/src/test/scala-2/cats/effect/std/AsyncAwaitSpec.scala
> +      } yield before && after
What is this magic ?

2021-05-29 07:48 UTC, Baccata commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +  }
8971556

2021-05-29 07:48 UTC, Baccata commented on tests/shared/src/test/scala-2/cats/effect/std/AsyncAwaitSpec.scala
> +      } yield before && after
8971556

2021-05-29 07:48 UTC, Baccata commented on tests/shared/src/test/scala-2/cats/effect/std/AsyncAwaitSpec.scala
> +        after <- IO(x must beEqualTo(1))
8971556

2021-05-29 07:48 UTC, Baccata commented on tests/shared/src/test/scala-2/cats/effect/std/AsyncAwaitSpec.scala
> +        _ <- async { ioAwait(IO.sleep(100.millis) *> ref.update(_ + 1)) }
8971556

2021-05-29 07:48 UTC, Baccata commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +/*
8971556

2021-05-29 07:49 UTC, Baccata commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +class AsyncAwaitDsl[F[_]](implicit F: Async[F]) {
8971556

2021-05-29 07:55 UTC, Baccata commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      (summary *> f).flatTap(r => F.delay{awaitedValue = Some(r)}).start.flatMap(_.join).flatMap {
> It actually surprises me that scalafmt gives this line a pass.

I had disabled formatting before the quasiquotes and forgotten to re-enable it. Fixed in 8971556

> Also, why is the .start.flatMap(_.join) necessary? 

2 birds, one stone : 
* working around #2013 as you guessed 
* prevent cases like OptionT.none to be run through the Dispatcher, which makes me nervous (even when calling unsafeRunAndForget). This is what I was pointing [here](https://github.com/typelevel/cats-effect/pull/1924#discussion_r641373346). When #2013 is fixed, could be replaced by `.forceR(F.void)` I suppose.

2021-05-29 08:02 UTC, Baccata commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +  type Callback[F[_]] = Either[Throwable, CallbackTarget[F]] => Unit
It does, because it's used in macro expansion, so the client code needs to have visibility over those types. 

These aliases have been really valuable during iteration as otherwise, any change the types lead to having to amend the quasiquote expression in several places which is really, really annoying due to not getting compile errors until the macro expansion. I'd rather keep them for maintainability reasons but will obviously abide if you make an executive call to remove them. 

In the meantime, I removed `CallbackTarget` as it's useless in this iteration and renamed `Callback` to `AwaitCallback` (8971556)

2021-05-29 08:09 UTC, Baccata commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      (summary *> f).flatTap(r => F.delay{awaitedValue = Some(r)}).start.flatMap(_.join).flatMap {
> At the very least we should use uncancelable to ensure the Fiber doesn't leak.

Is this correct : 0220ebf ?

2021-05-29 08:44 UTC, Baccata commented on tests/shared/src/test/scala-2/cats/effect/std/AsyncAwaitSpec.scala
> +    import IOAsyncAwait.{await => ioAwait, _}
Turned into a blackbox macro in 259b723. 

What you suggest might be possible but it would require a lot more metaprogramming skills than what I can offer. Like, you'd have to collect all the await blocks (which be typed `def await[F[_], A](fa: F[A]) : A` which would likely mess with inference), extract the F from each of them, ensure they're all consistent, implicitly resolve the Async typeclass instance ... 

Looking at [this library](https://github.com/rssh/cps-async-connect/blob/master/cats-effect/shared/src/test/scala/cps/cats/effect/StupidFizzBuzzSuite.scala#L48-L63), which provides the same feature for Scala 3, the UX might greatly improve. 

In the meantime, should I add partially applied instance for the specific case of IO ? If so, can you suggest a location / name ?

2021-05-29 08:50 UTC, Baccata commented on tests/shared/src/test/scala-2/cats/effect/std/AsyncAwaitSpec.scala
> +      val program = async(ioAwait(io))
8971556

2021-05-30 21:41 UTC, djspiewak commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      (summary *> f).flatTap(r => F.delay{awaitedValue = Some(r)}).start.flatMap(_.join).flatMap {
Almost! Commented on the commit

2021-05-30 21:43 UTC, djspiewak commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      (summary *> f).flatTap(r => F.delay{awaitedValue = Some(r)}).start.flatMap(_.join).flatMap {
> This is what I was pointing here. When #2013 is fixed, could be replaced by .forceR(F.void) I suppose

I'm not sure I understand why the `forceR`? Asynchronous non-terminating fibers don't take any resources and are eventually GC'd when no longer referenced, so they aren't really a problem per se.

2021-05-30 21:45 UTC, djspiewak commented on tests/shared/src/test/scala-2/cats/effect/std/AsyncAwaitSpec.scala
> +      } yield before && after
> What is this magic ?

LOL. The `must` syntax throws, so you don't really need the return results.

2021-05-30 21:46 UTC, djspiewak commented
This is ready for merge once we address the `poll` around the `join`.

2021-05-30 22:35 UTC, djspiewak commented
Looks like dead code elimination becomes very annoyed by what we're doing. Interesting…

2021-05-31 07:45 UTC, lrytz commented
> Looks like dead code elimination becomes very annoyed by what we're doing

Scalac's DCE? What went wrong?

2021-05-31 07:59 UTC, Baccata commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      (summary *> f).flatTap(r => F.delay{awaitedValue = Some(r)}).start.flatMap(_.join).flatMap {
> Asynchronous non-terminating fibers don't take any resources 

From the point of view of someone who doesn't know the innards of Dispatcher and how it relates to the effect's runtime, protecting against potential non-terminating behaviour seemed like a good reflex 😄. Also Dispatcher being polymorphic, can you guarantee that it'll be the case for all effect types ? (I reckon it'd be pretty bad if it wasn't the case, but still).

2021-05-31 08:02 UTC, vasilmkd commented on tests/shared/src/test/scala-2/cats/effect/std/AsyncAwaitSpec.scala
> +      def boom: Unit = throw Boom
Fatal warnings don't like this line. It needs a `def boom(): Unit` because it is a side effecting method.

2021-05-31 08:02 UTC, Baccata commented
> Looks like dead code elimination becomes very annoyed by what we're doing. Interesting… 

Addressed in 133094b. It is interesting that it became an error only after the macro turned into a blackbox.

2021-05-31 08:07 UTC, Baccata commented on tests/shared/src/test/scala-2/cats/effect/std/AsyncAwaitSpec.scala
> +      def boom: Unit = throw Boom
_sigh_ 7cf2ad5

2021-05-31 10:11 UTC, vasilmkd commented
CI looks great.

2021-05-31 19:12 UTC, djspiewak commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +  type Callback[F[_]] = Either[Throwable, CallbackTarget[F]] => Unit
I'm cool with keeping them. Just wanted to sanity check.

2021-05-31 19:36 UTC, djspiewak commented on std/shared/src/main/scala-2/AsyncAwait.scala
> + * async { await(io) + await(io) }
Since everyone just copy/pastes from examples:

```suggestion
 * object dsl extends AsyncAwaitDsl[IO]
 * import dsl._
 *
 * val io: IO[Int] = ???
 * async { await(io) + await(io) }
```

2021-05-31 19:37 UTC, djspiewak commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +      (summary *> f).flatTap(r => F.delay{awaitedValue = Some(r)}).start.flatMap(_.join).flatMap {
> can you guarantee that it'll be the case for all effect types ? (I reckon it'd be pretty bad if it wasn't the case, but still).

I *think* that any `F` for which non-termination in `Dispatcher[F]` is problematic would also be an `F` for which *fibers* are problematic. I think.

2021-05-31 20:06 UTC, djspiewak approved these changes

2021-05-31 20:13 UTC, vasilmkd commented on std/shared/src/main/scala-2/AsyncAwait.scala
> +class AsyncAwaitDsl[F[_]](implicit F: Async[F]) {
Love it.

2021-05-31 20:14 UTC, vasilmkd approved these changes
Let's go! A huge achievement.

2021-05-31 20:14 UTC, vasilmkd commented
@Baccata hats off.

2021-05-31 20:18 UTC, djspiewak commented
We should write up a page on this in the main section of the docs.

2021-05-31 22:49 UTC, merged