Adds documentation for async/await
typelevel/cats-effect pull request #2040
Opened 2021-06-04 10:41 UTC by Baccata

2021-06-04 20:33 UTC, djspiewak requested changes

2021-06-04 20:33 UTC, djspiewak commented on site-docs/sidebars.json
> +      "std/async-await"
Let's hold off on putting it in the sidebar until after it has a release, to avoid confusing people looking at the site

2021-06-04 20:33 UTC, djspiewak commented on docs/std/async-await.md
> +object dsl extends cats.effect.std.AsyncAwaitDsl[IO]
Can we do an `import` to clean this up a bit? People are going to copy/paste and things should look nice. :-)

2021-06-04 20:33 UTC, djspiewak commented on docs/std/async-await.md
> +title: Async/await
```suggestion
title: Async/Await
```

Also should we say like, "EXPERIMENTAL" or something like that? We really need to flag that this is something that we aren't promising compatibility on just yet.

2021-06-05 09:50 UTC, Baccata commented on docs/std/async-await.md
> +title: Async/await
cfb0fd6

2021-06-05 09:54 UTC, Baccata commented on docs/std/async-await.md
> +object dsl extends cats.effect.std.AsyncAwaitDsl[IO]
Yes Daniel, the shed can be blue if you'd like 😛  cfb0fd6

Seriously though, the fully qualified name was a conscious decision to optimise for copy/paste, since the pretty version is not necessarily the best in that regard.

2021-06-05 09:54 UTC, Baccata commented on site-docs/sidebars.json
> +      "std/async-await"
cfb0fd6

2021-06-05 10:07 UTC, Baccata commented on docs/std/async-await.md
> +`await` cannot be called from within local methods or lambdas (which prevents its use in `for` loops (that get translated to a `foreach` call)). This is due to a limitation in the Scala compiler.
@retronym is this a hard limitation, or something that could be addressed later ? Also, is there any publicly available write-up (even a comment in a PR) that I could link to ? 

I know that Haoyi did manage to enable it in mill's Task macros (which I'm borrowing implementation details from in [this PR](https://github.com/typelevel/cats-effect/pull/2027/files#diff-4b84b4080312c550c4a02469f70a788b7c013d5edad4d7261561859a924a0dd8R170)), but in that context I assume it's always fine because tasks called in `await` cannot depend on anything that was defined in the `async` block. Is there some devilish detail that prevents the `-Xasync` rewrite from doing the same thing ?

2021-06-05 16:58 UTC, djspiewak commented on docs/std/async-await.md
> +`await` cannot be called from within local methods or lambdas (which prevents its use in `for` loops (that get translated to a `foreach` call)). This is due to a limitation in the Scala compiler.
> When that guarantee doesn't exist, is there some devilish detail that prevents the -Xasync rewrite from allowing calls to await within lambdas ?

How would it rewrite it? Think about something like this:

```scala
val xs: List[Int] = ???
async {
  xs.foreach(i => await(IO.println(i)))
}
```

The "correct" rewriting here based on manual inspection would be the following:

```scala
xs.traverse_(i => IO.println(i))
```

But like… how is `-Xasync` supposed to know that? What if I have some weird type that the compiler doesn't know anything about which exposes a higher-order function, and then I use `await` within a lambda I pass to that function? How would that work?

This is really the benefit to Kotlin's approach to this problem, which lifts it all into the type system and forces declaration at method boundaries.

2021-06-05 16:59 UTC, djspiewak commented on docs/std/async-await.md
> +object dsl extends cats.effect.std.AsyncAwaitDsl[IO]
> Seriously though, the fully qualified name was a conscious decision to optimise for copy/paste, since the pretty version is not necessarily the best in that regard.

This is very true, but I'm guessing that anyone who is leaning on copy/paste here probably also has an editor which supports auto-import insertion. :-)

2021-06-05 17:36 UTC, Baccata commented on docs/std/async-await.md
> +`await` cannot be called from within local methods or lambdas (which prevents its use in `for` loops (that get translated to a `foreach` call)). This is due to a limitation in the Scala compiler.
> The "correct" rewriting here based on manual inspection would be the following:

I mean sure, but if I take your argument further, the whole async blocks should be rewritten into a series of `flatMap` calls, because that's the "correct" way to compose calls sequentially. 

I'm not even sure how the `-XAsync` machinery rewrites the AST, but it implements some kind of coroutine machinery under the hood, a bit like https://github.com/storm-enroute/coroutines used to. If that's the case, I'd like to understand what kind of problems happens when a yielding call happens within the lambda.

2021-06-05 17:48 UTC, Baccata commented on docs/std/async-await.md
> +`await` cannot be called from within local methods or lambdas (which prevents its use in `for` loops (that get translated to a `foreach` call)). This is due to a limitation in the Scala compiler.
I assume it's an ownership problem, as it'd be easy for an await to escape the scope of an async (at runtime) without this

2021-06-16 09:24 UTC, vasilmkd commented on site-docs/sidebars.json
> +      "std/async-await"
Wasn't there a release yesterday? I think you can add the sidebar link again. :)

2021-06-16 09:24 UTC, vasilmkd commented on site-docs/sidebars.json
> +      "std/async-await"
It's already done, sorry.

2021-06-16 09:37 UTC, Baccata commented on site-docs/sidebars.json
> +      "std/async-await"
np, should have updated the comment. Here's the commit that re-adds : cb7e0b1

2021-06-16 18:15 UTC, vasilmkd approved these changes

2021-06-17 14:25 UTC, djspiewak requested changes
Lots of bikeshedding, but otherwise this looks great and it's pretty much ready to go!

2021-06-17 14:25 UTC, djspiewak commented on docs/std/async-await.md
> +val program : IO[Int] = async[IO] { io.await + io.await }
```suggestion
val program: IO[Int] = async[IO] { io.await + io.await }
```

2021-06-17 14:25 UTC, djspiewak commented on docs/std/async-await.md
> +val program : IO[Int] = for {
```suggestion
val program: IO[Int] = for {
```

2021-06-17 14:25 UTC, djspiewak commented on docs/std/async-await.md
> +val program : IO[Int] = async[IO] {
```suggestion
val program: IO[Int] = async[IO] {
```

2021-06-17 14:25 UTC, djspiewak commented on docs/std/async-await.md
> +  for (i <- 1 to 3) (n += IO.pure(i).await ) // compile error
```suggestion
  for (i <- 1 to 3) { n += IO.pure(i).await } // compile error
```

2021-06-17 14:25 UTC, djspiewak commented on docs/std/async-await.md
> +val program : IO[Int] = async[IO]{
```suggestion
val program: IO[Int] = async[IO] {
```

2021-06-17 14:25 UTC, djspiewak commented on docs/std/async-await.md
> +  while(i <= 3){
```suggestion
  while (i <= 3) {
```

2021-06-17 14:25 UTC, djspiewak commented on docs/std/async-await.md
> +scalacOptions += "-Xasync" // scala 2.12.12+ / 2.13.3+
```suggestion
scalacOptions += "-Xasync" // scala 2.12.12+ / 2.13.3+ (not needed if on Scala 3)
```

2021-06-17 14:25 UTC, djspiewak commented on docs/std/async-await.md
> +import cats.effect.std.AsyncAwaitDsl
```suggestion
```

2021-06-17 14:25 UTC, djspiewak commented on docs/std/async-await.md
> +async {
```suggestion
async[IO] {
```

2021-06-17 14:25 UTC, djspiewak commented on docs/std/async-await.md
> +**However**, it is possible to call `await` within an imperative while loop:
```suggestion
**However**, it is possible to call `await` within an imperative `while` loop:
```

2021-06-26 02:24 UTC, merged