Add docs for Semaphore
typelevel/cats-effect pull request #2063
Opened 2021-06-17 22:38 UTC by armanbilge

Fixes #1927 mostly by way of CE2 copypasta.

2021-06-17 22:39 UTC, armanbilge commented on docs/std/semaphore.md
> +being blocked while waiting to acquire a permit. Blocking acquires are cancelable.
Re cancellation: this is correct right? CE2 was different here.

2021-06-17 22:54 UTC, djspiewak requested changes
Very nice!!! Thank you!

Would you mind adding this to the `sidebar.json` file? That will make it show up on the site.

2021-06-17 22:54 UTC, djspiewak commented on docs/std/semaphore.md
> +being blocked while waiting to acquire a permit. Blocking acquires are cancelable.
It is correct! Also blocking acquires were *generally* cancelable in CE2 though, but it sometimes depended on how exactly you did the acquisition. In CE3 they're always cancelable.

2021-06-17 23:03 UTC, armanbilge commented
Np, this was an easy one :) fixed the sidebar, and also noticed the sidebar TODO. Still quite a bit to do? Adding a page for `IO` would be nice, the lack of docs for `IOLocal` came up on Discord but I wasn't sure where they should go.

2021-06-18 16:04 UTC, djspiewak commented
> Np, this was an easy one :) fixed the sidebar, and also noticed the sidebar TODO. Still quite a bit to do? Adding a page for IO would be nice, the lack of docs for IOLocal came up on Discord but I wasn't sure where they should go.

Not sure either; let's just write them first and then place them somewhere! :-)

LOTS of stuff to do. I have a somewhat outdated list in #1715, and more generally in the [📚 docs label](https://github.com/typelevel/cats-effect/labels/%3Abooks%3A%20docs)

2021-06-18 16:04 UTC, merged