Add syntax for Supervisor
typelevel/cats-effect pull request #2105
Opened 2021-07-07 21:01 UTC by armanbilge

Following up on #2068.

2021-07-07 21:59 UTC, djspiewak requested changes

2021-07-07 21:59 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/syntax/package.scala
> +package object syntax {
I think this also needs an `all` and an `AllSyntax`, following the boilerplate pattern of the other packages. Otherwise, looks good!

2021-07-07 22:05 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/syntax/package.scala
> +package object syntax {
Definitely. Do we want to make `all` in core extend from this too?

2021-07-07 22:18 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/syntax/package.scala
> +package object syntax {
Hmm. In fact, shouldn't this `all` extend from kernel? To minimize imports

2021-07-07 22:22 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/syntax/package.scala
> +package object syntax {
I think that `all` in **core** should extend from this for sure. I don't think this should extend from **kernel** though. If you're using **std**, you should be more a la carte. If you're using **core**, you just get the whole thing by default.

2021-07-07 22:32 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/syntax/package.scala
> +package object syntax {
Done and done.

2021-07-07 22:51 UTC, djspiewak commented
Scalafmt :-)

2021-07-07 22:53 UTC, armanbilge commented
This was a weird one! I ran it like 100x, nothing, then tried `sbt clean` and it did its thing.

2021-07-07 22:58 UTC, djspiewak commented
`prePR` helps but doesn't cover everything. The scalafmt plugin is super weird. Restarting sbt and then running `prePR` usually does the trick.

2021-07-08 00:18 UTC, armanbilge commented
CI seems to be stuck checking workflows are up-to-date for an hour 🙃

2021-07-09 22:28 UTC, merged