Cats Effect 3 tracing docs
typelevel/cats-effect pull request #2128
Opened 2021-07-14 22:21 UTC by vasilmkd

2021-07-18 03:52 UTC, djspiewak requested changes
This is really great! I made a few suggestions along the way to try to make it more ever-green (i.e. just as relevant to a reader years from now as it is today). Also not *entirely* sure to do with the section in the middle, but we can work on it.

2021-07-18 03:52 UTC, djspiewak commented on docs/tracing.md
> +Cats Effect 3 release comes with the following features:
```suggestion
meaningful stack traces:
```

I'm not quite sure what to do with the following section. It contains some really cool information, but it also reads a lot more like release notes than documentation. :-) Maybe that's okay.

2021-07-18 03:52 UTC, djspiewak commented on docs/tracing.md
> +   - Class-loader safety -- for the first time ever, long-running Cats Effect
```suggestion
   - Class-loader safety -- long-running Cats Effect
```

2021-07-18 03:52 UTC, djspiewak commented on docs/tracing.md
> +mechanism of Cats Effect 3 has been completely rewritten to take advantage of
```suggestion
mechanism of Cats Effect was completely rewritten in version 3.2 to take advantage of
```

2021-07-18 03:52 UTC, djspiewak commented on docs/tracing.md
> +   stack tracing feature for Cats Effect 3, it was measured that the switch to
```suggestion
   stack tracing feature for Cats Effect, it was measured that the switch to
```

2021-07-18 03:52 UTC, djspiewak commented on docs/tracing.md
> +remember to performance test your specific application with tracing enabled
```suggestion
remember to performance test your specific application with and without tracing enabled
```

2021-07-18 03:52 UTC, djspiewak commented on docs/tracing.md
> +No tracing is instrumented by the program and thus incurs no performance impact.
```suggestion
Tracing is fully disabled and all performance impacts are negated. Outside of some extremely small (~8-16 bytes) object footprint differences, this should be exactly identical to a hypothetical `IO` run-loop which lacks any support for tracing.
```

2021-07-18 03:52 UTC, djspiewak commented on docs/tracing.md
> +applications and is enabled by default.
```suggestion
It's also worth qualifying the above numbers slightly. A "30% performance degradation" in this case is defined relative to `IO`'s evaluation *without any support for tracing.* This performance bar is extremely high, meaning that the absolute (as opposed to relative) difference between "tracing" and "no tracing at all" is measured in micro- and nanoseconds in most cases. To put all of this in perspective, even with tracing, `IO`'s evaluation is still multiple orders of magnitude faster than the equivalent program written using Scala's `Future` when measured using the same highly-synthetic benchmarks. All of which is not to say that `Future` is slow, but rather that these benchmarks are attempting to magnify even the slightest differences in `IO`'s performance and are not representative of most real-world scenarios.

When tracing was first introduced in Cats Effect 2, its absolute performance impact was considerably higher than the impact of the rewritten implementation in Cats Effect 3.2. Despite this, even extremely performance-sensitive real world applications subjected to intensive benchmarking and stress testing did not observe differences in top-line metrics.

It is for this reason that `cached` tracing is on by default, and is the recommended mode even when running in production.
```

2021-07-18 03:52 UTC, djspiewak commented on docs/tracing.md
> +The stack trace of an exception caught by the Cats Effect 3 `IO` runtime looks
```suggestion
Without tracing, the stack trace of an exception caught by the `IO` runtime often looks
```

2021-07-18 03:52 UTC, djspiewak commented on docs/tracing.md
> +```scala
```suggestion
```scala mdoc
```

2021-07-18 20:43 UTC, vasilmkd commented
I incorporated your changes in a single commit and reformatted the page.

2021-07-18 20:45 UTC, vasilmkd commented
I don't mind taking the middle part and dropping it in the release notes.

2021-07-19 14:54 UTC, djspiewak commented
Eh, let's keep it :-D

2021-07-19 14:54 UTC, merged