Add method forwarders to `Resource`
typelevel/cats-effect pull request #2134
Opened 2021-07-20 18:19 UTC by alexandrustana

This PR should fix #2116

2021-07-20 21:05 UTC, djspiewak requested changes
Looks really good! Some changes are needed, but this is close

2021-07-20 21:05 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +      implicit F: MonadCancel[F, Throwable]): Resource[F, A @uncheckedVariance] =
Does this actually need `@uncheckedVariance`?

2021-07-20 21:05 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +        Functor[(A @uncheckedVariance, *)].map(p)(fin => (_: Resource.ExitCase) => fin)
I'm guessing it's not needed here either

2021-07-20 21:05 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +        Functor[(A @uncheckedVariance, *)].map(p)(fu => (_: Resource.ExitCase) => fu))
Or here

2021-07-20 21:05 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +  def evalOn(ec: ExecutionContext)(implicit F: Async[F]): Resource[F, A @uncheckedVariance] =
Or here

2021-07-20 21:05 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +        Functor[(A @uncheckedVariance, *)].map(p)(fin => (_: Resource.ExitCase) => fin)
Or here

2021-07-20 21:05 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +      implicit F: MonadError[F, E]): Resource[F, A] =
Actually, this is the compiler telling you that you need a different type here! In particular, the signature should be something like this:

```suggestion
  def handleErrorWith[B >: A, E](f: E => Resource[F, B])(implicit F: MonadError[F, E]): Resource[F, B] =
```

2021-07-20 21:05 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +      implicit A: Semigroup[A @uncheckedVariance]): Resource[F, A] =
```suggestion
  def combine[B >: A](that: Resource[F, B])(implicit A: Semigroup[B]): Resource[F, B] =
```

2021-07-20 21:05 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +  def combineK(that: Resource[F, A @uncheckedVariance])(
Similar pattern to `combine`

2021-07-21 10:18 UTC, alexandrustana commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +      implicit F: MonadError[F, E]): Resource[F, A] =
Yeah, the compiler was pointing that the type variance wasn't ok.
I've switched to this approach (thank you for pointing it out) and removed the `@uncheckedVariance` occurrences

2021-07-21 14:39 UTC, djspiewak requested changes
Went a bit too far! :-) Some of these *do* need `uncheckedVariance`.

2021-07-21 14:39 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +      implicit F: MonadCancel[F, Throwable]): Resource[F, B] =
I think this one *shouldn't* need the context bounds.

```suggestion
  def onCancel(fin: Resource[F, Unit])(
      implicit F: MonadCancel[F, Throwable]): Resource[F, A] =
```

2021-07-21 14:39 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +      implicit F: MonadCancel[F, Throwable]): Resource[F, B] =
```suggestion
  def guaranteeCase(fin: Outcome[Resource[F, *], Throwable, A @uncheckedVariance] => Resource[F, Unit])(
      implicit F: MonadCancel[F, Throwable]): Resource[F, A] =
```

This is one case where I believe `@uncheckedVariance` is actually needed, for the same reason it is needed in `IO`.

2021-07-21 14:39 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +      implicit F: Concurrent[F]): Resource[F, Fiber[Resource[F, *], Throwable, B]] = {
```suggestion
  def start(
      implicit F: Concurrent[F]): Resource[F, Fiber[Resource[F, *], Throwable, A @uncheckedVariance]] = {
```

This one also needs `uncheckedVariance`. Basically this comes from the fact that `Fiber` and `Outcome` are both invariant, but their parameter is used in entirely covariant contexts when the type constructor is also covariant, meaning that `uncheckedVariance` is sound.

2021-07-21 14:39 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +  def evalOn[B >: A](ec: ExecutionContext)(implicit F: Async[F]): Resource[F, B] =
```suggestion
  def evalOn(ec: ExecutionContext)(implicit F: Async[F]): Resource[F, A] =
```

Another unnecessary context bound.

2021-07-21 15:19 UTC, alexandrustana commented
> Went a bit too far! :-) Some of these _do_ need `uncheckedVariance`.

Sorry for that 😓 

Seems that this type of functor invocation: `Functor[(A, *)].map(...)` 
also needs some kind of solution(`covariant type A occurs in invariant position in type [β$4$](A, β$4$) of type Λ$`). 
Maybe  `@uncheckedVariance` ?

2021-07-21 15:44 UTC, joroKr21 approved these changes
Some constraints can be relaxed further

2021-07-21 15:44 UTC, joroKr21 commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +  def attempt[E](implicit F: MonadError[F, E]): Resource[F, Either[E, A]] =
```suggestion
  def attempt[E](implicit F: ApplicativeError[F, E]): Resource[F, Either[E, A]] =
```

2021-07-21 15:44 UTC, joroKr21 commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +        MonadError[Resource[F, *], E].attempt(source).flatMap {
```suggestion
        source.attempt.flatMap {
```

2021-07-21 15:44 UTC, joroKr21 commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +      implicit F: MonadError[F, E]): Resource[F, B] =
```suggestion
      implicit F: ApplicativeError[F, E]): Resource[F, B] =
```

2021-07-21 15:44 UTC, joroKr21 commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +  def canceled[F[_]](implicit F: MonadCancel[F, Throwable]): Resource[F, Unit] =
```suggestion
  def canceled[F[_]](implicit F: MonadCancel[F, _]): Resource[F, Unit] =
```

2021-07-21 15:44 UTC, joroKr21 commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +  def never[F[_], A](implicit F: GenSpawn[F, Throwable]): Resource[F, A] =
```suggestion
  def never[F[_], A](implicit F: GenSpawn[F, _]): Resource[F, A] =
```

2021-07-21 15:44 UTC, joroKr21 commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +  def cede[F[_]](implicit F: GenSpawn[F, Throwable]): Resource[F, Unit] =
```suggestion
  def cede[F[_]](implicit F: GenSpawn[F, _]): Resource[F, Unit] =
```

2021-07-21 15:44 UTC, joroKr21 commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +      implicit F: GenConcurrent[F, Throwable]): Resource[F, Deferred[Resource[F, *], A]] =
```suggestion
      implicit F: GenConcurrent[F, _]): Resource[F, Deferred[Resource[F, *], A]] =
```

2021-07-21 15:44 UTC, joroKr21 commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +      implicit F: GenConcurrent[F, Throwable]): Resource[F, Ref[Resource[F, *], A]] =
```suggestion
      implicit F: GenConcurrent[F, _]): Resource[F, Ref[Resource[F, *], A]] =
```

2021-07-21 15:44 UTC, joroKr21 commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +      implicit F: GenTemporal[F, Throwable]): Resource[F, Unit] =
```suggestion
      implicit F: GenTemporal[F, _]): Resource[F, Unit] =
```

2021-07-21 15:44 UTC, joroKr21 commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +  def raiseError[F[_], A, E](e: E)(implicit F: MonadError[F, E]): Resource[F, A] =
```suggestion
  def raiseError[F[_], A, E](e: E)(implicit F: ApplicativeError[F, E]): Resource[F, A] =
```

2021-07-21 15:53 UTC, joroKr21 commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +        MonadError[Resource[F, *], E].attempt(source).flatMap {
This is probably not stack safe though

2021-07-21 16:21 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +        MonadError[Resource[F, *], E].attempt(source).flatMap {
It sucks but we probably have to `defer` around it.

2021-07-21 16:23 UTC, djspiewak commented
> Seems that this type of functor invocation: Functor[(A, *)].map(...)
also needs some kind of solution(covariant type A occurs in invariant position in type [β$4$](A, β$4$) of type Λ$).
> Maybe @uncheckedVariance ?

Ah that's unfortunate. Yes, it needs `@uncheckedVariance`. I'm actually slightly surprised that it has this problem, but it's not the end of the world.

2021-07-21 19:01 UTC, alexandrustana commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +        MonadError[Resource[F, *], E].attempt(source).flatMap {
Using `allocated` would require having `MonadCancel` in scope.

2021-07-22 12:20 UTC, alexandrustana commented
> Some constraints can be relaxed further

Thank you for the suggestions, I've tried to relax constraints in the places you suggested.
This however generated the need for an `ApplicativeError` instance and having this enabled me to change the hierarchy a bit. (e.g. `ResourceMonadError` now extends `ResourceMonad` and also `ResourceApplicativeError`)

2021-07-22 13:03 UTC, joroKr21 commented
> This however generated the need for an ApplicativeError instance and having this enabled me to change the hierarchy a bit. (e.g. ResourceMonadError now extends ResourceMonad and also ResourceApplicativeError)

Hmm I thought the constraints are on the `F` not on `Resource` - unless we nest them? 🤔

2021-07-23 07:49 UTC, alexandrustana commented
Unfortunately, the constraints are on `Resource`. Not sure what you mean about nesting 😅

2021-07-23 08:19 UTC, vasilmkd requested changes

2021-07-23 08:19 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +abstract private[effect] class ResourceApplicative[F[_]] extends Applicative[Resource[F, *]] {
Please revert this class, we have an implementation for `Applicative[Resource[F, *]]` because `Monad[Resource[F, *]]` extends it.

2021-07-23 08:19 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +private[effect] trait ResourceApplicativeError[F[_], E]
Please also remove this class, we have it through `MonadError[Resource[F, *], E]`.

2021-07-23 08:19 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +    Resource.raiseError[F, A, E](e)
Put these lines back in `ResourceMonadError` and also override `attempt` there.

2021-07-23 08:19 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +
Also remove these 2 traits.

2021-07-23 08:19 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +        ApplicativeError[Resource[F, *], E].attempt(source).flatMap {
Replace this line with `source.attempt.flatMap {` and you should be done. 😄

2021-07-23 08:23 UTC, joroKr21 commented
> Unfortunately, the constraints are on Resource. Not sure what you mean with nesting 😅

All the suggestions I made were constraints on `F[_]` 🤔 
I even checked that it compiles with just those changes.
By nesting I meant something like `Resource[Resource[F, *], A]` 😃

2021-07-23 13:01 UTC, alexandrustana commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +        ApplicativeError[Resource[F, *], E].attempt(source).flatMap {
I really thought that `attempt` would cause a `StackOverflow` that's why  I went with changing the hierarchy 😭

2021-07-23 13:07 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +        ApplicativeError[Resource[F, *], E].attempt(source).flatMap {
That was already the case before. We might want to do something about it now, let me see.

2021-07-23 13:08 UTC, alexandrustana commented
I kind of went over the top with these changes, didn't think just using `source.attempt` would be enough. 
Thank you @joroKr21 and @vasilmkd for the review and the suggestions.

2021-07-23 18:13 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +        ApplicativeError[Resource[F, *], E].attempt(source).flatMap {
Indeed, this is stack unsafe, but the previous implementation is also stack unsafe. Let's think about how to fix that in another issue/PR, this one is big enough.

2021-07-23 22:45 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +        Functor[(B, *)].map(p)(fin => (_: Resource.ExitCase) => fin)
We have an `import Resource._` at the top of the class body, so you can drop reduce `Resource.ExitCase` to `ExitCase`. Same for all the other places.

2021-07-23 22:45 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +  def forceR[B](that: Resource[F, B])(implicit F: MonadCancel[F, Throwable]): Resource[F, B] =
@djspiewak We don't have this for IO.

2021-07-23 22:45 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +  def empty[F[_], A](implicit A: Monoid[A]): Resource[F, A] = Resource.pure[F, A](A.empty)
@djspiewak I think this one is confusing. Thoughts? We don't have it for `IO`.

2021-07-23 22:46 UTC, vasilmkd commented
I fixed the stack-safety of `attempt` and added unit tests as well.

2021-07-24 01:18 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +  def forceR[B](that: Resource[F, B])(implicit F: MonadCancel[F, Throwable]): Resource[F, B] =
We should!

2021-07-24 01:18 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +  def empty[F[_], A](implicit A: Monoid[A]): Resource[F, A] = Resource.pure[F, A](A.empty)
I'm kind of on the fence about this one. I'm okay with it for both `Resource` and `IO`, but devoid of context it's also a slightly odd name. Maybe we should pass on it for now.

2021-07-24 01:21 UTC, djspiewak approved these changes
Approved modulo `empty`. I think I agree with @vasilmkd that we should pull that one out. Everything else looks great though, and this unblocks 3.2!

2021-07-24 08:13 UTC, vasilmkd requested changes
Let me make the last needed changes official:

- [ ] Add `!>` which is the symbolic name of `forceR`.
- [ ] Remove `Resource.empty` and move the implementation to `Monoid[Resource[F, *], A]`

And we should be done. Great work! 🎉

2021-07-24 20:23 UTC, djspiewak commented
I made the pair of changes. I think that's all we needed!

2021-07-24 21:37 UTC, vasilmkd approved these changes

2021-07-24 21:38 UTC, merged