Add chrome to CI matrix
typelevel/cats-effect pull request #2150
Opened 2021-07-24 22:38 UTC by armanbilge

Let's see what happens.

2021-07-24 22:45 UTC, djspiewak commented on build.sbt
> +Global / useChromeEnv := false
Random bikeshedding: would it be better if we had a `seleniumEnv = settingKey[Option[Env]]` where `Env` is either `Firefox` or `Chrome`?

2021-07-24 22:45 UTC, djspiewak commented on build.sbt
> +        "cats.effect.unsafe.IORuntime.fiberErrorCbs"),
Can we do the scalafmt in a separate commit?

2021-07-24 22:48 UTC, armanbilge commented on build.sbt
> +Global / useChromeEnv := false
Definitely!

2021-07-24 22:49 UTC, armanbilge commented on build.sbt
> +        "cats.effect.unsafe.IORuntime.fiberErrorCbs"),
Oops, sure.

2021-07-28 19:37 UTC, armanbilge commented on build.sbt
> +Global / useChromeEnv := false
Using a `String` seemed easier than defining `Env` (I tried this and SBT balked, I think maybe we need to add a package declaration to `build.sbt`?) although I would certainly prefer the latter.

2021-07-29 16:20 UTC, vasilmkd requested changes
Looks good!

2021-07-29 16:20 UTC, vasilmkd commented on .github/workflows/ci.yml
> +            ci: ciChrome
I think we don't test Scala.js on Windows, so I vote for dropping these combinations.

2021-07-29 16:20 UTC, vasilmkd commented on build.sbt
> +import org.openqa.selenium.remote.server.DriverFactory
Can you please move this import below the license header and group it with the other ones.

2021-07-29 16:20 UTC, vasilmkd commented on build.sbt
> +  settingKey[Option[String]]("Use headless browser (via geckodriver) for running tests")
`geckodriver` is the Firefox browser driver. Just drop the `(via geckodriver)` comment.

2021-07-29 16:23 UTC, vasilmkd commented on build.sbt
> +Global / useChromeEnv := false
Maybe sbt needs a Scala source file in `project` which can define the `Env` trait and then it can be imported in the main `build.sbt`?

2021-07-29 16:25 UTC, armanbilge commented on build.sbt
> +Global / useChromeEnv := false
I can try that. Btw I think `Browser` is preferable to `Env`?

2021-07-29 16:25 UTC, armanbilge commented on build.sbt
> +import org.openqa.selenium.remote.server.DriverFactory
Oops, yup. auto-import must have snuck that in there.

2021-07-29 16:26 UTC, armanbilge commented on build.sbt
> +  settingKey[Option[String]]("Use headless browser (via geckodriver) for running tests")
Didn't realize this :) makes sense

2021-07-29 16:27 UTC, armanbilge commented on build.sbt
> +Global / useChromeEnv := false
Or if we do `Env` then we shouldn't make it an `Option` and instead include `NodeJS` as a possible `Env`?

2021-07-29 16:28 UTC, vasilmkd commented on build.sbt
> +Global / useChromeEnv := false
That sounds cool.

2021-07-29 16:29 UTC, vasilmkd commented on build.sbt
> +  settingKey[Option[String]]("Use headless browser (via geckodriver) for running tests")
All good. 😄

2021-07-30 04:02 UTC, djspiewak approved these changes, later dismissed
Very nice! Needs conflict resolution but otherwise this is awesome

2021-07-30 04:03 UTC, armanbilge commented on build.sbt
> +      profile.setPreference("privacy.file_unique_origin", false)
We need to find the Chrome equivalent of this.

2021-07-30 04:04 UTC, armanbilge commented
Sorry don't merge yet!! Need to get webworker going on Chrome.

2021-07-30 05:46 UTC, armanbilge commented on build.sbt
> +      options.addArguments("--allow-file-access-from-files")
that was easy!

2021-07-30 12:37 UTC, armanbilge commented
Would you accept a PR disabling `sbt --client`?

2021-07-30 19:04 UTC, vasilmkd commented on build.sbt
> +      profile.setPreference("privacy.file_unique_origin", false)
https://dev.to/dengel29/loading-local-files-in-firefox-and-chrome-m9f

2021-07-30 19:08 UTC, vasilmkd commented on build.sbt
> +      profile.setPreference("privacy.file_unique_origin", false)
https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/chromium/ChromiumOptions.html#addArguments(java.util.List)

2021-07-30 20:03 UTC, vasilmkd approved these changes

2021-07-30 20:03 UTC, vasilmkd commented
Very cool work.

2021-07-30 20:22 UTC, djspiewak approved these changes

2021-07-30 20:22 UTC, merged