Add ParallelBenchmark
typelevel/cats-effect pull request #2167
Opened 2021-07-27 13:50 UTC by manufacturist

As requested by @vasilmkd, moved the `ParallelBenchmark` to a new PR. The reason why there are 6 benchmarks is to compare the performance of `parTraverse` vs `traverse`, under different CPU load.

Posted the benchmarks for the `series/3.x`:

```sbt
[info] Benchmark                                    (size)   Mode  Cnt    Score   Error  Units
[info] ParallelBenchmark.parTraverseCpuTokens100     10000  thrpt   20   52.561 ± 1.691  ops/s
[info] ParallelBenchmark.parTraverseCpuTokens1000    10000  thrpt   20   44.141 ± 1.213  ops/s
[info] ParallelBenchmark.parTraverseCpuTokens10000   10000  thrpt   20   18.174 ± 0.254  ops/s
[info] ParallelBenchmark.traverseCpuTokens100        10000  thrpt   20  741.288 ± 9.223  ops/s
[info] ParallelBenchmark.traverseCpuTokens1000       10000  thrpt   20  134.859 ± 5.774  ops/s
[info] ParallelBenchmark.traverseCpuTokens10000      10000  thrpt   20   15.097 ± 0.458  ops/s
```

2021-07-27 14:01 UTC, djspiewak commented
Outstanding! If I may ask, how many physical threads does your machine have? (`Runtime.getRuntime().availableProcessors()`)

2021-07-27 14:01 UTC, manufacturist commented
> Outstanding! If I may ask, how many physical threads does your machine have? (`Runtime.getRuntime().availableProcessors()`)

^ Just updated the machine details

2021-07-27 14:06 UTC, djspiewak commented on benchmarks/src/main/scala/cats/effect/benchmarks/ParallelBenchmark.scala
> +    1.to(size).toList.parTraverse(_ => IO(Blackhole.consumeCPU(1000L))).void.unsafeRunSync()
Ah! This isn't quite what I had in mind. The consumption time itself is less interesting to me than the size. We should tune the consumption time so that the `traverse` benchmarks step reasonably, so we're not drowning in noise.

```suggestion
  def parTraverseCpuTokens(): Unit =
    1.to(size).toList.parTraverse(_ => IO(Blackhole.consumeCPU(100L))).void.unsafeRunSync()
```

The `size` parameter can be specified in the `jmh` invocation, which is why `@Param` is helpful.

2021-07-27 14:12 UTC, djspiewak commented on benchmarks/src/main/scala/cats/effect/benchmarks/ParallelBenchmark.scala
> +    1.to(size).toList.parTraverse(_ => IO(Blackhole.consumeCPU(1000L))).void.unsafeRunSync()
Actually I retract my comment. This is fine :-)

2021-07-27 15:24 UTC, vasilmkd commented
I'm running the benchmark too, I will post base results.

2021-07-27 15:49 UTC, vasilmkd commented
```
Benchmark                                    (size)   Mode  Cnt    Score   Error  Units
ParallelBenchmark.parTraverseCpuTokens100     10000  thrpt   20   95.980 ± 0.942  ops/s
ParallelBenchmark.parTraverseCpuTokens1000    10000  thrpt   20   67.336 ± 8.235  ops/s
ParallelBenchmark.parTraverseCpuTokens10000   10000  thrpt   20   26.116 ± 0.104  ops/s
ParallelBenchmark.traverseCpuTokens100        10000  thrpt   20  361.982 ± 7.369  ops/s
ParallelBenchmark.traverseCpuTokens1000       10000  thrpt   20   54.546 ± 0.286  ops/s
ParallelBenchmark.traverseCpuTokens10000      10000  thrpt   20    5.711 ± 0.016  ops/s
```

2021-07-27 19:57 UTC, vasilmkd approved these changes

2021-07-27 20:27 UTC, djspiewak requested changes
Hold on merging this. Some changes @manufacturist and I discussed directly

2021-07-27 20:28 UTC, vasilmkd requested changes
Waiting for discussed changes then.

2021-07-28 05:52 UTC, manufacturist commented
Ran the benchmark with cpuTokens values `100` & `100000` as well to get more data & pushed the discussed changes from yesterday:
* Scale the cpuTokens from 0.1k - 10k to 1k & 100k
* Parametrize size as well

```bash
[info] Benchmark                      (cpuTokens)  (size)   Mode  Cnt      Score     Error  Units
[info] ParallelBenchmark.parTraverse          100     100  thrpt   20   6487.985 ± 251.364  ops/s
[info] ParallelBenchmark.parTraverse          100    1000  thrpt   20    791.526 ±   6.699  ops/s
[info] ParallelBenchmark.parTraverse          100   10000  thrpt   20     75.203 ±   0.372  ops/s
[info] ParallelBenchmark.parTraverse         1000     100  thrpt   20   4505.063 ± 170.821  ops/s
[info] ParallelBenchmark.parTraverse         1000    1000  thrpt   20    545.267 ±   3.686  ops/s
[info] ParallelBenchmark.parTraverse         1000   10000  thrpt   20     58.031 ±   4.109  ops/s
[info] ParallelBenchmark.parTraverse        10000     100  thrpt   20   2294.218 ±   7.110  ops/s
[info] ParallelBenchmark.parTraverse        10000    1000  thrpt   20    237.894 ±   1.132  ops/s
[info] ParallelBenchmark.parTraverse        10000   10000  thrpt   20     22.876 ±   0.288  ops/s
[info] ParallelBenchmark.parTraverse       100000     100  thrpt   20    320.065 ±   0.294  ops/s
[info] ParallelBenchmark.parTraverse       100000    1000  thrpt   20     32.039 ±   0.173  ops/s
[info] ParallelBenchmark.parTraverse       100000   10000  thrpt   20      3.186 ±   0.040  ops/s
[info] ParallelBenchmark.parTraverse      1000000     100  thrpt   20     33.128 ±   0.042  ops/s
[info] ParallelBenchmark.parTraverse      1000000    1000  thrpt   20      3.318 ±   0.008  ops/s
[info] ParallelBenchmark.parTraverse      1000000   10000  thrpt   20      0.351 ±   0.035  ops/s
[info] ParallelBenchmark.traverse             100     100  thrpt   20  68114.475 ± 750.640  ops/s
[info] ParallelBenchmark.traverse             100    1000  thrpt   20   8024.076 ± 104.133  ops/s
[info] ParallelBenchmark.traverse             100   10000  thrpt   20    918.410 ±   4.294  ops/s
[info] ParallelBenchmark.traverse            1000     100  thrpt   20  15431.432 ±  32.394  ops/s
[info] ParallelBenchmark.traverse            1000    1000  thrpt   20   1615.529 ±  19.228  ops/s
[info] ParallelBenchmark.traverse            1000   10000  thrpt   20    166.345 ±   0.537  ops/s
[info] ParallelBenchmark.traverse           10000     100  thrpt   20   1766.005 ±   7.986  ops/s
[info] ParallelBenchmark.traverse           10000    1000  thrpt   20    178.010 ±   0.157  ops/s
[info] ParallelBenchmark.traverse           10000   10000  thrpt   20     17.718 ±   0.106  ops/s
[info] ParallelBenchmark.traverse          100000     100  thrpt   20    179.566 ±   0.178  ops/s
[info] ParallelBenchmark.traverse          100000    1000  thrpt   20     17.847 ±   0.110  ops/s
[info] ParallelBenchmark.traverse          100000   10000  thrpt   20      1.728 ±   0.061  ops/s
[info] ParallelBenchmark.traverse         1000000     100  thrpt   20     17.867 ±   0.094  ops/s
[info] ParallelBenchmark.traverse         1000000    1000  thrpt   20      1.717 ±   0.084  ops/s
[info] ParallelBenchmark.traverse         1000000   10000  thrpt   20      0.178 ±   0.006  ops/s

```

2021-07-28 09:55 UTC, vasilmkd commented
Excellent.

2021-07-28 11:08 UTC, djspiewak approved these changes, later dismissed
Outstanding! That's actually more data points than I was expecting. 🙂 This is going to be super useful for some other changes as well, thank you!

2021-07-28 12:56 UTC, djspiewak approved these changes

2021-07-28 23:04 UTC, vasilmkd approved these changes

2021-07-28 23:04 UTC, vasilmkd commented
Thank you @manufacturist! Great work.

2021-07-28 23:04 UTC, merged