Add JSDOMNodeJSEnv to ci matrix and fix polyfill
typelevel/cats-effect pull request #2191
Opened 2021-08-02 19:18 UTC by armanbilge

My own attempt to fix the problem reported in #2188.

2021-08-02 21:11 UTC, djspiewak requested changes

2021-08-02 21:11 UTC, djspiewak commented on build.sbt
> +addCommandAlias("ciJSDOMNodeJS", browserCiCommand(JSDOMNodeJS))
Can you also update the `ci` alias? We should probably generate that alias in a way which requires less redundancy.

2021-08-02 21:19 UTC, armanbilge commented on build.sbt
> +addCommandAlias("ciJSDOMNodeJS", browserCiCommand(JSDOMNodeJS))
Fixed, I'll leave a generation scheme for a subsequent bikeshed sorry :)

2021-08-02 21:21 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/PolyfillExecutionContext.scala
> +            js.Dynamic.global.onmessage = { () => postMessageIsAsynchronous = false }
Why not also check if `onmessage` is undefined in the `if` statement?

2021-08-02 21:26 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/PolyfillExecutionContext.scala
> +            js.Dynamic.global.onmessage = { () => postMessageIsAsynchronous = false }
I considered this too, but `onmessage` in my browser console is `null`.

2021-08-02 21:27 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/PolyfillExecutionContext.scala
> +            js.Dynamic.global.onmessage = { () => postMessageIsAsynchronous = false }
Well, maybe that makes sense for my browser ... anyway I figured better not to mess with the if conditions since those are important.

2021-08-02 21:28 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/PolyfillExecutionContext.scala
> +            js.Dynamic.global.onmessage = { () => postMessageIsAsynchronous = false }
`null` is not the same as `undefined`, so it would pass the if check. Just saying.

2021-08-02 21:29 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/PolyfillExecutionContext.scala
> +            js.Dynamic.global.onmessage = { () => postMessageIsAsynchronous = false }
I'm not too fussed about it, but we should maybe try it.

2021-08-02 21:30 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/PolyfillExecutionContext.scala
> +            js.Dynamic.global.onmessage = { () => postMessageIsAsynchronous = false }
You are right, but IIRC correctly it is also `null` in JSDOMNodeJS env.

2021-08-02 21:30 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/PolyfillExecutionContext.scala
> +            js.Dynamic.global.onmessage = { () => postMessageIsAsynchronous = false }
Sorry, to clarify I think what I considered was adding a `null` check to the if statment.

2021-08-02 23:14 UTC, japgolly commented on core/js/src/main/scala/cats/effect/unsafe/PolyfillExecutionContext.scala
> +            case NonFatal(_) =>
This isn't going to work. Scala.JS (unfortunately) throws a fatal exception when referencing something in JS-land that isn't there at runtime. You've got to catch all exceptions.

2021-08-02 23:18 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/PolyfillExecutionContext.scala
> +            case NonFatal(_) =>
Thanks again for your eyes on this ... currently this is passing in all test environments, is there something I'm missing??

2021-08-04 22:51 UTC, japgolly commented
I just tested this and it does indeed work! Thanks for the revision! :+1:

2021-08-04 22:55 UTC, japgolly commented on core/js/src/main/scala/cats/effect/unsafe/PolyfillExecutionContext.scala
> +            case NonFatal(_) =>
No it turns out I'm wrong, it seems I'm the one that's missing something :smile: I tested this out and it works just as you're expecting it to.... which is so strange to me because my beliefs were built on experiences. Maybe Scala.JS has received some changes as to how this bit of surface area works and I must've missed it. I'll invalid my mental cache. Thanks for the collaboration :)

2021-08-04 22:56 UTC, armanbilge commented
Hooray!! Thanks for giving it a spin :)

2021-08-04 22:59 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/PolyfillExecutionContext.scala
> +            case NonFatal(_) =>
No worries! It sounded plausible to me too, I could have sworn I had similar experiences 🙃 But on the other hand I was able to replicate an issue with CI here, and make it go away, and it was consistent with your import scripts trick.

2021-08-04 23:10 UTC, vasilmkd approved these changes

2021-08-05 13:05 UTC, armanbilge commented on .gitignore
> +package-lock.json
@vasilmkd @djspiewak Just want to make sure you're aware that I decided to ignore the lockfile (created by the `JSDOM` dependency), but not sure about this decision at all. @mpilquist, @ChristopherDavenport, @rossabaker, and I have been struggling with this same issue for fs2 and http4s.

In this case its just a test dependency, but @rossabaker makes a good point about repeatable builds. https://github.com/http4s/http4s/pull/4938#discussion_r683397866

2021-08-05 13:08 UTC, vasilmkd requested changes
Holding off until a decision about the `package-lock` file has been made.

2021-08-05 15:17 UTC, vasilmkd commented
Wait a second, what @djspiewak asked in [Discord](https://discord.com/channels/632277896739946517/839254871646404638/872835073932660786) is actually a very valid question. If `JSDOMNodeJSEnv` is indeed running in `node`, which we know it is, then this code path should not be exercised at all, because `node` supports `setImmediate` natively. I'm confused here.

2021-08-05 15:18 UTC, armanbilge commented
It's possible they are somehow disabling it, to better emulate the browser?

2021-08-05 15:27 UTC, vasilmkd commented
I confirm that the native `setImmediate` works on vanilla `node`. I'm investigating further.

2021-08-05 15:42 UTC, armanbilge commented
> Holding off until a decision about the package-lock file has been made.

We decided to commit this.

2021-08-05 16:35 UTC, vasilmkd commented
I set up a small node project locally.

```
npm init
npm install --save jsdom
```

I copied code from their readme to get a basic set up going:

```js
// From the jsdom readme
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

// these 4 lines are mine
console.log(global.setImmediate);
global.setImmediate(() => console.log('hello setImmediate'));
console.log(setImmediate);
setImmediate(() => console.log('hello again setImmediate'));

// from the jsdom readme
const dom = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);
console.log(dom.window.document.querySelector("p").textContent); // "Hello world"

```

And I'm seeing this output:
```
[Function: setImmediate] {
  [Symbol(nodejs.util.promisify.custom)]: [Getter]
}
[Function: setImmediate] {
  [Symbol(nodejs.util.promisify.custom)]: [Getter]
}
Hello world
hello setImmediate
hello again setImmediate
```

This IMO means that `setImmediate` is not being disabled by `jsdom`.

2021-08-05 16:39 UTC, armanbilge commented
I mean, that all seems reasonable ... now try running it again through the ScalaJS test bridge? https://github.com/scala-js/scala-js-env-jsdom-nodejs

2021-08-05 16:41 UTC, vasilmkd commented
It fails there, or rather reports `undefined`. That doesn't mean that `jsdom` is doing something to disable it. It could just mean that our discovery process is wrong.

2021-08-05 16:45 UTC, armanbilge commented
> It could just mean that our discovery process is wrong.

That may very well be true, but I feel very inclined not to touch it. JSDOM is a fake environment, only used for testing. Whatever works should suffice.

2021-08-05 16:47 UTC, vasilmkd commented
I'm just using the PR to document all discoveries, I think this is more or less good to go.

2021-08-05 16:50 UTC, armanbilge commented
> I'm just using the PR to document all discoveries, I think this is more or less good to go.

Oh, absolutely, I appreciate your research efforts! Apologies if came across curt.

2021-08-05 17:39 UTC, vasilmkd commented
Found it, `scalajs-js-env-jsdom-nodejs` seems to hide a lot of `global` things https://github.com/scala-js/scala-js-env-jsdom-nodejs/pull/19.

2021-08-05 17:40 UTC, vasilmkd approved these changes

2021-08-05 17:41 UTC, armanbilge commented
Cool, that's what I thought!

2021-08-05 18:51 UTC, djspiewak approved these changes

2021-08-05 18:52 UTC, merged