WIP to fix IO cached tracing delay issue
typelevel/cats-effect pull request #2226
Opened 2021-08-13 11:42 UTC by armanbilge

The first commit demonstrates the issue described in #2225, note the test fails only for Scala 3.

2021-08-13 12:45 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    Delay(fn, Tracing.calculateTracingEvent(tracing.ThunkClassRetriever(thunk)))
Inline the lambda in `Delay` and remove the braces around the method.

2021-08-13 12:49 UTC, vasilmkd commented on core/jvm/src/main/scala/cats/effect/tracing/ThunkClassRetriever.scala
> +}
Can you move this into `Tracing.scala`?

2021-08-13 12:49 UTC, vasilmkd commented on core/jvm/src/main/scala/cats/effect/tracing/ThunkClassRetriever.scala
> +}
And rename the `apply` method to getThunkClass or something.

2021-08-13 12:50 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/tracing/ThunkClassRetriever.scala
> +}
Err, wait, not sure. `Tracing.scala` is cross-platform but we can't implement this on JS.

2021-08-13 12:53 UTC, vasilmkd commented on core/jvm/src/main/scala/cats/effect/tracing/ThunkClassRetriever.scala
> +}
`Platform`.

2021-08-13 13:05 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/tracing/ThunkClassRetriever.scala
> +private[tracing] class ThunkClassRetrieverImpl extends ThunkClassRetriever {
No need for `private[tracing]`, just `private`.

2021-08-13 13:06 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/tracing/ThunkClassRetriever.scala
> +private[tracing] class ThunkClassRetrieverImpl extends ThunkClassRetriever {
If it's just private, then we can't do `new` in `Tracing` I think.

2021-08-13 13:06 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/tracing/ThunkClassRetriever.scala
> +private[tracing] class ThunkClassRetrieverImpl extends ThunkClassRetriever {
Also please make the filename `ThunkClassRetrieverImpl`.

2021-08-13 13:07 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/tracing/ThunkClassRetriever.scala
> +private[tracing] class ThunkClassRetrieverImpl extends ThunkClassRetriever {
Oh I guess we can :) cool

2021-08-13 14:18 UTC, djspiewak reviewed
So this makes a lot of sense, and is also disheartening because it means that Scala 3 isn't optimizing thunk-to-function conversion, and thus Delay nodes are more expensive on that platform. I actually wonder if it would be even better to generalize this machinery slightly, and rather than returning the Class, return a Function0. We can still get the class from it, but effectively we would be cheating the compiler into implementing the optimization it previously did naturally.

2021-08-13 14:20 UTC, armanbilge commented
> I actually wonder if it would be even better to generalize this machinery slightly, and rather than returning the Class, return a Function0

Clever! Why not?

2021-08-13 14:33 UTC, vasilmkd commented
Please make it a part of tracing...

2021-08-13 14:33 UTC, armanbilge commented
Lol!

2021-08-13 14:34 UTC, vasilmkd commented
Or keep it in `cats.effect`. Just not in a subpackage.

2021-08-13 14:36 UTC, vasilmkd commented on core/jvm/src/main/java/cats/effect/util/ThunkImpl.java
> +}
Let's add a comment/javadoc on this class explaining the need for its existence. Mention the differences between Scala 2 and Scala 3.

2021-08-13 15:03 UTC, vasilmkd commented on core/jvm/src/main/java/cats/effect/ThunkImpl.java
> +  public <A> scala.Function0<A> asFunction0(scala.Function0<A> thunk) {
Add an `@Override` here.

2021-08-13 16:38 UTC, vasilmkd requested changes

2021-08-13 16:38 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/tracing/ThunkClassRetriever.scala
> +}
This is a leftover from the previous encoding. I think this is the final change left to do.

2021-08-13 17:21 UTC, vasilmkd reviewed
Can we run a quick `DeepBindBenchmark.delay` _without_ tracing on Scala 2.13 and Scala 3? Before and after.

2021-08-13 18:01 UTC, armanbilge commented
Command: `benchmarks/Jmh/run -wi 10 -i 10 -f 2 -t 1 DeepBindBenchmark.delay --jvmArgs -Dcats.effect.tracing.mode=none`

2.13 before:
```
[info] Benchmark                (size)   Mode  Cnt     Score    Error  Units
[info] DeepBindBenchmark.delay   10000  thrpt   20  3588.051 ± 75.498  ops/s
```

3 before:
```
[info] Benchmark                (size)   Mode  Cnt     Score    Error  Units
[info] DeepBindBenchmark.delay   10000  thrpt   20  2841.203 ± 45.684  ops/s
```

2.13 after:
```
[info] Benchmark                (size)   Mode  Cnt     Score    Error  Units
[info] DeepBindBenchmark.delay   10000  thrpt   20  3487.627 ± 87.979  ops/s
```

3 after:
```
[info] Benchmark                (size)   Mode  Cnt     Score    Error  Units
[info] DeepBindBenchmark.delay   10000  thrpt   20  3897.315 ± 39.551  ops/s
```

2021-08-13 22:05 UTC, armanbilge commented
2.13 @ 7732752:
```
[info] Benchmark                (size)   Mode  Cnt     Score     Error  Units
[info] DeepBindBenchmark.delay   10000  thrpt   20  3453.852 ± 110.719  ops/s
```

3 @ 7732752:
```
[info] Benchmark                (size)   Mode  Cnt     Score     Error  Units
[info] DeepBindBenchmark.delay   10000  thrpt   20  3431.805 ± 216.061  ops/s
```

2021-08-13 22:18 UTC, armanbilge commented
3 @ 7732752 (take 2):
```
[info] Benchmark                (size)   Mode  Cnt     Score     Error  Units
[info] DeepBindBenchmark.delay   10000  thrpt   20  3786.509 ± 129.755  ops/s
```

2021-08-14 09:13 UTC, vasilmkd commented
Here are my results:

```
Baseline 2.13
Benchmark                (size)   Mode  Cnt     Score    Error  Units
DeepBindBenchmark.delay   10000  thrpt   20  3028.428 ± 84.643  ops/s

Baseline 3.0
Benchmark                (size)   Mode  Cnt     Score     Error  Units
DeepBindBenchmark.delay   10000  thrpt   20  2848.246 ± 204.663  ops/s

Java code 2.13
Benchmark                (size)   Mode  Cnt     Score    Error  Units
DeepBindBenchmark.delay   10000  thrpt   20  3116.695 ± 84.533  ops/s

Java code 3.0
Benchmark                (size)   Mode  Cnt     Score     Error  Units
DeepBindBenchmark.delay   10000  thrpt   20  3706.874 ± 365.418  ops/s

Cross-platform 2.13
Benchmark                (size)   Mode  Cnt     Score     Error  Units
DeepBindBenchmark.delay   10000  thrpt   20  3328.456 ± 338.778  ops/s

Cross-platform 3.0
Benchmark                (size)   Mode  Cnt     Score     Error  Units
DeepBindBenchmark.delay   10000  thrpt   20  3414.873 ± 111.307  ops/s
```

2021-08-14 09:47 UTC, vasilmkd requested changes

2021-08-14 09:47 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/Thunk.scala
> +  private[this] val impl =
Can you please restore the comment that you put on the Java code.

2021-08-14 17:27 UTC, vasilmkd approved these changes
Great work. I can't tell you how happy I am that we get to keep cached tracing for `apply/delay`.

2021-08-14 20:49 UTC, merged