Implement `Async.fromThenable`
typelevel/cats-effect pull request #2237
Opened 2021-08-16 02:17 UTC by armanbilge

Fixes #2236.

2021-08-16 13:22 UTC, vasilmkd submitted a review, later dismissed

2021-08-16 17:44 UTC, djspiewak requested changes

2021-08-16 17:44 UTC, djspiewak commented on core/js/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +    asyncForIO.fromThenable(iot)
Can we just make `fromPromise` take a `Thenable` instead? That would mirror the JavaScript convention of treating "everything that has a `then`" as being secretly a `Promise`. It's even fully source and binary compatible in `IO`, and fully binary compatible in `Async`.

2021-08-16 19:04 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +    asyncForIO.fromThenable(iot)
Sure, makes sense!

> It's even fully source and binary compatible in IO, and fully binary compatible in Async.

I feel I am never going to understand binary compatibility 🤔 I didn't think this would be binary compatible because when relaxing the queue signatures to the source/sink supertypes in fs2 in https://github.com/typelevel/fs2/pull/2466, it _wasn't_ binary compatible. Why is it different here?

2021-08-16 19:18 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +    asyncForIO.fromThenable(iot)
Ahh, because type erasure.

2021-08-16 19:33 UTC, djspiewak commented on core/js/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +    asyncForIO.fromThenable(iot)
The binary type is erased to `IO` in the former case, and erased to `Object` in the latter case, so anything goes. :-P

2021-08-17 21:35 UTC, djspiewak approved these changes

2021-08-17 21:35 UTC, merged