Check `WorkerThread` ownership before scheduling
typelevel/cats-effect pull request #2254
Opened 2021-08-22 17:16 UTC by vasilmkd

This covers the interleaving between two instances of `WorkStealingThreadPool`. I did not have a chance to test the performance impact thoroughly, but in the quick benchmark run I did, the new code was faster, which, I'm not sure whether to trust. I will repeat the run when I have the time.

`series/3.x`:
```
Benchmark                          (size)   Mode  Cnt   Score   Error    Units
WorkStealingBenchmark.scheduling  1000000  thrpt   10  13.270 ± 1.109  ops/min
```

`This PR`:
```
Benchmark                          (size)   Mode  Cnt   Score   Error    Units
WorkStealingBenchmark.scheduling  1000000  thrpt   10  13.981 ± 1.537  ops/min
```

2021-08-22 20:13 UTC, vasilmkd commented
Here's another run:

`series/3.x`:
```
Benchmark                          (size)   Mode  Cnt   Score   Error    Units
WorkStealingBenchmark.scheduling  1000000  thrpt   20  15.228 ± 0.285  ops/min
```

`This PR`:
```
Benchmark                          (size)   Mode  Cnt   Score   Error    Units
WorkStealingBenchmark.scheduling  1000000  thrpt   20  14.966 ± 0.491  ops/min
```

2021-08-22 21:36 UTC, djspiewak requested changes

2021-08-22 21:36 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +        ()
I've seen some really weird things with the bytecode emitted by guarded cases. Can we formulate this to be more explicit?

2021-08-22 21:36 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +        ()
Also here

2021-08-22 21:47 UTC, vasilmkd commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +        ()
Yeah sure. I agree completely.

2021-08-22 22:34 UTC, vasilmkd commented
A new run of the scheduling benchmark:
```
Benchmark                          (size)   Mode  Cnt   Score   Error    Units
WorkStealingBenchmark.scheduling  1000000  thrpt   20  14.884 ± 0.635  ops/min
```

2021-08-22 22:41 UTC, djspiewak requested changes

2021-08-22 22:41 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +      thread.asInstanceOf[HelperThread].isOwnedBy(pool)) {
This may be slightly faster:

```scala
if (thread.isInstanceOf[WorkerThread]) {
  val wt = thread.asInstanceOf[WorkerThread]
  if (wt.isOwnedBy(pool)) {
    wt.reschedule(fiber)
  } else {
    val random = ThreadLocalRandom.current()
    overflowQueue.offer(fiber, random)
    notifyParked(random)
    ()
  }
} else if (thread.isInstanceOf[HelperThread]) {
  val ht = thread.asInstanceOf[HelperThread]
  if (ht.isOwnedBy(pool)) {
    ht.schedule(fiber)
  } else {
    val random = ThreadLocalRandom.current()
    overflowQueue.offer(fiber, random)
    notifyParked(random)
    ()
  }
} else {
  val random = ThreadLocalRandom.current()
  overflowQueue.offer(fiber, random)
  notifyParked(random)
  ()
}
```

2021-08-22 23:21 UTC, vasilmkd commented
Another run, but thermal throttling might have kicked in. The second fork was down in terms of the score.

```
Benchmark                          (size)   Mode  Cnt   Score   Error    Units
WorkStealingBenchmark.scheduling  1000000  thrpt   20  14.218 ± 0.894  ops/min
```

2021-08-23 00:40 UTC, djspiewak approved these changes

2021-08-23 00:40 UTC, merged