Added `TestControl`, with first-class support for time mocking
typelevel/cats-effect pull request #2276
Opened 2021-08-30 05:06 UTC by djspiewak

Fixes #2220
Fixes #1678

Time mocking is back and better than ever! Yay!!! Thoughts very much welcome. Folks who have expressed an interest in this include @SystemFw, @ChristopherDavenport, @benhutchison, and many others. Now is the time to give feedback! I tried to be comprehensive in the `TestControl` scaladoc.

Note that this also includes a binary-compatible (but source- and semantically-incompatible) reworking of `TestContext`. The previous API conflated too many concerns and was very error-prone. Time advancement and schedule ticking is now fully separated. Also, as a bonus, I found (and fixed!) a bug in `tickAll` which was causing all of our test suites to take *dramatically* longer than necessary, and now they run much faster both in CI and on my laptop. Drinks all around.

The primary concept here is that `TestControl` represents a relatively low level mechanism for controlling the runtime. Higher level mechanisms should be built on top of this and integrated within specific downstream test frameworks (such as munit). Note that, just as before, there's still no substitute for running your program on the *real* runtime, and there are several programs which will deadlock on `TestContext` but not on the real thing. However, for anything involving `sleep`, this kind of thing is basically indispensable.

In theory this should be a lot more convenient than what we had to do in CE2 (creating artificial `Clock` instances), since the runtime is automatically threaded through at all points, meaning that you can just use the normal `Clock` and `Temporal` instances and everything will just work out of the box. In fact, time mocking even works on the bare `IO` functions (e.g. `IO.sleep`, `IO.monotonic`, and `IO.realTime`).

As a final goodie, I added support for configuring the source of randomness used in `TestContext`, similar to how ScalaCheck supports optionally setting the seed as a base64-encoded value. I would imagine that downstream test framework support will print out the `seed` in any error messages, as well as provide an API for optionally configuring that seed and passing it to the `TestControl` they use internally to run your examples.

As I said, **now is the time for feedback!** This is a pretty meaningful API addition and I'd like to make sure we get it right.

2021-08-30 05:19 UTC, djspiewak commented
Published as `3.3-7-579f468` so that we can experiment in downstream libraries like https://github.com/typelevel/munit-cats-effect and https://github.com/typelevel/cats-effect-testing.

2021-08-30 07:36 UTC, vasilmkd requested changes, later dismissed
Very excited. Marking this as request changes but the changes are pretty minor.

Regarding the binary compatibility, because of the change in behavior, at least to me, the whole situation seems to give a false sense of security that this could be a drop in replacement.

Is there a way to make the `private[testkit]` implementations delegate to the new implementations in a way that is semantically correct in the new model? For example, do the `tick()` then `advanceAndTick()` trick or something.

If the answer is no, maybe it would indeed be better to not guarantee binary compatibility at all and just advise people to upgrade, recompile, fix source changes and change to the new semantics at the same time. Of course, you're much more experienced than me in this regard, so I won't fight any final decision.

2021-08-30 07:36 UTC, vasilmkd commented on kernel-testkit/shared/src/main/scala/cats/effect/kernel/testkit/TestContext.scala
> +      require(time > Duration.Zero)
I know this is very minor but this line doesn't need to be inside the critical region.

2021-08-30 07:36 UTC, vasilmkd commented on kernel-testkit/shared/src/main/scala/cats/effect/kernel/testkit/TestContext.scala
> +    synchronized {
We've had combinations of `ticked` and `real` before, and I can see this line called from inside a `real` `IO`. Should we mark this `scala.util.blocking`?

Ditto for the other `synchronized` blocks later in the code.

2021-08-30 07:36 UTC, vasilmkd commented on kernel-testkit/shared/src/main/scala/cats/effect/kernel/testkit/TestContext.scala
> +    }
🤯

2021-08-30 07:36 UTC, vasilmkd commented on kernel-testkit/shared/src/main/scala/cats/effect/kernel/testkit/TestContext.scala
> +  }
Are `tick(time: FiniteDuration)` and `tick$default$1` here for maintaining binary compatibility?

2021-08-30 07:36 UTC, vasilmkd commented on tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
> +        ticker.ctx.advanceAndTick(100.millis)
Why do we need a `tick()` followed by an `advanceAndTick` here? Trying to understand.

2021-08-30 07:36 UTC, vasilmkd commented on tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
> +        ticker.ctx.advanceAndTick(100.millis)
Is it the fact that it's right after an `unsafeToFuture()`?

2021-08-30 07:36 UTC, vasilmkd commented on testkit/shared/src/main/scala/cats/effect/testkit/TestControl.scala
> +   * do not need to run assertions between time windows.
Found the explanation for `tick()` followed by an `advanceAndTick()` thanks. Ignore the other question.

2021-08-30 07:36 UTC, vasilmkd commented on testkit/shared/src/main/scala/cats/effect/testkit/TestControl.scala
> +/*
Due to lack of comments on whole files, this is fantastic, I'm impressed by the integration. I cannot comment much on the API because I'm too used to it, but overall it makes sense to me.

2021-08-30 14:44 UTC, djspiewak commented on kernel-testkit/shared/src/main/scala/cats/effect/kernel/testkit/TestContext.scala
> +  }
Yep

2021-08-30 14:44 UTC, djspiewak commented on tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
> +        ticker.ctx.advanceAndTick(100.millis)
This is the case that is documented in the `tick` scaladoc. :-)

2021-08-30 14:46 UTC, djspiewak commented on kernel-testkit/shared/src/main/scala/cats/effect/kernel/testkit/TestContext.scala
> +    synchronized {
IMO if this ends up inside a real executor, we're in some serious trouble. :-P It doesn't hurt to add it though

2021-08-30 18:31 UTC, djspiewak commented
Noodled a bit on some Specs2 support built on top of this API: typelevel/cats-effect-testing#193

2021-08-31 06:25 UTC, alexandru commented on kernel-testkit/shared/src/main/scala/cats/effect/kernel/testkit/TestContext.scala
> +  def apply(seed: String): TestContext =
Inclusion of a seed is a very good idea 👍

2021-08-31 21:55 UTC, SystemFw commented on testkit/shared/src/main/scala/cats/effect/testkit/TestControl.scala
> + *
What happens with a program that waits on a deferred with a timeout? Should work right? as that won't end on the task queue until the deferred is complete

2021-08-31 21:55 UTC, SystemFw commented on testkit/shared/src/main/scala/cats/effect/testkit/TestControl.scala
> + * runtime (pro tip: do ''not'' use `unsafeRunSync` with this runtime, since
we need to make sure that the testing integrations do the right thing here

2021-08-31 21:55 UTC, SystemFw commented on testkit/shared/src/main/scala/cats/effect/testkit/TestControl.scala
> + * WARNING: ''Never'' use this runtime on programs which use the [[IO#evalOn]]
I think it's worth adding a sentence about behaviour of `blocking`

2021-08-31 21:55 UTC, SystemFw commented on testkit/shared/src/main/scala/cats/effect/testkit/TestControl.scala
> +   * has a chance to schedule itself, or simply use [[tickAll]] if you
Mm this is tricky. I wonder if this doesn't point out to a best practice of writing the whole test without asserting, i.e. "recording" assertions in the main fiber with `sleep`  while the test program runs in another fiber, and finally using `tickAll`, as opposed to using `advanceAndTick` and asserting

2021-08-31 21:55 UTC, SystemFw commented on kernel-testkit/shared/src/main/scala/cats/effect/kernel/testkit/TestContext.scala
> +final class TestContext private (_seed: Long) extends ExecutionContext { self =>
is this intended for end users now, or only `TestControl`?

2021-08-31 21:55 UTC, SystemFw commented on testkit/shared/src/main/scala/cats/effect/testkit/TestControl.scala
> +   * has a chance to schedule itself, or simply use [[tickAll]] if you
Or more simply that you should always `tick` first

2021-08-31 22:49 UTC, djspiewak commented on testkit/shared/src/main/scala/cats/effect/testkit/TestControl.scala
> + *
Correct!

2021-08-31 22:50 UTC, djspiewak commented on testkit/shared/src/main/scala/cats/effect/testkit/TestControl.scala
> + * runtime (pro tip: do ''not'' use `unsafeRunSync` with this runtime, since
Yep. Special and explicit integrations are needed in munit-cats-effect cats-effect-testing, and Weaver.

2021-08-31 22:50 UTC, djspiewak commented on testkit/shared/src/main/scala/cats/effect/testkit/TestControl.scala
> + * WARNING: ''Never'' use this runtime on programs which use the [[IO#evalOn]]
Good call. To more directly answer, it behaves like JavaScript: the blocking pool and the compute pool are both TestContext.

2021-08-31 22:51 UTC, djspiewak commented on testkit/shared/src/main/scala/cats/effect/testkit/TestControl.scala
> +   * has a chance to schedule itself, or simply use [[tickAll]] if you
Either one is definitely fine. Honestly I think the answer probably depends on what you're testing. For some things it may be difficult to get "in the middle" of some time-delayed flow to inject assertions.

2021-08-31 22:52 UTC, djspiewak commented on kernel-testkit/shared/src/main/scala/cats/effect/kernel/testkit/TestContext.scala
> +final class TestContext private (_seed: Long) extends ExecutionContext { self =>
Really both. It's still exposed to downstream users who need it. For example, it's very useful for anyone who wants to evaluate a data type against the CE laws. The main end user cases though are wrapped up in TestControl.

2021-09-01 16:55 UTC, SystemFw commented on kernel-testkit/shared/src/main/scala/cats/effect/kernel/testkit/TestContext.scala
> +final class TestContext private (_seed: Long) extends ExecutionContext { self =>
I think some more docs are needed then, I fear a lot of users will stumble upon it but only few will need it

2021-09-01 17:36 UTC, djspiewak commented on kernel-testkit/shared/src/main/scala/cats/effect/kernel/testkit/TestContext.scala
> +final class TestContext private (_seed: Long) extends ExecutionContext { self =>
Agreed

2021-09-08 01:27 UTC, djspiewak commented
Bumping this a bit, @SystemFw. Any follow-ups needed here? Should we look at the munit integration first?

2021-09-08 07:53 UTC, SystemFw commented
Yeah munit integration would be good, and tbh I think it'd be great to have a snapshot to try it out. I'm happy with it though, I hadn't realised that wasn't clear

2021-09-08 12:48 UTC, djspiewak commented
Actually published a snapshot quite a while ago. 😃 That's what the Specs2 integration is based on. I'll dig into munit.

2021-09-08 14:39 UTC, djspiewak commented
New snapshot published as `3.3-115-fab668b`

2021-09-08 16:27 UTC, djspiewak commented
Odd failure:

```
[info] IO monad should
2869
[error]   ! evaluate fibers correctly in presence of a parasitic execution context
2870
[error]    java.util.concurrent.TimeoutException: null (Runners.scala:109)
2871
[error] cats.effect.Runners.$anonfun$timeout$1(Runners.scala:109)
2872
[info] Total for specification ParasiticECSpec
```

2021-09-08 17:47 UTC, vasilmkd commented
Might not be an odd failure. The test uses `ticker` to evaluate equality between generated `IO` values.

2021-09-08 19:42 UTC, djspiewak commented
Yeah I'm definitely starting to suspect this is a legitimate failure. It's weird though. I can't reproduce it locally.

2021-09-09 12:27 UTC, SystemFw commented
> I'll dig into munit.

btw not necessarily how I want it to be, but for one of the use cases where you don't need to step, this is what I have in fs2:

Setup:
https://github.com/typelevel/fs2/blob/main/core/shared/src/test/scala/fs2/Fs2Suite.scala#L49-L93

Example usage:

https://github.com/typelevel/fs2/blob/2af0571de34cc11b6b2bafeef0baf487f0760ad8/core/shared/src/test/scala/fs2/TimedPullsSuite.scala#L56-L80

It doesn't work with scalacheck-effect atm

2021-09-09 13:52 UTC, djspiewak commented
@SystemFw What about this?

```scala
test("execute a simple test with mock time") {
  var first = false
  var second = false
  var third = false
  val wait = IO.sleep(1.hour)

  val program = for {
    _ <- IO { first = true }
    _ <- wait
    _ <- IO { second = true }
    _ <- wait
    _ <- IO { third = true }
  } yield 42

  program execute { (control, result) =>
    assert(result() == None)

    assert(!first)
    assert(!second)
    assert(!third)

    control.tick()

    assert(first)
    assert(!second)
    assert(!third)

    control.advanceAndTick(1.hour)

    assert(first)
    assert(second)
    assert(!third)

    control.advanceAndTick(1.hour)

    assert(first)
    assert(second)
    assert(third)

    assert(result() == Some(Right(42)))
  }
}
```

2021-09-09 15:22 UTC, SystemFw commented
Yeah,`executeFully` is what I have in the links I sent you. Your snippet for the stepthrough case looks great to me :)

2021-09-09 15:30 UTC, djspiewak commented
@SystemFw I'm writing some stuff to add to this PR which actually should cover MUnit nicely. I think the Specs2 specialness would remain, and maybe other test frameworks with a similar philosophy.

2021-09-09 15:57 UTC, djspiewak commented
@SystemFw Take a look and lmk what you think. You can get infix syntax by `import cats.effect.testkit.syntax.all._`. This import is unfortunate, but without doing some sort of orphan type trick, we don't have a good way of tucking it into the `IO` companion. I'm not *entirely* averse to doing the trick, so long as we're sure it won't cause any problems downstream.

2021-09-09 15:58 UTC, djspiewak commented on testkit/shared/src/main/scala/cats/effect/testkit/syntax/TestControlSyntax.scala
> +    TestControl.executeFully(wrapped, config = config, seed = seed)
Bikeshed this API!

2021-09-09 17:44 UTC, SystemFw commented
> This import is unfortunate, but without doing some sort of orphan type trick, we don't have a good way of tucking it into the IO companion

We could add the relevant implicits to one of the traits in munit-cats-effect, although strictly speaking the result of `execute` and `executeFully` is not `IO`

2021-09-09 18:31 UTC, danicheg commented
> > This import is unfortunate, but without doing some sort of orphan type trick, we don't have a good way of tucking it into the IO companion
> 
> We could add the relevant implicits to one of the traits in munit-cats-effect, although strictly speaking the result of `execute` and `executeFully` is not `IO`

Is it make sense to create another `Suite` that would use the `TestControl` semantic for `IO` execution via `ValueTransform`?

2021-09-09 19:01 UTC, djspiewak commented
> Is it make sense to create another Suite that would use the TestControl semantic for IO execution via ValueTransform?

I don't know what those words mean. Hopefully someone who knows munit will answer. :-P

If it's helpful, I've been thinking of `TestControl` as more around *assertions* than around *suites*. So for example, it might make sense to write a test which calls `execute` more than once on different `IO`s (though, stylistically, it's probably better to just have separate tests). This is very different than the rest of the Cats Effect support, which is more about making it possible to write tests *in* `IO`.

2021-09-09 19:03 UTC, djspiewak commented
Published a new snapshot as `3.3-138-c458766`

2021-09-10 05:43 UTC, Baccata commented on testkit/shared/src/main/scala/cats/effect/testkit/syntax/TestControlSyntax.scala
> +  def execute[B](config: IORuntimeConfig = IORuntimeConfig(), seed: Option[String] = None)(
<bikeshedding> 

I don't like this particular extension method. The lexical-scope, and unsafe nature of what happens in it, is communicated in a much clearer  fashion when using `TestControl.execute(io){ ... }`, whereas making it look like a method on "IO" makes it look like some sort of combinator. 

The `unsafe` methods on `IO` are okay, because the prefix makes it really clear that you're leaving the safe zone, it is obvious that they are not combinators. The lack of `unsafe` prefix separates this `execute` breaks this intuition. 

If I was benevolent dictator, I'd remove the `execute` extension method to push for a clearer, resource-like use of `TestControl` and would rename the `executeFully` to `unsafeExecuteFully`.

2021-09-10 05:54 UTC, Baccata commented on testkit/shared/src/main/scala/cats/effect/testkit/TestControl.scala
> +final class TestControl private (config: IORuntimeConfig, _seed: Option[String]) {
I'm thinking about how I'd support it in weaver ... not that it really "needs" supporting, because I'm pretty sure it would just work as is, but I'm thinking of how I'd like people to use it in `weaver`. 

In particular, the paradigm that Anton and I are going for is *USE IO GODDAMNIT !!!*, and enabling people to use a `IO => A` methods breaks that paradigm. 

So my question is : would it be it safe for weaver to encapsulate this (or recreate it) in a construct that'd expose advance/tick methods wrapped in`IO` ? I'm pretty sure it would, but ...

2021-09-10 10:53 UTC, SystemFw commented
The conversation is scattered all over the place 😄 
Anyway:

>  that would use the TestControl semantic for IO execution via ValueTransform?

This is what the fs2 snippet does. I would prefer it, and it's certainly doable for `executeFully`, but a bit less clear for `execute`

> my question is : would it be it safe for weaver to encapsulate this (or recreate it) in a construct that'd expose advance/tick methods wrapped inIO ? I'm pretty sure it would, but need to be sure.

second this, I think munit-cats-effect would do the same thing, and there's even a question about whether CE itself should do it this way

2021-09-10 13:41 UTC, djspiewak commented on testkit/shared/src/main/scala/cats/effect/testkit/syntax/TestControlSyntax.scala
> +  def execute[B](config: IORuntimeConfig = IORuntimeConfig(), seed: Option[String] = None)(
> If I was benevolent dictator, I'd remove the execute extension method to push for a clearer, resource-like use of TestControl and would rename the executeFully to unsafeExecuteFully.

Fortunately the BDFL owes you a favor or two…

2021-09-10 13:52 UTC, djspiewak commented
@Baccata and @SystemFw raise an interesting point, which broadly boils down to "`TestControl` is an effectful thing and should be in `IO`". I thought about this! Honestly I could go either way. My *concern* is it makes the model, which is already complex, even harder to grok. Actually I have two concerns, but first thing's first.

The problem here is the fact that there would end up being an "inner" `IO` and an "outer" `IO`, each running in different runtimes with very different semantics. Values destined for one runtime ending up in the other runtime would be pretty bad. As an example, I give a gold star to anyone who can correctly describe the semantics of the following (assuming an `IO`-wrapped version of the `TestControl` API as it stands):

```scala
for {
  latch <- IO.deferred[Unit]
  _ <- TestControl.execute(latch.get) { (control, results) =>
    control.tick *> latch.set(())
  }
} yield ()
```

Now imagine this is more complex, and instead of just testing the `latch.get` program, we're actually testing something much more complicated. Are we really going to be able to explain those semantics to users?

The counterargument here is that we may, *within* the bounds of the `execute` scope, want to call some application functions that manipulate internal state which affects the program. Those functions will *likely* be in `IO` (if the user is doing what we want them to do 🙂), and if `execute` is pretending to be pure there will be no way to sequence those methods other than doing `executeFully` or something, which sounds tricky.

My second concern about all of this, which I think I have a solution to, is that `tick()` may block, and so running it within an outer `IO` is a bit scary. I'm pretty sure I can fix that though…

As an aside, I'm open to a `Resource`-like API here. The main reason I *didn't* go that route is I really like the idea of marrying the `control` and the `results` together. At least to me, it feels much more intuitive to think of `TestControl` as a sort of handle into the runtime of a specific actively running `IO`. The API sort of encodes that metaphor. It is doable in a resourcy way as well.

Also if we really want to lean into that metaphor, maybe `TestControl` shouldn't expose `runtime` *at all* and just, *itself*, carry the `results`?

2021-09-10 13:58 UTC, djspiewak commented
Oh forgot to reply to one point…

> This is what the fs2 snippet does. I would prefer it, and it's certainly doable for executeFully, but a bit less clear for execute

The fact that it's not doable for `execute` is why I shied away from this concept. :-) I think it's important that we make very front-and-center the fact that this is a different sort of runtime, with different rules, operating in a different way, and there are benefits to that which you may or may not leverage. Making it automagically behave exactly like a normal `IO`, but only in one of the two major scenarios, runs a little bit counter to this.

Again, my main concern here is comprehensibility, particularly since this is to be used for testing. This is a *very* subtle bit of machinery, and I want people to understand it enough to use it with confidence and correctness in their tests.

2021-09-10 14:11 UTC, djspiewak commented
@SystemFw @Baccata @ChristopherDavenport Do you like this API better? https://gist.github.com/bfed5b1a99f05200314643f466830382 Ignore the scaladoc, it's all outdated now.

2021-09-10 14:40 UTC, danicheg commented
> @SystemFw @Baccata @ChristopherDavenport Do you like this API better? https://gist.github.com/bfed5b1a99f05200314643f466830382 Ignore the scaladoc, it's all outdated now.

`IO[Option[Either[Throwable, A]]]` 🤯

2021-09-10 14:43 UTC, vasilmkd commented
Can the resulting type `Option[Either[Throwable, A]]` be an `Outcome[Id, Throwable, A]`?

2021-09-10 14:58 UTC, djspiewak commented
> Can the resulting type Option[Either[Throwable, A]] be an Outcome[Id, Throwable, A]?

It can be, and that's obviously valid, but I thought that `Option[Either[` might be a little more ergonomic to work with. I'm up for changing it if you or others disagree.

2021-09-10 16:00 UTC, djspiewak commented
Okay I think I kinda like the pure API better. Pushed a more complete implementation. Lmk what you think. I didn't change `Option[Either[` to `Outcome` but I'm open to that as well.

2021-09-10 16:00 UTC, djspiewak commented
Okay I think I kinda like the pure API better. Pushed a more complete implementation. Lmk what you think. I didn't change `Option[Either[` to `Outcome` but I'm open to that as well.

2021-09-10 16:23 UTC, Baccata commented
I do like the pure API, and think I would have provided it in weaver myself, I appreciate not having to do it 😄 

I think an Outcome version would indeed communicate what the API does better. Not too bothered though.

2021-09-10 18:56 UTC, djspiewak commented
One quick realization: the `None` case here corresponds to both `Outcome.Canceled` and "did not complete", which is not something `Outcome` represents. I actually think that the `Outcome`-based API would be *less* explicit, not more, particularly since I think cancelation is actually going to show up as a `Left(_: CancellationException)`.

2021-09-10 19:02 UTC, vasilmkd commented
Is `None` mapping to both `Canceled` and "did not complete" also the case for the matchers that we currently have for `ticked`?

2021-09-10 19:03 UTC, djspiewak commented
> Is None mapping to both Canceled and "did not complete" also the case for the matchers that we currently have for ticked?

It was. I think @wemrysi split them apart, which is why we now have four matchers in `ticked`. The representation here is just a little different and more in line with how end-users usually see the same effects coming out of the `unsafeRun` family.

2021-09-10 19:07 UTC, vasilmkd commented
Ok, this does tell me that shoehorning this API into `Outcome` is not the way to go. However, I'm not exactly convinced that canceled and not completed should map to the same return value. On the other hand, I also don't have a good alternative solution at the moment, other than a bespoke 4 case `TestControlOutcome` enum or something.

2021-09-10 19:07 UTC, djspiewak commented
> I'm not exactly convinced that canceled and not completed should map to the same return value

Thinking about it (and not, you know, trying it), I'm pretty sure they don't. In fact, I think that cancelation maps to `Some(Left(_: CancellationException))`, which mirrors what users would see if they ran `unsafeRunSync()`.

2021-09-10 19:08 UTC, djspiewak commented
New snapshot (including the pure API) published as `3.3-141-b15d57b`

2021-09-10 19:10 UTC, vasilmkd commented
> Thinking about it (and not, you know, trying it), I'm pretty sure they don't. In fact, I think that cancelation maps to Some(Left(_: CancellationException)), which mirrors what users would see if they ran unsafeRunSync().

And this is exactly the situation that you described as suboptimal here:
> One quick realization: the None case here corresponds to both Outcome.Canceled and "did not complete", which is not something Outcome represents. I actually think that the Outcome-based API would be less explicit, not more, particularly since I think cancelation is actually going to show up as a Left(_: CancellationException).

I'm playing devil's advocate here, I do not have a preferred API, I want to help you arrive at one.

2021-09-10 19:28 UTC, djspiewak commented
Yeah I think I was just wrong in the first half of that comment. 😛 I'll try it though!

2021-09-10 19:43 UTC, djspiewak commented
```
scala> TestControl.executeFully(IO.canceled)
val res0: cats.effect.IO[Option[Either[Throwable,Unit]]] = IO(...)

scala> res0.unsafeRunSync()
val res1: Option[Either[Throwable,Unit]] = Some(Left(java.util.concurrent.CancellationException: The fiber was canceled))
```

I think we're good!

2021-09-10 21:51 UTC, vasilmkd reviewed
I am amazed by this PR and the scaladoc is very informative. Thank you for your effort. 🙏🏻 

One question still remains, do people think we need to build a higher level ADT for making the different outcomes more explicit. I'm personally worried about `Left(CancelationException)` not being great from an ergonomics point of view.

2021-09-10 21:51 UTC, vasilmkd commented on tests/jvm/src/test/scala/cats/effect/ParasiticECSpec.scala
> +        }
I'm pretty sure this change can be reverted.

2021-09-11 06:08 UTC, Baccata commented
> One question still remains, do people think we need to build a higher level ADT for making the different outcomes more explicit. I'm personally worried about `Left(CancelationException)` not being great from an ergonomics point of view.

I agree. Even `Option[Outcome[Id, Throwable, A]]` would be more consistent with the rest of CE

2021-09-11 06:42 UTC, vasilmkd commented
I don't hate that. I'm not sure if Daniel considers it a solution if we only do a last-mile wrapping of the `Option[Either[Throwable, A]]` into a `Option[Outcome[Id, Throwable, A]]`.

2021-09-11 08:45 UTC, Baccata commented
As long as cancellation is not surfaced as a cancellation exception, I'm happy 😉

2021-09-11 09:02 UTC, vasilmkd commented
Most definitely, I'm really not comfortable with that.

2021-09-11 15:04 UTC, djspiewak commented
Okay okay. 😛 I'll try the Option if Outcome approach…

2021-09-12 17:54 UTC, SystemFw commented
Well, remember that the UX here is writing assertions, and I think Outcome might actually be the worst UX, given that writing assertions that involve pattern matching is generally a bit annoying. In some ways the most immediate return type is actually `IO[Option[A]]` (and `CancelationException` plus other exceptions getting thrown), which integrates with every test framework and favours the most common case


P.S. I'm integrating this into `upperbound` and the experience is otherwise great, especially the fact that you can just call `TestControl.executeFully` with no other changes to munit-cats-effect nor a specific test setup beyond basic IO suites

2021-09-12 23:50 UTC, djspiewak commented
See [Discord](https://discord.com/channels/632277896739946517/839263556754472990/886672279327617134) for a long diatribe on why we replaced `executeFully` with `executeEmbed`. :-)

2021-09-13 01:05 UTC, djspiewak commented
Published as `3.3-161-09d830c`

2021-09-15 13:02 UTC, SystemFw commented
Ok, so I've tried `executeEmbed` 

TL;DR: it's much better, but we should remove the Option from there as well.

Note that I'm only talking `executeEmbed` here, not stepping through. Here are my arguments (some of them might be repeated from Discord):

- Most tests will only care about the actual results, which makes dealing with an Option pointless boilerplate.
- If you are calling `executeEmbed`, you are running the IO to completion, and nontermination is an exceptional outcome, and should therefore be represented as an exception. Note that this isn't the case with `results` inside `execute`, since you are legitimately sampling there.
- It's ok for the resulting Exception to be defined inside TestControl, e.g. as `TestControl.NonTerminationException`. This may appear bespoke, but being able to materialise nontermination (currently as an `Option`) _is_ bespoke to TestControl, so a bespoke exception actually seems very appropriate.
- **`Option` is bad UX on failed tests** . This might actually be the strongest argument. With `Option`, a non terminating program will fail as either `The result was None` or `NoSuchElementException`. Compare to a proper exception: `TestControl.NonTerminationException: the program you have run through TestControl never completed, which might indicate deadlock etc, see these docs etc.`

Hence, having `executeEmbed: F[A]` makes successful tests easier to write, and failed tests easier to understand, and should be preferred to the current API.

2021-09-15 13:25 UTC, djspiewak commented
> If you are calling executeEmbed, you are running the IO to completion, and nontermination is an exceptional outcome, and should therefore be represented as an exception. Note that this isn't the case with results inside execute, since you are legitimately sampling there.

I was thinking about it over the past couple days and came round to a similar opinion. I think this is probably the most compelling argument. Also I agree with the counterpoint on "bespokeness".

> Option is bad UX on failed tests . This might actually be the strongest argument. With Option, a non terminating program will fail as either The result was None or NoSuchElementException. Compare to a proper exception: TestControl.NonTerminationException: the program you have run through TestControl never completed, which might indicate deadlock etc, see these docs etc.

I think it gets even worse than that if someone writes their assertions *within* the `IO`, but then that `IO` deadlocks before a failed assertion gets hit, and then they discard the `Option` (e.g. by just returning the results of `executeEmbed` from `test`). In that scenario, there's no failure, but the test is definitely failing. Arguably that's a test where someone failed to account for every possible failure scenario (in this case, nontermination), but the UX should guide them towards checking for such.

So overall I think I'm in alignment. I'll make the change.

2021-09-16 16:13 UTC, djspiewak commented
Changes released in `3.3-162-2022ef9`

2021-09-19 20:49 UTC, djspiewak commented
Final thoughts @SystemFw or others?

2021-09-19 21:59 UTC, SystemFw commented
Really excited this is pretty much done :)
I'm happy with the api, are we set on names? I was thinking about `run` and `stepThrough`, but I wouldn't be mad if we kept the current names at all

2021-09-20 03:39 UTC, djspiewak commented
I actually really like the names. Honestly, `run` strikes me as a bit too innocuous. 🙂 Given the weirdness it's performing, I want people to be aware that they're flirting with dragons. Also the documentation pretty consistently refers to "execute" as the verb when running an IO (despite the fact that the production prefix is `unsafeRun`), so it fits pretty well.

The "Embed" suffix also works really well when comparing with the `Fiber` api, which is not an incorrect comparison. It also nudges people a bit to consider the stepping API first, which is good IMO even if it isn't the most commonly optimal function, simply because it invites people to understand a bit better what's going on under the surface.

I'm bikeshedding. 😃 Names matter but probably not as much as I'm implicitly asserting here. I just rather like the current ones.

2021-09-20 16:38 UTC, SystemFw commented
>  I just rather like the current ones.

That's ok, let's go ahead with the current ones :)

2021-09-20 16:38 UTC, SystemFw approved these changes

2021-09-20 20:38 UTC, merged

2021-10-22 12:08 UTC, bastewart commented
Useless comment: just wanted to say I really like this change (i've "borrowed" it temporarily, pending a release of 3.3)! It's a huge improvement over the hand-rolling required in the past to use `TestContext`. Very unrelated as well but I think it's a big validation of the design of CE3 that `TestControl` just exposes a function `IO ~> IO` and end-users don't have to do anything like overwriting the `ContextShift` and `Timer`.

2021-11-28 08:15 UTC, yanns commented
This is a really great addition!!! 🥇