Prevent eager creation of TimeoutException in IO.timeout
typelevel/cats-effect pull request #2294
Opened 2021-09-02 02:47 UTC by ixthe0

This PR addresses #2244 by delaying the construction of a `TimeoutException` until it is really needed (or never)

2021-09-02 07:04 UTC, vasilmkd requested changes

2021-09-02 07:04 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    timeoutTo(duration, IO.pure(duration).flatMap(d => IO.raiseError(new TimeoutException(d.toString))))
I think we can save the `IO.pure` allocation here by doing the following:
```scala
IO.defer(IO.raiseError(new TimeoutException(duration.toString)))
```

2021-09-03 02:42 UTC, ixthe0 commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    timeoutTo(duration, IO.pure(duration).flatMap(d => IO.raiseError(new TimeoutException(d.toString))))
@vasilmkd thank you!

Is there a reason to prefer `IO.defer` over `IO.pure`? They seem to introduce a similar level of memory overhead (allocation of `Delay` vs allocation of `Pure`), but `Delay` also includes `TracingEvent`

2021-09-03 06:19 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    timeoutTo(duration, IO.pure(duration).flatMap(d => IO.raiseError(new TimeoutException(d.toString))))
Meh, I forgot about the trace. We should still expect the trace to be cached. Otherwise not a huge reason to prefer `defer` other than the fact that it conveys the intent better than `pure` and `flatMap`.

2021-09-03 14:02 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    timeoutTo(duration, IO.pure(duration).flatMap(d => IO.raiseError(new TimeoutException(d.toString))))
`IO.defer` is a more declaratively correct thing to do. :-)

2021-09-03 14:03 UTC, djspiewak requested changes
This looks great! Can you also override `timeout` in the `Async` instance below, delegating to this implementation? That should ensure the semantics are consistent when people use `IO` via the typeclasses.

2021-09-03 14:32 UTC, vasilmkd commented
While we're at it, should we attempt to change `GenTemporal#timeout`. That one would need the `IO.unit.flatMap` trick because there's no `defer`.

2021-09-03 14:38 UTC, djspiewak commented
It would definitely be ideal yes. Fixing it in IO doesn't fix it for derived transformers.

2021-09-03 19:37 UTC, ixthe0 commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    timeoutTo(duration, IO.pure(duration).flatMap(d => IO.raiseError(new TimeoutException(d.toString))))
@vasilmkd @djspiewak makes sense, guys, thank you!

2021-09-05 02:25 UTC, ixthe0 commented
@vasilmkd correct me if I'm wrong, but the implementation you are referring to would look like so:
```
def timeout[A](fa: F[A], duration: FiniteDuration)(implicit ev: TimeoutException <:< E): F[A] = {
    timeoutTo(fa, duration, unit.flatMap(_ => raiseError[A](ev(new TimeoutException(duration.toString))))
}
```

@djspiewak I am not sure that I caught your idea correctly, but here's how I got it:
```
def timeout[A](fa: F[A], duration: FiniteDuration)(implicit ev: TimeoutException <:< E): F[A] = {
    flatMap(race(fa, sleep(duration))) {
        case Left(a)   => pure(a)
        case Right(_) => raiseError[A](ev(new TimeoutException(duration.toString)))
    }
}
```

I apologize in advance for rather beginner questions, I still need to get a lot of development context of CE3

2021-09-05 02:52 UTC, djspiewak commented
Looks right to me!

2021-09-07 10:48 UTC, vasilmkd commented
@ixthe0 I apologize for not giving this PR my full attention, I was really busy with more pressing stuff these days. Running the CI now and will review the code in a bit.

2021-09-07 14:00 UTC, vasilmkd approved these changes
Thank you @ixthe0! Great work.

2021-09-07 16:16 UTC, ixthe0 commented
@vasilmkd @djspiewak couldn't have done it without your help guys

2021-09-07 16:20 UTC, djspiewak approved these changes

2021-09-07 16:20 UTC, merged