Split `interruptible`
typelevel/cats-effect pull request #2343
Opened 2021-09-10 21:03 UTC by alexandrustana

This PR tries to fix #2268.
Running `mimaReportBinaryIssues` doesn't seem to report anything, so I hope the changes are binary compatible 😄 

TODO:
- [ ] add scalafix migration

2021-09-10 21:06 UTC, djspiewak requested changes
This looks really good apart from my one note! And I would generally trust mima: the approached you used is indeed binary compatible.

2021-09-10 21:06 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    override def interruptible[A](thunk: => A): IO[A] = IO.interruptible(false)(thunk)
I think we also need to change the definition of `interruptible` on the `IO` companion itself.

2021-09-10 21:07 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Sync.scala
>      suspend(if (many) InterruptibleMany else InterruptibleOnce)(thunk)
Oh, one more thing: I would delegate this implementation to the new public ones, rather than vice versa, since this is the shim.

2021-09-10 21:53 UTC, vasilmkd commented
Thanks for taking this on.

2021-09-10 22:06 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    override def interruptible[A](thunk: => A): IO[A] = IO.interruptible(false)(thunk)
Oh, while you do that, you should also fix the `thunk`s like in [#2226](https://github.com/typelevel/cats-effect/pull/2226/files#diff-2dec4bb5f2b890f966e62cfdfcc6d32746235e45b4a14113f56e38b49923132a), looks like I missed them.

2021-09-13 13:45 UTC, djspiewak submitted a review, later dismissed

2021-09-13 13:45 UTC, djspiewak commented on core/js/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +  def interruptible[A](thunk: => A): IO[A] = interruptible(false)(thunk)
Also needs to be accompanied by marking the original `interruptible` as `private[effect]`

2021-09-13 13:45 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/IOCompanionPlatform.scala
> -    val fn = () => thunk
The original `interruptible` needs to be marked as `private[effect]

2021-09-13 15:15 UTC, alexandrustana commented on core/js/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +  def interruptible[A](thunk: => A): IO[A] = interruptible(false)(thunk)
Is it necessary though? The class already has the `private[effect]` modifier.

2021-09-13 15:22 UTC, djspiewak commented on core/js/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +  def interruptible[A](thunk: => A): IO[A] = interruptible(false)(thunk)
It is! This class is inherited by a subclass which is *not* `private[effect]`.

2021-09-13 15:22 UTC, djspiewak commented
> for the output test folder a new version which is not yet released and will contain these changes)

Can we solve this by publishing a snapshot?

2021-09-13 16:58 UTC, alexandrustana commented on core/js/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +  def interruptible[A](thunk: => A): IO[A] = interruptible(false)(thunk)
I've added the modifier. But the only way to still be _binary compatible_ was to keep the methods as is in the `IOCompanionPlatforms`, override the method in `IO.scala` and add the modifier there.

2021-09-13 16:59 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    private[effect] override def interruptible[A](many: Boolean)(thunk: => A): IO[A] =
Wait you can do that?

2021-09-13 17:03 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    private[effect] override def interruptible[A](many: Boolean)(thunk: => A): IO[A] =
It technically doesn't change the visibility in the bytecode, so yes.

2021-09-13 17:08 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    private[effect] override def interruptible[A](many: Boolean)(thunk: => A): IO[A] =
Are we sure it does what we want downstream?

2021-09-13 17:15 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    private[effect] override def interruptible[A](many: Boolean)(thunk: => A): IO[A] =
Yeah, let's not take that risk.

2021-09-13 17:32 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    private[effect] override def interruptible[A](many: Boolean)(thunk: => A): IO[A] =
```
scala> import cats.effect.IO
import cats.effect.IO

scala> IO.interruptible(false) { println("hi") }
val res0: cats.effect.IO[Unit] = IO(...)
```

Looks like it doesn't mask it.

2021-09-13 18:25 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    private[effect] override def interruptible[A](many: Boolean)(thunk: => A): IO[A] =
Ok, thanks for confirming. Good to know.

2021-09-13 18:31 UTC, djspiewak commented
For posterity, the problem here is the following:

```
[error] cats-effect: Failed binary compatibility check against org.typelevel:cats-effect_2.13:3.1.0! Found 1 potential problems (filtered 7)
[error]  * static method interruptible(Boolean,scala.Function0)cats.effect.IO in class cats.effect.IO does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("cats.effect.IO.interruptible")
```

Looks like the `private[effect]` overload isn't getting peered into a static forwarder. I'm not totally certain how to trick the compiler into doing that…

2021-09-19 20:48 UTC, djspiewak commented
IMO, it's worth breaking binary compatibility with Java interop on this one function in order to get the better API for everyone. Anyone have any objections? Paging @rossabaker and @johnynek for opposing opinions.

2021-09-21 00:22 UTC, johnynek commented
just to chime in: 

My feeling is that runtime errors really suck, and if you want to be a super core library, you will be implicated in many diamonds, so try to never break binary compatibility.

But this is your project, of course, so make your own calls.

2021-09-21 13:24 UTC, djspiewak commented
I do very much agree with this. The only reason I'm even pondering the breakage is the fact that it's confined to the Java interop exclusively. Scala code paths never hit this forwarder and remain binary compatible.

2021-09-21 14:41 UTC, armanbilge commented
FWIW http4s recently made a similar decision to eschew Java forwarders in https://github.com/http4s/http4s/pull/5071#issuecomment-898705809.

2021-09-21 16:08 UTC, alexandrustana commented
@djspiewak @vasilmkd, can someone publish a snapshot, please, so I can try and write the scalafix migration? (if it is still needed I mean 😄 )

2021-09-21 16:14 UTC, vasilmkd commented
I will right now.

2021-09-21 16:28 UTC, vasilmkd commented
```scala
"io.vasilev" %%% "cats-effect" % "3.3-208-b352672"
```
@alexandrustana

2021-09-24 12:29 UTC, vasilmkd reviewed
How did the `build.sbt` changes get pulled in? That PR is not merged yet.

2021-09-25 18:45 UTC, rossabaker commented
This one is tough: a marginally better API for what is probably 100% of users, or a landmine for an unanticipated use case.  We chose the Scala users in http4s, but it makes me queasy, and the risk is higher on this project.

A third option is bytecode postprocessing.  I haven't done it in the Scala Era, but I'm pretty sure it would be possible.

2021-09-26 17:27 UTC, vasilmkd commented
With a repeated word of caution and previous experience, maybe it is worth reconsidering the extent of this change.

2021-10-05 10:07 UTC, alexandrustana commented
Having these in mind, should I close this PR?

2021-10-05 10:31 UTC, vasilmkd commented
No, not yet, let's have a discussion with Daniel, whenever he's back.

We'll definitely add `interruptibleOnce` and `interruptibleMany` if this doesn't go through, and the scalafix rules will still be good (with minor changes).

2021-10-10 19:26 UTC, djspiewak commented
I'm back ish. :-) To @rossabaker's point… There's another option here, which is that we can keep the current `interruptible` overload public and mark it as `@deprecated`. That's what's visible currently in the PR, and thus there is no binary breakage at all. It's kind of ugly, but it's not really the end of the world, and it's probably less fraught than bytecode shenanigans in the build.

Either way, I think that we can shift the discussion a bit. We agree the changes here are good (I think), and they're binary-compatible as currently written. I'm in favor of merging this PR and having a follow-up if we want to get fancy with hiding the old `interruptible` overload.

2021-10-10 19:28 UTC, djspiewak approved these changes
Awesome work, @alexandrustana! Thanks for shepherding this through the process, and sorry for handing you such a thorny change.

2021-10-10 19:28 UTC, djspiewak commented on scalafix/build.sbt
> +      "io.vasilev" %% "cats-effect" % "3.3-208-b352672"
Let's remember to update this to the mainline 3.3.0 once released

2021-10-10 19:28 UTC, merged

2021-10-11 06:05 UTC, fthomas commented
FYI: https://github.com/scala-steward-org/scala-steward/pull/2270 adds the v3_3_0 Scalafix to Scala Steward.

2021-10-11 06:28 UTC, alexandrustana commented
@djspiewak, @vasilmkd thank you for all the help and support 🙂

2021-10-11 06:48 UTC, vasilmkd commented
Thank you @fthomas!

@alexandrustana Thank you for the outstanding work and your patience.