Add embedError convenience function
typelevel/cats-effect pull request #2359
Opened 2021-09-18 16:09 UTC by ChristopherDavenport

2021-09-18 21:12 UTC, vasilmkd requested changes, later dismissed

2021-09-18 21:12 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/Outcome.scala
> +    }
`Outcome` has a `fold` method for this pattern match.

2021-09-18 21:14 UTC, vasilmkd reviewed
I think it's worth bikeshedding on the name and adding an accompanying scaladoc.

2021-09-18 21:54 UTC, ChristopherDavenport commented on kernel/shared/src/main/scala/cats/effect/kernel/Outcome.scala
> +    }
I used embed which seems more direct. Can use fold if you'd prefer.

2021-09-18 22:03 UTC, vasilmkd commented on kernel/shared/src/main/scala/cats/effect/kernel/Outcome.scala
> +    }
Even better.

2021-09-18 22:04 UTC, vasilmkd commented
I think the scaladoc should mention the cancelation case, saying that it embeds cancelation as an error. Otherwise 👍🏻

2021-09-18 23:46 UTC, armanbilge commented on kernel/shared/src/main/scala/cats/effect/kernel/Outcome.scala
> +   * as an exception.
```suggestion
   * as an `CancellationException`.
```

2021-09-21 14:41 UTC, djspiewak requested changes

2021-09-21 14:41 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Outcome.scala
> +  def embedError[F[_], A](outcome: Outcome[F, Throwable, A])(
I think this should be a member of `Outcome` like the other `embed`s.

2022-03-14 03:33 UTC, djspiewak approved these changes

2022-03-14 04:49 UTC, merged