Make JS IORuntime externally configurable
typelevel/cats-effect pull request #2367
Opened 2021-09-21 16:48 UTC by armanbilge

Should put JS in lock-step with JVM. Relies on `process.env` instead of system properties.

2021-09-22 21:23 UTC, vasilmkd commented
Are we dropping the support for the react app magic environment variables? Or is that no longer an issue?

2021-09-22 21:23 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/process.scala
> +      .orElse(Try(js.Dynamic.global.process.env.selectDynamic(s"REACT_APP_$key")).toOption)
@vasilmkd moved here?

2021-09-22 21:24 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/process.scala
> +      .orElse(Try(js.Dynamic.global.process.env.selectDynamic(s"REACT_APP_$key")).toOption)
Much better indeed, sorry for missing it.

2021-09-22 21:29 UTC, vasilmkd requested changes, later dismissed
Some Scala stdlib nits. Otherwise looks great.

2021-09-22 21:29 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/process.scala
> +      .orElse(Try(js.Dynamic.global.process.env.selectDynamic(s"REACT_APP_$key")).toOption)
You can use `.orElse` and the other chained methods directly on `Try` instead of going through `Option`. Obviously convert to `Option` at the very end.

2021-09-22 22:12 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/process.scala
> +      .orElse(Try(js.Dynamic.global.process.env.selectDynamic(s"REACT_APP_$key")).toOption)
Hmm, seems `Try` doesn't support filtering and rearranging that was a bad idea. So only a modest improvement in the end :)

2021-09-23 11:24 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/process.scala
> +      .orElse(Try(js.Dynamic.global.process.env.selectDynamic(s"REACT_APP_$key")).toOption)
Lol, it doesn't support `filterNot`.

2021-09-23 11:32 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/process.scala
> +      .orElse(Try(js.Dynamic.global.process.env.selectDynamic(s"REACT_APP_$key")).toOption)
The whole block would have to look like this I guess:
```scala
def env(key: String): Option[String] =
  Try(js.Dynamic.global.process.env.selectDynamic(key))
    .orElse(Try(js.Dynamic.global.process.env.selectDynamic(s"REACT_APP_$key")))
    .collect { case v if !js.isUndefined(v) => v.asInstanceOf[String] }
    .toOption
```

2021-09-23 14:04 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/process.scala
> +      .orElse(Try(js.Dynamic.global.process.env.selectDynamic(s"REACT_APP_$key")).toOption)
Wow I suck at this 😆 that looks great. Maybe we can make that `case v: String if !js.isUndefined(v)`?

2021-09-23 14:08 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/process.scala
> +      .orElse(Try(js.Dynamic.global.process.env.selectDynamic(s"REACT_APP_$key")).toOption)
Even better.

2021-09-23 14:57 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/process.scala
> +      .orElse(Try(js.Dynamic.global.process.env.selectDynamic(s"REACT_APP_$key")).toOption)
Took one more trick 😆 Nice golfing, thanks!

2021-09-23 19:42 UTC, vasilmkd reviewed
I'll do another pass a bit later.

2021-10-10 20:24 UTC, djspiewak approved these changes
Needs documentation, but otherwise looks great!

2021-10-10 20:24 UTC, merged