Global GC fiber bag implementation
typelevel/cats-effect pull request #2408
Opened 2021-10-13 11:10 UTC by vasilmkd

The global fallback for #2368. This PR does not yet contain the worker-thread-local suspended bags, that will arrive in a follow up PR.

One detail to discuss here is the fact that we're tying this bag to an `IORuntime` instance, which doesn't necessarily make it global the way the tracing cache is for example. I really do not know how we should treat `IORuntime`, but I am going to say that there might be possibilities for further optimizing cache lookups for tracing if we somehow decide that there can only ever be one `IORuntime` per JVM. Probably should be a separate discussion, but still something to think about.

2021-10-14 15:09 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> + * weak references are still not available in Scala.js.
Would this work?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

2021-10-14 15:11 UTC, djspiewak commented on core/js/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> + * weak references are still not available in Scala.js.
NICE FIND

2021-10-14 15:18 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> + * weak references are still not available in Scala.js.
One challenge with this approach is the fact that the value (`IOFiber`) holds a strong reference to the key, so that kind of prevents collection of the key. We circumvent this by using a `WeakReference` for the value (because `WeakHashMap` holds a strong reference to the value for whatever reason). `WeakReference` is not available on Scala.js. Unless this map holds weak references to the values, we cannot really use it.

2021-10-14 15:19 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> + * weak references are still not available in Scala.js.
This is also a limitation it seems:
> Because the references are weak, WeakMap keys are not enumerable. There is no method to obtain a list of the keys. If there was, the list would depend on the state of garbage collection, introducing non-determinism. If you want to have a list of keys, you should use a Map.

2021-10-14 15:22 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> + * weak references are still not available in Scala.js.
https://www.scala-js.org/api/scalajs-library/1.7.1/scala/scalajs/js/WeakRef.html

2021-10-14 15:24 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> + * weak references are still not available in Scala.js.
As for the second limitation, I'd have to think about it. Can we keep a list of weak references to keys ourselves? It'll probably need to be cleaned up now and again.

2021-10-14 15:25 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> + * weak references are still not available in Scala.js.
You're the JS master, but is targeting just ECMA Script 2021 feasible?

2021-10-14 15:26 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> + * weak references are still not available in Scala.js.
Anyway, after this PR lands we can have a play with the JS side. My real objection here was, don't be so presumptuous in the JS comments 😝

2021-10-14 15:29 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> + * weak references are still not available in Scala.js.
> You're the JS master, but is targeting just ECMA Script 2021 feasible?

Yes, we can do a feature test and gracefully fallback. It is already fairly well supported, just not standardized until ES2021.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef#browser_compatibility

2021-10-14 15:33 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> + * weak references are still not available in Scala.js.
Sounds good, I mainly based my assumptions around this discussion https://github.com/scala-js/scala-js/issues/4477.

2021-10-17 17:06 UTC, djspiewak requested changes

2021-10-17 17:06 UTC, djspiewak commented on core/js/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> +  private[this] val bag: mutable.Map[AnyRef, IOFiber[_]] =
So the problem here is we're retaining a hard reference to these fibers, thus preventing GC. We really need weak references to do this without causing memory leaks, so I think it would be better for now to make the JS fiber bag a no-op, otherwise we regress correctness quite a lot.

2021-10-17 17:06 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> +  private[this] val size: Int = Runtime.getRuntime().availableProcessors() << 2
Why `<< 2`?

2021-10-17 17:06 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> +    val rnd = ThreadLocalRandom.current()
Doesn't this have to be implemented using a `ThreadLocal` behind the scenes? I would assume that's quite slow. We could probably improve it at *least* in the happy path when code is running on our worker threads by exposing the worker-local source of randomness internally.

2021-10-17 17:20 UTC, vasilmkd commented on core/jvm/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> +    val rnd = ThreadLocalRandom.current()
Our worker threads will each have their own uncontended bag.

2021-10-17 17:21 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> +  private[this] val bag: mutable.Map[AnyRef, IOFiber[_]] =
JS has an `unmonitor` method which actually removes mappings from this map when they resume.

2021-10-17 17:22 UTC, vasilmkd commented on core/jvm/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> +  private[this] val size: Int = Runtime.getRuntime().availableProcessors() << 2
I believe @RafalSumislawski measured different configurations for the ThreadSafeHashtable and came up with this.

2021-10-17 18:10 UTC, RafalSumislawski commented on core/jvm/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> +  private[this] val size: Int = Runtime.getRuntime().availableProcessors() << 2
Indeed https://github.com/typelevel/cats-effect/pull/1937#issuecomment-835304694

2021-10-17 19:48 UTC, vasilmkd commented on core/jvm/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> +    val rnd = ThreadLocalRandom.current()
`ThreadLocalRandom` is indeed implemented using a `ThreadLocal`, but it's better than having a contended `java.util.Random` instance. We use something similar when external thread enqueue fibers on our work stealing pool.

As far as this PR goes, this only contains the global fallback. I still haven't implemented the bag for the work stealing pool, where each worker thread will have its own uncontended `WeakHashMap`. I will add that in another PR, I didn't want to make this one too big.

2021-10-17 19:49 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> +    val rnd = ThreadLocalRandom.current()
Also, landing this one lets me work in parallel on a JS implementation while Vasil tackles the work stealing pool version 😁

2021-10-18 01:02 UTC, djspiewak commented on core/js/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> +  private[this] val bag: mutable.Map[AnyRef, IOFiber[_]] =
Ah but what if they don't resume! Right now, if you suspend a fiber and then let it go out of scope, it will just be GC'd. This change breaks that, but only on JS.

2021-10-18 01:04 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> +    val rnd = ThreadLocalRandom.current()
> Our worker threads will each have their own uncontended bag.

I was going to ask whether or not they really need it, but thinking more, it makes sense that it would be worth avoiding the synchronization penalty.

2021-10-18 07:09 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> +  private[this] val bag: mutable.Map[AnyRef, IOFiber[_]] =
Sorry, I realize now what you mean. Yeah, that's really what I wanted initially, but got confused with the availability of weak references on JS and ended up making a mistake. I will make the JS bag a no-op for now and @armanbilge will iterate on it.

2021-10-18 21:49 UTC, djspiewak approved these changes

2021-10-18 21:49 UTC, merged