Async cancelation should first re-enqueue the fiber
typelevel/cats-effect pull request #2411
Opened 2021-10-14 22:02 UTC by vasilmkd

This matches the resumption mechanism in the fact that it simply enqueues the canceled fiber for cancelation, instead of executing the canceled fiber's run loop in place, which can already be running as part of another fiber's run loop (e.g. completing an async callback on a worker thread as part of an `IO.delay`).

It also seems to be slightly faster. I chose the `AsyncBenchmark.race` benchmark because it exercises cancelation.

`series/3.x`:
```
Benchmark            (size)   Mode  Cnt      Score      Error  Units
AsyncBenchmark.race     100  thrpt   20  14542.116 ± 1145.839  ops/s
```

`This PR`:
```
Benchmark            (size)   Mode  Cnt      Score     Error  Units
AsyncBenchmark.race     100  thrpt   20  18157.855 ± 430.937  ops/s
```

2021-10-17 16:46 UTC, djspiewak commented
So I'm struggling to see what this does *aside* from effectively injecting an `IO.cede` at the head of any list of finalizers (including if the finalizers are empty). It's not entirely clear to me how that interacts with `race`, but my guess is that the added dose of fairness probably causes the benchmark to wind down just a little faster. Ultimately, I think this is a fairness question more than a throughput one, and I'm trying to reason through whether it matters in practice.

2021-10-17 17:14 UTC, vasilmkd commented
It's a fairness issue, sure, but there's also a stack safety issue (which admittedly may not be too realistic in practice). Let's say there's an async callback for a given fiber A that needs to be completed in an `IO.delay` on another fiber B. And let's say that as soon as this callback is completed, cancelation from a third fiber is propagated. Then, fiber B would run `asyncCancel(null)` for fiber A as part of its run loop (run loop in a run loop situation). It's the same reason we don't resume fibers immediately on the happy path (or exception for that matter), but we enqueue them again (at least IMO).

2021-10-17 17:16 UTC, vasilmkd commented
It also doesn't inject `IO.cede` for all finalizers, only ones that would be run as part of `IO.async` callback completion when cancelation is propagated by a third party which couldn't win the race.

2021-10-17 19:01 UTC, vasilmkd commented
Honestly, same for calling `IOFiber#cancel`, more specifically `asyncCancel(fin)` inside a sequenced `IO.async_`, this will start the canceled fiber's run loop inside the current one. Can a huge chain of fibers be built that causes a stack overflow?

2021-10-17 19:12 UTC, djspiewak requested changes
Staring at this some more, I realized that we actually have a bigger fairness issue here. Imagine a very long chain of synchronous finalizers on a fiber, where each finalizer is itself less than the auto-cede threshold. We will hog the carrier thread the whole way through without ever once yielding.

Due to the way the whole machine works, there isn't a good way to pass the current autocede threshold through from one finalizer to the next, so the most direct solution might be to just reschedule the fiber on each iteration of the loop (rather than calling `runLoop` directly). WDYT?

Interestingly, this is probably exactly what's going on in the `race` benchmark, since this situation indirectly arises when you have a long chain of fibers, each of which cancels the next one in its finalizer.

**Edit**: 

> Can a huge chain of fibers be built that causes a stack overflow?

Jinx :-) Yes

2021-10-17 19:13 UTC, vasilmkd commented
So what's the game plan here then?

2021-10-17 19:15 UTC, djspiewak commented
I have an idea. I'll have a PR up in a minute.

2021-10-17 19:18 UTC, vasilmkd commented
Ah, you'll add a cede in `asyncCancel`?

2021-10-18 12:24 UTC, vasilmkd commented
@djspiewak I removed your commit because I want to keep this PR focused on the title. Your commit shows a slightly bigger problem, and that is the fact that we call `asyncCancel` from inside our run loop, which then starts a new instance of the run loop with a fresh stack and fresh iteration counts, while also adding a new stack frame. We need to rework `asyncCancel` to fix this. I will do that in a follow-up.

2021-10-18 12:27 UTC, vasilmkd commented
`runLoop` should only be called from methods ending with `R`, which are resumption methods called from `run()` whenever a fiber is picked up from a worker queue and executed, not from `K` methods which are continuations popped from the stack. The former creates 1 single run loop stack entry, the latter adds one each time `runLoop` is called. I will do a careful change in a follow-up, as I said.

2021-10-19 15:41 UTC, djspiewak approved these changes

2021-10-19 15:41 UTC, merged