Implement `SuspendedFiberBag` for JS
typelevel/cats-effect pull request #2433
Opened 2021-10-19 03:14 UTC by armanbilge

This was a fairly straightforward port of the JVM version. It feature tests for [`WeakMap`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap), [`WeakRef`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef), and [`FinalizationRegistry`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) and gracefully falls back to the no-op implementation.

2021-10-19 13:08 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/IterableWeakMap.scala
> +      js.typeOf(js.Dynamic.global.FinalizationRegistry) != "undefined"
You forgot to use `Undefined`? 😄

2021-10-19 13:08 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/IterableWeakMap.scala
> +  private[this] val finalizationGroup =
Can you please comment on what each of these fields are used for and what type of references they are holding to the keys and values. It's for my understanding. 😄

2021-10-19 13:10 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/IterableWeakMap.scala
> +      js.typeOf(js.Dynamic.global.FinalizationRegistry) != "undefined"
lol!

2021-10-19 13:13 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/IterableWeakMap.scala
> +  private[this] val finalizationGroup =
Yeah would be good for my understanding too 😆  I just ported from here.
https://github.com/tc39/proposal-weakrefs#iterable-weakmaps

2021-10-19 13:15 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/IterableWeakMap.scala
> +      js.typeOf(js.Dynamic.global.FinalizationRegistry) != "undefined"
```suggestion
  private[this] final val Undefined = "undefined"
  def isAvailable: Boolean =
    js.typeOf(js.Dynamic.global.WeakMap) != Undefined &&
      js.typeOf(js.Dynamic.global.WeakRef) != Undefined &&
      js.typeOf(js.Dynamic.global.FinalizationRegistry) != Undefined
```

2021-10-19 13:26 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/IterableWeakMap.scala
> +  private[this] val finalizationGroup =
IIUC the `WeakMap` here is the same as its Java equivalent, but its not iterable. So instead, we keep a set of weak references to the keys that we can use for iteration. They are weak so that the keys can still be GCed. The trouble is even though the key is GCed, the set will still contain the `WeakRef`. So lastly the `FinalizationRegistry` registers a finalizer that removes the corresponding `WeakRef` from the set when the key is GCed.

2021-10-19 13:29 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/IterableWeakMap.scala
> +  private[this] val finalizationGroup =
Cool. Can you please verify if the `WeakMap` holds strong references to the _values_ like `WeakHashMap` does on the JDK. There we use a weak hash map with weak ref values.

2021-10-19 13:31 UTC, vasilmkd commented
Is there some special feature that requires the `Entry` class to exist?

2021-10-19 13:32 UTC, armanbilge commented
You mean, instead of just using a tuple?

2021-10-19 14:00 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/IterableWeakMap.scala
> +  private[this] val finalizationGroup =
Hmm, good catch, `WeakMap` might be different here.

> As such native WeakMaps do not prevent garbage collection, which eventually removes references to the key object. "Weak" references also avoid preventing garbage collection of values in the map.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap#why_weakmap

2021-10-19 14:09 UTC, vasilmkd commented
Instead of just using a value, not a pair of the key and the value.

2021-10-19 14:10 UTC, armanbilge commented
It's needed for the `delete` functionality, which technically we don't need here.

2021-10-19 14:22 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/IterableWeakMap.scala
> +  private[this] val finalizationGroup =
Ok, I've been staring at the spec and I see nothing there about the values. So I think the safe thing to do is assume they are strong references.

https://262.ecma-international.org/6.0/#sec-weakmap-objects

2021-10-19 14:48 UTC, vasilmkd commented
If it's really not needed, let's delete it because we don't need a general solution.

If we do end up needing it, note that we always have a reference to both the key and the value (the opaque object and the fiber instance respectively) when calling the `unmonitor` method, so you can hack it together without allocating an `Entry` object instance.

2021-10-19 15:22 UTC, armanbilge commented
> If we do end up needing it, note that we always have a reference to both the key and the value (the opaque object and the fiber instance respectively) when calling the unmonitor method, so you can hack it together without allocating an Entry object instance.

I'm not sure that's true. We also need the `WeakRef` used to store the key in the set.

2021-10-19 15:30 UTC, vasilmkd commented
Wait a second, if we assume that the value is a strong reference, our fibers actually hold a strong reference to the key object, thus preventing GC of the keys, regardless of how they are held. We need a weak ref for the value of type `V`.

2021-10-19 15:31 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> +}
@vasilmkd you mean like the `WeakRef` used here?

2021-10-19 15:43 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
> +}
Yeah, got confused. All good. I guess this is better to preserve "semantic syntax compatibility" with the JVM code. 😆

2021-10-19 15:43 UTC, vasilmkd commented
I'll do another pass tonight.

2021-10-19 22:54 UTC, armanbilge commented
So, point-of-interest here. With all this talk about staying on Scala 3.0.x, there's the similar question of whether we should try and stay on an old SJS version. The feeling I got is people think this is less of a big deal, but in theory cats and cats-effect could probably dial back to SJS 1.5.x without consequences. The reason its relevant here is because I'm making use of APIs introduced in 1.7.x :)

2021-10-29 20:53 UTC, vasilmkd requested changes
In the home stretch now, just some scaladoc for easier future maintenance.

2021-10-29 20:53 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/IterableWeakMap.scala
> +// https://github.com/tc39/proposal-weakrefs#iterable-weakmaps
Let's write a paragraph here, mentioning the original project, what it offers and what we have taken/translated here. There's precedent for giving original projects a more prominent header, let's try to be consistent.

2021-10-29 20:53 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/IterableWeakMap.scala
> +private[unsafe] class IterableWeakMap[K, V] {
For easier future maintenance, let's add a scaladoc to the class, explaining its purpose (weak maps in JS are not iterable by nature, so we're augmenting them here by relying on a finalization registry which is a construct (that the JVM lacks) for registering cleanup callback functions to be executed when the GC reclaims a registered object. It would be cool if you added scaladoc/comments in the implementation methods, about what happens when, when something is registered, deregistered, cleaned up, etc.

2021-10-29 20:53 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/SuspendedFiberBag.scala
>   */
I think this can go on the new `NoOp` implementation. We should also add a small scaladoc on the iterable weak map backed one.

2021-10-29 20:53 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/IterableWeakMap.scala
> +  def get(key: K): Option[V] = weakMap.get(key).toOption
Out of curiosity, is there a way to translate an `UndefOr[A]` into an `A` where the undefined case is actually a `null`?

2021-10-29 20:55 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/IterableWeakMap.scala
> +  def get(key: K): Option[V] = weakMap.get(key).toOption
Yes, I think so. `UndefOr` has basically the same interface as `Option`.

2021-10-29 20:58 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/IterableWeakMap.scala
> +  def get(key: K): Option[V] = weakMap.get(key).toOption
I'm guessing Scala.js isn't actually allocating objects for this construct, right?

2021-10-29 20:59 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/IterableWeakMap.scala
> +  def get(key: K): Option[V] = weakMap.get(key).toOption
No, `UndefOr` is a compile-time construct only.

2021-10-29 21:44 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/IterableWeakMap.scala
> +private[unsafe] class IterableWeakMap[K, V] {
@vasilmkd I thought it's kind of like `Cleaner`(https://docs.oracle.com/javase/9/docs/api/java/lang/ref/Cleaner.html)?

2021-10-29 21:46 UTC, armanbilge commented
@vasilmkd added lots of comments, let me know what you think.

2021-10-30 17:17 UTC, vasilmkd approved these changes

2021-11-01 22:23 UTC, vasilmkd approved these changes

2021-11-01 22:24 UTC, merged