Fix of 2.x series tutorial paragraph about error promotion of join call
typelevel/cats-effect pull request #2457
Opened 2021-10-24 15:52 UTC by lrodero

The tutorial contains a paragraph about `.start` and `.join` that is messy if not plainly wrong. _E.g._ see [this msg](https://discord.com/channels/632277896739946517/632278585700384799/900807315190599800) in CE discord channel.

This PR tries to fix this for the 2.x series tutorial, briefly explaining the limitations of the `.start` + `.join` approach to underscore how using `.parMapN` or `.parSequence` is generally a better choice. Resulting text can be read [here](https://lrodero.github.io/cats-effect/docs/2.x/guides/tutorial).

2021-10-24 16:03 UTC, vasilmkd submitted a review, later dismissed

2021-10-25 13:55 UTC, djspiewak submitted a review, later dismissed
Minor typos but otherwise looks good. Nice catch!

2021-10-25 13:55 UTC, djspiewak commented on docs/guides/tutorial.md
> +the reamining fibers is the responsability of the programmer.
```suggestion
the remaining fibers is the responsibility of the programmer.
```

2021-10-25 18:27 UTC, vasilmkd submitted a review, later dismissed

2021-11-04 19:57 UTC, armanbilge commented on docs/guides/tutorial.md
> +does not cancel the execution of the other fibers. Taking care of cancelling
```suggestion
does not cancel the execution of the other fibers. Taking care of canceling
```

2021-11-04 19:57 UTC, armanbilge commented on docs/guides/tutorial.md
> +fiber are promoted by `join`, meaning that if the fiber throws an error the
```suggestion
fiber are promoted by `join`, meaning that if the fiber raises an error the
```

2021-11-04 19:59 UTC, armanbilge commented on docs/guides/tutorial.md
> +call to `join` will forward it to the main flow. Problem is, we need to call to
```suggestion
call to `join` will raise the error to the caller. Problem is, we need to call
```

2021-11-04 19:59 UTC, armanbilge commented on docs/guides/tutorial.md
> +`join` first, so if for example the `consumerFiber` throws an exception while
```suggestion
`join` first, so if for example the `consumerFiber` raises an exception while
```

2021-11-04 20:04 UTC, armanbilge commented on docs/guides/tutorial.md
> +flow until it reaches `consumerFiber.join`. Also, a fiber throwing an error
```suggestion
`producerFiber` is still running then the exception will not interrupt `producerFiber`
until it reaches `consumerFiber.join`. Also, a fiber throwing an error
```

2021-11-04 20:07 UTC, armanbilge commented on docs/guides/tutorial.md
> +with fibers_.
```suggestion
In contrast `parMapN` not only promotes errors raised by fibers to the caller, it also take care of canceling the other fibers. This way `parMapN`
leads to simpler and more concise code. _Thus, unless you have some specific and
unusual requirements you should prefer to use higher level commands such as
`parMapN` or `parSequence` to work with fibers_.
```

2021-11-04 20:07 UTC, armanbilge requested changes
Most of my proposed changes here are preferring "caller" instead of "main flow" which IMHO is unclear and confusing.

2021-11-04 20:35 UTC, lrodero commented on docs/guides/tutorial.md
> +with fibers_.
LGTM, but I found a typo (`take` -> `takes`).
```suggestion
In contrast `parMapN` not only promotes errors raised by fibers to the caller, it also takes care of canceling the other fibers. This way `parMapN`
leads to simpler and more concise code. _Thus, unless you have some specific and
unusual requirements you should prefer to use higher level commands such as
`parMapN` or `parSequence` to work with fibers_.
```

2021-11-04 20:37 UTC, lrodero commented
Changes proposed by @armanbilge LGTM. "Main flow" seemed to me appropriate when I wrote the text but it's true that can be an unclear expression.

2021-11-04 21:08 UTC, armanbilge approved these changes

2021-11-04 22:15 UTC, vasilmkd approved these changes

2021-11-04 22:15 UTC, vasilmkd commented
@armanbilge Merge at will.

2021-11-04 22:15 UTC, merged