Fix of 3.x series tutorial paragraph about error promotion of join call
typelevel/cats-effect pull request #2458
Opened 2021-10-24 15:58 UTC by lrodero

The tutorial contains a paragraph about `.start` and `.join` that is messy if not plainly wrong. _E.g._ see [this msg](https://discord.com/channels/632277896739946517/632278585700384799/900807315190599800) in CE discord channel.

This PR tries to fix this for the 3.x series tutorial, briefly explaining the limitations of the `.start` + `.join` (or `joinWith` or `joinWithNever`) approach to underscore how using `.parMapN` or `.parSequence` is generally a better choice. Resulting text can be read [here](https://lrodero.github.io/cats-effect/docs/tutorial).

2021-10-24 16:03 UTC, vasilmkd submitted a review, later dismissed

2021-10-25 16:26 UTC, djspiewak requested changes
Minor adjustment but otherwise looks really good!

2021-10-25 16:26 UTC, djspiewak commented on docs/tutorial.md
> +Cats-effect 3 provides additional `joinWith` or `joinWithNever` methods to make
```suggestion
Cats Effect provides additional `joinWith` or `joinWithNever` methods to make
```

2021-10-25 18:28 UTC, vasilmkd submitted a review, later dismissed

2021-11-04 19:36 UTC, vasilmkd commented
We should cherry-pick these commits to `series/3.2.x`. I tried changing the base branch, but unfortunately it pulls in everything from `series/3.x`.

2021-11-04 19:42 UTC, armanbilge commented on docs/tutorial.md
> +the `join` call to that fiber will _not_ hint it, it will just 'swallow' the
Maybe I have just as much misconceptions about this stuff as the next person ... but doesn't it bubble up the error in the `Outcome`? It's not a loud as _raising_ the error for sure, but I wouldn't say it's not hinting it or swallowing it?

2021-11-04 19:44 UTC, armanbilge commented on docs/tutorial.md
> +to use, more concise, and ease to reason with. _Because of that, if possible,
```suggestion
to use, more concise, and easier to reason about. _Because of that, if possible,
```

2021-11-04 19:46 UTC, vasilmkd commented on docs/tutorial.md
> +the `join` call to that fiber will _not_ hint it, it will just 'swallow' the
I'm in agreement, I think we should adjust the wording there.

2021-11-04 19:47 UTC, lrodero commented
If it helps I can try to create a new PR based on (and pointing to) `series/3.2.x`. I'll include the latest changes committed on this PR.

2021-11-04 19:48 UTC, vasilmkd commented
@lrodero That would be immensely helpful!

2021-11-04 19:49 UTC, armanbilge commented on docs/tutorial.md
> +sure at least that the error is promoted and give us a chance to deal with it.
```suggestion
sure at least that the error is raised with the usual `MonadError` semantics (e.g., short-circuiting).
```

2021-11-04 19:53 UTC, armanbilge commented on docs/tutorial.md
> +error. Also, the other fibers will keep running unaware of what happened.
```suggestion
the `join` call to that fiber will _not_ raise it, it will return normally
and you must explicitly check the `Outcome` to see if it errored.
Also, the other fibers will keep running unaware of what happened.
```

2021-11-04 19:53 UTC, armanbilge commented on docs/tutorial.md
> +error. Also, the other fibers will keep running unaware of what happened.
@vasilmkd thoughts?

2021-11-04 19:55 UTC, armanbilge commented on docs/tutorial.md
> +can easily get ourselves trapped in a tangled mess of fibers to keep an eye of.
```suggestion
can easily get ourselves trapped in a tangled mess of fibers to keep an eye on.
```

2021-11-04 19:59 UTC, lrodero commented on docs/tutorial.md
> +the `join` call to that fiber will _not_ hint it, it will just 'swallow' the
No problem on changing the paragraph :slightly_smiling_face: . But the expression 'swallow' was chosen purposefully. This code in CE3 won't show any error, it will show that last msg `All is fine`:
```scala
object TestStartJoin extends IOApp {

  def ok: IO[Unit] = IO(println("Waiting...")) >> IO.sleep(2 seconds) >> IO(println("Finished waiting"))
  def boom: IO[Unit] = IO.sleep(1 seconds) >> IO.raiseError(new Error("BOOM!"))

  override def run(args: List[String]): IO[ExitCode] =
    for {
      okFiber <- ok.start
      boomFiber <- boom.start
      _ <- okFiber.join
      _ <- boomFiber.join
      _ <- IO(println("All was fine"))
    } yield ExitCode.Success

}
```
Maybe 'swallows' is not the most fortunate expression, but I think the new paragraph should convey a clear warning that errors like the one shown above won't be raised.

2021-11-04 20:01 UTC, armanbilge commented on docs/tutorial.md
> +the `join` call to that fiber will _not_ hint it, it will just 'swallow' the
@lrodero what do you think about my proposed wording in https://github.com/typelevel/cats-effect/pull/2458#discussion_r743157479?

2021-11-04 20:02 UTC, armanbilge commented on docs/tutorial.md
> +the `join` call to that fiber will _not_ hint it, it will just 'swallow' the
Yes, I'm hesitant to say "swallows" because that would imply the error is gone...it's there in the outcome, which in this example is being discarded.

2021-11-04 20:09 UTC, armanbilge commented on docs/tutorial.md
> +`parSequence` to deal with fibers_.
```suggestion
to use, more concise, and easier to reason about. _Because of that, unless you have some specific and
unusual requirements you should prefer to use higher level commands such as
`parMapN` or `parSequence` to work with fibers_.
```

2021-11-04 20:13 UTC, lrodero commented on docs/tutorial.md
> +error. Also, the other fibers will keep running unaware of what happened.
LGTM! But I'm a bit concerned that the reader at this point does not know what `Outcome` is or where it comes from, so I'd change it to something like this:
```suggestion
the `join` call to that fiber will _not_ raise it, it will return normally and
you must explicitly check the `Outcome` instance returned by the `.join` call to
see if it errored. Also, the other fibers will keep running unaware of what
happened.
```

2021-11-04 20:14 UTC, armanbilge commented on docs/tutorial.md
> +error. Also, the other fibers will keep running unaware of what happened.
👍 good point

2021-11-04 20:18 UTC, lrodero commented
@vasilmkd No prob! If it's ok I'll wait until @armanbilge suggestions are included in this PR and then I'll open the new PR against `series/3.2.x` with the final text. There is no point in re-opening the discussion there I think.

2021-11-04 20:19 UTC, vasilmkd commented
Yeah, let's do that.

2021-11-04 20:22 UTC, vasilmkd commented
I believe I've merged all suggestions.

2021-11-04 20:23 UTC, armanbilge commented
Yes, I think so. Sorry, I'm just taking one more pass through with a couple more tweaks, I think some of the changes made it less coherent. Just a sec 😅

2021-11-04 20:25 UTC, armanbilge commented
Oh also, what did you think about my comments about "main flow" in the other PR targeting 2.x? If in agreement I'd like to remove it from here as well.

2021-11-04 20:30 UTC, lrodero commented
Ah, sorry, I was too impatient :sweat_smile: and I opened a PR for `series/3.2.x`... it's already closed :slightly_smiling_face: . Sorry for the noise there.

2021-11-04 20:35 UTC, armanbilge commented on docs/tutorial.md
> +Cats Effect provides additional `joinWith` or `joinWithNever` methods to make
```suggestion
happened.

Cats Effect provides additional `joinWith` or `joinWithNever` methods to make
```

I prefer paragraphs to big blocks of text, but no biggie.

2021-11-04 20:35 UTC, armanbilge commented on docs/tutorial.md
> +we must also consider if we should at least cancel the other running fibers. We
```suggestion
Now that we are raising the error, an additional complexity is that we need to cancel
the other running fibers so as to propagate the short-circuiting semantics. We
```

2021-11-04 20:44 UTC, lrodero commented on docs/tutorial.md
> +we must also consider if we should at least cancel the other running fibers. We
Hummm... sorry IMHO the new proposed text is less clear than the original :grimacing: . The wording in _An additional complexity is (...)_ looks a bit weird to me (though I must admit I'm not a native English speaker, by a long shot).

2021-11-04 20:46 UTC, armanbilge commented on docs/tutorial.md
> +we must also consider if we should at least cancel the other running fibers. We
No worries! Is it just that part? I'm happy to drop it completely.

2021-11-04 20:46 UTC, armanbilge commented on docs/tutorial.md
> +we must also consider if we should at least cancel the other running fibers. We
```suggestion
Now that we are raising the error,  we also need to cancel
the other running fibers so as to propagate the short-circuiting semantics. We
```

2021-11-04 20:47 UTC, armanbilge commented on docs/tutorial.md
> +we must also consider if we should at least cancel the other running fibers. We
Or even:

```suggestion
Now that we are raising the error, we also need to cancel the other running fibers. We
```

2021-11-04 20:50 UTC, armanbilge commented on docs/tutorial.md
> +care of cancelling the remaining alive fibers. As a result `parMapN` is simpler
```suggestion
In contrast `parMapN` does promote any error it finds to the caller _and_ takes
care of canceling the other running fibers. As a result `parMapN` is simpler
```

2021-11-04 20:54 UTC, armanbilge commented on docs/tutorial.md
> +consuming resources for nothing.
```suggestion
`joinWith` or `.joinWithNever` is reached. So in our example above if
`consumerFiber` raises an error then then we have no way to observe that
until the producer fiber has finished. Alarmingly, note that in our example the producer
_never_ finishes and thus the error would _never_ be observed! 
And even if the producer fiber did finish, it would have been
consuming resources for nothing.
```

2021-11-04 20:55 UTC, lrodero commented on docs/tutorial.md
> +we must also consider if we should at least cancel the other running fibers. We
Nice one, it simplifies the text :+1:

2021-11-04 20:58 UTC, lrodero commented on docs/tutorial.md
> +consuming resources for nothing.
Good! Just please fix `then then` -> `then`.

2021-11-04 21:08 UTC, armanbilge commented on docs/tutorial.md
> +consuming resources for nothing.
Ninja'd 😉

2021-11-04 21:45 UTC, lrodero commented
@armanbilge if you have no further suggestions I'd get ready the PR for `series/3.2.x`.

2021-11-04 21:46 UTC, armanbilge commented
I'm good 👍 I was waiting for @vasilmkd but he can have a final look in the new PR. Let me quickly apply the suggestions I've made.

2021-11-04 21:48 UTC, armanbilge approved these changes

2021-11-04 21:56 UTC, lrodero commented
Ok then, new [PR](https://github.com/typelevel/cats-effect/pull/2501) for `series/3.2.x` is ready @vasilmkd. I think we can close this one.

2021-11-04 21:57 UTC, armanbilge commented
Superseded by https://github.com/typelevel/cats-effect/pull/2501.

2021-11-04 21:57 UTC, closed without merging