Incorporate MapRef into Std
typelevel/cats-effect pull request #2464
Opened 2021-10-25 17:04 UTC by ChristopherDavenport

Fixes #2444 

Integrates MapRef.

Features: ShardedMapRef, ConcurrentHashMap, and Scala Concurrent Map Implementations, and Defaulted Ref/MapRef.

Why Care? This enables keyed concurrent state machines that don't space leak. It basically allows almost any state machine with a default state to be lifted to a keyed version of the same state machine that is removed entirely when it enters some zero state.

2021-10-25 17:05 UTC, ChristopherDavenport commented on tests/jvm/src/test/scala/cats/effect/std/MapRefTrieSpec.scala
> +    // test("MapRef.ofScalaConcurrentTrieMap - tryUpdate - should fail to update if modification has occurred" ) {
Never got these operational again when upgraded to ce3. Just never got them hammered out.

2021-10-25 17:08 UTC, ChristopherDavenport commented on std/shared/src/main/scala/cats/effect/std/MapRef.scala
> +  def defaultedRef[F[_]: Functor, A: Eq](ref: Ref[F, Option[A]], default: A): Ref[F, A] =
This makes sense here as this is where it necessary. But might be useful elsewhere. We could also rely on global equality if we like being risky or offer a global equality version.

2021-10-25 17:15 UTC, ChristopherDavenport commented on tests/jvm/src/test/scala/cats/effect/std/MapRefTrieSpec.scala
> +    // test("MapRef.ofScalaConcurrentTrieMap - tryUpdate - should fail to update if modification has occurred" ) {
Fixed

2021-11-01 22:40 UTC, armanbilge commented on tests/jvm/src/test/scala/cats/effect/std/MapRefJVMSpec.scala
> +  "MapRef" should { // Requires unsafeRunSync so doesn't work with JS
Interesting note, it's not just that JS doesn't have `unsafeRunSync` so this test doesn't work, it's actually that this test is meaningless on JS anyway because concurrent modifications are impossible :)

2021-11-01 22:55 UTC, armanbilge commented
Just a thought, could we abstract the current `RefSpec` in tests and reuse it for the various `MapRef` implementations?

2021-11-07 18:32 UTC, djspiewak requested changes
I really like this as an addition to the stdlib. My concerns basically boil down to the following:

- Confusing and IMO unnecessary `of`/`in` constructor duplication
- Inaccurate typeclass constraints faked by using `unit.map(_ => ...)` rather than `delay(...)`
- Syntax requires unnecessary imports
- Minor bikeshedding on test structure
- Lots of unnecessary and likely-inefficient use of `lazy val` rather than `def`

2021-11-07 18:32 UTC, djspiewak commented on std/jvm/src/main/scala/cats/effect/std/MapRefCompanionPlatform.scala
> +      .map(_ => scala.collection.concurrent.TrieMap.empty[K, V])
Very leery of something like this. :-)

2021-11-07 18:32 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/MapRef.scala
> +        hasBeenCalled <- Applicative[F].unit.map(_ => new AtomicBoolean(false))
…and here too. Why not simply embrace the fact that this is really forcing `Sync[F]`?

2021-11-07 18:32 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/MapRef.scala
> +  def inShardedImmutableMap[G[_]: Sync, F[_]: Async, K, V](
If we more fully embrace `Sync`, then we don't need to have the `of`/`in` split in the constructors.

2021-11-07 18:32 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/syntax/MapRefSyntax.scala
> +  implicit def mapRefOptionSyntax[F[_], K, V](
You can actually stick this into the `MapRef` companion and it won't require the import.

2021-11-07 18:32 UTC, djspiewak commented on tests/shared/src/test/scala/cats/effect/std/MapRefSpec.scala
> +    "MapRef.ofSingleImmutableMapRef - concurrent modifications" in real {
Uh… we're in Specs2, so this kind of test name is pretty confusing. :-) I would prefer if we did `"ofSingleImmutableMapRef" >> { ... }` and then inside that block have `"concurrent modifications" >> real {` etc etc.

2021-12-12 21:11 UTC, SystemFw commented on std/shared/src/main/scala/cats/effect/std/MapRef.scala
> +        hasBeenCalled <- Applicative[F].unit.map(_ => new AtomicBoolean(false))
I'm going to open an issue for what I'm about to say, and I also want to give a general review of MapRef (tl;dr mostly amazing, some api bikeshedding), but I'm going to drop it here in case I forget: we should relax the semantics on `access` to not need `hasBeenCalled`. It was in "broken" form in fs2 for ages, the only reason this was introduced is to conform to the docs, and it's a pain in the arse for things that want to implement Ref, like SignallingRef or MapRef.

2021-12-12 21:44 UTC, durban commented
This seems pretty useful. What I find very strange is that it uses universal equality/hash for the keys, while there is a `Hash` typeclass in Cats.

2022-03-22 20:55 UTC, ChristopherDavenport commented
Proposal:

1. Remove the `access` requirement on replay so concurrent constraint can get met by Ref implementation.
2. Make a single default implementation that matches on the effect type like the Queue implementation does that delegates to CHM on Async and Ref on Concurrent
3. All the current constructors live on in MapRef library but the trait and default lives here. That way people can still leverage the interface, but the advanced uses still have the library for those more advanced use cases that would bulk up the binary interface in cats-effect too much.

Thoughts?

2022-03-22 21:11 UTC, SystemFw commented
I'm in favour of the proposal above, and I think it would be good to get this into CE :)

2022-03-23 00:16 UTC, durban commented
I would recommend basing the default implementation on `TrieMap` instead, since that can support using the `Hash` typeclass for the keys.

2022-06-19 20:41 UTC, djspiewak approved these changes

2022-06-19 20:41 UTC, merged