Fiber dump docs
typelevel/cats-effect pull request #2504
Opened 2021-11-05 18:18 UTC by armanbilge

Exciting, but still lots to do :)

2021-11-07 18:49 UTC, djspiewak requested changes
In addition to the comments I noted, I think we should move this under the **core/** subdirectory (which should be created). I want to split out introductory docs from "Core Runtime" documentation. This is also where `TestControl` and tracing docs will end up, as well as the still-to-be-written `IO` and `Resource` docs.

2021-11-07 18:49 UTC, djspiewak commented on docs/fiber-dumps.md
> +For a running `IOApp` with tracing enabled, it's as simple as <kbd>Ctrl</kbd>-<kbd>T</kbd>. This is supported for _both_ the JVM and Node.js runtimes on macOS/BSD and Linux.
I think <kbd>Ctrl</kbd>-<kbd>T</kbd> only works on macOS/BSD, unfortunately, but the signals work fine on Linux.

2021-11-07 18:49 UTC, djspiewak commented on docs/fiber-dumps.md
> +## Interpreting a fiber dump
I think we should add a concrete example of a deadlock and what it looks like.

2021-11-23 22:15 UTC, vasilmkd commented
The documentation I added about `jlink` and GraalVM `native-image` refer to this document as `core/live-fiber-snapshot.md`. Just FIY. Feel free to decide on the name, but note those two documents might need changing. 😄

2022-01-31 04:28 UTC, djspiewak approved these changes

2022-01-31 04:28 UTC, merged