Create fiber-aware EC for JS
typelevel/cats-effect pull request #2506
Opened 2021-11-05 22:22 UTC by armanbilge

This is a slight adaptation of Daniel's code. The difference is, here we add the fiber to the set _as soon as it's queued_ (rather than when the underlying EC decides to run it). Then, just before the underlying EC starts running it, it removes it. In the process of running, it may re-enqueue itself.

2021-11-05 22:29 UTC, armanbilge commented
Btw, I think we can use a concurrent-version of this construct to wrap the blocking threadpool on JVM as well.

2021-11-05 22:46 UTC, armanbilge commented
One interesting takeaway, is that fiber dumps on JS will _never_ indicate a running fiber due to its single-threaded nature! You can't be observing, if something is running :)

2021-11-05 23:35 UTC, vasilmkd commented
@armanbilge Do you have an example of a fiber re-enqueueing itself from inside `.run()`?

2021-11-05 23:36 UTC, armanbilge commented
Err, isn't that what `IOFiber` does e.g. for ceding? Or maybe I don't understand how any of this works 😳

2021-11-05 23:41 UTC, vasilmkd commented
Actually, you're spot on. That's exactly what happens. On `cede`, the fiber calls `currentCtx.execute(this)`, which will immediately put the fiber in the bag, and then schedule it on the underlying executor. I think this works nicely.

2021-11-05 23:58 UTC, vasilmkd requested changes
This is phenomenal.

Please do not commit my suggestions one by one, apart from the large comment. Add a commit for the rest.

2021-11-05 23:58 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/FiberAwareExecutionContext.scala
> +private[effect] final class FiberAwareExecutionContext(ec: ExecutionContext)
Let's keep this just `private` for now, not `private[effect]`.

2021-11-05 23:58 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/FiberAwareExecutionContext.scala
> +private[effect] final class FiberAwareExecutionContext(ec: ExecutionContext)
```suggestion
private final class FiberAwareExecutionContext(ec: ExecutionContext)
```

2021-11-05 23:58 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/FiberAwareExecutionContext.scala
> +        // B/c JS is single-threaded, nobody can observe the bag while it is running anyway
```suggestion
        // We have to remove the fiber from the bag _before_ running it, because operations like
        // `IO.cede` will add it again. This, while convenient, is not really an issue. The real
        // reason we need to remove the fiber from the bag before running it is to remove the
        // strong reference to it, otherwise, the strong reference would break GC guarantees for
        // suspended operations like `IO.never`. Suspended fibers are still tracked through the
        // iterable weak map mechanism which respects the GC.
```

2021-11-05 23:58 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/FiberAwareExecutionContext.scala
> +  private[this] val fiberBag = mutable.Set[IOFiber[_]]()
```suggestion
  private[this] val fiberBag = mutable.Set.empty[IOFiber[_]]
```

2021-11-05 23:58 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/FiberAwareExecutionContext.scala
> +  def fibers: Set[IOFiber[_]] = fiberBag.toSet
```suggestion
  def liveFibers(): Set[IOFiber[_]] = fiberBag.toSet
```

The `()` will match the JVM code, which will be unsafe and contain side effects.

2021-11-05 23:58 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
> +  def defaultComputeExecutionContext: ExecutionContext = if (LinkingInfo.developmentMode)
Let's tie this to `SuspendedFiberBag/FiberMonitor`. If `WeakBag` is not available, IMO, there's no reason to track fibers, if we're not able to offer suspended ones. What do yo think?

2021-11-06 00:02 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/FiberAwareExecutionContext.scala
> +        // B/c JS is single-threaded, nobody can observe the bag while it is running anyway
No, wait.

2021-11-06 00:06 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/FiberAwareExecutionContext.scala
> +  def fibers: Set[IOFiber[_]] = fiberBag.toSet
👍 I think we may eventually need this behind a shared trait, so that code can do `isInstanceOf[FiberAwareEC]` or something to check if this method is available.

2021-11-06 00:08 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
> +  def defaultComputeExecutionContext: ExecutionContext = if (LinkingInfo.developmentMode)
Oops, good point. Agreed!

2021-11-06 00:09 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/FiberAwareExecutionContext.scala
> +  def fibers: Set[IOFiber[_]] = fiberBag.toSet
I have a plan, don't you worry ;)

2021-11-06 00:10 UTC, armanbilge commented
> Please do not commit my suggestions one by one, apart from the large comment. Add a commit for the rest.

Sorry, I'm a bit confused what gets committed when 😅

2021-11-06 00:10 UTC, vasilmkd commented
Make 1 commit with me as the co author (or not), do not commit my suggestions one by one. That's what I meant.

2021-11-06 00:19 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
> +  def defaultComputeExecutionContext: ExecutionContext = if (LinkingInfo.developmentMode)
I just reverted this for now. When we can see the big picture more clearly we're going to have to figure out the config, which needs to know if (1) in dev mode (2) tracing is enabled and (3) the necessary features are in place, and then do these together (or not). Tracing of course stands alone regardless of fiber dump support.

2021-11-06 00:20 UTC, vasilmkd commented on core/js/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
> +  def defaultComputeExecutionContext: ExecutionContext = if (LinkingInfo.developmentMode)
Yeah, no problem.

2021-11-06 00:23 UTC, vasilmkd commented
This is slightly annoying, but can you please edit the first commit and put Daniel as a co-author? I would really appreciate it. You can force push after that.

2021-11-06 00:41 UTC, vasilmkd approved these changes
Nice.

2021-11-06 00:41 UTC, merged