Small improvement to `interruptible` docs
typelevel/cats-effect pull request #2568
Opened 2021-11-20 17:14 UTC by alexandrustana

Aims to fix  #2566

2021-11-20 18:00 UTC, vasilmkd commented
@alexandrustana Can you please as part of this PR also carry over the `Sync#interruptible` and `Sync#interruptibleMany` scaladocs to `IO#interruptible` and `IO#interruptibleMany`? Thank you.

2021-11-20 18:01 UTC, vasilmkd commented
This is great btw, I will do another review pass again. Thank you so much.

2021-11-20 18:11 UTC, alexandrustana commented
> @alexandrustana Can you please as part of this PR also carry over the `Sync#interruptible` and `Sync#interruptibleMany` scaladocs to `IO#interruptible` and `IO#interruptibleMany`? Thank you.

Thank you for suggesting this, I was afraid porting that wouldn't be accepted  😅

2021-11-20 20:16 UTC, vasilmkd commented
You really shouldn't be worried about such things. Feel free to raise any issue or question that you might have. We will arrive at the best solution through discussion, as we always do. Nothing is off limits, especially not documentation, you can never go wrong with more documentation, however repetitive it may feel. 😄

2021-11-20 20:19 UTC, vasilmkd requested changes

2021-11-20 20:19 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/IO.scala
> +     *   The side effect which is to be suspended in `F[_]` and evaluated on a blocking
suspended in `IO`. Same for `interruptibleMany`.

2021-11-20 20:19 UTC, vasilmkd commented on docs/concepts.md
> +In particular, "asynchronous" is the opposite of "synchronous", and it pertains to a manner in which a given effect produces a value. Synchronous effects are defined using `apply` (also `delay` or `b
(also `delay`, `blocking`, `interruptible` or `interruptibleMany`. There are too many "or"s as of now. 😆

2021-11-20 20:19 UTC, vasilmkd commented on docs/migration-guide.md
> +The difference between `interruptible` and `interruptibleMany` is that in case of cancellation
This is nitpicking but we use "cancelation" throughout the codebase. This comment is just for consistency.

2021-11-20 22:38 UTC, vasilmkd commented on docs/migration-guide.md
> +The difference between `interruptible` and `interruptibleMany` is that in case of cancellation
```suggestion
The difference between `interruptible` and `interruptibleMany` is that in case of cancelation
```

2021-11-20 22:38 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/IO.scala
> +     *   The side effect which is to be suspended in `IO[_]` and evaluated on a blocking
```suggestion
     *   The side effect which is to be suspended in `IO` and evaluated on a blocking
```

2021-11-20 22:38 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/IO.scala
> +     *   The side effect which is to be suspended in `IO[_]` and evaluated on a blocking
```suggestion
     *   The side effect which is to be suspended in `IO` and evaluated on a blocking
```

2021-11-20 22:42 UTC, vasilmkd commented
@alexandrustana Can you please run `scalafmtAll` and push a commit? Thank you.

2021-11-21 07:58 UTC, alexandrustana commented
Sure thing. 
@vasilmkd thank you for the help and the kind words 🙂

2021-11-21 16:57 UTC, vasilmkd approved these changes
Great work, thank you so much again, for the feature as a whole. It will be very impactful.

2021-11-21 17:34 UTC, alexandrustana commented
Thank you for all the support when attempting to fix these issues 🙂 I'm really grateful for it.

Should an issue also be created for updating this
https://github.com/typelevel/cats-effect/blob/051bc754837766e6d4ce5fab8d1ca12c13768603/scalafix/build.sbt#L60
after the release?

2021-11-21 17:47 UTC, vasilmkd commented
Yes, feel free to open that issue.

2021-11-22 19:36 UTC, djspiewak approved these changes

2021-11-22 19:36 UTC, merged