Adds joinWithUnit for Fiber
typelevel/cats-effect pull request #2643
Opened 2021-12-11 01:59 UTC by etspaceman

Solves #2636

2021-12-11 09:21 UTC, vasilmkd commented
I'm against this method because it is no different from `joinWith(F.unit)` if your effect is already `F[Unit]`.

2021-12-11 13:28 UTC, etspaceman commented
Its really just a convenience method for a common pattern. What's the issue with adding it?

2021-12-11 14:07 UTC, vasilmkd commented
No issue. I was just voicing my opinion. My opinion may be wrong. 😄

2021-12-12 19:05 UTC, armanbilge commented
> I'm against this method because it is no different from `joinWith(F.unit)` if your effect is already `F[Unit]`.

Exactly, saves some typing and gets you autocomplete :) unless there's some reason this is an anti-pattern we don't want to encourage I'm 👍

2021-12-17 15:16 UTC, etspaceman commented
@djspiewak any thoughts on this one?

2021-12-19 07:29 UTC, djspiewak requested changes
I think this is honestly quite reasonable. It's a fairly common pattern and the auto-complete alone is worth it. Left some minor comments.

2021-12-19 07:29 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Fiber.scala
> +  def joinWithUnit(implicit F: GenSpawn[F, E], ev: Unit <:< A): F[A] =
```suggestion
  def joinWithUnit(implicit F: MonadCancel[F, E], ev: Unit <:< A): F[A] =
```

2021-12-19 07:29 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Fiber.scala
> +    joinWith(F.unit.map(ev(_)))
I'm actually in favor of using a cast here since it avoids an allocation.

```suggestion
    val _ = ev
    joinWith(F.unit.asInstanceOf[F[A]])
```

(also assume the addition of some wrapping braces)

2021-12-19 14:58 UTC, etspaceman commented on kernel/shared/src/main/scala/cats/effect/kernel/Fiber.scala
> +    joinWith(F.unit.map(ev(_)))
This is done

2021-12-19 14:58 UTC, etspaceman commented on kernel/shared/src/main/scala/cats/effect/kernel/Fiber.scala
> +  def joinWithUnit(implicit F: GenSpawn[F, E], ev: Unit <:< A): F[A] =
This is done

2021-12-19 17:23 UTC, djspiewak approved these changes

2021-12-19 17:23 UTC, merged