Implement `std.Env[F]` for cross-platform environment variables
typelevel/cats-effect pull request #2650
Opened 2021-12-13 15:34 UTC by armanbilge

Fixes https://github.com/typelevel/cats-effect/issues/2532. As @SystemFw [pointed out](https://discord.com/channels/632277896739946517/839263556754472990/919679231993184406):
> I think some things should be quite uncontroversial, like `Env`
> it's used all over the place and the design space is tiny

So, here we are 😁

2021-12-27 02:48 UTC, kubukoz commented on core/js/src/main/scala/cats/effect/process.scala
> +    OptionT(env.get(key)).orElseF(env.get(s"REACT_APP_$key")).value.unsafeRunSync()
I don't really like this, feels like React users could add this fallback on their own (or just use the key with this prefixed from the beginning).

2021-12-27 02:49 UTC, kubukoz submitted a review, later dismissed

2021-12-27 02:51 UTC, kubukoz commented on std/jvm/src/main/scala/cats/effect/std/EnvCompanionPlatform.scala
> +    def get(name: String): F[Option[String]] = F.delay(sys.env.get(name))
`System.getenv` should be better as it doesn't force the entire environment. I think there's a difference in the security manager...

2021-12-27 02:51 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/process.scala
> +    OptionT(env.get(key)).orElseF(env.get(s"REACT_APP_$key")).value.unsafeRunSync()
FTR this is only used for detecting CE config (e.g., tracing, etc.).

2021-12-27 02:52 UTC, kubukoz commented on tests/shared/src/test/scala/cats/effect/std/EnvSpec.scala
> +      Env[IO].get("HOME").flatMap(x => IO(x must beSome))
You could set a concrete value with `envVars` in sbt (assuming we have `fork` in the JVM tests), should make for more accurate testing.

2021-12-27 02:53 UTC, armanbilge commented on tests/shared/src/test/scala/cats/effect/std/EnvSpec.scala
> +      Env[IO].get("HOME").flatMap(x => IO(x must beSome))
Yeah, tried that first. Doesn't work for Node.js and was lazy to split the tests (:

2021-12-27 02:56 UTC, kubukoz commented on core/js/src/main/scala/cats/effect/process.scala
> +    OptionT(env.get(key)).orElseF(env.get(s"REACT_APP_$key")).value.unsafeRunSync()
ah wait I thought this was used _in_ Env. LGTM

2021-12-27 02:56 UTC, kubukoz commented on tests/shared/src/test/scala/cats/effect/std/EnvSpec.scala
> +      Env[IO].get("HOME").flatMap(x => IO(x must beSome))
huh, it worked on my machine...

2021-12-27 02:56 UTC, armanbilge commented on std/jvm/src/main/scala/cats/effect/std/EnvCompanionPlatform.scala
> +    def get(name: String): F[Option[String]] = F.delay(sys.env.get(name))
Oh, good point. Didn't know that, here's the source for anyone curious.
https://github.com/scala/scala/blob/4b2151cbe4c857d49556b70c3fa0f5e236fd7754/src/library/scala/sys/package.scala#L67

2022-01-01 22:14 UTC, armanbilge commented on std/jvm/src/main/scala/cats/effect/std/EnvCompanionPlatform.scala
> +      F.delay(Map.from(sys.env)) // a somewhat redundant copy, to shake the unsafe withDefault
Alternatively, we could build the `Map` ourselves directly from `System.getenv()`, but I didn't want to fight deprecation warnings for the Java collections converters across 2.12/2.13.

2022-01-05 05:13 UTC, rossabaker requested changes
:+1: on adding it to `std`.  :-1: on `toMap`.  :-1: to me appealing to Haskell, but I think they got this right.

2022-01-05 05:24 UTC, armanbilge commented
Thanks. I don't have any strong feeling about `toMap` (it's honestly annoying to implement) but I am curious why it's not a good idea generally :)

2022-01-05 15:23 UTC, rossabaker commented
Hmm.  My inline comment did not arrive with my ❌.  Sorry.

On some platforms, notably Windows, environments are case insensitive.  That's why the Scala map has a default, and why even `Map.empty ++ sys.env` breaks the property that `get(x) <-> toMap(_.get(x))`.  You can hack around that, but a `Map` whose lookup is inconsistent with the equality of its keys will always do weird shit.

In [Haskell](https://hackage.haskell.org/package/base-4.16.0.0/docs/System-Environment.html), they have (translating to Scala and tagless):
* `String => F[Option[String]]` (like our `get`)
* `F[List[(String, String)]]` (instead of our `toMap`).

We might quibble about `List` and the ordering it might imply, but separating the lookup from the iteration insulates the base library from weird shit.

2022-01-05 15:44 UTC, armanbilge commented
Aha, thanks. That was bothering me too. Returning a `List` of key-value pairs seems good to me. B/c of the unordered thing, could we return a `Set` here?

2022-01-05 16:01 UTC, rossabaker commented
`Set`'s featured operation is `contains`, which has the same problems as the `Map`.  `scala.collection.immutable.Iterable` says just the right amount here.

2022-01-05 17:01 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/Env.scala
> +  def entries: F[Iterable[(String, String)]]
🚲 🏠 ?

2022-01-05 17:17 UTC, kubukoz commented on std/shared/src/main/scala/cats/effect/std/Env.scala
> +  def entries: F[Iterable[(String, String)]]
lgtm

2022-01-05 18:42 UTC, rossabaker approved these changes
Now people can pick their own tradeoffs with `entries.map(SomeOtherCollectionFactory)`... or probably just iterate over it.

2022-01-16 03:53 UTC, djspiewak approved these changes
Tentatively approved, though I'm not thrilled about `Iterable`. Does Cats have a `Foldable[Iterable]`?

2022-01-16 15:02 UTC, rossabaker commented
There is not.  There is a `Foldable[collection.Iterable]` in alleycats.  Some of the `Foldable` operations suggest an ordering, which is the reason I objected to `List`.

A `List` isn't the end of the world: the ordering is arbitrary, but harmless.  I still think `Map` and `Set` lead to platform-specific dragons.

2022-01-17 17:46 UTC, merged