Allow wrapping compute instance in IORuntime
typelevel/cats-effect pull request #2657
Opened 2021-12-16 11:13 UTC by majk-p

I'm working on migrating applications from CE2 to CE3. In CE2 I used `IOApp` and prior to running any `IO`, I'd override the default execution context with the one wrapped with Kanela.

With CE3 we have this `IORuntime` that hides the underlying execution context. If I wanted to reproduce that approach with CE3, I'd basically have to create the whole `IORuntime` on my own. Instead of doing that, doing `runtime.copy(context = wrap(runtime.context))` would be enough.

This PR introduces a method that exposes the necessary API for my use case. What do you think about it? Is it the right approach or is there anything else I should try?

2021-12-16 11:48 UTC, majk-p commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntime.scala
> +  def wrappingCompute(wrapCompute: ExecutionContext => ExecutionContext): IORuntime =
Suggestions of the better name are obviously welcome :wink:

2021-12-16 14:20 UTC, armanbilge commented
@majk-p and I had a very nice chat in [Discord](https://discord.com/channels/632277896739946517/839263556754472990/921005196274958357) :) Some notes:
1. The current API is flexible enough to do what is needed, but too difficult to use. Particularly, the fact that `createDefaultComputeThreadPool` needs a reference to the runtime being created is confusing.
2. I like how this PR provides a simple interface to the user, but I'm worried if being able to access and share a compute pool between multiple `IORuntime`s could violate some of our internal assumptions e.g. when registering mbeans, fiber bags, etc. 
3. I propose we introduce an API `IORuntimeBuilder` that has the defaults baked in, but also exposes methods such as the one proposed in this PR. No resources should get allocated until the user `.build`s it. This should help solve the complexity in (1).

2021-12-16 19:27 UTC, armanbilge reviewed
Nice job navigating the cross-platform stuff! I really like how this is looking :)

2021-12-16 19:27 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  }
I'm not sure if we should make the shutdown overridable, since it's supposed to shutdown the threadpools that were created for this runtime. Instead, I think we should collect a shutdown for each option, and automatically combine the shutdowns in the builder.

2021-12-16 19:27 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def withComputeWrapper(wrapper: ExecutionContext => ExecutionContext) = {
This is good for your usecase :) can we also add options for someone to completely replace the compute and blocking pools?

2021-12-16 19:27 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def withScheduler(scheduler: Scheduler) = {
We should also ask for an operation to shutdown the `Scheduler`.

2021-12-16 19:27 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeBuilderPlatform.scala
> +private[unsafe] abstract class IORuntimeBuilderPlatform {
```suggestion
private[unsafe] abstract class IORuntimeBuilderPlatform { self: IORuntimeBuilder =>
```

Then, you will be able to access all of its member variables, without need to request them as parameters in the `build` method below.

2021-12-17 08:13 UTC, majk-p commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  }
Thank you, I wasn't sure how the shutdown logic works. I've done as asked, also I've added `def addShutdownHook(shutdown: () => Unit)` for introducing custom shutdown logic.

2021-12-17 08:13 UTC, majk-p commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def withComputeWrapper(wrapper: ExecutionContext => ExecutionContext) = {
Sure thing, done :wink:

2021-12-17 08:13 UTC, majk-p commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def withScheduler(scheduler: Scheduler) = {
Done :+1:

2021-12-17 08:14 UTC, majk-p commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeBuilderPlatform.scala
> +private[unsafe] abstract class IORuntimeBuilderPlatform {
For some reason, I thought it wouldn't work when I first tried it. Seems like my IDE was playing tricks on me. Done now :+1:

2021-12-17 15:20 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +final class IORuntimeBuilder protected (
Default parameters are a bit of a pain to deal with in library APIs when it comes to binary compatibility. Let's wait for some of the more experienced folks to weigh in.

2021-12-17 15:24 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +final class IORuntimeBuilder protected (
True. Fortunately this is a `protected` constructor (it can probably be made `private` btw :) so no concerns with bincompat.

2021-12-17 15:28 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +final class IORuntimeBuilder protected (
The public methods also contain default parameters. GitHub should allow file level comments.

2021-12-17 15:30 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +final class IORuntimeBuilder protected (
Ah, haven't looked at the latest updates. Those defaults should probably just be removed IMO.

2021-12-17 15:39 UTC, majk-p commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +final class IORuntimeBuilder protected (
WDYT about doubling the methods for convenience like below?
```scala
  def overrideCompute(compute: ExecutionContext, shutdown: () => Unit = () => ()) = {
    customCompute = Some((compute, shutdown))
    this
  }
  def overrideCompute(compute: ExecutionContext ) = {
    this.overrideCompute(compute, () => ())
  }
```

2021-12-17 15:43 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def overrideCompute(compute: ExecutionContext, shutdown: () => Unit = () => ()) = {
```suggestion
  def setCompute(compute: ExecutionContext, shutdown: () => Unit) = {
```

Or, `withCompute`? Not sure what's more idiomatic, but I think `set` is for mutable and `with` is for immutable.

Vasil makes a good point about default parameters. If we really want to make `shutdown` optional we can add an overload. I think we should make it required though, to force users to think about shutdown. It's easy to type `() => ()` anyway.

2021-12-17 15:43 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def overrideCompute(compute: ExecutionContext, shutdown: () => Unit = () => ()) = {
Oh, another thing to consider: what if they `setCompute` twice, should we `shutdown` the previous one? We can either not care (it's a strange thing to do) or we can only allow them to call `setCompute` at most once (if there's already a custom compute set, raise an error).

2021-12-17 15:43 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def overrideBlocking(blocking: ExecutionContext, shutdown: () => Unit = () => ()) = {
Same comments as above :)

2021-12-17 15:43 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def withScheduler(scheduler: Scheduler, shutdown: () => Unit = () => ()) = {
same comments here 😉

2021-12-17 15:43 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def build: IORuntime =
I wonder if we should only allow to call this method once, so a builder can't be re-used.

2021-12-17 15:43 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeBuilderPlatform.scala
> +      extraShutdownHooks.foreach(_())
I think we want to run `extraShutdownHooks` in reverse, because the list is built in reverse order that they are added.

2021-12-17 15:43 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def addShutdownHook(shutdown: () => Unit) = {
Actually, I'm not sure what a realistic use-case for this method is, do you have one in mind? Seems strange for shutting down an `IORuntime` to also shutdown resources not related to it :)

2021-12-17 15:45 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def withComputeWrapper(wrapper: ExecutionContext => ExecutionContext) = {
```suggestion
  def transformCompute(wrapper: ExecutionContext => ExecutionContext) = {
```

Maybe? Naming things is hard 😆

2021-12-17 15:49 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +}
One more idea: maybe we should have a `Builder` method inside of the `IORuntime` object. Or even move all of this into a nested class.

2021-12-18 18:21 UTC, majk-p commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def addShutdownHook(shutdown: () => Unit) = {
I can think of a such situation. Say I'm creating `InstrumentedIOApp` that uses custom `IORuntime`. I would use `IORuntimeBuilder().withComputeWrapper(addInstrumentation)` and then I might want to go with `addShutodwnHook` to make sure that all instrumentation modules are stopped. I guess this might also be helpful when debugging.
Do you feel like we should drop it?

2021-12-18 18:30 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def addShutdownHook(shutdown: () => Unit) = {
Aha, thanks for explaining. That makes sense to me 👍 let's keep it.

(One alternative would be for to collect the shutdown hook in `withComputeWrapper`, like we do for `setCompute` etc., but that seems more confusing to me.)

2021-12-18 18:39 UTC, majk-p commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def overrideCompute(compute: ExecutionContext, shutdown: () => Unit = () => ()) = {
I've renamed all the methods that do override to use the `set` prefix. Allowing to set compute/blocking/shutdown and build just once sounds great. Just to make sure I got you right, do you think we should throw some runtime exception?
Sounds most straightforward, but I wonder if it's worth it to prevent on type-level somehow? or perhaps it would just be an overengineering?

2021-12-18 18:41 UTC, majk-p commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def overrideBlocking(blocking: ExecutionContext, shutdown: () => Unit = () => ()) = {
Done ;)

2021-12-18 18:41 UTC, majk-p commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def withScheduler(scheduler: Scheduler, shutdown: () => Unit = () => ()) = {
Done ;)

2021-12-18 18:41 UTC, majk-p commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeBuilderPlatform.scala
> +      extraShutdownHooks.foreach(_())
Good catch, thank you! done :+1:

2021-12-18 18:43 UTC, majk-p commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def build: IORuntime =
Sounds good reasonable. Do you think this should be just based on some mutable bool state or do you have something more sophisticated in mind?

2021-12-18 18:57 UTC, majk-p commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +}
I've added the `builder` to `IORuntime`, although I'd prefer to keep `IORuntimeBuiler` separate for clarity, it's kinda large due to the number of mutation methods. I find the relation with `IORuntimeBuilderPlatform` more straightforward this way.

2021-12-18 19:01 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def build: IORuntime =
Nah, a mutable boolean is fine :)

```suggestion
  def build(): IORuntime =
```

2021-12-18 19:02 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def overrideCompute(compute: ExecutionContext, shutdown: () => Unit = () => ()) = {
Typelevel stuff is cool but probably too over-engineered for this 😆 I was just thinking a runtime exception.

2021-12-18 19:03 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +}
Thanks! Agree about organization; anyway we can decide this in a final bikeshedding :)

2021-12-18 21:04 UTC, majk-p commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def build: IORuntime =
Done

2021-12-18 21:07 UTC, majk-p commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def withComputeWrapper(wrapper: ExecutionContext => ExecutionContext) = {
Much better :wink:

2021-12-18 21:33 UTC, majk-p commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +  def overrideCompute(compute: ExecutionContext, shutdown: () => Unit = () => ()) = {
Done :wink:

2021-12-19 19:07 UTC, armanbilge reviewed
Just some nitpicks, thanks for adding scaladocs for everything :)

Let's give the other maintainers an opportunity to take a look as well.

2021-12-19 19:07 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +    protected var builderExecuted: Boolean = false
I wonder if these should be volatiles or atomics or something, oh the joys of mutable code 😆

2021-12-19 19:07 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +   * Override the defaul computing execution context
```suggestion
   * Set a custom compute pool
```

2021-12-19 19:07 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +   *   execution context for compute
```suggestion
   *   [[ExecutionContext]] for compute
```

2021-12-19 19:07 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +   *   method called upon compute context shutdown
```suggestion
   *   shutdown hook upon [[IORuntime]] shutdown
```

2021-12-19 19:07 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +      throw new RuntimeException("Compute can only be set once")
```suggestion
      throw new IllegalStateException("Compute can be set only once")
```

2021-12-20 07:43 UTC, majk-p commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +   *   execution context for compute
Seems this has actually broken the build, it fails with
>Could not find any member to link
Looks like [fixing this would require a workaround](https://stackoverflow.com/a/23177275/2040487) in build.sbt. Should we go this way or just unlink it?

2021-12-20 11:46 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +   *   execution context for compute
Woops, sorry. `` `ExecutionContext` `` is fine 👍

2021-12-20 12:26 UTC, majk-p commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +   *   execution context for compute
Fixed

2021-12-20 12:33 UTC, majk-p commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +    protected var builderExecuted: Boolean = false
Do you think it's a real case to use builder across multiple threads or something? I'd say it's overengineering at this point :wink:

2021-12-20 12:52 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +    protected var builderExecuted: Boolean = false
I have no idea what people will do :P mostly it feels strange to write public APIs that are not threadsafe (usually we get this for free with immutability). We can leave this for now, it's just a minor thing.

2022-01-31 04:22 UTC, djspiewak requested changes
I finally got to this! Sorry for the delay.

Couple notes, and one bit of bikeshedding: I think we should use `with` rather than `set` for the main build functions. Beyond that, I think this is good. In general, I'd rather see people *not* building custom `IORuntime`s on the regular, but when you need to do it, this is much much nicer than what was previously necessary.

2022-01-31 04:22 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntime.scala
> +  def builder: IORuntimeBuilder =
```suggestion
  def builder(): IORuntimeBuilder =
```

Yay, mutable code!

2022-01-31 04:22 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
> +   * Override the defaul blocking execution context
```suggestion
   * Override the default blocking execution context
```

2022-02-02 20:22 UTC, majk-p commented
Thanks for the feedback @djspiewak! I've made the changes and hopefully also fixed the build :wink:

2022-02-03 20:31 UTC, kubukoz commented
Needs a merge from series/3.x, then headers can be regenerated :)

2022-02-05 18:45 UTC, djspiewak approved these changes

2022-02-05 18:46 UTC, merged