Scalafix Organize Imports
typelevel/cats-effect pull request #2660
Opened 2021-12-17 17:12 UTC by etspaceman

Naturally a ton of file changes. The main ones that changes were made to manually were:

- .scalafix.conf
- build.sbt
- project/Common.scala
- project/CI.scala
- project/plugins.scala

I also had to make a few updates manually to imports to make things work properly. E.g.:

```scala
import org.scalatest.Prop
import Prop.forAll
```

This was not working properly because `import Prop._` would get sent to the top, which would then cause it to no longer be in scope. I updated these types of imports to use fully qualified imports, e.g. `import org.scalatest.Prop.forAll`.

The ordering of the imports is just copied from what I've done in my other projects. The ordering is fully debatable and can be changed to whatever the team here sees fit.

2021-12-17 17:14 UTC, etspaceman commented on .scalafix.conf
> +  groups = [
This organizes imports separated by new lines. E.g.:

```scala
import java.util.CompletableFuture

import scala.concurrent.duration._

import org.openjdk.jmh.annotations._

import cats.Eq
```

2021-12-17 17:26 UTC, vasilmkd commented
Is it possible to configure this? I believe a lot of files in the codebase are doing local imports and dependency imports first, then imports from the `scala.*` standard library and then imports from the `java.*` standard library.

2021-12-17 17:28 UTC, etspaceman commented on .scalafix.conf
> +  groups = [
@vasilmkd this is where the configuration is. We can change it up to whatever you see fit 😄

2021-12-17 17:43 UTC, vasilmkd commented on .scalafix.conf
> +  groups = [
Nice, I think going for `["*", "scala.", "java."]` should give the least diff.

2021-12-17 17:44 UTC, etspaceman commented on .scalafix.conf
> +  groups = [
Do you want the cats dependencies in their own grouping?

2021-12-17 17:45 UTC, etspaceman commented on .github/workflows/ci.yml
> +        run: sbt ++${{ matrix.scala }} scalafixAll --check
Scalafix semanticDb doesn't have support for Scala 3 and thus OrganizeImports wont work. So this will only run the check on 2.13.x

2021-12-17 17:53 UTC, vasilmkd commented on .scalafix.conf
> +  groups = [
On the surface, no, but if it looks particularly nice, why not.

2021-12-17 17:54 UTC, etspaceman commented on .scalafix.conf
> +  groups = [
Where should those be? At the top or bottom?

2021-12-17 18:31 UTC, etspaceman commented on .scalafix.conf
> +  groups = [
Updated to include the sorting you provided. Let me know if you want a different sort

2021-12-17 18:33 UTC, etspaceman commented on .scalafmt.conf
> -  rules = [PreferCurlyFors, RedundantParens, SortImports]
SortImports conflicts with the OrganizeImports so `scalafixAll --check` doesn't work properly in the CI. Removed it here.

2021-12-17 19:20 UTC, vasilmkd commented on .scalafix.conf
> +  groups = [
"scala." in the middle of "*" and "java." will be a smaller diff.

2021-12-17 19:24 UTC, vasilmkd commented on .scalafix.conf
> +  groups = [
Please add a newline at the end of this file as well.

2021-12-17 20:03 UTC, etspaceman commented on build.sbt
> +    cond = Some(s"matrix.scala != '$Scala3' && matrix.os != '$Windows'")
Seem to have a weird exception in the CI on windows machines here. See https://github.com/typelevel/cats-effect/runs/4564105278?check_suite_focus=true

Might be worth opening a bug w/ Scalafix

2021-12-17 20:04 UTC, etspaceman commented on build.sbt
> +    cond = Some(s"matrix.scala != '$Scala3' && matrix.os != '$Windows'")
Also Scala3 would require us to disable the `removeUnused` imports that this plugin offers. After talking w/ @vasilmkd and @armanbilge we decided to disable this check in the Scala 3 CIs.

2021-12-17 20:21 UTC, etspaceman commented on build.sbt
> +    cond = Some(s"matrix.scala != '$Scala3' && matrix.os != '$Windows'")
Created an issue: https://github.com/scalacenter/scalafix/issues/1510

2021-12-19 07:23 UTC, djspiewak requested changes
This is great and thank you for taking this on! One quick bikeshed nit and it's ready for merge.

2021-12-19 07:23 UTC, djspiewak commented on .scalafix.conf
> +  groups = ["cats.", "*", "scala.", "java."]
Quick note: I would generally remove the leading `"cats."` here. It's something of a coincidence that those imports tend to come first, stemming from the fact that `ca` is alphabetically ordered before almost any other plausible top level package names. Beyond that, this looks like what I would (subjectively!) want!

2021-12-19 07:23 UTC, djspiewak commented
Oh actually, additional idea: can you add this to the `prePR` alias? That alias already runs scalafmt, so it would be helpful if it could also run the import organization.

2021-12-19 13:09 UTC, etspaceman commented on .scalafix.conf
> +  groups = ["cats.", "*", "scala.", "java."]
Yep, can do. I'll do that when I get a chance.

2021-12-19 13:10 UTC, etspaceman commented on build.sbt
> +  "; root/clean; root/scalafixAll; scalafmtSbt; +root/scalafmtAll; +root/headerCreate")
@djspiewak The scalafix command was added to prePR.

2021-12-19 14:51 UTC, etspaceman commented on .scalafix.conf
> +  groups = ["cats.", "*", "scala.", "java."]
This is done

2021-12-19 17:33 UTC, djspiewak requested changes
Ah! I misunderstood how this config works. Also scanned through and I'm going to bikeshed some more…

- Is there a way to make it group by top-level package? It seems that `*` just lumps everything together, as opposed to splitting apart (e.g.) `cats` from `org`
- We should add `javax.` to the end of the list. I forgot about that one!

The ideal would be something like this:

```scala
import cats.{Functor, Monad}
import cats.effect.IO
import cats.effect.kernel.Resource
import cats.effect.syntax.all._

import org.thingy.Wut

import sun.misc.Unsafe

import scala.collection.immutable

import java.util.Collection

import javax.swing.JFrame
```

2021-12-19 17:40 UTC, etspaceman commented
We could do that as long as we are explicit about it. E.g. "org.", "com.", etc. The rule also allows for regex groups. fwiw. 

We can also control the newlines, so we can have pretty fine tuned control. 

https://github.com/liancheng/scalafix-organize-imports#221-value-type

Feel free to play around with the PR to test out different configurations. Fair warning, when changing the config locally, I've often had to run it 2x for the compile to work properly. Not sure why. But once it's run successfully on all files, the rule works seamlessly going forward.

2021-12-19 21:07 UTC, etspaceman commented
@djspiewak I tried to capture all of the top-level packages explicitly in the config. LMK what you think.

2021-12-19 21:08 UTC, etspaceman commented on .scalafix.conf
> +  importsOrder = SymbolsFirst
SymbolsFirst matches what scalafmt was doing. The default for this plugin is Ascii, which is why some of the sorting changed on the initial runs.

2021-12-19 21:09 UTC, etspaceman commented on .scalafmt.conf
> -  rules = [PreferCurlyFors, RedundantParens, SortImports]
Technically we should be able to add this back but I'm going to keep it out because we are now controlling this through scalafix

2021-12-20 16:23 UTC, djspiewak commented on .scalafix.conf
> +  importsOrder = SymbolsFirst
Odd. Scanning through the diff, it seems that symbols are still being sorted last, not first. Am I missing something?

2021-12-20 16:26 UTC, etspaceman commented on .scalafix.conf
> +  importsOrder = SymbolsFirst
I was a bit confused too. There's another option that I think I have to set to be the same: `importSelectorsOrder`. I'll set that here and push a change.

2021-12-20 17:54 UTC, djspiewak commented on .scalafix.conf
> +  importsOrder = SymbolsFirst
That looks much better!

2021-12-20 17:54 UTC, djspiewak approved these changes

2021-12-20 17:54 UTC, merged