Add tryTakeN, tryTakeFrontN, tryTakeBackN to Queue and Dequeue
typelevel/cats-effect pull request #2670
Opened 2021-12-19 22:15 UTC by etspaceman

Solves #2637

TODO
- [ ] Add tests

2021-12-19 22:19 UTC, armanbilge commented
👍 to the methods, but my 2 cents is we should add them as syntax extensions so we don't have to break binary compatibility.

2021-12-19 22:24 UTC, etspaceman commented
I can certainly do that. @djspiewak WDYT?

2021-12-20 03:15 UTC, djspiewak commented
Actually I think we can keep them on the main trait, we just have to define the default (naive) implementations there. We can't add new *abstract* members, but we can add new concrete ones.

2021-12-20 03:16 UTC, armanbilge commented
Oh, is the "naive" implementation just `N = 1`? That works.

2021-12-20 03:18 UTC, armanbilge commented
Except, I don't think that's possible. Because we can't get to a `List` without `map`ping, but we don't have `Functor` unless I'm missing something.

2021-12-20 14:14 UTC, etspaceman commented
The implementation i designed requires a Monad for tailRecM, which i wouldn't have on the trait.

2021-12-20 15:49 UTC, etspaceman commented
I have moved the methods to a syntax area per this discussion

2021-12-20 15:50 UTC, etspaceman commented on std/shared/src/main/scala/cats/effect/std/syntax/package.scala
> +  object backpressure extends BackpressureSyntax
I noticed BackpressureSyntax didn't have an associated object so I created one here.

2021-12-20 16:15 UTC, armanbilge commented
Sorry, after looking at your changes I just realized what Daniel may have been getting at. We _can_ actually define the methods on the trait by requiring the additional constraints, exactly as you've done for the syntax extensions:
```scala
  def tryTakeBackN(maxN: Option[Int])(implicit F: Monad[F]): F[Option[List[A]]] = 
    _tryTakeN(maxN)(wrapped.tryTakeBack)
```

This is probably nicer 🙃

2021-12-20 16:16 UTC, etspaceman commented
Ok, can do

2021-12-20 16:46 UTC, etspaceman commented
Alright I think this is at a pretty good point. LMK what you think @djspiewak @armanbilge

2021-12-20 22:00 UTC, etspaceman commented
Per a conversation w/ @djspiewak I added tryOfferN/tryOfferFrontN/tryOfferBackN methods as well.

2022-01-01 03:50 UTC, djspiewak requested changes
Minor issue and then good to go. The inconsistency in the constraints on the methods is unfortunate but unavoidable, and it's better than a `Queue2` or something equally hideous.

2022-01-01 03:50 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/Dequeue.scala
> +   * any additional performatnce benefits.
```suggestion
   * any additional performance benefits.
```

There are a couple of these :-)

2022-01-01 19:46 UTC, etspaceman commented on std/shared/src/main/scala/cats/effect/std/Dequeue.scala
> +   * any additional performatnce benefits.
Fixed

2022-01-01 20:21 UTC, djspiewak approved these changes

2022-01-01 20:24 UTC, etspaceman commented
CI seems to have failed due to an unrelated test, undeterministically:

```
[error]   x exit on fatal error with other unsafe runs
[error]    java.lang.InterruptedException
[error]    	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326)
[error]    	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
[error]    	at cats.effect.IOPlatform.$anonfun$unsafeRunTimed$2(IOPlatform.scala:81)
[error]    	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
[error]    	at cats.effect.unsafe.WorkerThread.blockOn(WorkerThread.scala:572)
[error]    	at scala.concurrent.package$.blocking(package.scala:124)
[error]    	at cats.effect.IOPlatform.unsafeRunTimed(IOPlatform.scala:81)
[error]    	at cats.effect.IOPlatform.unsafeRunSync(IOPlatform.scala:42)
[error]    	at catseffect.examples.FatalErrorUnsafeRun$.$anonfun$run$3(examplesplatform.scala:42)
[error]    	at cats.effect.unsafe.WorkerThread.blockOn(WorkerThread.scala:607)
[error]    	at scala.concurrent.package$.blocking(package.scala:124)
[error]    	at cats.effect.IOFiber.runLoop(IOFiber.scala:948)
[error]    	at cats.effect.IOFiber.execR(IOFiber.scala:1293)
[error]    	at cats.effect.IOFiber.run(IOFiber.scala:123)
[error]    	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:530) doesn't contain 'Boom!' (IOAppSpec.scala:217)
```

2022-01-01 20:27 UTC, djspiewak commented
Oh this is fun. I think this is a race condition with the interruption handling in the worker threads.

2022-01-01 21:05 UTC, merged