IOFiber - Auxiliary methods.
typelevel/cats-effect pull request #2708
Opened 2021-12-31 18:47 UTC by diesalbla

Introduce a factory `spawnFiber` method, to create new IOFiber objects for the `Start` and `Race` cases. This factory uses the localState, execution context, and runtime, of this fiber.

From the `scheduleFiber` method remove the "ec" parameter. It seems that the `currentCtx` is always used, and it is not modified from load to call.

2021-12-31 20:28 UTC, djspiewak requested changes

2021-12-31 20:28 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +  @inline
This is ignored btw and doesn't need to be here

2021-12-31 20:28 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +  @inline
Also unnecessary

2021-12-31 20:28 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +  private[this] def runtimeRun(io: IO[Any]): Unit =
Not to bikeshed too much, but I think this might be better-named something like `initRunLoop`

2021-12-31 20:34 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
>      }
@djspiewak You made me explicitly switch to the isInstanceOf/asInstanceOf style once. Is that still desirable?

2021-12-31 20:57 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
>      }
Oh, good catch! I missed that. Yes, I would prefer the explicit style here because we're less reliant on how pattern matching is encoded, and the JVM optimization is a bit fragile sometimes.

2022-01-01 03:51 UTC, djspiewak commented
```
[error] /home/runner/work/cats-effect/cats-effect/core/shared/src/main/scala/cats/effect/IOFiber.scala:630:23: local val ec in method loop is never used
62
[error]                   val ec = currentCtx
63
[error]                       ^
64
```

Warnings are fatal in CI and non-fatal locally. :-)

2022-01-01 13:45 UTC, vasilmkd approved these changes, later dismissed
Nice cleanup. Thanks for tackling this.

2022-01-01 16:36 UTC, vasilmkd commented
Can we target this at `series/3.3.x` instead? And the follow up PR.

2022-01-01 19:19 UTC, diesalbla commented
> Can we target this at series/3.3.x instead? And the follow up PR. 

Done.

2022-06-16 04:11 UTC, closed without merging