Handle interruption around blocking waits
typelevel/cats-effect pull request #2724
Opened 2022-01-02 09:16 UTC by vasilmkd

Resolves #2720.

Removes code that captures mutable variables and volatile at that, for which the Scala runtime has specific classes (`VolatileMutableReference` or something similar, TIL).

2022-01-06 16:58 UTC, djspiewak requested changes
The use of the `Queue` is super nice honestly. I never thought of doing it that way. Some quick comments on the interrupted `poll` cases but otherwise this looks good to me!

2022-01-06 16:58 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/IOApp.scala
> +          counter.decrementAndGet()
TIL `decrement` isn't a method on `AtomicInteger.

2022-01-06 16:58 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/IOApp.scala
> +          case _: InterruptedException =>
Won't this happen in Sbt if someone hits Ctrl-C repeatedly? I mean, if the interruption were working *at all* in Sbt, which it isn't.

2022-01-06 16:58 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/IOApp.scala
> +            s"result is null but is interrupted? ${Thread.currentThread().isInterrupted()}")
Debug code? Feels like this case should be handled similarly to the `catch { case _: InterruptedException => ...}` below.

2022-01-07 21:45 UTC, vasilmkd commented on core/jvm/src/main/scala/cats/effect/IOApp.scala
> +          case _: InterruptedException =>
What do you suggest should be done here? No `catch` at all?

2022-01-07 21:47 UTC, vasilmkd commented on core/jvm/src/main/scala/cats/effect/IOApp.scala
> +            s"result is null but is interrupted? ${Thread.currentThread().isInterrupted()}")
Yes. I had a bug in my original implementation because I accidentally called `queue.poll()` instead of `queue.take()` and I was getting strange `null` results because `poll` is non-blocking and returns `null` if the queue is empty. I forgot to remove this code.

2022-01-07 22:36 UTC, vasilmkd commented on core/jvm/src/main/scala/cats/effect/IOApp.scala
> +          case _: InterruptedException =>
I removed it. This matches the previous behavior.

2022-01-08 22:17 UTC, djspiewak approved these changes

2022-01-08 22:17 UTC, merged