Workaround for dotty#14240
typelevel/cats-effect pull request #2743
Opened 2022-01-10 16:56 UTC by armanbilge

Reported by @mn98. This turned out to be a Scala 3 bug reported in https://github.com/lampepfl/dotty/issues/14240, but we can code defensively around it in the mean time.

2022-01-10 16:57 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/ExitCode.scala
> +  override def hashCode = code
I cheated on this one. If we really care about keeping this stable, I can figure out what's supposed to go here.

2022-01-10 17:58 UTC, djspiewak submitted a review, later dismissed
This is really annoying :-( As long as mima blesses it though I think we'll be okay.

2022-01-10 17:58 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/ExitCode.scala
> +  def unapply(ec: ExitCode): Option[Int] = Some(ec.code)
```suggestion
  def unapply(ec: ExitCode): Some[Int] = Some(ec.code)
```

This way we keep exhaustiveness checking

2022-01-10 18:27 UTC, vasilmkd commented on core/shared/src/main/scala/cats/effect/ExitCode.scala
> +  override def hashCode = code
As a wrapper of an integer, this is ok.

2022-01-10 18:28 UTC, vasilmkd requested changes
Just Daniel's suggestion.

2022-01-10 19:01 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/ExitCode.scala
> +  def unapply(ec: ExitCode): Option[Int] = Some(ec.code)
This is how I did it at first, but mima complained actually. So I have no idea if/how we are getting exhaustive checking right now, maybe not at the bytecode level 🤔

2022-01-10 19:31 UTC, armanbilge commented
Actually, hang on. The lack of exhaustivity check would be source-breaking, and quite frankly annoying. This is no good. I wonder if we can work around it.

2022-01-10 20:07 UTC, armanbilge commented on core/shared/src/main/scala-3/cats/effect/ExitCode.scala
> +  def unapply(ec: ExitCode): Some[Int] = Some(ec.code)
Bincompat is so much more fun on Scala 3 :)

2022-01-10 20:16 UTC, armanbilge commented
@djspiewak we really need that sbt-spiewak release with mima for Scala 3 enabled ... 

I manually added:
```scala
mimaPreviousArtifacts += "org.typelevel" %%% "cats-effect" % "3.3.4",
```

Not only did I miss the `_1` method, it seems the `unapply` encoding on Scala 3 actually doesn't use `Option` at all?

```
[error] cats-effect: Failed binary compatibility check against org.typelevel:cats-effect_3:3.3.4! Found 3 potential problems
[error]  * static method unapply(cats.effect.ExitCode)cats.effect.ExitCode in class cats.effect.ExitCode has a different result type in current version, where it is scala.Option rather than cats.effect.ExitCode
[error]    filter with: ProblemFilters.exclude[IncompatibleResultTypeProblem]("cats.effect.ExitCode.unapply")
[error]  * method _1()Int in class cats.effect.ExitCode does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("cats.effect.ExitCode._1")
[error]  * method unapply(cats.effect.ExitCode)cats.effect.ExitCode in object cats.effect.ExitCode has a different result type in current version, where it is scala.Option rather than cats.effect.ExitCode
[error]    filter with: ProblemFilters.exclude[IncompatibleResultTypeProblem]("cats.effect.ExitCode.unapply")
[error] stack trace is suppressed; run last coreJVM / mimaReportBinaryIssues for the full output
[error] (coreJVM / mimaReportBinaryIssues) Failed binary compatibility check against org.typelevel:cats-effect_3:3.3.4! Found 3 potential problems
```

2022-01-12 01:16 UTC, armanbilge commented
Forgot to indicate ready-for-review :)

2022-01-14 00:56 UTC, vasilmkd requested changes
Here's more on how `unapply` and pattern matching has changed in Scala 3. https://docs.scala-lang.org/scala3/reference/changed-features/pattern-matching.html

And they say Scala 3 is not a new language.

2022-01-14 00:56 UTC, vasilmkd commented on core/shared/src/main/scala-3/cats/effect/ExitCode.scala
> +    with Serializable {
I wouldn't object if the new syntax was used in this file.

2022-01-14 00:56 UTC, vasilmkd commented on core/shared/src/main/scala-3/cats/effect/ExitCode.scala
> +import scala.annotation.targetName
This might be unused. Please double check.

2022-01-14 00:56 UTC, vasilmkd commented on core/shared/src/main/scala-3/cats/effect/ExitCode.scala
> +  def productElement(n: Int): Any = if (n == 0) code else throw new NoSuchElementException
The quirks of Scala 3. Scala 3 supports creating instances of objects without the `new` keyword, but it can't do it in this case because it cannot see through the `type NoSuchElementException = java.util.NoSuchElementException` alias. It works if you import it, which is whatever.

More on the subject https://docs.scala-lang.org/scala3/reference/other-new-features/creator-applications.html.

2022-01-14 01:13 UTC, armanbilge commented on core/shared/src/main/scala-3/cats/effect/ExitCode.scala
> +    with Serializable {
Our scalac options like the braces I think.

2022-01-14 01:14 UTC, armanbilge commented on core/shared/src/main/scala-3/cats/effect/ExitCode.scala
> +import scala.annotation.targetName
Good catch, no unused warnings :(

2022-01-14 23:51 UTC, vasilmkd commented on core/shared/src/main/scala-3/cats/effect/ExitCode.scala
> +    with Serializable {
Does `fs2` have Scala 3 specific sources with the new syntax or did I misremember something. If we're not set up for it in `cats-effect`, this change is not worth that.

2022-01-14 23:53 UTC, armanbilge commented on core/shared/src/main/scala-3/cats/effect/ExitCode.scala
> +    with Serializable {
I mean, I hope the split sources are only temporary until the bug is fixed. But wishful thinking maybe :)

2022-01-14 23:56 UTC, vasilmkd commented on .scalafmt.conf
> +}
Does this do anything? Genuine question.

2022-01-14 23:57 UTC, armanbilge commented on .scalafmt.conf
> +}
`scalafmt` raises a warning without it.

2022-01-15 00:02 UTC, vasilmkd approved these changes

2022-01-15 17:20 UTC, djspiewak approved these changes

2022-01-15 17:20 UTC, merged