Add IO.rethrow and IO.debug
typelevel/cats-effect pull request #2757
Opened 2022-01-14 15:59 UTC by BalmungSan

IMHO they both come in handy, especially when using concrete `IO` which many newcomers do.

Let me know if I could have done better in the **Scaladoc** comments or in the tests :)

2022-01-14 16:12 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +   * IO.pure(3).attempt.rethrow.unsafeRunSync() === 3
Maybe the example should be more like `IO(Left(ex)).rethrow`? So that you don't need to know the signature of `attempt`, and also the `A <:< Either[Throwable, B]` is difficult to know what that means exactly.

2022-01-14 16:19 UTC, BalmungSan commented on core/shared/src/main/scala/cats/effect/IO.scala
> +   * IO.pure(3).attempt.rethrow.unsafeRunSync() === 3
> So that you don't need to know the signature of attempt

Yeah, I also thought about it but then what should be after the `===`? A `throw ex`?

> and also the A <:< Either[Throwable, B] is difficult to know what that means exactly.

Not sure what you mean? Like that, I should add a comment note?

2022-01-14 16:25 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +   * IO.pure(3).attempt.rethrow.unsafeRunSync() === 3
Maybe?
```
IO(Right(a)).rethrow === IO.pure(a)
IO(Left(ex)).rethrow === IO.raiseError(ex)
```

> Not sure what you mean? Like, should I add a comment note? or what?

Sorry, I meant this is another good reason to have an example that specifically demonstrates the use of `Either`, because it is not straightforward to understand from the method signature that it has to be an `IO[Either[Throwable, A]]`.

2022-01-14 16:45 UTC, BalmungSan commented on core/shared/src/main/scala/cats/effect/IO.scala
> +   * IO.pure(3).attempt.rethrow.unsafeRunSync() === 3
@armanbilge ahhh makes sense, thanks for the snippets; I just pushed an update.

2022-01-14 17:15 UTC, BalmungSan commented
Uhm the failing tests doesn't look like my fault, does it?

2022-01-14 23:29 UTC, vasilmkd commented
I'm asking from a user experience perspective, the printout of `debug` has a `Left/Right` wrapping around the result, which is not necessarily a part of the type signature. I wonder if a pattern match on the result of `attempt` and then printing out the vanilla result or the throwable is a better experience. Otherwise I quite like this change.

2022-01-15 00:54 UTC, BalmungSan commented
@vasilmkd yeah, I was thinking the same when I wrote the function, I was just worried that doing too much for a quick debug method was not worth it and may encourage users to use it for real logging _(because originally I thought of including things like thread name and timestamp)_

However, on second thought, a simple prefix like `Success: ${a}` and `Failure: ${ex.getMessage}` may be good enough.
What do you think?

2022-01-15 16:27 UTC, wemrysi commented
> However, on second thought, a simple prefix like Success: ${a} and Failure: ${ex.getMessage} may be good enough.
What do you think?

I think a prefix would be helpful for communicating the outcome at-a-glance (especially for values like `IO[Unit]`) 👍  Speaking of outcome, how about `Succeeded: ${a}` and `Errored: ${ex}` to be consistent with the cases in `Outcome` and include the name of the `Throwable` (as sometimes messages aren't terribly meaningful out of context)?

2022-01-15 17:17 UTC, djspiewak requested changes
Honestly both of these are fantastic. Couple thoughts.

1. Echoing @wemrysi's suggestion of following `Outcome`'s vernacular to render results. Though, there shouldn't be a situation where you render `Canceled`. To that end, this should also be implementable without the extra boxing of `attempt` (by relying on `flatTap` and `handleErrorWith`).
2. Might be worth looking at Fs2's `Stream#debug` function, which provides some extra configurability for the prefix (for everyone who likes to `println(">>>> THE THING HERE")`) and such

2022-01-15 17:17 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  def debug: IO[A] =
```suggestion
  def debug(implicit A: Show[A] = Show.fromToString): IO[A] =
```

Just to be consistent with `IO.println` and to give extra flexibility on the `A` rendering.

2022-01-16 17:16 UTC, BalmungSan commented
@vasilmkd @wemrysi @djspiewak

Hey all, sorry for the delay.
I just pushed a couple of changes regarding `debug`, I hope you like them :)
Let me know if you think there is something else that may be done.

Also, do you know if it is possible _(and worth it)_ to test `debug`?

2022-01-17 02:01 UTC, djspiewak approved these changes
Very nice! Also I don't see a need to test `debug`. It's basically just `println` :-P

2022-01-17 02:01 UTC, merged