Configurable caching of blocking threads
typelevel/cats-effect pull request #2773
Opened 2022-01-24 00:23 UTC by vasilmkd

I invite you to bikeshed on the JVM property name.

2022-01-24 15:26 UTC, rossabaker commented
Is it assumed that system properties are all read at startup?  Unlike environment variables, which are theoretically mutable, system properties are certainly mutable.

2022-01-24 16:21 UTC, djspiewak commented
They're read when `IORuntimeConfig` is classloaded.

2022-01-31 03:00 UTC, djspiewak requested changes
I like this quite a bit, but I do think we should split it away from JavaScript. It's kind of a pain to have these split APIs, but we've been trying to follow a paradigm of keeping things fairly independent and not foisting APIs on JS which don't make sense on that platform.

2022-01-31 03:00 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeConfigCompanionPlatform.scala
> +      Try(System.getProperty("cats.effect.blocking.cache.expiration"))
We should probably start thinking of namespaces a bit more hierarchically. Maybe `cats.effect.runtime.blocking.expiration`? Bikeshedding is hard.

2022-02-01 15:44 UTC, djspiewak approved these changes

2022-02-01 15:44 UTC, djspiewak commented
Btw we'll need to document this, but it's good enough to just get it in for now. The properties documentation is kind of bad right now.

2022-02-01 15:44 UTC, merged