Add documentation to IO.blocking, IO.interruptible, IO.interruptibleMany
typelevel/cats-effect pull request #2805
Opened 2022-02-02 16:09 UTC by kamilkloch

Copy & paste of Sync#blocking docs, with small modfications.

2022-02-04 15:21 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +   * use [[interruptible]] or [[interruptibleMany]].
Unfortunately it seems scaladoc doesn't like `[[interruptible]]` b/c there's two methods named `interruptible` and it doesn't know which to link.

2022-02-04 16:06 UTC, vasilmkd commented on core/jvm/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +   * use [[interruptible]] or [[interruptibleMany]].
There is a way to disambiguate but I'm never sure how to do it exactly. I think this might be helpful and there should also exist a page for Scala 2 but I cannot find it at the moment.

https://docs.scala-lang.org/scala3/guides/scaladoc/linking.html

2022-02-05 17:55 UTC, djspiewak requested changes
This looks like a really good start, thank you!

Once the `IO` docs are done, can we copy them over to `Sync` as well? Also IIRC there's a way to inherit scaladoc between members to avoid redundancy, but I can't remember how that works exactly.

2022-02-05 17:55 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +   * Note that the created effect will be uncancelable; if you need cancellation then you should
Minor nit, but we tend to use the alternative spelling, "cancelation".

```suggestion
   * Note that the created effect will be uncancelable; if you need cancelation then you should
```

2022-02-05 17:55 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +   * in the event of cancellation. The interrupt will be attempted only once.
```suggestion
   * in the event of cancelation. The interrupt will be attempted only once.
```

2022-02-05 17:55 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +   * Like [[blocking]] but will attempt to abort the blocking operation using thread interrupts
It might be worth tossing some notes on here about the tradeoffs. Specifically, I would note the following two caveats:

- This has slightly more overhead than `blocking` due to the machinery necessary for the interrupt coordination
- Thread interrupts are very often poorly considered by Java (and Scala!) library authors, and it is possible for interrupts to result in resource leaks or invalid states. It's important to be certain that this will *not* be the case before using this mechanism.

2022-02-05 17:55 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +   * operation completes or exits.
```suggestion
   * in the event of cancelation. The interrupt will be attempted repeatedly until the blocking
   * operation completes or exits.
```

I might also say a few words about *why* this exists. In particular, noting that library authors tend to handle interruption incorrectly, and they may set up a situation where they suppress an interrupt unintentionally (e.g. by catching `Throwable` or even `Exception`) and then resume their work. Repeatedly interrupting is one workaround for this situation, though it does come at a cost, since a *second* blocking thread must be tied down in a hot `while` loop just calling `interrupt()` repeatedly, so the overhead of this effect is relatively high and should only be used in situations where there are no other options.

2022-02-05 18:01 UTC, armanbilge commented
> Also IIRC there's a way to inherit scaladoc between members to avoid redundancy, but I can't remember how that works exactly.

I think we could take advantage of this if the companion objects for `IO` and `SyncIO` inherited directly from the `Async` and `Sync` typeclasses. We'd also get a lot of currently duplicated methods for free.

2022-02-07 10:41 UTC, kamilkloch commented on core/jvm/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +   * use [[interruptible]] or [[interruptibleMany]].
I tried `[[interruptible[A](=>A):IO[A]*]]`, but it did not help. I give up.

2022-02-07 11:10 UTC, kamilkloch commented on core/jvm/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +   * use [[interruptible]] or [[interruptibleMany]].
@vasilmkd Could you check if this works in VSCode?  Here is the scaladoc cheatsheeet: https://github.com/scala/scala/blob/2.12.x/test/scaladoc/resources/links.scala

2022-02-07 11:42 UTC, kamilkloch commented on core/jvm/src/main/scala/cats/effect/IOCompanionPlatform.scala
> +   * Like [[blocking]] but will attempt to abort the blocking operation using thread interrupts
@djspiewak I basically added the above comment, please take a look.

2022-02-07 12:44 UTC, kamilkloch commented
> > Also IIRC there's a way to inherit scaladoc between members to avoid redundancy, but I can't remember how that works exactly.
> 
> I think we could take advantage of this if the companion objects for `IO` and `SyncIO` inherited directly from the `Async` and `Sync` typeclasses. We'd also get a lot of currently duplicated methods for free.

A great idea, in general. The burden of syncing documentation across two separate locations would go away.

2022-03-14 05:42 UTC, djspiewak approved these changes

2022-03-14 05:42 UTC, merged