Use Java release option
typelevel/cats-effect pull request #2825
Opened 2022-02-16 09:57 UTC by vasilmkd

Examples incoming. I will edit this comment.

2022-02-16 10:28 UTC, armanbilge commented
Seems like fs2 could benefit from this?

2022-02-16 10:39 UTC, vasilmkd commented
The first example in Scala:

```scala
package io.vasilev

import java.lang.invoke.{MethodHandles, VarHandle}

object VarHandles {

  @volatile private[this] var n: Int = 0

  private[this] final val N: VarHandle = MethodHandles.lookup().findVarHandle(classOf[VarHandles.type], "n", classOf[Int])
}

```

```sh
scalac io/vasilev/VarHandles.scala --release 8
-- [E006] Not Found Error: io/vasilev/VarHandles.scala:9:29 --------------------
9 |  private[this] final val N: VarHandle = MethodHandles.lookup().findVarHandle(classOf[VarHandles.type], "n", classOf[Int])
  |                             ^^^^^^^^^
  |                             Not found: type VarHandle

longer explanation available when compiling with `-explain`
-- [E008] Not Found Error: io/vasilev/VarHandles.scala:9:64 --------------------
9 |  private[this] final val N: VarHandle = MethodHandles.lookup().findVarHandle(classOf[VarHandles.type], "n", classOf[Int])
  |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |value findVarHandle is not a member of java.lang.invoke.MethodHandles#Lookup
2 errors found
```

2022-02-16 10:46 UTC, vasilmkd commented
@mpilquist

2022-02-16 11:00 UTC, vasilmkd commented
And with this, I will be deleting JDK 8 from my machine.

2022-02-16 11:57 UTC, vasilmkd commented
https://github.com/scala/scala/pull/6362

2022-02-16 13:05 UTC, mpilquist commented
I don’t think this helps with fs2 where we us newer JDK APIs but want a JAR that’s 8 compatible. It should work for scodec though.

2022-02-21 19:34 UTC, djspiewak requested changes
This is super impressive! Two concerns. First, can we sanity-check the `ByteBuffer` scenario on Scala 2 as well as Scala 3? Or did you already do that and I missed it? Second, I'd rather see this done as a one-off autoplugin rather than a `settings` val like this.

2022-02-21 19:34 UTC, djspiewak commented on build.sbt
> +lazy val releaseSettings = Seq(
This can be achieved more easily by tossing a one-off autoplugin into `project/`

2022-02-21 19:34 UTC, djspiewak commented on build.sbt
> +    javacOptions ++= {
IMO we should add these to the aforementioned autoplugin and apply them to all projects just so we don't accidentally forget to add them in the future.

2022-02-21 19:36 UTC, vasilmkd commented
@djspiewak Please read the first post carefully. ByteBuffer is covered.

2022-02-21 19:37 UTC, djspiewak commented
@vasilmkd I was mostly concerned about Scala 2, since the OP output looks more like Scala 3's error messages and they have two different backends. If both have been sanity checked though I'm very strongly :+1:

2022-02-21 19:37 UTC, vasilmkd commented
I'll post Scala 2 too.

2022-02-21 19:45 UTC, vasilmkd commented
# Scala 2
## Example 1

```scala
package io.vasilev

import java.lang.invoke.{ MethodHandles, VarHandle }

object VarHandles {

  @volatile private[this] var n: Int = 0

  private[this] final val N: VarHandle = MethodHandles.lookup().findVarHandle(classOf[VarHandles.type], "n", classOf[Int])
}
```

```sh
scalac io/vasilev/VarHandles.scala --release 8 
io/vasilev/VarHandles.scala:3: error: object VarHandle is not a member of package invoke
import java.lang.invoke.{ MethodHandles, VarHandle }
       ^
io/vasilev/VarHandles.scala:9: error: not found: type VarHandle
  private[this] final val N: VarHandle = MethodHandles.lookup().findVarHandle(classOf[VarHandles.type], "n", classOf[Int])
                             ^
io/vasilev/VarHandles.scala:9: error: value findVarHandle is not a member of java.lang.invoke.MethodHandles.Lookup
  private[this] final val N: VarHandle = MethodHandles.lookup().findVarHandle(classOf[VarHandles.type], "n", classOf[Int])
                                                                ^
3 errors
```

---
## Example 2

```scala
package io.vasilev

import java.nio.ByteBuffer

object Buffers {
  private[this] final val buffer: ByteBuffer = ByteBuffer.allocate(16)

  val flipped: ByteBuffer = buffer.flip()
}
```

```sh
scalac io/vasilev/Buffers.scala --release 8
io/vasilev/Buffers.scala:8: error: type mismatch;
 found   : java.nio.Buffer
 required: java.nio.ByteBuffer
  val flipped: ByteBuffer = buffer.flip()
                                       ^
1 error
```

---
## Example 3

```scala
package io.vasilev

import java.nio.ByteBuffer

object Buffers {
  private[this] final val buffer: ByteBuffer = ByteBuffer.allocate(16)

  buffer.flip()
}
```

1. Compiling without `-release 8` on JDK 17
```sh
scalac io/vasilev/Buffers.scala
javap -p -c io.vasilev.Buffers\$
Compiled from "Buffers.scala"
public final class io.vasilev.Buffers$ {
  public static final io.vasilev.Buffers$ MODULE$;

  private static final java.nio.ByteBuffer buffer;

  public static {};
    Code:
       0: new           #2                  // class io/vasilev/Buffers$
       3: dup
       4: invokespecial #14                 // Method "<init>":()V
       7: putstatic     #16                 // Field MODULE$:Lio/vasilev/Buffers$;
      10: bipush        16
      12: invokestatic  #22                 // Method java/nio/ByteBuffer.allocate:(I)Ljava/nio/ByteBuffer;
      15: putstatic     #24                 // Field buffer:Ljava/nio/ByteBuffer;
      18: getstatic     #24                 // Field buffer:Ljava/nio/ByteBuffer;
      21: invokevirtual #28                 // Method java/nio/ByteBuffer.flip:()Ljava/nio/ByteBuffer; <------- notice the new JDK 9+ method with overloaded return type, which cannot be called on JDK 8.
      24: pop
      25: return

  private io.vasilev.Buffers$();
    Code:
       0: aload_0
       1: invokespecial #29                 // Method java/lang/Object."<init>":()V
       4: return
}
```

2. Compiling with `-release 8` on JDK 17
```sh
scalac io/vasilev/Buffers.scala -release 8
javap -p -c io.vasilev.Buffers\$
Compiled from "Buffers.scala"
public final class io.vasilev.Buffers$ {
  public static final io.vasilev.Buffers$ MODULE$;

  private static final java.nio.ByteBuffer buffer;

  public static {};
    Code:
       0: new           #2                  // class io/vasilev/Buffers$
       3: dup
       4: invokespecial #14                 // Method "<init>":()V
       7: putstatic     #16                 // Field MODULE$:Lio/vasilev/Buffers$;
      10: bipush        16
      12: invokestatic  #22                 // Method java/nio/ByteBuffer.allocate:(I)Ljava/nio/ByteBuffer;
      15: putstatic     #24                 // Field buffer:Ljava/nio/ByteBuffer;
      18: getstatic     #24                 // Field buffer:Ljava/nio/ByteBuffer;
      21: invokevirtual #28                 // Method java/nio/ByteBuffer.flip:()Ljava/nio/Buffer; <------ notice that scalac used the JDK 8 compatible method
      24: pop
      25: return

  private io.vasilev.Buffers$();
    Code:
       0: aload_0
       1: invokespecial #29                 // Method java/lang/Object."<init>":()V
       4: return
}
```

2022-02-21 19:56 UTC, djspiewak commented
Honestly outstanding! I think this means I can delete Java 8

2022-02-21 19:57 UTC, armanbilge commented
> Second, I'd rather see this done as a one-off autoplugin rather than a settings val like this.

*cough* sbt-typelevel *cough* 😝

2022-02-21 20:01 UTC, djspiewak commented
> cough sbt-typelevel cough 😝

:-D It's on my "to peruse" list. Still digging out from under everything else for the time being though.

2022-02-21 20:03 UTC, vasilmkd commented on project/Java8Target.scala
> +        if (version.startsWith("1.8"))
Let's factor this out as it is repeated:
`val isJdk8: Boolean = System.getProperty("java.version").startsWith("1.8")`

2022-03-09 18:16 UTC, vasilmkd commented
Superseded by #2857.

2022-03-09 18:17 UTC, closed without merging