Indicate a completed state in IOFiber#toString
typelevel/cats-effect pull request #2829
Opened 2022-02-16 17:49 UTC by iRevive

My naive implementation of https://github.com/typelevel/cats-effect/issues/2628. 

When fiber is completed, the stack trace events are not available anymore. 
Technically, there is room for premature optimization:
```scala
val hash = System.identityHashCode(this).toHexString
if (isDone) {
  s"cats.effect.IOFiber@$hash COMPLETED"
} else {
  val state = if (suspended.get()) "SUSPENDED" else "RUNNING"

  val opAndCallSite =
    Tracing.getFrames(tracingEvents).headOption.map(frame => s": $frame").getOrElse("")

   s"cats.effect.IOFiber@$hash $state$opAndCallSite"
}
```

But I don't think it's worth it.

2022-02-21 19:04 UTC, djspiewak requested changes
This looks super-great! Aside from the minor nit, I think it's ready to go!

2022-02-21 19:04 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +  private def isDone: Boolean =
Minor nit: `private[this]` would be preferred for this type of thing, since it will inline better.

2022-02-21 19:09 UTC, armanbilge commented
In the original issue I made a note https://github.com/typelevel/cats-effect/issues/2628#issuecomment-986169842 that this needs to be changed in a couple places, besides `toString`.

I think for this change to take effect for fiber dumps we need to change it somewhere in here too:
https://github.com/typelevel/cats-effect/blob/f423ac754fecdf563cc60b4ed4800374ff80c251/core/jvm/src/main/scala/cats/effect/unsafe/FiberMonitor.scala#L93

And also for JS.

2022-02-21 19:12 UTC, armanbilge commented
Actually, maybe the change should be here:
https://github.com/typelevel/cats-effect/blob/f423ac754fecdf563cc60b4ed4800374ff80c251/core/shared/src/main/scala/cats/effect/unsafe/FiberMonitorShared.scala#L26-L31

If the fiber is done it can ignore the provided status `String`.

2022-02-21 19:36 UTC, djspiewak commented
@armanbilge Don't we already have something somewhere which puts the fiber status onto dumps? I thought we had it elsewhere because the fiber dump capability is able to more accurately determine *what* a fiber is doing than the fiber itself can.

2022-02-21 19:54 UTC, armanbilge commented
> I thought we had it elsewhere because the fiber dump capability is able to more accurately determine what a fiber is doing than the fiber itself can.

Yes, that's exactly why we have a separate `fiberString` that takes a `status` as an argument. However, that currently does not take into account whether the fiber is done or not.

2022-02-21 19:55 UTC, djspiewak commented
> Yes, that's exactly why we have a separate fiberString that takes a status as an argument. However, that currently does not take into account whether the fiber is done or not.

Ah! Yes, I'd like to see that improved.

2022-02-22 06:54 UTC, iRevive commented
Thanks for the details. I will implement mentioned suggestions

2022-02-22 07:00 UTC, armanbilge commented
Another possibility I didn't consider this morning is that we should filter out the fibers that are done, and not include them in the dump at all (either they haven't been GCed yet, or there's a strong reference). We should see what @djspiewak thinks.

2022-02-22 19:27 UTC, djspiewak commented
> Another possibility I didn't consider this morning is that we should filter out the fibers that are done, and not include them in the dump at all (either they haven't been GCed yet, or there's a strong reference). We should see what @djspiewak thinks.

This is a good point. IMO yes, a done fiber shouldn't be displayed in the dump.

2022-03-05 22:40 UTC, djspiewak approved these changes

2022-03-05 22:40 UTC, merged

2022-03-05 22:41 UTC, armanbilge commented
This PR still needed some follow-up work, I'll re-open the issue.

2022-03-05 22:42 UTC, armanbilge commented
Also, this could probably go into 3.3.x, no?

2022-03-06 05:44 UTC, djspiewak commented
> Also, this could probably go into 3.3.x, no?

Probably yes, now that I think about it. We would need to revert this though, PR the revert, then re-PR the change with a new base. Doesn't seem worth it. We can just let this fall through to 3.4.0.