Add Semaphore#tryPermit
typelevel/cats-effect pull request #2843
Opened 2022-02-25 15:58 UTC by TimWSpence

A hopefully safer abstraction over `Semaphore#tryAcquire` which ensures that we always release the permit

2022-02-25 16:01 UTC, SystemFw requested changes

2022-02-25 16:01 UTC, SystemFw commented on std/shared/src/main/scala/cats/effect/std/Semaphore.scala
> +          Resource.makeFull { (poll: Poll[F]) => poll(tryAcquire) } { _ => release }
shouldn't this only release when acquired?

2022-02-25 16:04 UTC, TimWSpence commented on std/shared/src/main/scala/cats/effect/std/Semaphore.scala
> +          Resource.makeFull { (poll: Poll[F]) => poll(tryAcquire) } { _ => release }
🤦 yes. Yes it should

2022-02-25 16:41 UTC, SystemFw commented on std/shared/src/main/scala/cats/effect/std/Semaphore.scala
> +          Resource.makeFull { (poll: Poll[F]) => poll(tryAcquire) } { _ => release }
Also, you shouldn't `poll`, and make it uncancelable instead

2022-03-02 14:50 UTC, SystemFw approved these changes

2022-03-02 20:01 UTC, djspiewak approved these changes

2022-03-02 20:01 UTC, merged