Add IO.randomUUID convenience method
typelevel/cats-effect pull request #2852
Opened 2022-03-01 16:27 UTC by Daenyth

2022-03-01 16:39 UTC, armanbilge approved these changes, later dismissed

2022-03-01 17:08 UTC, djspiewak requested changes
@Daenyth Looks like this needs to be split

2022-03-01 17:08 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +import cats.effect.std.{Console, Env, GenUUID}
I believe you mean `UUIDGen` :-)

2022-03-02 15:05 UTC, Daenyth commented on core/shared/src/main/scala/cats/effect/IO.scala
> +import cats.effect.std.{Console, Env, GenUUID}
Damnit

2022-03-03 10:58 UTC, wjoel commented
Wouldn't `Random` be a better place for this? https://github.com/typelevel/cats-effect/blob/series/3.x/std/shared/src/main/scala/cats/effect/std/Random.scala

2022-03-03 15:14 UTC, djspiewak commented
It could be, yes, but this is also a wildly common case, so I think it's fair to lean a bit toward better convenience. `Random` isn't any harder to summon than `UUIDGen`, but IO is just… there.

2022-03-03 17:34 UTC, wjoel commented
Fair enough (even if I personally don't generate random UUIDs *that* often ;) ), but maybe the help text could include a reference `Random` so newbies that type `IO.rando...` have a better chance of discovering it. Just a thought.

2022-03-04 20:27 UTC, djspiewak approved these changes

2022-03-04 20:27 UTC, merged

2022-03-05 03:27 UTC, Daenyth commented
I was looking at that too - `UUIDGen` doesn't actually use `Random`, it just wraps `UUID.randomUUID()` in `Sync[F].delay`

2022-03-05 05:50 UTC, djspiewak commented
This actually might be something that should be addressed, since randomUUID can block threads.

2022-03-05 17:27 UTC, rossabaker commented
I have seen `UUID.randomUUID` kill more than one service in the years BCE (Before Cats Effect).  The synchronization isn't obvious until you start profiling why you're getting single-threaded performance.