Migrate to sbt-typelevel
typelevel/cats-effect pull request #2857
Opened 2022-03-03 18:36 UTC by armanbilge

Taking the conservative approach and not mixing up the build too much with sbt-typelevel gospel 😉 

Opening for CI. I anticipate this PR will fail while we get MiMa up-to-speed on Scala 3 and possible Scala.js.

2022-03-03 18:40 UTC, armanbilge commented on build.sbt
> +ThisBuild / tlCiReleaseBranches := Nil
No CI publishing :)

2022-03-03 18:40 UTC, armanbilge commented on .github/workflows/ci.yml
> +  PGP_SECRET: ${{ secrets.PGP_SECRET }}
Hmm, I guess these are baked in a little too hard :) anyway should be harmless.

2022-03-03 18:40 UTC, armanbilge commented on build.sbt
> +ThisBuild / githubWorkflowBuildMatrixExclusions := {
sbt-typelevel already does some of these exclusions for us. Rather than tease apart what's been upstreamed we'll just keep using our own.

2022-03-03 18:40 UTC, armanbilge commented on project/Common.scala
> +      )
Sorry, this is a spiewak-ism 😝 Vasil has a PR to upstream where it belongs.

- https://github.com/sbt/sbt-header/pull/282

2022-03-03 19:20 UTC, armanbilge commented
I just added like a 100+ mima filters. At a glance they all seem reasonable but would be good for someone to look with a more careful eye.

2022-03-03 20:13 UTC, armanbilge commented on build.sbt
> +ThisBuild / tlUntaggedAreSnapshots := false
I almost forgot 😆

2022-03-04 17:46 UTC, djspiewak requested changes
Btw I do agree with the reformattings, but why are they happening as part of this PR?

2022-03-04 17:46 UTC, djspiewak commented on build.sbt
> +val GraalVM = JavaSpec.graalvm("11")
Why is the Graal version not specified. This feels a little weird in general since it suggests that the GraalVM version would be either unstable or unconfigurable.

2022-03-04 17:46 UTC, djspiewak commented on build.sbt
> +ThisBuild / tlJdkRelease := Some(8)
Why is this needed if we aren't doing CI releases?

2022-03-04 17:46 UTC, djspiewak commented on project/Common.scala
> +      )
It does indeed belong in upstream

2022-03-04 17:46 UTC, djspiewak commented on .github/workflows/ci.yml
> +  PGP_SECRET: ${{ secrets.PGP_SECRET }}
Bleh. :-) I'd definitely like to see these cleaned up, but it's kind of okay for now.

2022-03-04 17:47 UTC, djspiewak commented on .github/workflows/ci.yml
> +    tags: [v*]
Oh actually one extra bit: we don't need to build tags because we're not doing CI releases. This appears to be another thing that's a bit too baked-in.

2022-03-04 17:49 UTC, armanbilge commented on build.sbt
> +val GraalVM = JavaSpec.graalvm("11")
I can revert this. Most people probably want the latest Graal and not a specific version (which is easy to forget to update, as we've forgotten to here :)

2022-03-04 17:51 UTC, armanbilge commented on build.sbt
> +ThisBuild / tlJdkRelease := Some(8)
Because neither of these has anything to do with CI release :)

`tlVersionIntroduced` tells MiMa not to look for Scala 3 artifacts older than 3.1.1.

`tlJdkRelease` is the upstreamed version of https://github.com/typelevel/cats-effect/pull/2825.

2022-03-04 17:52 UTC, armanbilge commented on .github/workflows/ci.yml
> +    tags: [v*]
Yep, I noticed this with the other stuff. It's also harmless but will definitely fix upstream.

2022-03-04 17:58 UTC, armanbilge commented
Formatting changes are probably because sbt-typelevel brings you latest sbt-scalafmt which this branch missed.

- https://github.com/typelevel/cats-effect/pull/2690

which includes a fix for:

- https://github.com/scalameta/sbt-scalafmt/issues/190

2022-03-04 18:14 UTC, armanbilge commented on build.sbt
> +val GraalVM = JavaSpec.graalvm("11")
Btw @vasilmkd what are your thoughts on this topic, maybe we need to revise the JDK index to support this?

2022-03-04 19:07 UTC, djspiewak commented on .github/workflows/ci.yml
> +    tags: [v*]
Not *quite* harmless since it counts against our running instance quota, but mostly harmless yes. :-)

2022-03-04 22:05 UTC, vasilmkd commented on build.sbt
> +val GraalVM = JavaSpec.graalvm("11")
We were already on latest, I was doing it manually. Graalvm also follows the JDK release cycle, so as soon as the latest drops, the previous one is obsolete and unsupported. I don't want to sound dismissive, but I'm not interested in changing the index to support old versions.

2022-03-04 22:53 UTC, armanbilge commented on build.sbt
> +val GraalVM = JavaSpec.graalvm("11")
I see the latest in the index is 22.0.0.2 and CE is on 21.3.0, so we've fallen behind again (at least on this branch).

Ok @djspiewak your call, how do you want to configure this for CE?

> version would be either unstable

It depends on what you are targeting. If you are targeting JDK whatever then shouldn't it be as stable as any of the other JVMs?

OTOH, if you are targeting specific GraalVM APIs then obviously it makes a difference. Actually [I have a project like this](https://github.com/armanbilge/fungio/).

FTR I didn't remove the ability to configure a specific GraalVM (it still shells out to [DeLaGuardo/setup-graalvm](https://github.com/DeLaGuardo/setup-graalvm) like you set it up) although it is now a little more "discouraged" because I expect 99% of projects don't actually want this.

Finally, if you truly want stability, you should really pin the JDK index to a particular hash anyway :)

2022-03-11 20:52 UTC, vasilmkd commented
In light of https://github.com/lampepfl/dotty/issues/14624 and https://github.com/lampepfl/dotty/pull/14662, I think we can go ahead and apply the MiMa filters for the Scala 3 issue.

2022-03-11 20:54 UTC, armanbilge commented
After this PR merges, I'll do a follow-up which adds JDK17/Scala3 to CI. That will force us to add the mima filters.

2022-03-29 16:06 UTC, armanbilge commented on .github/workflows/ci.yml
> +    tags: [v*]
So actually this one is harder to fix, because it controls the _entire_ workflow file. Even though neither CI nor publishing may not need to run on tags, in general there may be other jobs in the workflow (such as deploying a website) that need to be triggered.

2022-04-02 05:46 UTC, djspiewak commented
`show version`
`3.3.9-18-b0b4a99-20220402T054540Z-SNAPSHOT`

How do I make it stop? :-( Worktrees do seem to work though.

2022-04-02 09:14 UTC, armanbilge commented
Cool! So not a blocker ... right? 😇

2022-04-02 16:28 UTC, djspiewak commented
LOL. Well, I really want to make that version stuff at least *configurable*, because the transitive impact it has on the ecosystem is… unpleasant. Not a hard blocker, but definitely a something. I'll see if I can fix it myself in sbt-tl

2022-04-02 16:34 UTC, djspiewak commented
Oh, it's more sbt-git issues: 

```
sbt:root> show gitUncommittedChanges
[info] benchmarks / gitUncommittedChanges
[info] 	true
[info] testsJVM / gitUncommittedChanges
[info] 	true
```

2022-04-02 17:10 UTC, djspiewak commented
Alright, managed to get it working, sort of. `3.3.9-20-44bf4e1` has been published to sonatype so we can make sure things are in good shape. I published it using Java 11, fwiw, so we can test the release flag while we're at it.

Basically, we needed one last fix for sbt-git which I completely forgot about. Namely, they're determining dirty directories incorrectly (by using `git status` and then grepping for text). This has issues between different versions of `git`, and so the workaround is to use `git status -s` and check to see if it returns *any* results.

2022-04-02 18:23 UTC, djspiewak commented
Release looks good. Branch appears to be generally functional. I'm in favor of merging this, though it would be nice to see the sbt-git workaround upstreamed at some point.

2022-04-02 18:27 UTC, djspiewak commented on build.sbt
> +ThisBuild / githubWorkflowBuildMatrixExclusions := {
We shoudl try to inherit more in the future, but this is a fine start.

2022-04-02 18:28 UTC, djspiewak approved these changes

2022-04-02 18:40 UTC, vasilmkd commented
Let's go! 🚀

2022-04-02 18:41 UTC, vasilmkd approved these changes

2022-04-02 19:20 UTC, armanbilge commented
🎉 I wasn't sure if we'd make it 😂 thank you! Obviously still plenty to upstream 😬

2022-04-02 19:20 UTC, merged