Use Performance API for high-precision time on JS
typelevel/cats-effect pull request #2895
Opened 2022-03-20 20:39 UTC by armanbilge

Follow-up to https://github.com/typelevel/cats-effect/pull/2416.

Always an adventure on JS :) there's nothing in the ES standard, but amazingly both [browsers](https://developer.mozilla.org/en-US/docs/Web/API/Performance) and [Node.js](https://nodejs.org/api/perf_hooks.html#performance-measurement-apis) have implemented the same APIs for once! With of course the caveat that for whatever reason [`performance.timeOrigin`](https://developer.mozilla.org/en-US/docs/Web/API/Performance/timeOrigin) is "experimental technology" on the web 🙃

2022-03-20 20:48 UTC, djspiewak submitted a review, later dismissed

2022-03-20 21:28 UTC, armanbilge commented
One learning from this PR is that `IO.cede` on browsers very nearly takes a millisecond ...

2022-03-20 22:19 UTC, armanbilge commented
Urgh, extremely annoying! On browsers `IO.cede` is too slow; on Node.js, without it is too fast.

2022-03-20 22:53 UTC, armanbilge commented
Hmm, even with the `cede` Node.js is having issues :( I can't replicate locally though.
```
[error]   x use high-precision time
[error]    0 microseconds is equal to 0 nanoseconds (/home/runner/work/cats-effect/cats-effect/tests/js/target/scala-2.13/cats-effect-tests-test-fastopt/https:
```

2022-03-20 23:21 UTC, armanbilge commented
Node 14 is LTS for one more year. I guess we should keep it in CI :(
https://nodejs.org/en/about/releases/

2022-03-21 00:09 UTC, djspiewak requested changes

2022-03-21 00:09 UTC, djspiewak commented on core/js/src/main/scala/cats/effect/unsafe/SchedulerCompanionPlatform.scala
> +      require(!(performance.timeOrigin + performance.now()).isNaN)
Exceptions are pretty expensive. Can we turn this into a simple `if`/`else`?

2022-03-21 00:10 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/SchedulerCompanionPlatform.scala
> +      require(!(performance.timeOrigin + performance.now()).isNaN)
Even for a one-time initialization?

2022-03-21 00:11 UTC, armanbilge commented on core/js/src/main/scala/cats/effect/unsafe/SchedulerCompanionPlatform.scala
> +      require(!(performance.timeOrigin + performance.now()).isNaN)
Yeah, you're probably right :( I've used `Try` in many places, maybe I should dial those back.

2022-03-21 00:43 UTC, armanbilge commented
This is looking to be flaky on Chrome. Unfortunately the resolution there is 100 microseconds (versus 5 microseconds on Firefox with `privacy.reduceTimerPrecision=false`). I guess I can try `cede` again, but that may be dangerously slow 😅

2022-04-07 16:27 UTC, djspiewak submitted a review, later dismissed

2022-04-07 16:27 UTC, djspiewak commented
@armanbilge This is ready to go once the conflicts are resolved.

2022-04-07 16:52 UTC, djspiewak approved these changes

2022-04-07 17:57 UTC, merged