Added orElse combinator to IO
typelevel/cats-effect pull request #2940
Opened 2022-04-04 14:09 UTC by walesho

Added orElse combinator to IO. 

Example of Usuage 
`val firstIO = IO.raiseError[Int]`
 `val secondIO = IO.pure(42)`
 `val program = firstIO orElse secondIO // this would result to secondIO `

2022-04-04 15:51 UTC, rossabaker commented
This is what the `MonoidK` instance does for `combineK`.  I think it's a useful enough operation to give it a name like this.

2022-04-04 16:18 UTC, satorg commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    handleErrorWith(_ => other)
If it just calls to `handleErrorWith` then (perhaps) it would be better to add such a method directly to Cats' `ApplicativeError` type class instead of just `IO`. Because apparently it would make `orElse` functionality uniformly available for all `ApplicativeError` implementers (which includes IO from Cats Effect 2.x, Monix Task, fs2.Stream, etc). Wdyt?

2022-04-04 16:18 UTC, djspiewak reviewed
This is great! Can you please run `sbt prePR` though? Additionally, as @rossabaker pointed out, these are the same semantics as `MonoidK[IO]`, so it might be worth adjusting that instance to delegate to `orElse` to avoid duplication and improve test coverage.

2022-04-05 12:40 UTC, rossabaker commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    SemigroupK[IO].combineK(this, other)
I would go the other way around: leave this like you had it, and implement SemigroupK in terms of it.

2022-04-05 13:48 UTC, walesho commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    SemigroupK[IO].combineK(this, other)
Thanks for the input. I would follow that approach.

2022-04-05 20:03 UTC, rossabaker commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    handleErrorWith(_ => other)
It's already [syntax on `ApplicativeError`](https://github.com/typelevel/cats/blob/e0784fc0d95b9c4eed0bb1ddce6c69e3fd9a4a4f/core/src/main/scala/cats/syntax/applicativeError.scala#L76-L77).  I'm not sure why it shouldn't also be on the type class.

Regardless, I think the trend on `IO` has been toward a rich interface without typeclass syntax.  Adding it here is consistent with `Either`, `EitherT`, etc.

2022-04-05 20:16 UTC, satorg commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    handleErrorWith(_ => other)
> I'm not sure why it shouldn't also be on the type class.

I wonder too. I wonder if there is any convention on that in general. The syntax was introduced in typelevel/cats#2243 but seems the option for adding it to the typeclass had not been discussed nor challenged.

In general, having a method on typeclass makes it possible to override it in a particular implementation (e.g. for the sake of optimization). Not sure if may make sense for this `orElse` though.

2022-04-05 20:25 UTC, satorg commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    handleErrorWith(_ => other)
> It's already [syntax on ApplicativeError](https://github.com/typelevel/cats/blob/e0784fc0d95b9c4eed0bb1ddce6c69e3fd9a4a4f/core/src/main/scala/cats/syntax/applicativeError.scala#L76-L77).

Btw, the syntax for `ApplicativeError` is defined in this way:
```scala
  def orElse(other: => F[A])(implicit F: ApplicativeError[F, E]): F[A] =
    F.handleErrorWith(fa)(_ => other)
```
Notice it takes `other` as a by-name param while the suggested addition to `IO` takes it as just a value.

Wouldn't it be better to keep these two methods in correspondence to each other? I.e. to declare the latter's `other` as a by-name parameter too? @rossabaker @djspiewak , wdyt?

2022-04-05 20:25 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    handleErrorWith(_ => other)
Right, good catch. This should definitely be a by-name.

2022-04-05 20:26 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    handleErrorWith(_ => other)
Btw, it's really OOPy but if we had inheritable syntax traits for the monad classes themselves, couldn't we get all this syntax for free and avoid oopsies? Similar to how I've suggested that the `IO` companion object itself should implement `Async[IO]`.

2022-04-05 20:38 UTC, djspiewak requested changes

2022-04-05 20:38 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    handleErrorWith(_ => other)
So the by-name parameter point is a really important one. If this already exists as syntax on `ApplicativeError`, then we need to be consistent with that.

2022-04-05 21:55 UTC, djspiewak approved these changes
Looks good to me!

2022-04-06 13:59 UTC, armanbilge commented
CI failure is because series/3.x is behind series/3.3.x so MiMa is rightfully upset :) merging https://github.com/typelevel/cats-effect/pull/2947 should fix this, I'll look into that now.

2022-04-06 14:42 UTC, rossabaker approved these changes

2022-04-06 16:13 UTC, armanbilge commented
Closing / re-opening to trigger CI on a fresh merge commit, apologies.

2022-04-06 18:17 UTC, armanbilge commented
Congrats on your first PR! @walesho 🎉

2022-04-06 18:17 UTC, merged