Add `GenTemporal#cachedRealTime`
typelevel/cats-effect pull request #2941
Opened 2022-04-04 17:10 UTC by brendanmaguire

This method provides a nested effect which calculates time using a cached offset and `monotonic`. This is much faster than calling `realTime` repeatedly and is useful for some applications where precise time is not required

2022-04-04 17:11 UTC, brendanmaguire commented
As described in the discussion in #2416 , and in particular [this comment](https://github.com/typelevel/cats-effect/pull/2416#issuecomment-1073308423).

2022-04-04 17:12 UTC, brendanmaguire commented
@djspiewak & @armanbilge , would you mind taking a look. It seems messy to me but I'm not sure how to clean it up. Suggestions welcome.

2022-04-04 19:56 UTC, djspiewak reviewed
Doesn't seem too messy to me. :-) It's a surprisingly involved effect. The big thing that would clean it up is just leveraging the syntax.

2022-04-04 19:56 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +   * This should only be used in situations where precise time does not need to be guaranteed.
```suggestion
   * This should generally be used in situations where precise "to the millisecond" alignment to the
   * system real clock is not needed. In particular, if the system clock is updated (e.g. via an NTP sync),
   * the inner effect will not observe that update until up to `refreshPeriod`. This is an acceptable
   * tradeoff in most practical scenarios, particularly with frequent sequencing of the inner effect.
```

2022-04-04 19:56 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +   * `Clock[F]#monotonic` to give an approximation of the real time.
```suggestion
   * `Clock[F]#monotonic` to give an approximation of the real time. The practical benefit of this is a reduction
   * in the number of syscalls, since `realTime` will only be sequenced once per `refreshTime` window, and it
   * tends to be (on most platforms) multiple orders of magnitude slower than `monotonic`.
```

2022-04-04 19:56 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +    map(cacheValuesRefF) { cacheValuesRef =>
Random fyi: you can use cats syntax within this class. :-) There should be a `private implicit val self = this` or something like that within `GenTemporal`, meaning you can safely do things like `cacheValuesRefF.map { ...}`.

2022-04-04 19:56 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +    }
```suggestion
    val minCacheValuesF = (cacheValuesF, cacheValuesF) mapN {
      case ((_, offset1), (_, offset2)) => offset1.min(offset2)
    }
```

2022-04-04 19:56 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +        flatMap(cacheValuesRef.access) {
I would probably use `Ref#set` and `Ref#get` directly instead.

2022-04-04 19:56 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +  def cachedRealTime(refreshPeriod: Duration): F[F[FiniteDuration]] = {
What do you think about `ttl` as a name for this parameter?

2022-04-05 08:32 UTC, brendanmaguire commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +  def cachedRealTime(refreshPeriod: Duration): F[F[FiniteDuration]] = {
Sounds good to me :+1:

2022-04-05 08:35 UTC, brendanmaguire commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +    map(cacheValuesRefF) { cacheValuesRef =>
Ah! I didn't know this. I will use the more idiomatic approach.

I didn't notice `for` comprehensions in the codebase (apart from tests). Is there a reason for this?

2022-04-05 08:42 UTC, brendanmaguire commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +    }
I get the following compilation error when attempting to use `mapN`:

```
Could not find an instance of Functor for F
```

Am I missing an import? :thinking:

2022-04-05 08:48 UTC, brendanmaguire commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +    }
Ah, I see this is what you were referring to with the `private implicit val self = this`. Thanks for the tip!

2022-04-05 09:20 UTC, brendanmaguire commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +    }
I've changed this locally to use `mapN` but your suggestion won't quite work as we need to retain both the `cacheRefreshTime` (to determine when to refresh) and `offset` (to determine the time). I'll push what I have and you can see if it looks right.

2022-04-05 09:28 UTC, brendanmaguire commented
Thanks for the feedback @djspiewak :slightly_smiling_face: Changes pushed.

2022-04-05 09:30 UTC, brendanmaguire commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +   *   [[timeout]] for a variant which respects backpressure and does not leak fibers
```suggestion
```

2022-04-05 21:51 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +    map(cacheValuesRefF) { cacheValuesRef =>
`for` comprehensions are somewhat tricky for a few reasons. First, the desugaring is unintuitive and can create issues, both semantic and performance-related, if you aren't careful (particularly in recursive cases). Second, the desugaring is actually *different* between Scala 2 and Scala 3, so generally we try not to use them unless it's really convincingly safe to do so.

Stylistically though, I quite like them :-)

2022-04-05 21:55 UTC, djspiewak requested changes
Really minor required change and some stylistic nits, but this is looking very good!

2022-04-05 21:55 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +   * per `refreshTime` window, and it tends to be (on most platforms) multiple orders of
```suggestion
   * per `ttl` window, and it tends to be (on most platforms) multiple orders of
```

2022-04-05 21:55 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +    }
Much cleaner, IMO!

2022-04-05 21:55 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +    } yield (cacheRefreshTime, realTimeNow - cacheRefreshTime)
Btw this can also be done with `mapN`, and it's probably cleaner to do so.

2022-04-05 21:55 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +    }
IMO if we're going to use `for` here, this is the place to do it. :-)

2022-04-06 06:40 UTC, brendanmaguire commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +    map(cacheValuesRefF) { cacheValuesRef =>
Ah yes, this makes sense. I will remove them.

2022-04-06 06:41 UTC, brendanmaguire commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +    }
I'm happy to remove the use of `for` given the reasons you've outlined above.

2022-04-06 06:41 UTC, brendanmaguire commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +    } yield (cacheRefreshTime, realTimeNow - cacheRefreshTime)
Good point :slightly_smiling_face: Will change.

2022-04-06 06:47 UTC, brendanmaguire commented
Thanks again for the feedback @djspiewak . I will start using `mapN` more often in my own code after this :slightly_smiling_face: Changes made.

2022-04-07 16:23 UTC, djspiewak commented
Reopening to get a new merge commit for CI

2022-04-08 05:09 UTC, hepin1989 commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +        }
can this be rewrite to for expression?

2022-04-10 16:37 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +        }
It could be but we tend to avoid them in most places since their desugaring is both unintuitive (creating an extra `map` in most cases) *and* not the same across Scala 2 and 3 (due to our use of a compiler plugin on the former). Perhaps more relevantly though, I don't think a `for`-comprehension would help much here with readability, since you would still have the testing due to the `F[F[FiniteDuration]]` result type.

2022-04-10 16:37 UTC, djspiewak approved these changes

2022-04-10 16:37 UTC, merged