Duration
typelevel/cats-effect pull request #2954
Opened 2022-04-09 14:28 UTC by b3nk3i

Generalize timeout and friends to take a Duration #2855

2022-04-09 14:34 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  def timeout[A2 >: A](duration: Duration): IO[A2] =
Thanks for the PR! At a glance your changes are looking good 👍 

It's a little bit annoying, but for binary compatibility, we actually need to keep the old method in addition to adding the new one.

2022-04-09 14:38 UTC, b3nk3i commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  def timeout[A2 >: A](duration: Duration): IO[A2] =
thanks for the feedback :)
I can put back the old method

2022-04-09 15:32 UTC, djspiewak requested changes
This is looking like a very nice start! Thank you for taking this on.

2022-04-09 15:32 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +  def handleFinite[A](fa: F[A], duration: Duration)(f: FiniteDuration => F[A]): F[A] = {
This should probably be private. 🙂

2022-04-09 15:32 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  def timeout[A2 >: A](duration: Duration): IO[A2] =
More specifically, I believe we need a protected overload which handles the FiniteDuration case, and the public overload then becomes the Duration. This would preserve binary compatibility and semantics with older implementers of the trait.

2022-04-12 08:34 UTC, walesho commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  def timeout[A2 >: A](duration: Duration): IO[A2] =
What would be the practical implication of taking a Duration? Since we can already do IO.timeout(5 Seconds) using FiniteDuration as it were.

2022-04-12 15:58 UTC, satorg commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  def timeout[A2 >: A](duration: Duration): IO[A2] =
@walesho I'd guess it is just for the sake of generalization. If `Duration.Inf` is passed to the `timeout` method, then the operation should never timeout. It may not be that useful with literals and constant values, but imagine if the timeout value is taken from configs. So there will be an easy way to disable timeouts from the configs simply by passing an infinite value out there.

2022-04-17 19:07 UTC, djspiewak requested changes
Almost there! Just a quick tweak to avoid bloating the public API. I'll work on fixing the scaladoc links and will push the changes, since that's the most annoying thing in the universe.

2022-04-17 19:07 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  protected def timeout[A2 >: A](duration: FiniteDuration): IO[A2] =
This can actually be `private[effect]` instead of `protected`, since `IO` is final.

2022-04-17 19:07 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  protected def timeoutTo[A2 >: A](duration: FiniteDuration, fallback: IO[A2]): IO[A2] = {
Same here…

2022-04-17 19:07 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
> +  def handleFinite[F[_], A](fa: F[A], duration: Duration)(f: FiniteDuration => F[A]): F[A] = {
This needs to be `private[kernel]` instead of public, since this is unintentionally adding to the public API surface!

2022-06-18 00:40 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  def timeout[A2 >: A](duration: Duration): IO[A2] =
Note that the type parameter here is unnecessary since `IO` is covariant but I guess we'd rather not break source-compatibility at this stage /shrug

2022-06-18 01:22 UTC, armanbilge commented on kernel/shared/src/main/scala-2.12/cats/effect/kernel/syntax/GenTemporalSyntaxCompat.scala
> +  def timeoutAndForget$extension[F[_], A, E](
Yes, they have to be public. Yes, it's really annoying.

2022-06-18 19:53 UTC, djspiewak commented on kernel/shared/src/main/scala-2.12/cats/effect/kernel/syntax/GenTemporalSyntaxCompat.scala
> +  def timeoutAndForget$extension[F[_], A, E](
Why can't they be `private[kernel]`?

2022-06-18 19:53 UTC, armanbilge commented on kernel/shared/src/main/scala-2.12/cats/effect/kernel/syntax/GenTemporalSyntaxCompat.scala
> +  def timeoutAndForget$extension[F[_], A, E](
Because static forwarders and binary compatibility. This is only on 2.12 btw.

2022-06-18 21:24 UTC, djspiewak commented on kernel/shared/src/main/scala-2.12/cats/effect/kernel/syntax/GenTemporalSyntaxCompat.scala
> +  def timeoutAndForget$extension[F[_], A, E](
Grrrrrrrrrrrrr.

Okay :-P

2022-06-18 21:24 UTC, djspiewak approved these changes

2022-06-18 21:24 UTC, merged