Configurable dispatcher
typelevel/cats-effect pull request #2959
Opened 2022-04-13 11:06 UTC by iRevive

Follow up to https://github.com/typelevel/cats-effect/issues/1881#issuecomment-1096987607. 

The PR is based on https://github.com/typelevel/cats-effect/pull/2854

2022-04-13 12:14 UTC, iRevive commented on tests/shared/src/test/scala/cats/effect/std/DispatcherSpec.scala
> +            _ <- IO(runner.unsafeRunAndForget(cdl.release >> fiberLatch.await))
Without `cdl.release` and `cdl.await` the test does not pass on the sequential dispatcher.

```scala
.use(runner => IO(runner.unsafeRunAndForget(fiberLatch.await)))
```

As far as I debugged, the dispatcher is closed faster than the task is picked up by the queue. 

A test to reproduce:
```scala
"effect is not executed" in real {
  for {
    fiberLatch <- CountDownLatch[IO](1)
    fiber <- Dispatcher
      .sequential[IO](await = true)
      .use(runner => IO(runner.unsafeToFuture(fiberLatch.await)))
      .start
    _ <- fiberLatch.release
    future <- fiber.joinWithNever
  } yield {
    scala.concurrent.Await.result(future, Duration.Inf) // never completes
    ok
  }
}
```

2022-04-13 12:24 UTC, iRevive commented on std/shared/src/main/scala/cats/effect/std/Dispatcher.scala
> +      (workers: Int, fork: (F[Unit] => F[F[Unit]])) <- mode match {
Unfortunately, JS requires a little help there.

2022-04-13 12:24 UTC, iRevive commented on tests/shared/src/test/scala/cats/effect/std/DispatcherSpec.scala
> +            _ <- IO(runner.unsafeRunAndForget(cdl.release >> fiberLatch.await))
cc @djspiewak

2022-04-13 13:55 UTC, iRevive commented on std/shared/src/main/scala/cats/effect/std/Dispatcher.scala
> +              .pure[F, F[Unit] => F[F[Unit]]]((_: F[Unit]).as(F.unit).handleError(_ => F.unit))
Is `as(F.unit)` necessary, since we are already operating on `F[Unit]`?

2022-04-13 14:43 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/Dispatcher.scala
> +      (workers: Int, fork: (F[Unit] => F[F[Unit]])) <- mode match {
Why is this JS specific? This code is in a shared file right? Actually the JVM/JS compilers are the same, only the backend is different, which is why I'm surprised and curious :)

2022-04-13 16:34 UTC, iRevive commented on std/shared/src/main/scala/cats/effect/std/Dispatcher.scala
> +      (workers: Int, fork: (F[Unit] => F[F[Unit]])) <- mode match {
CI is upset with these errors: https://github.com/typelevel/cats-effect/runs/6006857516?check_suite_focus=true#step:17:62

```
[error] -- [E007] Type Mismatch Error: /home/runner/work/cats-effect/cats-effect/std/shared/src/main/scala/cats/effect/std/Dispatcher.scala:207:61 
[error] 207 |        val latches = new Array[AtomicReference[() => Unit]](workers)
[error]     |                                                             ^^^^^^^
[error]     |                                             Found:    (workers : Any)
[error]     |                                             Required: Int
[error] -- [E134] Type Error: /home/runner/work/cats-effect/cats-effect/std/shared/src/main/scala/cats/effect/std/Dispatcher.scala:209:17 
[error] 209 |        while (i < workers) {
[error]     |               ^^^
[error]     |None of the overloaded alternatives of method < in class Int with types
[error]     | (x: Double): Boolean
[error]     | (x: Float): Boolean
[error]     | (x: Long): Boolean
[error]     | (x: Int): Boolean
[error]     | (x: Char): Boolean
[error]     | (x: Short): Boolean
[error]     | (x: Byte): Boolean
[error]     |match arguments ((workers : Any))
```

I can assume, something is going wrong with unapply in `withFilter`.

2022-04-13 16:38 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/Dispatcher.scala
> +      (workers: Int, fork: (F[Unit] => F[F[Unit]])) <- mode match {
Hmm, I see compile errors in the JVM job too.
https://github.com/typelevel/cats-effect/runs/6006857453?check_suite_focus=true#step:17:52

2022-04-13 17:13 UTC, iRevive commented on std/shared/src/main/scala/cats/effect/std/Dispatcher.scala
> +      (workers: Int, fork: (F[Unit] => F[F[Unit]])) <- mode match {
Ah, it's less suspicious now.

2022-04-17 17:40 UTC, djspiewak commented
It looks like this has been rebased. Please don't do that. :-) Since this is building on top of another PR, it needs to be based *on that branch*, merged with `series/3.x`.

In general, we don't rebase commits on non-draft PRs (outside of weird circumstances) for exactly this reason.

2022-04-17 17:41 UTC, djspiewak commented on tests/shared/src/test/scala/cats/effect/std/DispatcherSpec.scala
> +            _ <- IO(runner.unsafeRunAndForget(cdl.release >> fiberLatch.await))
Ahhhhhh! Interesting. Whoops.

2022-04-17 17:43 UTC, djspiewak requested changes
Changes look very good! I would add some overloads and undo the rebasing, but otherwise this is ready to go.

2022-04-17 17:43 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/Dispatcher.scala
> +  def parallel[F[_]: Async](await: Boolean): Resource[F, Dispatcher[F]] =
IMO we should mirror `Supervisor` here and create zero-parameter overloads that default `await` to `false`.

2022-04-17 18:48 UTC, djspiewak submitted a review, later dismissed
Looks fantastic! Thank you!

2022-04-17 18:48 UTC, djspiewak commented
I'm going to launder my changes through this PR, since the original one hasn't really been approved yet. :-P

2022-04-17 18:49 UTC, iRevive commented on std/shared/src/main/scala/cats/effect/std/Dispatcher.scala
> +  def parallel[F[_]: Async](await: Boolean): Resource[F, Dispatcher[F]] =
Good point. I added overloaded methods.

2022-04-17 18:59 UTC, iRevive commented
The documentation can be slightly improved:
```scala
/**
 * @define createDispatcher
 *   Create a [[Dispatcher]] that can be used within a resource scope. Once the resource scope
 *   exits, all active effects will be canceled, and attempts to submit new effects will throw
 *   an exception.
 *
 * @define parallelDetails
 *.  This corresponds to a pattern in which a single `Dispatcher` is being used by multiple ...
 *
 * @define sequentialDetails
 *.  This corresponds to a [[Dispatcher]] mode in which submitted actions are evaluated strictly ...
 */
object Dispatcher {

  /**
   * $createDispatcher
   * $parallelDetails
   */
  def parallel[F[_]: Async]: Resource[F, Dispatcher[F]] =
    parallel[F](await = false)
    
  /**
   * $createDispatcher
   * $sequentialDetails
   */
  def sequential[F[_]: Async]: Resource[F, Dispatcher[F]] =
    sequential[F](await = false)
    
  /**
   * $createDispatcher
   * $parallelDetails
   */
  def parallel[F[_]: Async](await: Boolean): Resource[F, Dispatcher[F]] =
    apply(Mode.Parallel, await)
    
   /**
   * $createDispatcher
   * $sequentialDetails
   */
  def sequential[F[_]: Async](await: Boolean): Resource[F, Dispatcher[F]] =
    apply(Mode.Sequential, await)
}
```

That way every overloaded method will have detailed documentation.

2022-04-17 19:01 UTC, djspiewak commented
> The documentation can be slightly improved

You sir are a master of understatement. :-D

I knew there was a way to define this type of expansion but can never remember it! We should definitely do that, though with an added sentence describing the default semantic on the no-args overloads.

2022-04-17 19:06 UTC, armanbilge commented
Woah, that's cool.

2022-04-17 19:24 UTC, djspiewak commented
Interesting! `DispatcherSpec` failed

2022-04-17 19:52 UTC, iRevive commented
Here are examples of the [macro definitions](https://docs.scala-lang.org/overviews/scaladoc/for-library-authors.html#macros):

<details>
  <summary>Generated scaladoc</summary>
  <img width="763" alt="image" src="https://user-images.githubusercontent.com/6395483/163729790-45193e99-8749-4678-93d9-fd71c96a8464.png">
</details>

<details>
  <summary>IntelliJ: method popup</summary>
  <img width="616" alt="image" src="https://user-images.githubusercontent.com/6395483/163729398-527e1def-7a31-45c1-9e96-123ef939eff6.png">
</details>

<details>
  <summary>IntelliJ: source code (published jar) with <a href="https://www.jetbrains.com/help/idea/working-with-code-documentation.html#toggle-rendered-view" target="_blank">rendered view</a></summary>
  
<img width="678" alt="image" src="https://user-images.githubusercontent.com/6395483/163729777-ee4a7891-53f9-430d-a1ba-cdc716c0516f.png">

</details>

<details>
  <summary>IntelliJ: source code (published jar)</summary>
<img width="601" alt="image" src="https://user-images.githubusercontent.com/6395483/163729625-6cccbf15-0552-45ce-bb90-f506731296e6.png">
</details>

I have mixing feelings tbh. I personally prefer raw scaladoc as a source of documentation during development. And with macro definitions, raw scaladoc is kinda meaningless.

Also, I'm not sure how Metals handle it since I'm not using it.

2022-04-17 20:02 UTC, iRevive commented
Weird. The tests are passing locally on `GraalVM 11` and `Azul VM 15.0`.

Could you restart CI jobs, please? Seems I do not have enough permissions for that.

2022-04-26 23:15 UTC, djspiewak approved these changes
Thank you for taking this on!

2022-04-26 23:15 UTC, merged