add `useIt` method to `Resource`
typelevel/cats-effect pull request #2976
Opened 2022-05-03 22:12 UTC by mberndt123

Hey there,

I've added a method I call `useIt`, which is equivalent to `use(identity)`. As a motivation, consider this example from the cats-effect documentation:

```scala
  (
    for {
      in1 <- file("file1")
      in2 <- file("file2")
      out <- file("file3")
    } yield (in1, in2, out)
  ).use { case (file1, file2, file3) =>
    for {
      bytes1 <- read(file1)
      bytes2 <- read(file2)
      _ <- write(file3, bytes1 ++ bytes2)
    } yield ()
  }
```
This looks very clumsy to me. Every allocated resource is mentioned at least 3 times here: once to the left of `<-`, once to the right of `yield`, and then again to the right of `case`. The reader also needs to keep track of the fact that `in1` is the same as `file1` etc., creating opportunities for confusion.

I find it more elegant to simply `yield` the action to be performed and then call `useIt`. 

```scala
  (
    for {
      in1 <- file("file1")
      in2 <- file("file2")
      out <- file("file3")
    } yield for {
        bytes1 <- read(in1)
        bytes2 <- read(in2)
        _ <- write(out, bytes1 ++ bytes2)
      } yield ()
  ).useIt
```

There is precedent for this kind of shortcut, e. g. `combineAll` is a shortcut for `foldMap(identity)`, and I hope that having this method, along with an example in the documentation, helps people discover what I consider to be a neat little trick.

2022-05-04 00:46 UTC, satorg commented
Just a side note (regardless of the value of this change):
if there're several effects which are independent of each other, then sometimes a parallel composition can come in handy:
```scala
(file("file1"), file("file2"), file("file3"))
  .tupled
  .use { case (file1, file2, file3) =>
    for {
      (bytes1, bytes2) <- (read(file1), read(file2)).tupled
      _ <- write(file3, bytes1 ++ bytes2)
    } yield ()
  }
```
Also this approach (with small changes in the code above) allows running the independent effects concurrently.

2022-05-04 06:00 UTC, mberndt123 commented
Yes, that's also something that I like to do. But it doesn't always work, sometimes you really do need flatMap.Am 04.05.2022 02:46 schrieb Sergey Torgashov ***@***.***>:
Just a side note (regardless of the value of this change):
if there're several effects which are independent of each other, then sometimes a parallel composition can come in handy:
(file("file1"), file("file2"), file("file3"))
  .tupled
  .use { case (file1, file2, file3) =>
    for {
      (bytes1, bytes2) <- (read(file1), read(file2)).tupled
      _ <- write(file3, bytes1 ++ bytes2)
    } yield ()
  }
Also this approach (with small changes in the code above) allows running the independent effects concurrently.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-05-16 15:18 UTC, Daenyth commented
`use(identity)` is always a resource leak bug

The value you return from `use` will be a *closed* resource, so there's never a point to this shape and it certainly shouldn't be in the api

2022-05-16 16:40 UTC, mberndt123 commented
Hi @Daenyth,

Thank you for your feedback. Actually, `use(F.pure(_))` is not a leak. If anything, it's a use-after-free error, but even that isn't necessarily true. The above example an be written like so:
```scala
val resource = for {
  in1 <- file("file1")
  in2 <- file("file2")
  out <- file("file3")
  ret <- Resource.eval {
    for {
      bytes1 <- read(in1)
      bytes2 <- read(in2)
      _ <- write(out, bytes1 ++ bytes2)
    } yield ()
  }
} yield ret
resource.use(F.pure(_))
```
This isn't a use-after-free, despite using the pattern that you claim is always incorrect. That said, I prefer the `use(identity)` pattern as it doesn't require `Resource.eval` and is less likely to lead to use-after-free errors. 

Now that we've clarified that part, I would like to better understand why you think it's not useful. Do you also think that `combineAll` is useless and people should write `foldMap(identity)` instead? Or do you think it's not a common use case? Because I see this pattern all the time. Almost every program works by allocating a bunch of resources at startup (DB connection pool, HTTP client, message broker connections, …) and then performing an IO action. So almost every realistic program has at least one use for this method :-)

2022-05-17 07:16 UTC, SystemFw commented
I don't think this method is all that useful, but I also don't think it's harmful, it's just a convenience for people that use `for` heavily (which I don't recommend, but it's of course legitimate). So, I'm not against adding it, although I'd probably name it `useNow`

2022-05-21 16:09 UTC, djspiewak reviewed
Definitely on the fence about this. It's kind of skating pretty close to a shortcut for `use(pure(_))`, which is to say, a resource leak. I can see it being useful beyond just `for` comprehensions though. It's kind of like the inverse of `background`. Maybe something like `useEval` or `useFlatten` would be a more descriptive name?

2022-05-21 17:16 UTC, mberndt123 commented
fwiw, I'd rather not call it `useNow` as that name is used in another effect system as a shortcut for `use(_.pure)`. That's useful for code such as `for (f <- openFile; content <- Resource.eval(readFile(f))) yield content` and doesn't necessarily imply a use-after-free error. I rather like the name `useIt`.

2022-06-17 17:28 UTC, djspiewak requested changes
After sleeping on this for a while, I think I'm in favor of adding it. I am going to bike-shed the name though. :-) Let's go with `useEval` instead. `useFlatten` is also a reasonable alternative and I wouldn't quibble if you prefer it. `useIt` is nice and short, but it's also not particularly descriptive of what's going on here.

I'm not concerned about the resource leak side of things, since this is basically just a slightly indirect way of constructing an otherwise-safe `use`.

2022-06-17 17:28 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
> +  def useIt[B](implicit ev: A <:< F[B], F: MonadCancel[F, Throwable]): F[B] =
```suggestion
  def useEval[B](implicit ev: A <:< F[B], F: MonadCancel[F, Throwable]): F[B] =
```

2022-06-18 09:34 UTC, mberndt123 commented
@djspiewak,

OK, `useEval` seems reasonable.

2022-06-18 19:53 UTC, djspiewak approved these changes
Thanks for sticking with this! Sorry again for how busy I've been over the past few months.

2022-06-18 19:53 UTC, merged