Print fatal errors
typelevel/cats-effect pull request #3008
Opened 2022-05-25 15:07 UTC by sbly

This is meant to address #2961. This is my first PR. I'm not sure I understood the ticket correctly. I'm not sure if this is the right place to address the issue, or if it needs to be done deeper, inside the IO runloop. Could I get some feedback? Thank you

2022-05-26 14:17 UTC, armanbilge reviewed
Thanks for the PR! To appease CI you can run `coreJVM/scalafixAll` in sbt. Perhaps we forgot to add this to the `prePR` command, sorry about that :)

2022-05-26 14:17 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +      case Left(e) => System.err.println(e)
I wonder if we can use `e.printStackTrace()` here instead :)

2022-05-26 16:39 UTC, sbly commented on core/shared/src/main/scala/cats/effect/IO.scala
> +      case Left(e) => System.err.println(e)
Whoops, good point :)

2022-05-26 16:41 UTC, sbly commented
@armanbilge Thanks for the review! Running `scalafixAll` worked. I checked the `prePR` command and it should be calling it:

```
addCommandAlias(
  "prePR",
  "; root/clean; root/scalafixAll; scalafmtSbt; +root/scalafmtAll; +root/headerCreate")
```

but when I use `prePR` directly, it doesn't seem to call scalafix. I think maybe this has to do with project aggregation in sbt, but I'm not familiar enough with this project's structure to diagnose the issue

2022-05-29 18:46 UTC, djspiewak requested changes
Right idea, but not quite there! :-) So the problem with `unsafeRunAndForget` comes from the fact that it is delegating to `unsafeRunAsync`, and `unsafeRunAsync` boxes fatal errors. Note that `unsafeRunAsyncOutcome` has the same issue.

There are two things we could do here, and I think I've convinced myself that one of them is better. Specifically, in `unsafeRunAsync` and `unsafeRunAsyncOutcome`, we check to see if the error is *not* `NonFatal` and then specifically print it in that case. We can still *try* to box it and send it along, but this is basically the last moment that we can be absolutely certain we have our hands on the error before more bad things become possible due to the type signatures.

In theory, `unsafeRunAndForget` shouldn't need to be changed.

2022-05-31 14:11 UTC, sbly commented
@djspiewak Thanks for the feedback! I implemented your suggestion.

2022-06-16 03:54 UTC, djspiewak approved these changes
Sorry this took me so long!

2022-06-16 03:54 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +        if (!NonFatal(t)) {
TIL `NonFatal` has an `apply` method.

2022-06-16 03:55 UTC, merged