Handle `Uncancelable` in `syncStep` interpreter
typelevel/cats-effect pull request #3064
Opened 2022-06-29 16:39 UTC by armanbilge

`SyncIO` is effectively uncancelable, so we don't need to do anything special in this case.

2022-06-29 17:43 UTC, djspiewak requested changes

2022-06-29 17:43 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +
`Sync` extends `MonadCancel`, so we should actually delegate here rather than assuming that the underlying type is uncancelable.

2022-06-29 17:44 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +
Ouch, good catch.

2022-06-29 17:49 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +
Wait, no, this is interpreting specifically into `SyncIO`, so there's nothing to do here. We'll have to fix this on merge into `series/3.x`

2022-06-29 17:53 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +
In fact, our tests catch this mistake on `series/3.x` anyway :)

```
failing seed for async.syncStep identity is ncXLceSQmGLs4bYfy4oHs3x-u4VCJHPY3rB6uQ5UJwO=
[error] x async.syncStep identity
[error]  Falsified after 13 passed tests.
[error]  > Labels of failing property:Expected: IO(...)
[error]  Received: IO(...)> ARG_0: IO(...)
[error]  > ARG_1: 3
[error]  > ARG_1_ORIGINAL: 2147483647
[error]  The seed is ncXLceSQmGLs4bYfy4oHs3x-u4VCJHPY3rB6uQ5UJwO=
```

2022-06-29 18:19 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +
`series/3.x` version in https://github.com/typelevel/cats-effect/pull/3065.

2022-07-07 01:10 UTC, djspiewak approved these changes

2022-07-07 01:10 UTC, merged