Handle `Uncancelable` and `OnCancel` in `syncStep` interpreter in 3.x
typelevel/cats-effect pull request #3065
Opened 2022-06-29 18:19 UTC by armanbilge

Forward merge of https://github.com/typelevel/cats-effect/pull/3064.

2022-06-29 18:22 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +          interpret(ioa, limit)
So this is kind of cheating, but I'm not sure if we can do better.

For `OnCancel`, what happens if we need to bail out the `finalizer`? Then we would need to return a `Left(...)` but I don't see how that's possible if we're in the process of being canceled.

I haven't thought as deeply about `Uncancelable`, but the mental gymnastics of implementing `Poll[IO]` in terms of `Poll[G]` were enough to put me off 😂

2022-07-16 20:29 UTC, djspiewak requested changes

2022-07-16 20:29 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +            if G.isInstanceOf[MonadCancel.Uncancelable[G, Throwable] @unchecked] =>
Okay, so finally looped around to this. The correct way to do something like this is via `rootCancelScope`:

```suggestion
        case IO.Uncancelable(body, _) if G.rootCancelScope == CancelScope.Uncancelable =>
```

2022-07-16 20:31 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +            if G.isInstanceOf[MonadCancel.Uncancelable[G, Throwable] @unchecked] =>
Ah, right! Forgot about this.

2022-07-16 20:36 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +            if G.isInstanceOf[MonadCancel.Uncancelable[G, Throwable] @unchecked] =>
I already made the change locally :-)

2022-07-17 18:49 UTC, merged