Native Image documentation example
typelevel/cats-effect pull request #3069
Opened 2022-07-02 13:58 UTC by TonioGela

Hello! 👋
I added an example of how to use `sbt-native-image` to produce a native-image executable, including some brief information about what was discovered/explained in #3051.

<details>
<summary>SPOILER: Opinionated addition</summary>
A little addition to the docs may be the usage of `hyperfine` (a tool written in Rust) to measure the startup time of the native executable. I added it since its report is so much more detailed compared to the one of `time`:

```sh
$ time ./HelloWorld
Hello world
./HelloWorld  0.01s user 0.01s system 99% cpu 0.022 total

$ hyperfine --warmup 30 ./HelloWorld
Benchmark 1: ./HelloWorld
  Time (mean ± σ):      20.4 ms ±   0.5 ms    [User: 11.3 ms, System: 10.0 ms]
  Range (min … max):    19.3 ms …  21.9 ms    110 runs
```
I can replace that piece with the `time` output if we don't want to advertise external tools
</details>

The `scala-cli` section in `faq.md` can IMHO be extracted in its file so that #2989 can be closed and the doc tidied up a bit.

2022-07-02 22:14 UTC, djspiewak requested changes

2022-07-02 22:14 UTC, djspiewak commented on docs/core/native-image.md
> +$ hyperfine ./target/native-image/cats-effect-3-hello-world
I think this is completely fine actually but I would link the tool so that people know what this is referencing. :-)

2022-07-03 10:07 UTC, TonioGela commented on docs/core/native-image.md
> +$ hyperfine ./target/native-image/cats-effect-3-hello-world
Cool, I added a reference to it. How about the whole text? I'm not a native speaker, so sometimes, my phrasing could be confusing.

2022-07-03 23:27 UTC, djspiewak approved these changes
Looks good, thank you!

2022-07-03 23:27 UTC, merged