CPU starvation checker
typelevel/cats-effect pull request #3090
Opened 2022-07-11 13:12 UTC by TimWSpence

Opening this for comment for the moment. Resolves https://github.com/typelevel/cats-effect/issues/2762

2022-07-11 13:21 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeConfigCompanionPlatform.scala
> +        .flatMap { d => Try(d.asInstanceOf[FiniteDuration]) }
I think you can just do `case fd: FiniteDuration => ...` here, instead of ... this :P

2022-07-11 13:22 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeConfigCompanionPlatform.scala
> +        .flatMap { d => Try(d.asInstanceOf[FiniteDuration]) }
It might help to transform the `Try` to an `Option`.

2022-07-11 13:25 UTC, TimWSpence commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeConfigCompanionPlatform.scala
> +        .flatMap { d => Try(d.asInstanceOf[FiniteDuration]) }
haha yup, either of those would be preferable 😂

2022-07-25 16:15 UTC, TimWSpence commented
@armanbilge are you still planning to do https://github.com/typelevel/cats-effect/pull/3098? Or should I add another parameter to toggle this on/off (instead of allowing `initialDelay = Duraiton.Inf`)

2022-07-25 16:17 UTC, armanbilge commented
Yup, feel free to base off https://github.com/typelevel/cats-effect/pull/3098.

2022-09-19 11:51 UTC, djspiewak requested changes
Does this *have* to build on top of the `FiniteDuration` => `Duration` PR? That has some subtleties so I wanted to untangle these things ideally.

2022-09-19 11:51 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeConfigCompanionPlatform.scala
> +      Try(System.getProperty("cats.effect.cpu.starvation.check.initial.delay"))
I'm not sure I like the paradigm of splitting up words in property names with `.`. :-) Something like `cats.effect.starvation.check.initialDelay` makes a bit more sense in terms of the hierarchy.

2022-09-21 07:33 UTC, djspiewak commented
Oh additional question: can we do this in a common location so it can be shared across the `IOApp`s? This is even more useful on JavaScript than on the JVM!

2022-09-22 11:42 UTC, TimWSpence commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeConfigCompanionPlatform.scala
> +      Try(System.getProperty("cats.effect.cpu.starvation.check.initial.delay"))
sure! And no it doesn't have to be based on top of that at all - I was just trying to avoid an additional parameter to disable it entirely. But I can rebase and do that - would be nice to unblock this!

2022-09-22 11:43 UTC, TimWSpence commented
> Oh additional question: can we do this in a common location so it can be shared across the `IOApp`s? This is even more useful on JavaScript than on the JVM!

Yes, good point!

2022-09-22 12:18 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeConfigCompanionPlatform.scala
> +      Try(System.getProperty("cats.effect.cpu.starvation.check.initial.delay"))
https://github.com/typelevel/cats-effect/pull/3098 already merged in so this point is moot :)

2022-09-22 13:59 UTC, TimWSpence commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeConfigCompanionPlatform.scala
> +      Try(System.getProperty("cats.effect.cpu.starvation.check.initial.delay"))
Haha great!!

2022-09-22 14:51 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/CpuStarvationCheck.scala
> +              .errorln("[WARNING] you're CPU threadpool is probably starving")
😛 
```suggestion
              .errorln("[WARNING] your CPU threadpool is probably starving")
```

2022-09-23 16:34 UTC, TimWSpence commented on core/shared/src/main/scala/cats/effect/CpuStarvationCheck.scala
> +              .errorln("[WARNING] you're CPU threadpool is probably starving")
Already spotted it! 😛

2022-09-23 17:04 UTC, djspiewak requested changes

2022-09-23 17:04 UTC, djspiewak commented on tests/shared/src/main/scala/catseffect/examples.scala
> +    val run = IO.delay(fib(1000)).replicateA_(50)
Fwiw, `Thread.sleep` also works :-P

2022-09-23 17:04 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/CpuStarvationCheck.scala
> +              .whenA(delta > runtimeConfig.cpuStarvationCheckThreshold)
Couple thoughts on this…

First, I think we should probably have the starvation threshold be a *multiple* of the interval. In other words, the check threshold should be a `Double` like `0.1` or `0.2` (representing 10% of 20%, respectively). Then the calculation itself would be something like this:

```suggestion
      .flatMap { now =>
        IO.sleep(runtimeConfig.cpuStarvationCheckInterval) >> IO
          .monotonic
          .map(_ - now)
          .flatMap { delta =>
            Console[IO]
              .errorln("[WARNING] Your CPU is probably starving. Consider reducing the granularity of your `delay`s or adding more `cede`s. This may also be a sign that you are unintentionally running blocking I/O operations (such as File or InetAddress) without the `blocking` combinator.")
              .whenA(delta >= runtimeConfig.cpuStarvationCheckInterval.toDouble * (1 + runtimeConfig.cpuStarvationCheckThreshold))
```

My second thought is that we should be more explanatory in the error message. I took a stab at it in the above. Probably needs line wrapping at the very least.

2022-09-23 17:04 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeConfig.scala
> +  private[unsafe] def DefaultCpuStarvationCheckInitialDelay = 10.millis
Is `10.millis` a sufficient initial delay? That's usually well within warmup times. I would think more like `10.seconds` would be better.

2022-09-23 17:04 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeConfig.scala
> +  private[unsafe] def DefaultCpuStarvationCheckThreshold = 100.millis
If we accept my suggestion from above, this would become `0.1d`

2022-09-23 17:04 UTC, djspiewak commented on tests/shared/src/main/scala/catseffect/examples.scala
> +      IO.println("boom").whenA(!r.eq(runtime)) >> IO.pure(ExitCode.Success)
Why did this change?

2022-09-24 12:52 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeConfigCompanionPlatform.scala
> +        .getOrElse(DefaultCpuStarvationCheckThreshold)
We need to add these for JS and Native too 😅

2022-10-05 11:26 UTC, TimWSpence commented on core/shared/src/main/scala/cats/effect/CpuStarvationCheck.scala
> +              .whenA(delta > runtimeConfig.cpuStarvationCheckThreshold)
Yep, thank you!

2022-10-05 11:27 UTC, TimWSpence commented on tests/shared/src/main/scala/catseffect/examples.scala
> +    val run = IO.delay(fib(1000)).replicateA_(50)
haha good point!

2022-10-05 11:27 UTC, TimWSpence commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeConfig.scala
> +  private[unsafe] def DefaultCpuStarvationCheckInitialDelay = 10.millis
Yeah this was an entirely arbitrary value I stuck in whilst getting things to compile 😅 `10.seconds` sounds reasonable 👍

2022-10-05 11:30 UTC, TimWSpence commented on tests/shared/src/main/scala/catseffect/examples.scala
> +      IO.println("boom").whenA(!r.eq(runtime)) >> IO.pure(ExitCode.Success)
Sorry, I hadn't finished getting this to work properly. But the problem is that we are now using the config for something other than instantiating the runtime so the way the test previously worked (`override def runtimeConfig = sys.error("boom")`) has to change

2022-10-05 11:30 UTC, TimWSpence commented
Apologies @djspiewak and @armanbilge for being so slow on this. Will try to get it over the line this week

2022-10-09 00:01 UTC, djspiewak requested changes
Just need a couple adjustments and then I think we're good to go. I changed the base so we're now pointing to 3.4.x

2022-10-09 00:01 UTC, djspiewak commented on core/js/src/main/scala/cats/effect/unsafe/IORuntimeConfigCompanionPlatform.scala
> +        .env("CATS_EFFECT_CPU_STARVATION_CHECK_INTERNAL")
Typo!

```suggestion
        .env("CATS_EFFECT_CPU_STARVATION_CHECK_INTERVAL")
```

2022-10-09 00:01 UTC, djspiewak commented on core/js/src/main/scala/cats/effect/unsafe/IORuntimeConfigCompanionPlatform.scala
> +        .env("CATS_EFFECT_CPU_STARVATION_CHECK_INITIALDELAY")
```suggestion
        .env("CATS_EFFECT_CPU_STARVATION_CHECK_INITIAL_DELAY")
```

2022-10-09 00:01 UTC, djspiewak commented on core/native/src/main/scala/cats/effect/unsafe/IORuntimeConfigCompanionPlatform.scala
> +      Option(System.getenv("CATS_EFFECT_CPU_STARVATION_CHECK_INTERNAL"))
```suggestion
      Option(System.getenv("CATS_EFFECT_CPU_STARVATION_CHECK_INTERVAL"))
```

2022-10-09 00:01 UTC, djspiewak commented on core/native/src/main/scala/cats/effect/unsafe/IORuntimeConfigCompanionPlatform.scala
> +      Option(System.getenv("CATS_EFFECT_CPU_STARVATION_CHECK_INITIALDELAY"))
```suggestion
      Option(System.getenv("CATS_EFFECT_CPU_STARVATION_CHECK_INITIAL_DELAY"))
```

This makes me feel like we should find a way to share some of this between JS and Scala Native. Probably not for this PR but something to think about for a follow-up.

2022-10-09 00:01 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/CpuStarvationCheck.scala
> +      |without the `blocking` combinator.""".stripMargin
```suggestion
    """[WARNING] Your CPU is probably starving. Consider increasing the granularity
      |of your delays or adding more cedes. This may also be a sign that you are
      |unintentionally running blocking I/O operations (such as File or InetAddress)
      |without the blocking combinator.""".stripMargin
```

Had a look at `TestControl` and it seems that we skip the backticks usually.

2022-10-10 08:46 UTC, TimWSpence commented on core/js/src/main/scala/cats/effect/unsafe/IORuntimeConfigCompanionPlatform.scala
> +        .env("CATS_EFFECT_CPU_STARVATION_CHECK_INTERNAL")
ouch! Sorry about that!!

2022-10-10 08:49 UTC, TimWSpence commented
> Just need a couple adjustments and then I think we're good to go. I changed the base so we're now pointing to 3.4.x

Thank you!!

2022-10-10 09:39 UTC, TimWSpence commented on core/native/src/main/scala/cats/effect/unsafe/IORuntimeConfigCompanionPlatform.scala
> +      Option(System.getenv("CATS_EFFECT_CPU_STARVATION_CHECK_INITIALDELAY"))
Yes, would be nice!

2022-10-10 17:45 UTC, djspiewak approved these changes
As another follow-up, we should document the new envars and properties.

2022-10-10 17:45 UTC, merged