Add scope to IOLocal
typelevel/cats-effect pull request #3128
Opened 2022-08-17 16:44 UTC by wunderk1nd-e

2022-08-23 09:32 UTC, wunderk1nd-e commented
I think the CI failure might be an unrelated issue (flakiness?)

2022-08-23 09:32 UTC, bplommer commented
Could be nice to have this as an instance method on `IOLocal`?

2022-08-26 14:07 UTC, iRevive commented
What if we use `Resource` instead? From my point of view, it offers better flexibility and composability
```scala
trait IOLocal[A] {
  def scope[A](value: A): Resource[IO, A] =
    Resource.make(local.getAndSet(value))(local.set)
}
```

That way, the scope can be managed for `Resource`, `fs2.Stream`, and `IO`:
```scala
val local: IOLocal[String] = ???

val stream: fs2.Stream[IO, ...] = fs2.Stream.resource(local.scope("my-scope")).evalMap(_ => ???)
val resource: Resource[IO, ...] = local.scope("external").flatMap(_ => ??? >> local.scope("internal"))
val io: IO[...] = local.scope("my-scope").use(_ => ???)
```

2022-09-19 07:10 UTC, djspiewak requested changes
Agreed this should probably be `Resource`, and also would offer better ergonomics as an instance method. Overall though I like this concept!

2022-10-26 18:31 UTC, closed without merging