Record CPU starvation metrics
typelevel/cats-effect pull request #3236
Opened 2022-11-11 11:33 UTC by janstenpickle

Builds on the work by @TimWSpence that adds CPU starvation detection, adding an MBean in the JVM with metrics on how many times starvation has been detected, the maximum clock drift and the current clock drift.

2022-11-11 15:39 UTC, janstenpickle commented on core/jvm/src/main/scala/cats/effect/metrics/CpuStarvationMbeanImpl.scala
> +      if (driftMs > 0) IO.delay(maxClockDrift.updateAndGet(_.max(driftMs))).void
`Ref` seems to reimplement the Java "spin" for updating an atomic reference, I think to avoid conversion of a function to `UnaryOperator` on every modification.

Here the modification will only be performed if drift is detected, so shouldn't happen often, but I'm happy to copy the "spin" in `Ref` if needed!

2022-11-11 23:47 UTC, djspiewak requested changes
Some minor adjustments! This is really great though.

2022-11-11 23:47 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/metrics/CpuStarvationMbeanImpl.scala
> +    lazy val driftMs = drift.toMillis
Minor point, but I think the `lazy` modifier here is meant as a performance optimization, but the allocation of the thunk is definitely more expensive than simply calling the function. :-)

2022-11-11 23:47 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/metrics/CpuStarvationMbeanImpl.scala
> +      if (driftMs > 0) IO.delay(maxClockDrift.updateAndGet(_.max(driftMs))).void
I don't think there's any need to port `Ref`'s spin implementation in this case, but I *would* like if you would use `Math.max` instead of `.max`. The performance difference between the two is several orders of magnitude.

2022-11-11 23:47 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/metrics/JvmCpuStarvationMetrics.scala
> +object JvmCpuStarvationMetrics {
Minor nit, but can we make this `private[effect]` as well?

2022-11-11 23:47 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/metrics/CpuStarvationMetrics.scala
> +object CpuStarvationMetrics {
Should also be `private[effect]`

2022-11-11 23:47 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/metrics/CpuStarvationMetrics.scala
> +  private[effect] def noOp: CpuStarvationMetrics = new CpuStarvationMetrics {
This kind of confused me when I first looked at it. In general, we try to make platform-specific code confined to that particular platform, rather than available everywhere. This might also avoid the `trait` penalty.

2022-11-12 07:00 UTC, janstenpickle commented on core/jvm/src/main/scala/cats/effect/metrics/CpuStarvationMbeanImpl.scala
> +    lazy val driftMs = drift.toMillis
Good to know! I just realised I use it immediately below, so I may as well just change it to a val

2022-11-12 18:28 UTC, djspiewak approved these changes, later dismissed
Thank you!

2022-11-12 21:08 UTC, merged