Fix propagation of `ExitCase` in `Resource#{both,combineK}`
typelevel/cats-effect pull request #3307
Opened 2022-12-06 06:05 UTC by armanbilge

Noticed this while looking into https://github.com/typelevel/cats-effect/pull/3227. `ExitCase`s were not being propagated at all to the finalizers.

2022-12-06 06:09 UTC, armanbilge commented on tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
> +        }
This semantic is kind of counter-intuitive. Even though the left `Resource` errors, ultimately the `combineK`ed `Resource` is acquired and used successfully. So the left finalizer is passed `Succeeded`.

This is a by-product of the fact that the left `Resource` is not released eagerly even if it errors. Maybe this semantic is undesirable?

2022-12-10 04:21 UTC, filipwiech commented on tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
> +        }
After mulling this over I think it makes sense and is expected, although I could be wrong (I went back and forth on this in my mind a couple times before settling on the conclusion). It would be consistent with what `Resource.both` is doing, the reasoning being as follows:

`Resource.both` requires both Resources to be acquired successfully - if any of them errors out (or gets canceled), then all of them get an `ExitCase.Errored` (or `ExitCase.Canceled` respectively), even the one that succeded, because the operation as a whole has failed.

Conversely, `Resource.combineK` needs any of the combined Resources to be acquired successfully - if just one of them succedes, then all of them (well, the ones that were actually evaluated) get an `ExitCase.Succeeded`, even the ones that failed, because the operation as a whole has succeded.

I hope it makes sense. In any case, whichever semantic will be introduced, it could be a good idea to document it in the scaladoc, especially if it seems to be counter-intuitive. 🙂 

However, I'm not sure if any sort of consistency between `Reource.both` and `combineK` is desired. There's also the case of `Resource.race` which will release loser eagerly in #3226.

2022-12-10 04:23 UTC, filipwiech commented on tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
> +        "right errored, test left" >> ticked { implicit ticker =>
Would it be a good idea to document these exit case propagation semantics in the scaladoc for the `Resource#both`? 🙂

2022-12-10 04:28 UTC, filipwiech commented on tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
> +        "use canceled, test left" >> ticked { implicit ticker =>
Would it make sense to add cases for "use errored/canceled, test right" (for when left Resource fails to acquire, but right succedes)? 🙂

2022-12-10 04:57 UTC, filipwiech commented on tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
> +        }
> The fact that ExitCase from the use operation propagates to all the input Resources, regardless of their own, seems to be aligned as well.
One more thought regarding this: one could say that in the case of `combineK` only one Resource is used in the end (similarly to the winner of the `Resource.race`), so there's no need to propagate `ExitCase`  from `use` to the one that wasn't. So I guess that could be one reason to maybe release eagerly in `combineK`. 😄

2022-12-10 10:49 UTC, filipwiech commented on tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
> +        "right canceled, test left" >> ticked { implicit ticker =>
What would happen if right was canceled and left errored out (and vice versa)? Would they both get `ExitCase.Errored`? Maybe it could be a good idea to add tests for those cases. 🙂

2022-12-10 12:40 UTC, filipwiech commented on tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
> +        "left errored, test right" >> ticked { implicit ticker =>
In case one of the Resources errors out during acqusition and the other one self-cancels, will the `ExitCase` of the right Resource propagate/overwrite the result on the left? Could be worth it to add tests for those scenarios. 🙂

2022-12-10 12:43 UTC, filipwiech commented on tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
> +        "left errored, test left" >> ticked { implicit ticker =>
Would it make sense to add tests for "left canceled, test left/right" too? 🙂

2022-12-23 22:16 UTC, djspiewak requested changes
Adding a Request Changes for @filipwiech's suggestions, which are all excellent

2022-12-23 22:20 UTC, armanbilge commented
@djspiewak does that mean you think we should change the `combineK` semantic?

2022-12-24 02:38 UTC, armanbilge commented on tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
> +        "left errored, test left" >> ticked { implicit ticker =>
If left cancels, no resources are acquired, so no finalizers are run.

2022-12-24 02:38 UTC, armanbilge commented on tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
> +        "right canceled, test left" >> ticked { implicit ticker =>
> What would happen if right was canceled and left errored out (and vice versa)?

Depends which happens first. If right cancels first, it's covered by this test. If left errors first it's covered by "left errored, test right"

2022-12-24 02:38 UTC, armanbilge commented on tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
> +        "left errored, test right" >> ticked { implicit ticker =>
If a resource errors out or cancels during acquisition, then it has no exit case because the finalizer never runs.

2022-12-24 02:38 UTC, armanbilge commented on tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
> +        "use canceled, test left" >> ticked { implicit ticker =>
Yes it would!

2022-12-24 02:38 UTC, armanbilge commented on tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
> +        "right errored, test left" >> ticked { implicit ticker =>
Yes, even in two weeks I've forgotten what it was 😂

2022-12-24 17:32 UTC, djspiewak commented on tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
> +        }
I feel like this is somewhat similar to the following:

```scala
case object TestException extends RuntimeException

Resource.raiseError[IO, Unit, Throwable](TestException)
  .onFinalizeCase(IO.println(_))
  .voidError
```

Do we print out `Succeeded` here? If so, then this `combineK` semantic is reasonable. If not, then we're being inconsistent.

2022-12-24 18:40 UTC, armanbilge commented on tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
> +        }
The following program doesn't print.

```scala
//> using lib "org.typelevel::cats-effect::3.4.2"

import cats.effect._
import cats.syntax.all._

object App extends App {
  case object TestException extends RuntimeException

  def run = Resource
    .raiseError[IO, Unit, Throwable](TestException)
    .onFinalizeCase(IO.println(_))
    .voidError
    .use_

}
```

2022-12-24 20:53 UTC, djspiewak commented on tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
> +        }
It prints for me? `Succeeded`. Here's an even more interesting example:

```scala
(Resource.unit.onFinalizeCase(IO.println(_)) *> Resource.raiseError[IO, Unit, Throwable](TestException)).voidError.use_
```

Prints `Succeeded`. Meanwhile:

```scala
(Resource.unit.onFinalizeCase(IO.println(_)) *> Resource.raiseError[IO, Unit, Throwable](TestException)).use_ 
```

Prints `Errored(...)`.

I think `combineK` is fine as-is. It's rather weird, but we're at least consistent with the backpropagation of final state.

2022-12-24 20:53 UTC, djspiewak approved these changes

2022-12-24 20:54 UTC, merged