Use configurable `reportFailure` for `MainThread`
typelevel/cats-effect pull request #3315
Opened 2022-12-12 18:54 UTC by armanbilge

2022-12-13 15:51 UTC, filipwiech approved these changes, later dismissed
Would it be possible to introduce a simple unit test for this change? 🙂

2022-12-23 21:53 UTC, djspiewak requested changes
What @filipwiech said :-)

2022-12-24 01:57 UTC, armanbilge commented on tests/jvm/src/main/scala/catseffect/examplesplatform.scala
> +  }
I wouldn't consider this a simple test exactly (testing `IOApp` never is), but here we are :)

2022-12-24 02:22 UTC, djspiewak approved these changes

2022-12-24 02:29 UTC, merged