ConcurrentAtomicCell
typelevel/cats-effect pull request #3347
Opened 2023-01-05 22:34 UTC by BalmungSan

Adds a `Concurrent` based implementation of `AtomicCell` while leaving the current `Async` based one as a fallback.
In theory, the `Async` one should be more performant; especially if #3346 also improves the performance of `Mutex`.

However, it is not clear if such supposed improvement is worth the trickery did in this PR.
If not, we may just delete the `Async` implementation.

2023-01-05 22:37 UTC, BalmungSan commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +              AtomicCell.concurrent(init)
Is this the right way to also fallback to the `Async` based implementation when the concrete type also has an `Async` instance?

2023-01-05 22:48 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +              AtomicCell.concurrent(init)
All this `Make` stuff? No, we don't need it.

2023-01-05 22:48 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +              AtomicCell.concurrent(init)
Ah, but the pattern match is right 👍

2023-01-05 22:50 UTC, BalmungSan commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +              AtomicCell.concurrent(init)
> All this Make stuff? No, we don't need it.

That is how `Ref` does it, why it is not needed in this case?

> Ah, but the pattern match is right 👍

**Scala 3** says otherwise :(

2023-01-05 22:54 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +              AtomicCell.concurrent(init)
> That is how `Ref` does it, why it is not needed in this case?

You can make a `Ref` with either a `Concurrent` or `Sync`. Note that `Sync` may not be `Concurrent`.

But in this case we are choosing between `Concurrent` or `Async`, but every `Async` is `Concurrent`, so really all we need is `Concurrent` :)

> Scala 3 says otherwise :(

Dare I ask ... what's the error 😅

2023-01-05 23:09 UTC, BalmungSan commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +              AtomicCell.concurrent(init)
> You can make a Ref with either a Concurrent or Sync. Note that Sync may not be Concurrent.

🤦‍♂️

I feel stupid now.

> Dare I ask ... what's the error 😅

Sure:
```
[error] -- [E007] Type Mismatch Error: /home/runner/work/cats-effect/cats-effect/std/shared/src/main/scala/cats/effect/std/AtomicCell.scala:130:37 
[error] 130 |              AtomicCell.async(init)(f)
[error]     |                                     ^
[error]     |Found:    cats.effect.kernel.Concurrent[F] & cats.effect.kernel.Async[?1.CAP]
[error]     |Required: cats.effect.kernel.Async[F]
```

2023-01-05 23:11 UTC, BalmungSan commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +              AtomicCell.concurrent(init)
Uhm, it seems matching `Async[F]` will work...

2023-01-06 00:06 UTC, BalmungSan commented on build.sbt
> +      ProblemFilters.exclude[MissingClassProblem]("cats.effect.std.AtomicCell$Impl")
This exclusion is safe, right?

2023-01-06 02:43 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +    (Ref.of[F, A](init), Mutex[F]).mapN { (ref, m) => new ConcurrentImpl(ref, m) }
Do we have a precedent for leaving these public?

2023-01-06 02:43 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +    def of[A](init: A)(implicit F: Concurrent[F]): F[AtomicCell[F, A]] =
I'm surprised if MiMa is not yelling about this. We need to add a deprecated, source-incompatible signature for bincompat:
```scala
def of[A](init: A, F: Async[F]): ...
```

Same for `empty`.

2023-01-06 02:43 UTC, armanbilge commented on tests/shared/src/test/scala/cats/effect/std/AtomicCellSpec.scala
> +  }
Nice 👍

2023-01-06 03:23 UTC, BalmungSan commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +    (Ref.of[F, A](init), Mutex[F]).mapN { (ref, m) => new ConcurrentImpl(ref, m) }
I was thinking the same.
On one side, I think it is a good idea to let users be explicit if they want.
On the other hand, this may be an internal API subject to change.

2023-01-06 03:24 UTC, BalmungSan commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +    def of[A](init: A)(implicit F: Concurrent[F]): F[AtomicCell[F, A]] =
Shouldn't matter, as you said, an `Async` is a `Concurrent`

2023-01-06 03:57 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +    def of[A](init: A)(implicit F: Concurrent[F]): F[AtomicCell[F, A]] =
It doesn't matter for source-compatibility, but it does matter for binary-compatibility. Binary-compatibility doesn't care about inheritance relationships.

Is MiMa really not warning about this? 😓

2023-01-06 04:02 UTC, BalmungSan commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +    def of[A](init: A)(implicit F: Concurrent[F]): F[AtomicCell[F, A]] =
> Binary-compatibility doesn't care about inheritance relationships

Why wouldn't it? How would dynamic dispatch work otherwise?

> Is MiMa really not warning about this? 😓

Nop.

2023-01-06 04:20 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +    def of[A](init: A)(implicit F: Concurrent[F]): F[AtomicCell[F, A]] =
> Why wouldn't it? How would dynamic dispatch work otherwise?

Not sure what to tell you, that's just how it is :) on the JVM, the binary signature is defined by the precise fully-qualified classnames of the arguments. There is no dynamic dispatch on method arguments, only on `this`.

---

I figured out why MiMa is not warning. It's because of this.
https://github.com/BalmungSan/cats-effect/blob/df9f0ef7cb431c69d3e360e19159e1341704ccbd/std/shared/src/main/scala/cats/effect/std/AtomicCell.scala#L128

It's package-private, so MiMa ignores it even though it is actually public API. The fact this even works is probably due to https://github.com/scala/bug/issues/6794.

I learned this the hard way in FS2, when MiMa didn't warn me and I broke bincompat. See https://github.com/typelevel/fs2/pull/2940#discussion_r916698532.

IMO the only safe thing to do is to make this public.

2023-02-04 21:50 UTC, djspiewak requested changes
Some minor changes. Also can we add benchmarks to decide whether it's worth having the `Async` version?

2023-02-04 21:50 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +      of(M.empty)(F)
I'm pretty sure we don't need this since `Async <: Concurrent`

2023-02-04 21:50 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +    (Ref.of[F, A](init), Mutex[F]).mapN { (ref, m) => new ConcurrentImpl(ref, m) }
I would definitely make these private. :-) They're very internal.

2023-02-04 22:09 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +      of(M.empty)(F)
We do, bin-compatiblity doesn't care about inheritance.

2023-02-04 22:19 UTC, BalmungSan commented
> Also can we add benchmarks to decide whether it's worth having the Async version?

I really would like to benchmark this `Async` version plus the `Async` `Mutex` of #3346 with the `Concurrent` version of both.
However, I have never done proper benchmarking before, is there some guide you would recommend? Also, I guess it would make sense to add those benchmarks to the repo itself.

2023-02-04 22:22 UTC, BalmungSan commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +      of(M.empty)(F)
We already discussed this in one of the _resolved_ reviews. I also thought it wasn't necessary.

2023-02-04 22:34 UTC, BalmungSan commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +    (Ref.of[F, A](init), Mutex[F]).mapN { (ref, m) => new ConcurrentImpl(ref, m) }
Done :)

2023-02-04 22:41 UTC, armanbilge commented
Discussed offline with Luis: I propose we remove the `Async` variant for now, so we can land this PR, which is blocking 3.5.0.

Afterwards we can play with benchmarks and optimizations forward-compatibly, esp. since the performance of an `Async` `AtomicCell` hinges on the performance of an `Async` mutex.

2023-02-04 22:47 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/AtomicCell.scala
> +      of(M.empty)(F)
This surprises me immensely. I thought that `invokevirtual` respected contravariance.

2023-02-04 22:48 UTC, djspiewak commented
Agree with the removing the `Async` version for now.

Regarding how to benchmark… I always copy/paste from the existing benchmarks dir. :-) It's pretty self explanatory.

2023-02-04 23:02 UTC, djspiewak approved these changes

2023-02-04 23:52 UTC, merged