Thread blocking detection
typelevel/cats-effect pull request #3387
Opened 2023-01-27 15:33 UTC by TimWSpence

Attempt to detect erroneous use of `IO.apply` or `IO.delay` to suspend blocking operations, instead of using `IO.blocking` or `IO.interruptible`.

Addresses https://github.com/typelevel/cats-effect/issues/3288.

2023-01-27 15:35 UTC, TimWSpence commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +            if (!parked && (state == Thread.State.BLOCKED || state == Thread
This is the most insane scalafmt I've ever seen 😂

2023-01-28 03:55 UTC, armanbilge commented on build.sbt
> +      ProblemFilters.exclude[DirectMissingMethodProblem]("cats.effect.unsafe.IORuntime.createWorkStealingComputeThreadPool"),
This exclusion is not safe, it's a real bincompat issue :)

2023-01-28 13:46 UTC, TimWSpence commented on build.sbt
> +      ProblemFilters.exclude[DirectMissingMethodProblem]("cats.effect.unsafe.IORuntime.createWorkStealingComputeThreadPool"),
Haha yeah I did wonder about that. What's the right way to handle this again? I tried adding a new method with the extra flag and having the old one delegate to that but I got errors about multiple methods with default arguments

2023-01-28 15:27 UTC, armanbilge commented on build.sbt
> +      ProblemFilters.exclude[DirectMissingMethodProblem]("cats.effect.unsafe.IORuntime.createWorkStealingComputeThreadPool"),
> having the old one delegate to that but I got errors about multiple methods with default arguments

You did it right, just remove the default arguments from the old, deprecated one :)

2023-01-30 14:46 UTC, TimWSpence commented on build.sbt
> +      ProblemFilters.exclude[DirectMissingMethodProblem]("cats.effect.unsafe.IORuntime.createWorkStealingComputeThreadPool"),
🤦 thanks!

2023-01-30 19:33 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
> +  def createWorkStealingComputeThreadPool(
I think we should deprecated it, but keep it public.

2023-01-30 19:35 UTC, armanbilge commented on tests/js/src/main/scala/catseffect/examplesplatform.scala
> +  }
I've been defining the stubs as `IO.never` (see examples above), and just not running them for JS, since this test doesn't make sense on JS anyway.

2023-01-30 19:36 UTC, TimWSpence commented on tests/js/src/main/scala/catseffect/examplesplatform.scala
> +  }
Ah that's why those tests said `IO.never` 🤦 Yeah that's much better 👍

2023-01-30 19:38 UTC, TimWSpence commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
> +  def createWorkStealingComputeThreadPool(
Makes sense 👍 Is `3.5.0` the right version to put? And while we're on the topic, is `series/3.x` the right branch to target?

2023-01-30 19:42 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
> +  def createWorkStealingComputeThreadPool(
Yes, we never add new APIs in a minor branch e.g. 3.4.x, only bug fixes.

2023-02-03 14:26 UTC, durban commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +            while (otherIdx == idx) {
If the pool size is 1, this is an infinite loop.

2023-02-03 14:31 UTC, TimWSpence commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +            while (otherIdx == idx) {
Good point!

2023-02-03 21:50 UTC, djspiewak requested changes

2023-02-03 21:50 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/IOApp.scala
> +  protected def blockedThreadDetectionEnabled: Boolean = false
IMO we should *also* read this from a system property, similar to a lot of the other runtime configuration parameters

2023-02-03 21:50 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +    private[unsafe] val blockedThreadDetectionEnabled: Boolean
Just aesthetically, I kinda prefer `reportFailure` to be last, but that's just me.

2023-02-03 21:50 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +  private[unsafe] val workerThreads: Array[WorkerThread] = new Array(threadCount)
This has performance implications. Why was the visibility changed?

2023-02-03 21:50 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +        |`IO.blocking` or `IO.interruptible` instead.""".stripMargin
Interestingly, in a follow-up PR, we can probably additionally detect if the blocking is coming from an `apply`/`delay` and actually point users at the exact line of code that needs to change.

2023-02-03 21:50 UTC, djspiewak commented on tests/jvm/src/main/scala/catseffect/examplesplatform.scala
> +      loop.start >> IO(Thread.sleep(2.seconds.toMillis))
⛳ 

```suggestion
      IO.unit.foreverM.start >> IO(Thread.sleep(2.seconds.toMillis))
```

2023-02-03 21:50 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +              otherIdx = random.nextInt(pool.workerThreads.length)
Rather than looping, can we go with a more constant-time approach here? Something like:

```suggestion
              otherIdx = (idx + Math.max(1, random.nextInt(pool.workerThreads.length - 1))) % pool.workerThreads.length
```

This would guarantee that `otherIdx` always ends up *not* on `idx` on our second try, so long as there is more than one thread.

2023-02-03 21:50 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +          if (pool.blockedThreadDetectionEnabled && pool.workerThreads.length > 1) {
We should simplify this branch prediction by simply checking the number of worker threads on pool init and overriding `blockedThreadDetectionEnabled` to `false` if it's `1`.

2023-02-05 12:57 UTC, TimWSpence commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +  private[unsafe] val workerThreads: Array[WorkerThread] = new Array(threadCount)
It was changed so that the worker threads could get a handle to the other threads to check the thread state. What are the implications sorry? Are they mitigated by having a `private[effect] def workerThread(idx: Int)` method or something instead?

On a related performance note, I wasn't sure what the logic is for what is worth pre-fetching? The worker thread currently accesses a few things via the reference to the pool and I wasn't sure whether to pre-fetch any of them?

2023-02-05 12:57 UTC, TimWSpence commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +        |`IO.blocking` or `IO.interruptible` instead.""".stripMargin
Good point! Should I do that as part of this change?

2023-02-05 12:58 UTC, TimWSpence commented on tests/jvm/src/main/scala/catseffect/examplesplatform.scala
> +      loop.start >> IO(Thread.sleep(2.seconds.toMillis))
I'm thoroughly ashamed of myself 😂

2023-02-05 13:02 UTC, TimWSpence commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +              otherIdx = random.nextInt(pool.workerThreads.length)
Nice! Is that sufficiently more expensive that we don't want to do this on the first attempt?

2023-02-05 13:43 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +  private[unsafe] val workerThreads: Array[WorkerThread] = new Array(threadCount)
> What are the implications sorry? Are they mitigated by having a `private[effect] def workerThread(idx: Int)` method or something instead?

Yup, see bytecode comparison in https://github.com/typelevel/cats/pull/4314#discussion_r988196572.

2023-02-05 19:12 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +              otherIdx = random.nextInt(pool.workerThreads.length)
I just worry about pathological cases that are hard to track down. I'd rather be constant time if at all possible. If we don't want to do the fancy modular arithmetic thing, IMO the next-best thing would be to just turn the `while` into an `if` above and, if we happen to randomly select our own index, just bail out and get it next time.

2023-02-05 19:12 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +        |`IO.blocking` or `IO.interruptible` instead.""".stripMargin
Let's do it in a follow-up so we don't block this. :-)

2023-02-05 19:15 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +  private[unsafe] val workerThreads: Array[WorkerThread] = new Array(threadCount)
> What are the implications sorry?

The tldr is that bytecode-`private` is more efficient than bytecode-`public` because of the effect it has on the generated assembly (e.g. `private` methods can't be overridden, so it's a static dispatch rather than a dynamic one). Scala takes this a step further because `private[this] val`/`var` turns into a *field* access in the bytecode, meaning you avoid the `invoke`, which is even faster still.

2023-02-07 17:03 UTC, TimWSpence commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +  private[unsafe] val workerThreads: Array[WorkerThread] = new Array(threadCount)
Awesome, many thanks both as always ❤️ This week is quite busy in work but I'll try to turn this around ASAP

2023-02-13 16:41 UTC, TimWSpence commented on core/jvm/src/main/scala/cats/effect/IOApp.scala
> +  protected def blockedThreadDetectionEnabled: Boolean = false
Thus far, the system properties all feed into `IORuntimeConfig` which is shared across all platforms but this is only relevant for the JVM. Is that OK?

2023-02-14 00:18 UTC, djspiewak approved these changes

2023-02-14 00:18 UTC, merged

2023-02-14 16:01 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/IOApp.scala
> +  protected def blockedThreadDetectionEnabled: Boolean = false
Still, even if its configured here, we can read it from a system property. That way it can be enabled without recompiling an app?

Yeah, sorry, a bit late to the part 😝 

Also this will be relevant to Native in the near future.