Even faster async mutex
typelevel/cats-effect pull request #3409
Opened 2023-02-09 18:09 UTC by armanbilge

This PR tries my idea from https://github.com/typelevel/cats-effect/pull/3346#issuecomment-1374040239 of re-using the `UnsafeUnbounded` datastructure from the async queue to implement the async mutex. /cc @BalmungSan 

#### this PR
```
[info] Benchmark                           (fibers)  (iterations)   Mode  Cnt    Score   Error  Units
[info] MutexBenchmark.cancellationAsync          10          1000  thrpt   20   15.434 ± 1.058  ops/s
[info] MutexBenchmark.cancellationAsync         100          1000  thrpt   20    3.203 ± 0.464  ops/s
[info] MutexBenchmark.happyPathAsync             10          1000  thrpt   20  145.271 ± 5.933  ops/s
[info] MutexBenchmark.happyPathAsync            100          1000  thrpt   20   13.297 ± 1.656  ops/s
[info] MutexBenchmark.highContentionAsync        10          1000  thrpt   20   22.955 ± 2.932  ops/s
[info] MutexBenchmark.highContentionAsync       100          1000  thrpt   20    2.953 ± 0.479  ops/s
```
#### series/3.x
```
[info] Benchmark                           (fibers)  (iterations)   Mode  Cnt    Score   Error  Units
[info] MutexBenchmark.cancellationAsync          10          1000  thrpt   20   14.627 ± 1.514  ops/s
[info] MutexBenchmark.cancellationAsync         100          1000  thrpt   20    3.234 ± 0.658  ops/s
[info] MutexBenchmark.happyPathAsync             10          1000  thrpt   20  124.522 ± 7.762  ops/s
[info] MutexBenchmark.happyPathAsync            100          1000  thrpt   20   11.987 ± 0.379  ops/s
[info] MutexBenchmark.highContentionAsync        10          1000  thrpt   20   16.659 ± 2.072  ops/s
[info] MutexBenchmark.highContentionAsync       100          1000  thrpt   20    2.131 ± 0.127  ops/s
```

2023-02-09 18:12 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/package.scala
> +    with scala.util.control.NoStackTrace
Instead of placing this in the package object we could also make a top-level `object FailureSignal extends RuntimeException with NoStackTrace`.

2023-02-09 18:12 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/UnsafeUnbounded.scala
> +private final class UnsafeUnbounded[A] {
Didn't make any changes here, just copy-pasta.

2023-02-09 18:12 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/Mutex.scala
> +          } catch {
There's some fairness corruption here under contention, where an acquirer may cut-in-line of an acquirer that had placed itself in the queue.

2023-02-09 18:14 UTC, BalmungSan commented on std/shared/src/main/scala/cats/effect/std/Mutex.scala
> +          } catch {
Are the FIFO semantics of the current `Mutex` something we would like to preserve? If so, should we be louder about it on the docs?

BTW, does the `Semaphore` based one guarantee that as well?

2023-02-09 18:17 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/Mutex.scala
> +          } catch {
Overall it's still FIFO (or should be, we should add a test if we don't have already). It's just under contention it can be slightly corrupted—but under contention, who was really "first" anyway?

I think this was the long-running debate Daniel and Fabio had for the async queue :)

2023-02-09 18:19 UTC, BalmungSan commented on benchmarks/src/main/scala/cats/effect/benchmarks/MutexBenchmark.scala
> +    mutex.flatMap { m => m.lock.use_.replicateA_(fibers * iterations) }.unsafeRunSync()
I wonder what is the rationale for this change? And why only to the happy path?

2023-02-09 18:23 UTC, armanbilge commented on benchmarks/src/main/scala/cats/effect/benchmarks/MutexBenchmark.scala
> +    mutex.flatMap { m => m.lock.use_.replicateA_(fibers * iterations) }.unsafeRunSync()
Maybe I misunderstood the purpose of the benchmark, but we want to replicate many acquire/releases of the same mutex from the same fiber—we don't need to allocate a new mutex in each iteration, and "fibers" is not really accurate term. It's just iterations in the end.

Actually you are right, we can probably make a similar change to the other benchmarks.

2023-02-09 21:12 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/UnsafeUnbounded.scala
> +private final class UnsafeUnbounded[A] {
Oh, another advantage of pulling this out into a top-level class it is much easier to provide an specialized implementation for JS without `Platform` shenanigans.

2023-02-10 19:35 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/Mutex.scala
> +    private[this] val locked = new AtomicBoolean(false)
If we swap this `AtomicBoolean` for an `AtomicInteger` then do we basically have an `AsyncSemaphore`?

2023-02-14 00:15 UTC, djspiewak requested changes
Minor change

2023-02-14 00:15 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/UnsafeUnbounded.scala
> +private final class UnsafeUnbounded[A] {
I originally planned on pulling it out to the top-level but got lazy.

2023-02-14 00:15 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/package.scala
> +    with scala.util.control.NoStackTrace
I think that *either* approach introduces a memory barrier unless we locally cache the value. If we locally cache the value, then they're the same. I would prefer the top-level object approach, tbh, but we really need to make sure it's pre-cached within scopes.

2023-02-14 01:33 UTC, djspiewak requested changes

2023-02-14 01:33 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/Mutex.scala
> +    private[this] val failureSignal = FailureSignal // prefetch
Super minor thing but I'd prefer if we shadow `FailureSignal` here by prefetching the fully-qualified name. This avoids the need for the backticks, and also prevents people from accidentally introducing memory barriers by referring to the non-prefetched thing.

2023-02-14 01:36 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/Mutex.scala
> +    private[this] val failureSignal = FailureSignal // prefetch
Yeah I thought about this as well. I was more afraid that I would _forget_ to prefetch it, unless I always referred to it under a name only available as a prefetch.

2023-02-14 02:01 UTC, djspiewak approved these changes

2023-02-14 02:01 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/Mutex.scala
> +    private[this] val failureSignal = FailureSignal // prefetch
Well now this way your *only* option is to prefetch.

2023-02-14 02:03 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/Mutex.scala
> +    private[this] val failureSignal = FailureSignal // prefetch
If you remembered to shadow it in the first place 😆 if the shadow doesn't exist in your current scope, you have no way of knowing that you are going through the memory barrier.

2023-02-14 02:09 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/Mutex.scala
> +    private[this] val failureSignal = FailureSignal // prefetch
I feel like we introduce new scopes less often than we introduce new code in scopes. :-P

2023-02-14 02:39 UTC, merged