Add Recipes node with simple example for `Supervisor`
typelevel/cats-effect pull request #3412
Opened 2023-02-14 07:10 UTC by mtomko

This is intended to (begin to) address https://github.com/typelevel/cats-effect/issues/3410

2023-02-14 19:32 UTC, mtomko commented
I may add https://scastie.scala-lang.org/ewn7NUzwSoSPwNSoaL9KBA as an example too, unless people think it's too silly

2023-02-16 18:44 UTC, djspiewak requested changes
My largest concern is this sets a high bar for people who want to add more recipes! 😃 Outstanding work. Minor change but otherwise good to go.

2023-02-16 18:44 UTC, djspiewak commented on docs/recipes.md
> +    }
```suggestion
    Supervisor[IO](await = true).flatMap { supervisor =>
      HttpServer(handler(supervisor)).resource
    }.useForever
```

Could also futz with `ResourceApp` to golf this down even further, but I do think that using `flatMap` rather than `use` here is important.

2023-02-16 18:55 UTC, mtomko commented on docs/recipes.md
> +    }
This looks great, thanks for the suggestion. I wouldn't have thought of `useForever`. Was `use` incorrect or simply unhelpful?

2023-02-16 18:56 UTC, mtomko commented on docs/recipes.md
> +    }
I've committed your suggestion. I'll glance at `ResourceApp`, too, though.

2023-02-16 19:08 UTC, djspiewak approved these changes

2023-02-17 21:35 UTC, merged