Add Recipe presenting real world use case
typelevel/cats-effect pull request #3451
Opened 2023-02-22 00:03 UTC by Wosin

2023-02-22 02:06 UTC, djspiewak requested changes
Should we discuss the `modify` + `flatten` idiom as well?

2023-02-22 02:06 UTC, djspiewak commented on docs/recipes.md
> +  IO.defer(input + 1 )
```suggestion
  IO(input + 1 )
```

:-) I think you meant `delay`, but `apply` is even more concise.

2023-02-22 02:06 UTC, djspiewak commented on docs/recipes.md
> +    IO.defer(input + 1 )
```suggestion
    IO(input + 1 )
```

2023-02-22 02:06 UTC, djspiewak commented on docs/recipes.md
> +```scala mdoc:silet
```suggestion
```scala mdoc:silent
```

2023-02-22 02:06 UTC, djspiewak commented on docs/recipes.md
> +      if(requests >= limit)
```suggestion
      if (requests >= limit)
```

2023-02-22 02:06 UTC, djspiewak commented on docs/recipes.md
> +    cell.evalModify{ requests =>
```suggestion
    cell evalModify { requests =>
```

2023-02-22 09:42 UTC, Wosin commented
Hey, I've actually found simpler example, let me know if that works, I think RateLimiter was a little farfetched.

2023-02-27 17:58 UTC, iRevive commented on docs/recipes.md
> +trait Service{
To keep things consistent. 

```suggestion
trait Service {
```

2023-02-27 17:58 UTC, iRevive commented on docs/recipes.md
> +object StubService extends Service{
```suggestion
object StubService extends Service {
```

2023-02-27 18:09 UTC, iRevive commented on docs/recipes.md
> +    atomicCell evalModify (current => {
```suggestion
    atomicCell evalModify { current => 
```

2023-02-27 18:12 UTC, iRevive commented on docs/recipes.md
> +      requestService.query().map(result =>
I do not have a strong opinion there. A curly bracket feels more idiomatic for a multiline block, but both options are valid.

```suggestion
      requestService.query().map { result => 
```

2023-03-07 17:02 UTC, djspiewak requested changes
Looks very good! Just a couple minor cleanups and then ready to go

2023-03-07 17:02 UTC, djspiewak commented on docs/recipes.md
> +Cats effect provides [Ref](std/ref.md), that we can use to model mutable concurrent reference.
```suggestion
Cats Effect provides [Ref](std/ref.md), that we can use to model mutable concurrent reference. 
```

2023-03-07 17:02 UTC, djspiewak commented on docs/recipes.md
> +  IO(input + 1 )
```suggestion
  IO(input + 1)
```

2023-03-07 17:02 UTC, djspiewak commented on docs/recipes.md
> +      requestService.query().map { result =>
Just trying to be consistent on this one.

```suggestion
      requestService.query() map { result =>
```

2023-03-08 12:35 UTC, iRevive commented on docs/recipes.md
> +    IO(input + 1 )
```suggestion
    IO(input + 1)
```

2023-03-13 08:42 UTC, iRevive commented on docs/recipes.md
> +```scala mcdoc:silent
One last change I believe :) 
```suggestion
```scala mdoc:silent
```

2023-03-29 19:22 UTC, djspiewak approved these changes
I like this example quite a bit. Nicely done!

2023-03-29 19:23 UTC, merged