Add console as config in ioRuntimeConfig, pass it to CPUStarvation
typelevel/cats-effect pull request #3496
Opened 2023-03-15 14:34 UTC by manuelcueto

2023-03-15 16:49 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeConfig.scala
> +    val cpuStarvationConsole: Console[IO]) {
If we are going to put a `Console` into the `IORuntimeConfig`, I wonder if it shouldn't be specific to the cpu starvation check. It might be a good, general purpose logging mechanism to use in other places as well.

2023-03-15 16:50 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntimeConfig.scala
> +    val cpuStarvationConsole: Console[IO]) {
Eh, nevermind, seems both Daniel and I think that an ad-hoc callback hook makes more sense than a `Console` :)

2023-04-15 00:17 UTC, djspiewak approved these changes

2023-04-15 00:19 UTC, djspiewak requested changes

2023-04-15 00:19 UTC, djspiewak commented on core/js/src/main/scala/cats/effect/IOApp.scala
> +  protected def onCpuStarvationWarn: CpuStarvationWarningMetrics => IO[Unit] =
Actually one quick nit: shouldn't this be a method, rather than a function?

```suggestion
  protected def onCpuStarvationWarn(metrics: CpuStarvationWarningMetrics): IO[Unit] =
```

It means we can't define it in a point-free fashion, but the users are much more likely to define this in a non-point-free fashion, similar to `reportFailure`.

2023-05-02 17:08 UTC, manuelcueto commented on core/js/src/main/scala/cats/effect/IOApp.scala
> +  protected def onCpuStarvationWarn: CpuStarvationWarningMetrics => IO[Unit] =
Will look into this tomorrow morning.  👍  Thanks for the review

2023-05-03 14:22 UTC, djspiewak approved these changes

2023-05-03 14:22 UTC, djspiewak commented
Thank you for taking this on!

2023-05-03 14:23 UTC, merged