Add Lock to std
typelevel/cats-effect pull request #3542
Opened 2023-04-17 22:42 UTC by kevchuang

Resolves #3535

2023-04-18 01:26 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/Lock.scala
> +}
I suspect we should have an implementation here as well, apart from just `HotSwap`. People are almost certainly going to try to do `Lock[IO].flatMap(lock => ...)` and wonder why it doesn't work. :-D

2023-04-18 02:52 UTC, djspiewak requested changes
Forgot to note the requested changes in the PR state :-)

2023-04-18 13:01 UTC, durban commented on std/shared/src/main/scala/cats/effect/std/Hotswap.scala
> +sealed trait Hotswap[F[_], R] extends Lock[F] {
I'm not sure `Hotswap` should extend `Lock` – it seems more like an implementation detail of `Hotswap`.

2023-04-25 17:06 UTC, djspiewak approved these changes
LGTM!

2023-04-25 17:14 UTC, armanbilge requested changes

2023-04-25 17:14 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/Lock.scala
> +}
We may want to consider adding some other APIs here. For example:
```scala
  def tryShared: Resource[F, Boolean]
  def tryExclusive: Resource[F, Boolean]
```

Also should check Chris's lib for inspiration.

2023-04-25 17:14 UTC, armanbilge commented on std/shared/src/main/scala/cats/effect/std/Lock.scala
> +    }
We should add a test for this implementation. For example to verify that the exclusive lock is indeed exclusive.

2023-04-25 17:41 UTC, kevchuang commented on std/shared/src/main/scala/cats/effect/std/Lock.scala
> +}
Understood ! I'm working on that !

2023-04-26 22:38 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/Lock.scala
> +    }
Definitely should be tested. It occurred to me the other day that I just didn't catch that; thanks for being on it, Arman. :-)

2023-04-26 23:07 UTC, ChristopherDavenport commented
Not sure this is as much enough for folks that want with traditional locking.

Like its an approach, but locks are decently diverse.

2026-03-08 18:25 UTC, closed without merging