Setup CI release
typelevel/cats-effect pull request #3577
Opened 2023-04-29 09:11 UTC by armanbilge

*flashes* **Get-Out-of-Faraday-Cage-Free™** *card*

2023-04-29 09:14 UTC, armanbilge commented on build.sbt
> +ThisBuild / githubWorkflowArtifactDownloadExtraKeys += "ci"
So that we also download JS and Native artifacts.

2023-04-29 09:14 UTC, armanbilge commented on build.sbt
> +  )
Straightforward Node.js action that just polls the GHA Checks API for status of the Cirrus CI jobs.

https://github.com/armanbilge/await-cirrus

2023-04-29 14:57 UTC, djspiewak requested changes

2023-04-29 14:57 UTC, djspiewak commented on build.sbt
> +  )
Just to avoid bus factor, probably better to have it under the typelevel org.

2023-05-02 22:35 UTC, djspiewak approved these changes

2023-05-02 22:36 UTC, merged