Proof-of-concept thread-local `IOLocal`s
typelevel/cats-effect pull request #3636
Opened 2023-05-16 19:34 UTC by armanbilge

Still needs quite a bit of work, but wanted to sketch the basic idea.

Goal: to expose a fiber's `IOLocal`s as `ThreadLocal`s within a side-effecting block, so that they can be accessed and modified in unsafe land. 

Motivation: basically telemetry Java interop.
- https://github.com/typelevel/otel4s/issues/202
- https://github.com/typelevel/natchez/issues/706

Constraints: to do this as safely as possible 😅

2023-05-16 19:39 UTC, armanbilge commented on core/jvm/src/main/java/cats/effect/IOFiberConstants.java
> +  static final boolean dumpLocals = Boolean.getBoolean("cats.effect.tracing.dumpLocals");
Bikesheddable configuration for opting-in. So the rest of us don't have to pay the penalty 😇

2023-05-16 19:39 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +          }
I did this just for `delay`, but I guess `blocking` and `interruptible` would want it too.

2023-05-16 19:39 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IOLocals.scala
> +final class IOLocals private[effect] (private[this] var state: IOLocalState) {
Ok, so I was extremely lazy with implementing this thing. But the main idea of this wrapper API is that it should only give the user access to `IOLocal`s that they know about i.e. they should not able to clear out other locals that happen to be present.

2023-05-16 23:55 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +          }
Even better, no more allocation here 😅

2023-05-16 23:55 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IOLocals.scala
> +  def reset[A](iol: IOLocal[A]): Unit = threadLocal.set(threadLocal.get() - iol)
Ok, this API seems pretty reasonable. Static methods, should be even callable from Java 😅

2023-05-17 00:17 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IOLocals.scala
> +  }
Special-cased `WorkerThread` so it's just a field access instead of a map lookup 😎

2023-05-17 01:04 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +      if (IOFiberConstants.dumpLocals) unsafe.IOLocals.getState else Map.empty,
We can even go in the opposite direction for `IO#unsafeRun*` 😁 

It's less clear if/how to do this for fibers started in a `Dispatcher`, since they should be inheriting locals from the fiber backing the `Dispatcher`.

2023-05-18 02:23 UTC, rossabaker reviewed
Interesting.  I will try to give a snapshot of this a shot over on the otel4s side.

2023-05-18 02:23 UTC, rossabaker commented on core/jvm/src/main/java/cats/effect/IOFiberConstants.java
> +  static final boolean dumpLocals = Boolean.getBoolean("cats.effect.tracing.dumpLocals");
Is this specifically "tracing", even if that's the most obvious use case?

2023-05-18 02:23 UTC, rossabaker commented on core/shared/src/main/scala/cats/effect/unsafe/IOLocals.scala
> +      threadLocal.set(threadLocal.get() + (iol -> value))
Does this idiom compile to something more efficient than boring old pattern matching?

```
thread match {
  case thread: WorkerThread =>...
  case thread => ...
}

2023-05-18 02:25 UTC, armanbilge commented on core/jvm/src/main/java/cats/effect/IOFiberConstants.java
> +  static final boolean dumpLocals = Boolean.getBoolean("cats.effect.tracing.dumpLocals");
Oh woops, this was a very lazy copy-pasta. I copied it from the system properties we use to configure fiber tracing. We should rename it anyway, `dumpLocals` is not quite right I think 😅

2023-05-18 02:26 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IOLocals.scala
> +      threadLocal.set(threadLocal.get() + (iol -> value))
Only if you're superstitious. Daniel is 😜

2023-05-18 03:30 UTC, satorg commented on core/shared/src/main/scala/cats/effect/unsafe/IOLocals.scala
> +      threadLocal.set(threadLocal.get() + (iol -> value))
Well, at least for Scala 2.13.10 this snippet
```scala
class WorkerThread extends Thread {
  var modifyMe: Int = _
}

abstract class Test {
  def doSomethingElse(): Unit

  def testIf(thread: Thread): Unit = {
    if (thread.isInstanceOf[WorkerThread])
      thread.asInstanceOf[WorkerThread].modifyMe += 1
    else
      doSomethingElse()
  }

  def testMatch(thread: Thread): Unit = {
    thread match {
      case wt: WorkerThread => wt.modifyMe += 1
      case _ => doSomethingElse()
    }
  }
}
```
produces the following result (according to CFR):
```java
public abstract class Test {
    public abstract void doSomethingElse();

    public void testIf(Thread thread) {
        if (thread instanceof WorkerThread) {
            WorkerThread workerThread = (WorkerThread)thread;
            workerThread.modifyMe_$eq(workerThread.modifyMe() + 1);
            return;
        }
        this.doSomethingElse();
    }

    public void testMatch(Thread thread) {
        Thread thread2 = thread;
        if (thread2 instanceof WorkerThread) {
            WorkerThread workerThread = (WorkerThread)thread2;
            workerThread.modifyMe_$eq(workerThread.modifyMe() + 1);
            return;
        }
        this.doSomethingElse();
    }
}
```

2023-05-21 03:00 UTC, armanbilge commented on core/jvm/src/main/java/cats/effect/IOFiberConstants.java
> +public final class IOFiberConstants {
This is not good. To avoid this we'll either have to replicate it at both the `cats.effect` and `cats.effect.unsafe` levels, or move the thread-local `IOLocals` helpers into `cats.effect`.

2023-06-23 14:31 UTC, kevin-lee commented
I apologise for jumping in and asking this question but, can it be used as an alternative to [Local](https://monix.io/docs/current/execution/local.html) from Monix?
 I need it specifically for logging, much like what's explained in the post, ["Better logging with Monix 3, part 1: MDC"](https://web.archive.org/web/20230201063241/https://olegpy.com/better-logging-monix-1/) but with cats-effect 3. This has been a blocker for my company's transition from cats-effect 2 with Monix to cats-effect 3. The issue has become increasingly critical as more and more libraries cease to support cats-effect 2, choosing to support only cats-effect 3 instead. So it would be great to see if there's any upcoming solution.

2023-06-23 15:03 UTC, armanbilge commented
@kevin-lee no problem! At a glance, yes, this does look like an alternative/replacement to that Monix feature. Perhaps @alexandru can confirm :)

2023-06-28 14:10 UTC, kevin-lee commented on core/jvm/src/main/java/cats/effect/IOFiberConstants.java
> +  static final boolean dumpLocals = Boolean.getBoolean("cats.effect.tracing.dumpLocals");
What about `cats.effect.localContextPropagation` similar to Monix's `monix.environment.localContextPropagation`?

2023-06-28 14:15 UTC, kevin-lee commented
> @kevin-lee no problem! At a glance, yes, this does look like an alternative/replacement to that Monix feature. Perhaps @alexandru can confirm :)

@armanbilge Thank you. That's great!
It looks quite similar and looks like it can be used for the same purpose, but I can see the methods in `IOLocals` taking `IOLocal[A]` whereas the methods in [`Local`](https://github.com/monix/monix/blob/f2cca0d895d26831ba8c4b90746eab648ad3bb12/monix-execution/shared/src/main/scala-2/monix/execution/misc/Local.scala#L254) from Monix don't. So I'm wondering if it can be used for the same purpose. I need to use it in a logging library like Logback, which doesn't have `IO` or any effect.
Yeah, it would be nice if @alexandru can confirm this.

2023-06-28 14:31 UTC, armanbilge commented
> but I can see the methods in `IOLocals` taking `IOLocal[A]` whereas the methods in [`Local`](https://github.com/monix/monix/blob/f2cca0d895d26831ba8c4b90746eab648ad3bb12/monix-execution/shared/src/main/scala-2/monix/execution/misc/Local.scala#L254) from Monix don't. So I'm wondering if it can be used for the same purpose. I need to use it in a logging library like Logback, which doesn't have `IO` or any effect.

@kevin-lee the `IOLocal[A]` is just the "key". Once you have that key (and you can build one unsafely outside of the effect) then you don't need any more effects to read and write it.

For an example integration, see this PR with implements a Java SPI using this `IOLocals` API.
- https://github.com/typelevel/otel4s/pull/214

2023-06-28 14:39 UTC, kevin-lee commented
> @kevin-lee the `IOLocal[A]` is just the "key". Once you have that key (and you can build one unsafely outside of the effect) then you don't need any more effects to read and write it.
> 
> For an example integration, see this PR which implements a Java SPI using this `IOLocals` API.
> 
> * [Experimental IOLocalContextStorage otel4s#214](https://github.com/typelevel/otel4s/pull/214)

@armanbilge Oh... got it. It looks very promising then. Thank you!

2023-06-28 18:17 UTC, armanbilge commented on core/jvm/src/main/java/cats/effect/IOFiberConstants.java
> +  static final boolean dumpLocals = Boolean.getBoolean("cats.effect.tracing.dumpLocals");
Thanks, I liked that! I went with `cats.effect.ioLocalPropagation`.

2023-06-28 22:16 UTC, armanbilge commented
@kubukoz @kevin-lee I published this PR as `3.6-02a43a6` to Maven if you want to experiment with it :) I'm going to update Ross' PR to use this latest snapshot.

2023-06-29 01:26 UTC, kubukoz commented
Awesome! I tried it out:

```scala
//> using scala "2.13.10"
//> using lib "org.typelevel::cats-effect:3.6-02a43a6"
import cats.effect.IOApp
import cats.effect.IO
import cats.effect.IOLocal
import cats.effect.unsafe.implicits._
import cats.effect.unsafe.IOLocals
import scala.jdk.CollectionConverters._
import cats.implicits._

object Demo extends IOApp.Simple {
  val init = Map("hello" -> "world")

  def run: IO[Unit] = IOLocal(init)
    .flatMap { loggingCtx =>
      def pureLog(msg: String) = loggingCtx.get.flatMap { ctx =>
        IO.println(s"$ctx: $msg")
      }

      def impureLog(msg: String) = IO.blocking {
        val ctx = IOLocals.get(loggingCtx)
        println(s"$ctx: $msg")
      }

      loggingCtx.set(init ++ Map("extra" -> "cats")) *>
        pureLog("msg with full context") *>
        impureLog("impure msg with full context")

    }

}

```

Weirdly, this gives me something I did not expect:

```
Map(hello -> world, extra -> cats): msg with full context
Map(hello -> world): impure msg with full context
```

Apparently the `set` doesn't get propagated all the way to my `IOLocals.get`. What could I be doing wrong?

2023-06-29 01:29 UTC, armanbilge commented
@kubukoz Thanks for trying it! Did you enable it via the system property? `-Dcats.effect.ioLocalPropagation=true`, surely there's a scala-cli way to do that.

2023-06-29 01:30 UTC, kubukoz commented
y'all gotta start writing docs in PR descriptions :P

2023-06-29 01:32 UTC, armanbilge commented
> I suppose the reason not to make this the default is perf?

That's a good point. We could enable it by default and make it opt-out, after all we enable tracing by default and that has a non-trivial performance cost. I'll defer to Daniel for the final decision on this.

2023-06-29 02:17 UTC, kubukoz commented
alright, I have logback.

```scala
//> using scala "2.13.10"
//> using lib "org.typelevel::cats-effect:3.6-02a43a6"
//> using lib "ch.qos.logback:logback-classic:1.4.8"
//> using resourceDir "./resources"
//> using javaProp "cats.effect.ioLocalPropagation=true"
package demo

import cats.effect.IO
import cats.effect.IOApp
import cats.effect.IOLocal
import cats.effect.unsafe.IOLocals
import cats.effect.unsafe.implicits._
import cats.implicits._
import ch.qos.logback.classic.LoggerContext
import ch.qos.logback.classic.spi.LogbackServiceProvider
import ch.qos.logback.classic.util.LogbackMDCAdapter
import ch.qos.logback.core.Appender
import ch.qos.logback.core.AppenderBase
import ch.qos.logback.core.spi.AppenderAttachable
import ch.qos.logback.core.spi.AppenderAttachableImpl
import ch.qos.logback.core.status.StatusManager
import org.slf4j.LoggerFactory
import org.slf4j.MDC
import org.slf4j.helpers.BasicMDCAdapter
import org.slf4j.spi.MDCAdapter

import java.{util => ju}
import scala.jdk.CollectionConverters._
import scala.util.Using

object Globals {
  lazy val loggingCtx = IOLocal(Map("hello" -> "world")).unsafeRunSync()
}

import Globals._

class CatsAppender[E] extends AppenderBase[E] with AppenderAttachable[E] {
  private val aai = new AppenderAttachableImpl[E]()

  override protected def append(
    eventObject: E
  ): Unit = Using.Manager { man =>
    IOLocals.get(loggingCtx).foreach { case (k, v) =>
      man {
        MDC.putCloseable(k, v)
      }
    }

    aai.appendLoopOnAppenders(eventObject)
  }

  // just proxying to AAI

  override def addAppender(newAppender: Appender[E]): Unit = aai.addAppender(newAppender)

  override def iteratorForAppenders(): ju.Iterator[Appender[E]] = aai.iteratorForAppenders()

  override def getAppender(name: String): Appender[E] = aai.getAppender(name)

  override def isAttached(appender: Appender[E]): Boolean = aai.isAttached(appender)

  override def detachAndStopAllAppenders(): Unit = aai.detachAndStopAllAppenders()

  override def detachAppender(x: Appender[E]): Boolean = aai.detachAppender(x)

  override def detachAppender(x: String): Boolean = aai.detachAppender(x)

}

object Demo extends IOApp.Simple {
  val logger = LoggerFactory.getLogger(getClass())

  implicit class LoggingOps[A](ioa: IO[A]) {

    def withContext(f: Map[String, String]) = loggingCtx.get.flatMap { ctx =>
      loggingCtx.set(ctx ++ f) *> ioa <* loggingCtx.set(ctx)
    }

  }

  def logWithContext(msg: String) = loggingCtx.get.flatMap { ctx =>
    IO.println(s"hello:${Console.CYAN}${ctx
        .getOrElse("hello", "")}${Console.RESET} extra:${Console.MAGENTA}${ctx
        .getOrElse("extra", "")}${Console.RESET} $msg")
  }

  def run: IO[Unit] =
    logWithContext("init ctx, pure") *>
      IO.blocking(logger.info("init ctx, impure")) *>
      loggingCtx.update(_ + ("extra" -> "cats")) *>
      logWithContext("full ctx, pure") *>
      IO.blocking(logger.info("full ctx, impure")) *>
      loggingCtx.set(Map.empty) *>
      logWithContext("empty ctx, pure") *>
      IO.blocking(logger.info("empty ctx, impure"))

}
```

logback.xml in `resources`:

```xml
<configuration>
  <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
    <layout>
      <Pattern>hello:%cyan(%X{hello:-}) extra:%magenta(%X{extra:-}) %msg%n</Pattern>
    </layout>
  </appender>

  <appender name="CATS" class="demo.CatsAppender">
    <appender-ref ref="CONSOLE"/>
  </appender>

  <root level="debug">
    <appender-ref ref="CATS"/>
  </root>
</configuration>
```

2023-07-03 09:30 UTC, kevin-lee commented
@armanbilge Oh that's great! Thanks Arman.
Sorry it will take some time to write test for my case. I'll share it as soon as it's done.

2023-07-07 13:40 UTC, kevin-lee commented
Apologies for the delay. I had to create a Monix version for comparison with the Cats Effect 3 version. I'm still testing the CE3 one, but I plan to finish testing this weekend and will share the results then.

2023-07-09 09:16 UTC, kevin-lee commented
My code is [here](https://github.com/kevin-lee/logger-f/blob/5a7b5ad5340e3459d8a043a2c219bed24bbb14f8/modules/logger-f-logback-mdc-cats-effect3/shared/src/main/scala/loggerf/logger/logback/Ce3MdcAdapter.scala) and my test code is
```scala

import cats.effect._
import ch.qos.logback.classic.encoder.PatternLayoutEncoder
import ch.qos.logback.classic.spi.ILoggingEvent
import ch.qos.logback.classic.{Level, Logger, LoggerContext}
import ch.qos.logback.core.ConsoleAppender
import org.slf4j.LoggerFactory
import cats.syntax.all._
import org.slf4j.MDC

object TestApp extends IOApp.Simple {
  println(s"cats.effect.ioLocalPropagation=${sys.props.getOrElse("cats.effect.ioLocalPropagation", "")}")
  sys.props.put("cats.effect.ioLocalPropagation", "true")
  println(s"cats.effect.ioLocalPropagation=${sys.props.getOrElse("cats.effect.ioLocalPropagation", "")}")
  Ce3MdcAdapter.initialize()

  implicit val logger: Logger = {

    val loggerContext = LoggerFactory.getILoggerFactory.asInstanceOf[LoggerContext]

    val encoder = new PatternLayoutEncoder()
    encoder.setContext(loggerContext)
    encoder.setPattern("[%-5level] [%highlight(%thread)][Id=%boldCyan(%X{myId})]: %msg %n")
    encoder.start

    val consoleAppender = new ConsoleAppender[ILoggingEvent]
    consoleAppender.setContext(loggerContext)
    consoleAppender.setEncoder(encoder)
    consoleAppender.start

    val logger = LoggerFactory.getLogger("MyLogger").asInstanceOf[Logger]
    logger.addAppender(consoleAppender)
    logger.setLevel(Level.INFO)
    logger.setAdditive(false)

    logger
  }

  override def run: IO[Unit] = {
    logger.info("""Start""")
    logger.info("""Before MDC.put("myId", "0")""")
    MDC.put("myId", "0")
    logger.info("""After MDC.put("myId", "0")""")
    for {
      _ <- IO.unit
      _ = logger.info(""""Before run fiber - before MDC.put("myId", "999")""")
      _ = MDC.put("myId", "999")
      _ = logger.info("""Before run fiber - after MDC.put("myId", "999")""")
      a <- req("1", "Clark")
      b <- req("2", "Bruce")
      c <- req("3", "Diana")
      _ <- (a.joinWithNever, b.joinWithNever, c.joinWithNever).parMapN((_, _, _) => ())
      _ = logger.info("[0] After join all - logger.info")
      _ <- IO(logger.info("[1] After join all - IO(logger.info)"))
      _ = logger.info("[2] After join all - logger.info")
    } yield ()
  }

  def req(requestId: String, userName: String): IO[FiberIO[Unit]] = (
    IO {
      logger.info(s"""Before MDC.put("myId", $requestId)""")
      MDC.put("myId", requestId)
      logger.info(s"""After MDC.put("myId", $requestId)""")
      logger.info(s"Received a request to create a user $userName")
    }.flatMap { _ =>
      IO(())
        .flatMap(_ => IO(()))
    }.flatMap(_ => registerUser(userName))
  ).start

  def registerUser(name: String): IO[Unit] = IO {
    logger.info(s"Registering a new user named $name")
  }

}
```
This is the result I got
<img width="981" alt="Screenshot 2023-07-09 at 7 08 05 pm" src="https://github.com/typelevel/cats-effect/assets/2307335/4b736ed5-0b77-4a21-9c81-f5592dc5c12a">

I'm wondering why there's no `Id` for
```
[INFO ] [io-compute-3][Id=]: "Before run fiber - before MDC.put("myId", "999") 
```
and
```
[INFO ] [io-compute-2][Id=]: [0] After join all - logger.info 
```

I also put the code in Scastie, but unfortunately, the log color is messed up even when I set no color for the log.
https://scastie.scala-lang.org/kevin-lee/2RBs3JJfRteaC2T9SJuL2Q/2

All the libraries I used
```sbt
Seq(
  "org.slf4j" % "slf4j-api" % "2.0.6",
  "ch.qos.logback" % "logback-classic" % "1.4.7",
  "io.kevinlee" % "logback-scala-interop" % "0.1.0",
  "org.typelevel" %% "cats-effect" % "3.6-02a43a6"
)
```

2023-07-09 11:15 UTC, armanbilge commented
@kevin-lee thanks for giving that a try!

Note that `IOLocal`-propagation will only work correctly for side-effecting code that is properly suspended. So you should replace:
```scala
_ = logger.info(...)
```
with
```scala
_ <- IO(logger.info(...))
```

2023-07-09 11:25 UTC, kevin-lee commented
@armanbilge But if you see this code,
```scala
      _ = logger.info("[0] After join all - logger.info")
      _ <- IO(logger.info("[1] After join all - IO(logger.info)"))
      _ = logger.info("[2] After join all - logger.info")
```
the result is
```
[INFO ] [io-compute-0][Id=]: [0] After join all - logger.info 
[INFO ] [io-compute-0][Id=0]: [1] After join all - IO(logger.info) 
[INFO ] [io-compute-0][Id=0]: [2] After join all - logger.info 
```
The third one has no `IO`, but it works fine.

***
Also the very first put and get without `IO`
```scala
    logger.info("""Before MDC.put("myId", "0")""")
    MDC.put("myId", "0")
    logger.info("""After MDC.put("myId", "0")""")
```
shows
```
[INFO ] [main][Id=]: Start 
[INFO ] [main][Id=]: Before MDC.put("myId", "0") 
[INFO ] [main][Id=0]: After MDC.put("myId", "0") 
```
That `0` for `Id` seems to be passed to the rest of `IO` ones.
***

I need the logs from the libraries, which do not use `IO`, to get the context-specific data (e.g. userId, IP, device, etc.) from that `MDC`.

2023-07-09 11:36 UTC, armanbilge commented
> But if you see this code,

I'm not sure what you specifically mean by "works fine". For sure, in some specific cases, you may not be able to notice the issue i.e. that example is not sophisticated enough. But in general as you start modifying the MDC both directly as an `IOLocal` and unsafely, you will start to observe weird issues if you are not properly suspending your side-effecting blocks.

---

> Also the very first put and get without `IO`

Yes, the `main` thread is special-cased, because that's the thread that `unsafeRun`s the `IO`.

---

> I need the logs from the libraries, which do not use `IO`

Yes, sure, absolutely :) the key thing is not that that each log needs to be surrounded in `IO`. It's that the _entire action_ is in `IO`. So something like this would be 100% okay:

```scala
_ <- IO(LibraryThatDoesNotUseIO.doManyManyThings())`
```

2023-07-09 14:33 UTC, kevin-lee commented
@armanbilge Ok, got it. I'll change the test code and check it again. Thank you!

2023-07-11 10:12 UTC, kevin-lee commented
@armanbilge Could you please check if these new tests and results are all OK?

![io-local-01](https://github.com/typelevel/cats-effect/assets/2307335/55d9f993-37e1-4173-a52d-2bb4d5697a32)

***

![io-local-02](https://github.com/typelevel/cats-effect/assets/2307335/9d0daecc-6368-4b09-948f-a88505056879)

2023-09-03 17:30 UTC, henricook commented
> I apologise for jumping in and asking this question but, can it be used as an alternative to [Local](https://monix.io/docs/current/execution/local.html) from Monix? I need it specifically for logging, much like what's explained in the post, ["Better logging with Monix 3, part 1: MDC"](https://web.archive.org/web/20230201063241/https://olegpy.com/better-logging-monix-1/) but with cats-effect 3. This has been a blocker for my company's transition from cats-effect 2 with Monix to cats-effect 3. The issue has become increasingly critical as more and more libraries cease to support cats-effect 2, choosing to support only cats-effect 3 instead. So it would be great to see if there's any upcoming solution.

I'm sorry I'm not adding anything to the issue here other than a big upvote ⬆️ for giving us refugees from `Monix` a replacement for `TaskLocal` that propagates. It's also blocking our migration.

We use `TaskLocal` like an `AuditContext` - one of the effects we execute determines that a user's access token is good and stores information about that user in an `AuditContext` instance on `TaskLocal`.

That means when we write to the database (for example) we can record who caused a change without having to past an implicit _everywhere_ or making all our functions take an `F[_]: AuditContext`-like type param.

I think this work will let us achieve that? Although I don't immediately see IOLocal's propagating after adding `3.6-02a43a6` to my project, enabling the flag, and praying.

2023-09-03 17:38 UTC, henricook commented
This might be amazingly naive, but is this a good piece of code that I'd expect to work with this?

```scala
import cats.effect.{ExitCode, IO, IOApp, IOLocal}

object PropagationApp extends IOApp {

  case class MyAuditContext(name: String)

  val myLocal = IOLocal[Option[MyAuditContext]](None)

  def run(args: List[String]): IO[ExitCode] =
    for {
      _           <- IO.println("hello")
      local1      <- myLocal
      _           <- local1.set(Some(MyAuditContext("John Smith")))
      local1Value <- local1.get
      _           <- IO.println(s"Local Out 1 = ${local1Value}")
      local2      <- myLocal
      local2Value <- local2.get
      _           <- IO.println(s"Local Out 2 = ${local2Value}")
    } yield ExitCode.Success
}
```

Currently:

```
hello
Local Out 1 = Some(MyAuditContext(John Smith))
Local Out 2 = None
```

And I think I'd expect both Local Outs to be `Some`?

2023-09-03 20:40 UTC, kubukoz commented
@henricook aren't you able to capture locals before any writes to the database, without the "unsafe propagation" part? What kind of library are you using for database writes, then?

2023-09-03 22:11 UTC, djspiewak requested changes

2023-09-03 22:11 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +            IOLocals.setState(localState)
Dumb question: can't we simply do this when we get scheduled on a thread? We know when we're on a thread and we know when we get off of it, so can't we simply set and clear the state respectively at those points?

2023-09-03 22:11 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/IOLocals.scala
> +object IOLocals {
I (begrudgingly) think this is a somewhat reasonable API. Kinda sucks but this is definitely a thing people run into.

2023-09-03 22:11 UTC, djspiewak commented on tests/jvm/src/test/scala/cats/effect/unsafe/IOLocalsSpec.scala
> +    "return a default value" in ticked { implicit ticker =>
We should probably do all of these as `real` specs instead, since we definitely want to see this working across thread yields and such.

To that end, I'd like to see things working across multiple fibers with `cede`s and `async` boundaries.

2023-09-03 22:26 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +            IOLocals.setState(localState)
No we can't, unless we unify how the state represented. Currently it's a var to an immutable map in the fiber and also in the thread. While the fiber is running its copy of the var may be updated effectually in the runloop so the thread-local copy would need to be kept in sync with that. Or we could drive all updates through the thread-local copy of the var, but then there would be a penalty for accessing it esp. if we are not running on a worker thread.

Putting aside technical issues, nobody should be unsafely messing about with `IOLocal`s outside of a properly suspended side-effect block and this strategy enforces that.

2023-09-04 07:06 UTC, henricook commented
I'm overwhelmingly happy to report that this MR has successfully replaced our usage of Monix's `TaskLocal`. It's really fortuitous timing for us and will save us a lot of retrofitting in our migration.

With some helpful tips along the way from Arman here's an abbreviated before and after example that just stores an AuditContext object in `*Local` with a single `requestId` key:

Caveat: I've assembled this from compiling files but I haven't compiled the examples I've typed in below:

With Monix Task:

```scala
import monix.eval.Task
import monix.execution.misc.Local

case class AuditContext(
  request: RequestId,
)

object AuditContext {
  private[this] val taskLocalInstance = Local[Option[AuditContext]](None)

  def getTaskLocal: Option[AuditContext] = taskLocalInstance()

  private def setTaskLocal(context: AuditContext): Unit =
    taskLocalInstance.update(Some(context))

  def requestId: Option[RequestId] = getTaskLocal.flatMap(_.requestId)

  def beginRequest(requestId: RequestId): Unit = {
    AuditContext.setTaskLocal(
     AuditContext(
        requestId
     )
   )
  }
}
```

With this branch in `cats-effect` `3.6-02a43a6` and an app running with `-D cats.effect.ioLocalPropagation=true`:

```scala
import cats.effect.unsafe.{IOLocals, IORuntime}
import cats.effect.{IO, IOLocal}

case class AuditContext(
  request: RequestId,
)

object AuditContext {
  // Notes: Here's an example using .syncStep which I gather is a good thing, and obviously your IORuntime.global might vary: https://github.com/typelevel/otel4s/blob/fe7259e6dc3f2af3019912b8d786ba484b052692/java/common/src/main/scala/org/typelevel/otel4s/java/IOLocalContextStorageProvider.scala#L26-L37
  // unsafeRunSync'ing this is important, or you'll generate a new IOLocal every time and it won't do what you expect
  private[this] val ioLocalInstance = IOLocal[Option[AuditContext]](None).unsafeRunSync()(IORuntime.global)

  // Unlike in Monix `get`s are wrapped - in an `IO`
  def getIOLocal: IO[Option[AuditContext]] = ioLocalInstance.get

  private def setIOLocal(context: AuditContext): Unit =
     IOLocals.set(ioLocalInstance, Some(context))

  def requestId: Option[RequestId] = getIOLocal.map(_.map(_.requestId))

  def beginRequest(requestId: RequestId): Unit = {
    AuditContext.setIOLocal(
     AuditContext(
        requestId
     )
   )
  }
}

```

2023-09-04 17:08 UTC, henricook commented
Testing this out with a `/ping` endpoint on a Play Framework controller, which I think replicates my situation doesn't seem to give me the results that I'd expect. I'm intentionally mixing things up with ConnectionIOs here because it replicates my app where we might want to access Audit information stored in the IOLocal from database-writing code.

```scala
def dbLogger =  ??? // Add your logging preferences here
def logger = ???

    def ping: Action[AnyContent] = Action.async { _ =>
    val io = {
      val dbOps = for {
        _ <- sql"""SELECT 2""".query[Int].unique
        _ <- dbLogger.warn(s"=== AuditContext in CIO Unsafe = ${AuditContext.getIOLocalUnsafe}")
        _ = AuditContext.setIOLocalUnsafe(
              AuditContext(action = BusinessAction("OOOOO Changed in CIO", JsObject.empty))
            )
      } yield ()

      AuditContext.setIOLocalUnsafe(
        AuditContext(
          action = BusinessAction("Test2", JsObject.empty)
        )
      )

      for {
        _   <- logger.warn(s"=== AC 1 UnSafe = ${AuditContext.getIOLocalUnsafe}")
        _   <- dbOps.transact(cc.db.innerTransactor)
        _   <- logger.warn(s"=== AC 2 UnSafe = ${AuditContext.getIOLocalUnsafe}")
        res <- IO.pure(Ok("PONG"))
        _   <- logger.warn(s"=== AC 3 UnSafe = ${AuditContext.getIOLocalUnsafe}")
      } yield res
    }

    io.unsafeToFuture()(IORuntime.global)
  }
  ```
  
  And that implementation of `AuditContext`:
  
  ```scala
object AuditContext {
  private[this] val ioLocalInstance = IOLocal[Option[AuditContext]](None).unsafeRunSync()(IORuntime.global)

  def getIOLocalUnsafe: Option[AuditContext] = IOLocals.get(ioLocalInstance)

  def setIOLocalUnsafe(context: AuditContext): Unit =
    IOLocals.set(ioLocalInstance, Some(context))
}
  ```

2023-09-05 10:21 UTC, henricook commented
Despite IOLocal generally being unsuitable for our main TaskLocal usage I am planning on using it for a `LocalMdcAdapter` i.e. Logback MDC. As this is all set quite early on in our requests lifetime the fact that it can't be modified later on (i.e. after ConnectionIOs) isn't much of a problem:

```
import cats.effect.IOLocal
import cats.effect.unsafe.{IOLocals, IORuntime}
import ch.qos.logback.classic.util.LogbackMDCAdapter

import java.{util => ju}

class LocalMdcAdapter extends LogbackMDCAdapter {

  private[this] val map =
    IOLocal[ju.Map[String, String]](new ju.HashMap[String, String]()).unsafeRunSync()(IORuntime.global)

  override def put(key: String, `val`: String): Unit = {
    IOLocals.update(
      map
    ) { theMap =>
      theMap.put(key, `val`)
      theMap
    }
  }

  override def get(key: String): String = IOLocals.get(map).get(key)

  override def remove(key: String): Unit =
    IOLocals.update(map) { theMap =>
      theMap.remove(key)
      theMap
    }

  // Note: we're resetting the Local to default, not clearing the actual hashmap
  override def clear(): Unit =
    IOLocals.update(map) {
      theMap =>
        theMap.clear()
        theMap
    }

  override def getCopyOfContextMap: ju.Map[String, String] = IOLocals.get(map)

  override def setContextMap(contextMap: ju.Map[String, String]): Unit = {
    IOLocals.update(map) { _ => contextMap }
    new ju.HashMap(contextMap)
  }

  override def getPropertyMap: ju.Map[String, String] = IOLocals.get(map)
  override def getKeys: ju.Set[String]                = IOLocals.get(map).keySet()
}
```

2023-09-25 19:45 UTC, NthPortal commented on core/jvm/src/main/java/cats/effect/unsafe/IOLocalsConstants.java
> +  static final boolean ioLocalPropagation = Boolean.getBoolean("cats.effect.ioLocalPropagation");
it would be very helpful if this was exposed to the end user in some way so that they can check if it's enabled and potentially raise an error if not (for example, we don't want people trying to use an `IOLocal`-backed `ContextStorageProvider` and its associated `Local` in otle4s if this value is `false`)

2023-09-25 19:54 UTC, armanbilge commented on core/jvm/src/main/java/cats/effect/unsafe/IOLocalsConstants.java
> +  static final boolean ioLocalPropagation = Boolean.getBoolean("cats.effect.ioLocalPropagation");
Great point. fa99a5cf46a791f81723a570fd38e42fead04ae5, wdyt?

2023-09-25 20:19 UTC, NthPortal commented on core/jvm/src/main/java/cats/effect/unsafe/IOLocalsConstants.java
> +  static final boolean ioLocalPropagation = Boolean.getBoolean("cats.effect.ioLocalPropagation");
lgtm, cheers!

2023-09-25 22:43 UTC, kubukoz commented on core/jvm/src/main/java/cats/effect/unsafe/IOLocalsConstants.java
> +  static final boolean ioLocalPropagation = Boolean.getBoolean("cats.effect.ioLocalPropagation");
very cool!

2023-09-26 14:17 UTC, kevin-lee commented on core/jvm/src/main/java/cats/effect/unsafe/IOLocalsConstants.java
> +  static final boolean ioLocalPropagation = Boolean.getBoolean("cats.effect.ioLocalPropagation");
That's a great suggestion. I also wanted to ask something similar.
Could this be a more explicit option type like Monix's so that more options can be added when necessary?
* https://github.com/monix/monix/blob/952034ad4884b64fb4241d78f33fdef07f267157/monix-eval/shared/src/main/scala/monix/eval/Task.scala#L4466-L4470
* https://github.com/monix/monix/blob/952034ad4884b64fb4241d78f33fdef07f267157/monix-execution/jvm/src/main/scala/monix/execution/internal/Platform.scala#L134-L137

2023-09-26 14:35 UTC, armanbilge commented on core/jvm/src/main/java/cats/effect/unsafe/IOLocalsConstants.java
> +  static final boolean ioLocalPropagation = Boolean.getBoolean("cats.effect.ioLocalPropagation");
> Could this be a more explicit option type

You mean so that it can be configured by user-code at runtime?

The advantage of using system properties with static final fields is that their values are constant at JVM startup, which allows the JIT to optimize those branches. Allowing dynamic configuration would circumvent that.

Or if I missed your point, sorry, please explain 😅 note we also have a lot of configuration available in `IORuntimeConfig` class which can be configured programmatically at runtime.

2023-09-27 20:42 UTC, NthPortal commented on core/shared/src/main/scala/cats/effect/unsafe/IOLocals.scala
> +  def propagating: Boolean = ioLocalPropagation
small bikeshed: do you think `isPropagating` or `propagates` might be a better name?

2023-09-27 22:23 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IOLocals.scala
> +  def propagating: Boolean = ioLocalPropagation
Hmm, maybe `arePropagating` (as in "`IO` locals are propagating")?

Or `propagate` as in "`IO` locals do propagate" ... but that sounds more like a toggle for implementor (should I propagate or not).

2023-09-28 22:42 UTC, NthPortal commented on core/shared/src/main/scala/cats/effect/unsafe/IOLocals.scala
> +  def propagating: Boolean = ioLocalPropagation
`arePropagating` sounds nice

2023-09-29 13:41 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IOLocals.scala
> +  def propagating: Boolean = ioLocalPropagation
```suggestion
  def arePropagating: Boolean = ioLocalPropagation
```

2023-09-30 10:55 UTC, kevin-lee commented on core/jvm/src/main/java/cats/effect/unsafe/IOLocalsConstants.java
> +  static final boolean ioLocalPropagation = Boolean.getBoolean("cats.effect.ioLocalPropagation");
@armanbilge Oh, I didn't mean to configure it at runtime. I meant that it would be good to have a proper type for setting local propagation instead of having just `Boolean`.
But, I got your point of `static final`, so please ignore what I said. 😅

2023-09-30 16:05 UTC, armanbilge commented on core/jvm/src/main/java/cats/effect/unsafe/IOLocalsConstants.java
> +  static final boolean ioLocalPropagation = Boolean.getBoolean("cats.effect.ioLocalPropagation");
> I meant that it would be good to have a proper type for setting local propagation instead of having just `Boolean`.

Got it, thanks :) Monix also seems to be using just a `Boolean` for setting local propagation anyway. The difference is that it allows it to be configured dynamically per task.

https://github.com/monix/monix/blob/952034ad4884b64fb4241d78f33fdef07f267157/monix-eval/shared/src/main/scala/monix/eval/Task.scala#L4406

2023-09-30 16:45 UTC, armanbilge commented
I did a quick benchmark and this feature is definitely not free 😕 

`ioLocalPropagation=false`
```
[info] Benchmark                (size)   Mode  Cnt     Score     Error  Units
[info] DeepBindBenchmark.delay   10000  thrpt   20  4161.322 ± 553.643  ops/s
```

`ioLocalPropagation=true`
```
[info] Benchmark                (size)   Mode  Cnt     Score     Error  Units
[info] DeepBindBenchmark.delay   10000  thrpt   20  3382.086 ± 279.254  ops/s
```

2023-09-30 17:13 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +            IOLocals.setState(localState)
What we _can_ do is set the current fiber in a thread local every time we get scheduled on a thread. Then the unsafe `IOLocals` manipulations can operate on the state via the current fiber and we don't need to pay the penalty for every `delay` block. Based on the benchmarks this strategy is seeming more attractive 😅 

Note this would leave the fiber's `IOLocal` state exposed to unsafe manipulations outside of `delay` blocks.

2023-11-15 21:45 UTC, NthPortal commented
@armanbilge what's the status of this?

2023-11-15 22:21 UTC, armanbilge commented
I intend to land this in the upcoming v3.6.0 release (no ETA for this yet, but I'll make a milestone). The benchmarks I posted above for the initial implementation were disappointing, but I still need to benchmark the new implementation that I pushed in 3589db441f70f47562a2d360a19533a437000a99.

2023-11-29 13:39 UTC, kevin-lee commented
@armanbilge That's great. Thank you! I'm sure you can optimize it afterwards, and in the meantime, it would be extremely useful for people who need this feature.

2023-11-29 16:57 UTC, armanbilge commented
> I'm sure you can optimize it afterwards

Unfortunately it's not so simple. The performance impact I reported before was for _all_ users of Cats Effect, including those who are not using this feature. We want to avoid slowing down the entire runtime for everyone, because that would be a serious regression. So before we can release this, we need to minimize its impact on existing users who do not need this feature.

Still I'm optimistic about the performance of the revised implementation. Will report updated benchmarks, soon ...

2024-01-02 20:34 UTC, henricook commented
How'd it go @armanbilge ? If you've had time

2024-01-30 03:12 UTC, djspiewak requested changes
I think I've come round to the opinion this is a necessary evil, it's just bikeshedding some of the API and vetting out a few concerns about the implementation.

2024-01-30 03:12 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +private[effect] final class WorkerThread[P](
Fwiw, this is redundant. `private` on top-level entities is always equivalent to package-private.

2024-01-30 03:12 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +      implicit runtime: unsafe.IORuntime): IOFiber[A @uncheckedVariance] =
Is this needed?

2024-01-30 03:12 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOLocal.scala
> +  private[effect] abstract class AbstractIOLocal[A] extends IOLocal[A] {}
Is this used for anything?

2024-01-30 03:12 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/IOLocals.scala
> +  def arePropagating: Boolean = ioLocalPropagation
```suggestion
  def isPropagating: Boolean = ioLocalPropagation
```

Slightly more idiomatic naming.

2024-01-30 03:12 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/IOLocals.scala
> +object IOLocals {
Random thought… would it be more reasonable to have an `IOLocal#unsafeThreadLocal` method instead? It's basically the same API, avoids the need to have package private stuff, and has a chance of being slightly more compatible for the one or two APIs out there which take explicit `ThreadLocal`s. Also I realize this has probably been suggested at some point and I *probably* shot it down but I'm starting to think it could be the lesser evil.

2024-01-30 03:12 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +
Oh this is so annoying…

Okay, to make this slightly *less* annoying, can we project out a super `trait` of `IOFiber` which just covers the `IOLocal` state manipulating stuff? At least that way we're making it very clear what the API is intended to accomplish.

2024-01-30 03:12 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    }
We definitely need to do some careful benchmarking here. This particular bit is very sensitive to inliner shenanigans.

2024-01-30 03:12 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +  private[effect] var currentIOFiber: IOFiber[_] = _
As mentioned in Discord, I really would prefer if we fixed `_active`. I get that we will still need the fall-through to `ThreadLocal` when we're off the WSTP, but that way we could at least optimize the happy path a bit more. Also, even more importantly, it would avoid creating a second field which is almost but not entirely duplicative with the first field in `WorkerThread`.

2024-04-22 16:32 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +  private[effect] var currentIOFiber: IOFiber[_] = _
Sorry, finally circling back to this.

> As mentioned in Discord, I really would prefer if we fixed `_active`.

So the reason that I don't like `_active` is that it does a lot of (useful) shenanigans that make it difficult to reason about.

For example, here is some code in `LocalQueue`.

https://github.com/typelevel/cats-effect/blob/5d73623923da4f0adc3e56f1a4bb352c26ab9f98/core/jvm/src/main/scala/cats/effect/unsafe/LocalQueue.scala#L365-L368

In an ideal world, a `Runnable` would be set as `active` at the exact time when it is `run()` and unset immediately after. But because `_active` is intended to be used for fiber dumps, it relies on non-local cleverness to try and publish more aggressively.

`_active` optimizes for visibility but this makes it hard to reason about.

Meanwhile `currentIOFiber` doesn't have visibility concerns, so its easier to write a correct implementation.

2024-05-29 19:21 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +  private[effect] var currentIOFiber: IOFiber[_] = _
For posterity, we've decided to live with the duplication for now, and we'll ticket out future work to clean it up since it's fully internal.

2024-06-05 00:16 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +private[effect] final class WorkerThread[P](
It's not actually :) `WorkerThread` is in `cats.effect.unsafe`, this exposes it to `cats.effect`.

2024-06-05 00:17 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IOLocals.scala
> +  def arePropagating: Boolean = ioLocalPropagation
Previously bikeshed in https://github.com/typelevel/cats-effect/pull/3636#discussion_r1340726643 but I switched to `isPropagating`.

2024-06-05 00:18 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/unsafe/IOLocals.scala
> +object IOLocals {
Yeah, I like this idea! 👍 Also reduces our API surface.

2024-06-05 00:19 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    }
We meaning you 😛

2024-06-05 00:20 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +
Not entirely sure what you mean but I'll play the too internally bikesheddy card for now.

2024-06-05 00:20 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +      implicit runtime: unsafe.IORuntime): IOFiber[A @uncheckedVariance] =
Is what needed exactly? But either way the answer is "yes" 🤣

2024-06-05 00:45 UTC, armanbilge commented on core/js-native/src/main/scala/cats/effect/IOFiberConstants.scala
> +  final val ioLocalPropagation = false
Since JS/Native currently lack a mechanism to eliminate branches based on system properties at link- or run-time we just hard-code to `false` to DCE at compile-time.

2024-06-05 00:45 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/IOLocalPlatform.scala
> +  def unsafeThreadLocal(): ThreadLocal[A] = if (ioLocalPropagation)
This is the new API based on the `ThreadLocal` interface. Thoughts?

1. I made it JVM-only. We could definitely support this on JS/Native but I'm not yet convinced that there is a good reason to do so: no Java libs to interop with and performance implications.

2. We could make this a `lazy val` (or similar) instead. Creating the `ThreadLocal` "view" isn't observably effectual.

3. If `ioLocalPropagation == false` it throws an `UnsupportedOperationException`. Libraries can check `IOLocal.isPropagating` before deciding to call this method.

    Alternatively we could return a no-op `ThreadLocal` that never sets and always returns the default value.

2024-06-07 03:22 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
> +private[effect] final class WorkerThread[P](
Oh I misread the file path.

2024-06-07 03:22 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +      implicit runtime: unsafe.IORuntime): IOFiber[A @uncheckedVariance] =
I meant the `uncheckedVariance` I think, but yeah it makes sense since `IOFiber` is invariant.

2024-06-07 03:23 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    }
Yeah yeah yeah… Give me a pair of shas! :)

2024-06-07 03:24 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/IOLocalPlatform.scala
> +  def unsafeThreadLocal(): ThreadLocal[A] = if (ioLocalPropagation)
I think this is great, all of it.

2024-07-04 03:39 UTC, djspiewak commented
Finished benchmarking. @armanbilge let's see your armchair performance reasoning explain this result. I'm at a loss.

## Before

```
[info] Benchmark                                             (cpuTokens)   (size)   Mode  Cnt      Score     Error    Units
[info] DeepBindBenchmark.async                                       N/A    10000  thrpt   10   2786.655 ±   3.536    ops/s
[info] DeepBindBenchmark.delay                                       N/A    10000  thrpt   10   9613.496 ± 234.106    ops/s
[info] DeepBindBenchmark.pure                                        N/A    10000  thrpt   10  11168.222 ± 465.787    ops/s
[info] MapCallsBenchmark.batch120                                    N/A      N/A  thrpt   10    338.430 ±   3.116    ops/s
[info] MapCallsBenchmark.batch30                                     N/A      N/A  thrpt   10     86.709 ±   0.563    ops/s
[info] MapCallsBenchmark.one                                         N/A      N/A  thrpt   10      2.944 ±   0.017    ops/s
[info] MapStreamBenchmark.batch120                                   N/A      N/A  thrpt   10   5561.435 ±  14.217    ops/s
[info] MapStreamBenchmark.batch30                                    N/A      N/A  thrpt   10   2524.134 ±   2.286    ops/s
[info] MapStreamBenchmark.one                                        N/A      N/A  thrpt   10   3233.048 ±   4.027    ops/s
[info] ParallelBenchmark.parTraverse                               10000     1000  thrpt   10    886.610 ±   0.865    ops/s
[info] ParallelBenchmark.traverse                                  10000     1000  thrpt   10     70.460 ±   0.067    ops/s
[info] ShallowBindBenchmark.async                                    N/A    10000  thrpt   10   2031.729 ±   3.593    ops/s
[info] ShallowBindBenchmark.delay                                    N/A    10000  thrpt   10   9778.303 ±  62.426    ops/s
[info] ShallowBindBenchmark.pure                                     N/A    10000  thrpt   10  11973.770 ±  32.027    ops/s
[info] WorkStealingBenchmark.alloc                                   N/A  1000000  thrpt   10     14.152 ±   0.090  ops/min
[info] WorkStealingBenchmark.manyThreadsSchedulingBenchmark          N/A  1000000  thrpt   10     31.868 ±   5.072  ops/min
[info] WorkStealingBenchmark.runnableScheduling                      N/A  1000000  thrpt   10    870.238 ±   3.475  ops/min
[info] WorkStealingBenchmark.runnableSchedulingScalaGlobal           N/A  1000000  thrpt   10   2245.542 ±   7.645  ops/min
[info] WorkStealingBenchmark.scheduling                              N/A  1000000  thrpt   10     29.631 ±   2.092  ops/min
```

## After

```
[info] Benchmark                                             (cpuTokens)   (size)   Mode  Cnt      Score     Error    Units
[info] DeepBindBenchmark.async                                       N/A    10000  thrpt   10   2814.793 ±   6.982    ops/s
[info] DeepBindBenchmark.delay                                       N/A    10000  thrpt   10   9589.880 ±  27.294    ops/s
[info] DeepBindBenchmark.pure                                        N/A    10000  thrpt   10  11377.434 ±  37.080    ops/s
[info] MapCallsBenchmark.batch120                                    N/A      N/A  thrpt   10    336.483 ±   2.160    ops/s
[info] MapCallsBenchmark.batch30                                     N/A      N/A  thrpt   10     85.833 ±   0.404    ops/s
[info] MapCallsBenchmark.one                                         N/A      N/A  thrpt   10      2.925 ±   0.007    ops/s
[info] MapStreamBenchmark.batch120                                   N/A      N/A  thrpt   10   5684.510 ±   8.954    ops/s
[info] MapStreamBenchmark.batch30                                    N/A      N/A  thrpt   10   2522.568 ±   7.291    ops/s
[info] MapStreamBenchmark.one                                        N/A      N/A  thrpt   10   3284.312 ±   2.895    ops/s
[info] ParallelBenchmark.parTraverse                               10000     1000  thrpt   10    891.486 ±   0.846    ops/s
[info] ParallelBenchmark.traverse                                  10000     1000  thrpt   10     70.303 ±   0.060    ops/s
[info] ShallowBindBenchmark.async                                    N/A    10000  thrpt   10   1985.424 ±   2.771    ops/s
[info] ShallowBindBenchmark.delay                                    N/A    10000  thrpt   10   9655.691 ± 182.608    ops/s
[info] ShallowBindBenchmark.pure                                     N/A    10000  thrpt   10  10075.531 ±  22.884    ops/s
[info] WorkStealingBenchmark.alloc                                   N/A  1000000  thrpt   10     14.044 ±   0.078  ops/min
[info] WorkStealingBenchmark.manyThreadsSchedulingBenchmark          N/A  1000000  thrpt   10     48.611 ±   1.642  ops/min
[info] WorkStealingBenchmark.runnableScheduling                      N/A  1000000  thrpt   10   2987.595 ±   5.299  ops/min
[info] WorkStealingBenchmark.runnableSchedulingScalaGlobal           N/A  1000000  thrpt   10   2249.480 ±  48.568  ops/min
[info] WorkStealingBenchmark.scheduling                              N/A  1000000  thrpt   10     52.240 ±   3.133  ops/min
```

2024-07-04 18:50 UTC, djspiewak commented
@armanbilge I really can't explain these results

## Before

```
[info] Benchmark                                             (cpuTokens)   (size)   Mode  Cnt      Score     Error    Units
[info] DeepBindBenchmark.async                                       N/A    10000  thrpt   10   2786.655 ±   3.536    ops/s
[info] DeepBindBenchmark.delay                                       N/A    10000  thrpt   10   9613.496 ± 234.106    ops/s
[info] DeepBindBenchmark.pure                                        N/A    10000  thrpt   10  11168.222 ± 465.787    ops/s
[info] MapCallsBenchmark.batch120                                    N/A      N/A  thrpt   10    338.430 ±   3.116    ops/s
[info] MapCallsBenchmark.batch30                                     N/A      N/A  thrpt   10     86.709 ±   0.563    ops/s
[info] MapCallsBenchmark.one                                         N/A      N/A  thrpt   10      2.944 ±   0.017    ops/s
[info] MapStreamBenchmark.batch120                                   N/A      N/A  thrpt   10   5561.435 ±  14.217    ops/s
[info] MapStreamBenchmark.batch30                                    N/A      N/A  thrpt   10   2524.134 ±   2.286    ops/s
[info] MapStreamBenchmark.one                                        N/A      N/A  thrpt   10   3233.048 ±   4.027    ops/s
[info] ParallelBenchmark.parTraverse                               10000     1000  thrpt   10    886.610 ±   0.865    ops/s
[info] ParallelBenchmark.traverse                                  10000     1000  thrpt   10     70.460 ±   0.067    ops/s
[info] ShallowBindBenchmark.async                                    N/A    10000  thrpt   10   2031.729 ±   3.593    ops/s
[info] ShallowBindBenchmark.delay                                    N/A    10000  thrpt   10   9778.303 ±  62.426    ops/s
[info] ShallowBindBenchmark.pure                                     N/A    10000  thrpt   10  11973.770 ±  32.027    ops/s
[info] WorkStealingBenchmark.alloc                                   N/A  1000000  thrpt   10     14.152 ±   0.090  ops/min
[info] WorkStealingBenchmark.manyThreadsSchedulingBenchmark          N/A  1000000  thrpt   10     31.868 ±   5.072  ops/min
[info] WorkStealingBenchmark.runnableScheduling                      N/A  1000000  thrpt   10    870.238 ±   3.475  ops/min
[info] WorkStealingBenchmark.runnableSchedulingScalaGlobal           N/A  1000000  thrpt   10   2245.542 ±   7.645  ops/min
[info] WorkStealingBenchmark.scheduling                              N/A  1000000  thrpt   10     29.631 ±   2.092  ops/min
```

## After

```
[info] Benchmark                                             (cpuTokens)   (size)   Mode  Cnt      Score     Error    Units
[info] DeepBindBenchmark.async                                       N/A    10000  thrpt   10   2814.793 ±   6.982    ops/s
[info] DeepBindBenchmark.delay                                       N/A    10000  thrpt   10   9589.880 ±  27.294    ops/s
[info] DeepBindBenchmark.pure                                        N/A    10000  thrpt   10  11377.434 ±  37.080    ops/s
[info] MapCallsBenchmark.batch120                                    N/A      N/A  thrpt   10    336.483 ±   2.160    ops/s
[info] MapCallsBenchmark.batch30                                     N/A      N/A  thrpt   10     85.833 ±   0.404    ops/s
[info] MapCallsBenchmark.one                                         N/A      N/A  thrpt   10      2.925 ±   0.007    ops/s
[info] MapStreamBenchmark.batch120                                   N/A      N/A  thrpt   10   5684.510 ±   8.954    ops/s
[info] MapStreamBenchmark.batch30                                    N/A      N/A  thrpt   10   2522.568 ±   7.291    ops/s
[info] MapStreamBenchmark.one                                        N/A      N/A  thrpt   10   3284.312 ±   2.895    ops/s
[info] ParallelBenchmark.parTraverse                               10000     1000  thrpt   10    891.486 ±   0.846    ops/s
[info] ParallelBenchmark.traverse                                  10000     1000  thrpt   10     70.303 ±   0.060    ops/s
[info] ShallowBindBenchmark.async                                    N/A    10000  thrpt   10   1985.424 ±   2.771    ops/s
[info] ShallowBindBenchmark.delay                                    N/A    10000  thrpt   10   9655.691 ± 182.608    ops/s
[info] ShallowBindBenchmark.pure                                     N/A    10000  thrpt   10  10075.531 ±  22.884    ops/s
[info] WorkStealingBenchmark.alloc                                   N/A  1000000  thrpt   10     14.044 ±   0.078  ops/min
[info] WorkStealingBenchmark.manyThreadsSchedulingBenchmark          N/A  1000000  thrpt   10     48.611 ±   1.642  ops/min
[info] WorkStealingBenchmark.runnableScheduling                      N/A  1000000  thrpt   10   2987.595 ±   5.299  ops/min
[info] WorkStealingBenchmark.runnableSchedulingScalaGlobal           N/A  1000000  thrpt   10   2249.480 ±  48.568  ops/min
[info] WorkStealingBenchmark.scheduling                              N/A  1000000  thrpt   10     52.240 ±   3.133  ops/min
```

2024-07-04 18:50 UTC, djspiewak commented
## Before

```
[info] Benchmark                                             (cpuTokens)   (size)   Mode  Cnt      Score     Error    Units
[info] DeepBindBenchmark.async                                       N/A    10000  thrpt   10   2786.655 ±   3.536    ops/s
[info] DeepBindBenchmark.delay                                       N/A    10000  thrpt   10   9613.496 ± 234.106    ops/s
[info] DeepBindBenchmark.pure                                        N/A    10000  thrpt   10  11168.222 ± 465.787    ops/s
[info] MapCallsBenchmark.batch120                                    N/A      N/A  thrpt   10    338.430 ±   3.116    ops/s
[info] MapCallsBenchmark.batch30                                     N/A      N/A  thrpt   10     86.709 ±   0.563    ops/s
[info] MapCallsBenchmark.one                                         N/A      N/A  thrpt   10      2.944 ±   0.017    ops/s
[info] MapStreamBenchmark.batch120                                   N/A      N/A  thrpt   10   5561.435 ±  14.217    ops/s
[info] MapStreamBenchmark.batch30                                    N/A      N/A  thrpt   10   2524.134 ±   2.286    ops/s
[info] MapStreamBenchmark.one                                        N/A      N/A  thrpt   10   3233.048 ±   4.027    ops/s
[info] ParallelBenchmark.parTraverse                               10000     1000  thrpt   10    886.610 ±   0.865    ops/s
[info] ParallelBenchmark.traverse                                  10000     1000  thrpt   10     70.460 ±   0.067    ops/s
[info] ShallowBindBenchmark.async                                    N/A    10000  thrpt   10   2031.729 ±   3.593    ops/s
[info] ShallowBindBenchmark.delay                                    N/A    10000  thrpt   10   9778.303 ±  62.426    ops/s
[info] ShallowBindBenchmark.pure                                     N/A    10000  thrpt   10  11973.770 ±  32.027    ops/s
[info] WorkStealingBenchmark.alloc                                   N/A  1000000  thrpt   10     14.152 ±   0.090  ops/min
[info] WorkStealingBenchmark.manyThreadsSchedulingBenchmark          N/A  1000000  thrpt   10     31.868 ±   5.072  ops/min
[info] WorkStealingBenchmark.runnableScheduling                      N/A  1000000  thrpt   10    870.238 ±   3.475  ops/min
[info] WorkStealingBenchmark.runnableSchedulingScalaGlobal           N/A  1000000  thrpt   10   2245.542 ±   7.645  ops/min
[info] WorkStealingBenchmark.scheduling                              N/A  1000000  thrpt   10     29.631 ±   2.092  ops/min
```

## After

```
[info] Benchmark                                             (cpuTokens)   (size)   Mode  Cnt      Score     Error    Units
[info] DeepBindBenchmark.async                                       N/A    10000  thrpt   10   2814.793 ±   6.982    ops/s
[info] DeepBindBenchmark.delay                                       N/A    10000  thrpt   10   9589.880 ±  27.294    ops/s
[info] DeepBindBenchmark.pure                                        N/A    10000  thrpt   10  11377.434 ±  37.080    ops/s
[info] MapCallsBenchmark.batch120                                    N/A      N/A  thrpt   10    336.483 ±   2.160    ops/s
[info] MapCallsBenchmark.batch30                                     N/A      N/A  thrpt   10     85.833 ±   0.404    ops/s
[info] MapCallsBenchmark.one                                         N/A      N/A  thrpt   10      2.925 ±   0.007    ops/s
[info] MapStreamBenchmark.batch120                                   N/A      N/A  thrpt   10   5684.510 ±   8.954    ops/s
[info] MapStreamBenchmark.batch30                                    N/A      N/A  thrpt   10   2522.568 ±   7.291    ops/s
[info] MapStreamBenchmark.one                                        N/A      N/A  thrpt   10   3284.312 ±   2.895    ops/s
[info] ParallelBenchmark.parTraverse                               10000     1000  thrpt   10    891.486 ±   0.846    ops/s
[info] ParallelBenchmark.traverse                                  10000     1000  thrpt   10     70.303 ±   0.060    ops/s
[info] ShallowBindBenchmark.async                                    N/A    10000  thrpt   10   1985.424 ±   2.771    ops/s
[info] ShallowBindBenchmark.delay                                    N/A    10000  thrpt   10   9655.691 ± 182.608    ops/s
[info] ShallowBindBenchmark.pure                                     N/A    10000  thrpt   10  10075.531 ±  22.884    ops/s
[info] WorkStealingBenchmark.alloc                                   N/A  1000000  thrpt   10     14.044 ±   0.078  ops/min
[info] WorkStealingBenchmark.manyThreadsSchedulingBenchmark          N/A  1000000  thrpt   10     48.611 ±   1.642  ops/min
[info] WorkStealingBenchmark.runnableScheduling                      N/A  1000000  thrpt   10   2987.595 ±   5.299  ops/min
[info] WorkStealingBenchmark.runnableSchedulingScalaGlobal           N/A  1000000  thrpt   10   2249.480 ±  48.568  ops/min
[info] WorkStealingBenchmark.scheduling                              N/A  1000000  thrpt   10     52.240 ±   3.133  ops/min
```

2024-07-28 21:36 UTC, djspiewak commented
Finally scraped together the time needed to shave a few dev environment yaks and test this PR with propagation *enabled*. The performance hit is about 25% on microbenchmarks involving `delay` or `map`, and (as expected) ~0% (within margin of error) on everything else. The bizarre acceleration of WSTP scheduling on non-`parTraverse` benchmarks remains consistent (notably, `parTraverse` itself was around 0%).

So I think the summary of this PR, from a performance standpoint, is the following:

- When **disabled**, no meaningful impact.
  + Does seem to spookily effect the WSTP microbenchmarks in a way which resets the baseline
- When **enabled**, 25% worse on `delay`/`map` microbenchmarks
  + No effect within margin of error on scheduling or `traverse`-y benchmarks
  + WSTP microbenchmark baseline effect remains and is of the same magnitude

So enabling this is analogous to enabling cached tracing, but of course would be cumulative with that flag as well, so technically turning both of them on would bop your microbenchmark scores by something like 55%. It's very unclear whether this type of performance impact *matters* in practice. We would probably need to run some end-to-end scale tests with propagation enabled in order to see.

Given that this is default-off and the impact when *disabled* is zero (outside of the still bizarre WSTP microbenchmark mirages), I'm comfortable merging this as-is and we can do some further testing. We should also probably document (or at least, write a ticket to document) the performance effects so it doesn't surprise anyone.

2024-08-05 18:35 UTC, armanbilge commented
I added some documentation.

> The performance hit is about 25% on microbenchmarks involving `delay` or `map`, and (as expected) ~0% (within margin of error) on everything else.

Discussed on Discord, but to clarify there is no reason to expect that `delay` or `map` should be impacted differently, because the propagation logic runs when the fiber is scheduled/descheduled, not for specific ops. (Although note that my initial implementation ran the propagation logic ran before/after `delay` blocks, in which case the performance discrepancy would be expected.)

2024-09-23 14:41 UTC, henricook commented
@djspiewak Please forgive my impetuousness - do you have a guesstimate of when this might be going in please?

2024-11-21 19:56 UTC, djspiewak submitted a review, later dismissed

2024-11-21 19:59 UTC, henricook commented
Oh-em-gee. Exciting.

2024-11-21 20:00 UTC, djspiewak commented
@armanbilge Conflict resolution time!

2024-11-21 22:07 UTC, djspiewak approved these changes

2024-11-22 03:23 UTC, merged

2024-11-27 11:29 UTC, NthPortal commented
can someone drop a message here when this PR ends up in a release?

2024-11-27 15:56 UTC, kubukoz commented
@NthPortal I'd recommend subscribing to releases additionally/instead:

<img width="348" alt="image" src="https://github.com/user-attachments/assets/5fc42df6-6f68-4a23-ac0b-e946a6a3603f">

<img width="466" alt="image" src="https://github.com/user-attachments/assets/b1c47a54-20c1-4fd0-abbc-a20a853fa118">

2024-11-27 17:13 UTC, djspiewak commented
We're working to get an RC out asap!

2025-02-06 00:03 UTC, kevin-lee commented
@armanbilge 
I can't find `cats.effect.unsafe.IOLocals` anymore, so to do [this](https://github.com/kevin-lee/logger-f/blob/52c15b8e689031076eec325e8fce10074a98ce8d/modules/logger-f-logback-mdc-cats-effect3/shared/src/main/scala/loggerf/logger/logback/Ce3MdcAdapter.scala#L32) and [this](https://github.com/kevin-lee/logger-f/blob/52c15b8e689031076eec325e8fce10074a98ce8d/modules/logger-f-logback-mdc-cats-effect3/shared/src/main/scala/loggerf/logger/logback/Ce3MdcAdapter.scala#L36), should I just call `unsafeRunSync()` for each get and set case?

2025-02-06 00:16 UTC, armanbilge commented
@kevin-lee use `IOLocal#unsafeThreadLocal()`:

https://github.com/typelevel/cats-effect/blob/1adf36872c6c9d8bfed118705ab6d2e1efe2f36f/core/jvm/src/main/scala/cats/effect/IOLocalPlatform.scala#L23-L29