add evalOn(executor)
typelevel/cats-effect pull request #3637
Opened 2023-05-17 11:06 UTC by homycdev

https://github.com/typelevel/cats-effect/issues/3633

2023-05-17 13:11 UTC, armanbilge reviewed
Thanks!

There is one thing I didn't think of, that we should add a test for: Scala has an `ExecutionContextExecutor` type that is both an `ExecutionContext` and an `Executor`. What happens if someone passes that to `evalOn`, how does it disambiguate?

https://www.scala-lang.org/api/2.13.10/scala/concurrent/ExecutionContextExecutor.html

2023-05-17 13:11 UTC, armanbilge commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +      OptionT(F.evalOn(fa.value, executor))
Instead of implementing it for every `Async` ...

2023-05-17 13:11 UTC, armanbilge commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +  def evalOn[A](fa: F[A], executor: Executor): F[A]
... we should just add a default implementation here, that everyone can use :)

2023-05-17 13:11 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +        .flatMap(ec => fa.evalOn(ec))
Nice! This looks exactly like what I imagined. We can make this the default implementation in `Async`.

I have one more suggestion: we can pattern match and check if the `Executor` is already an `ExecutionContext`, and skip the conversion in that case.

We do something similar here.
https://github.com/typelevel/cats-effect/blob/7e24bb96d4921f4bb50bf439c3429bcff998f457/kernel/shared/src/main/scala/cats/effect/kernel/Async.scala#L200-L206

2023-05-17 13:17 UTC, durban commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +  def evalOn[A](fa: F[A], executor: Executor): F[A]
Wait, how does adding a new abstract method _not_ fail the mima check?

2023-05-17 13:18 UTC, armanbilge commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +  def evalOn[A](fa: F[A], executor: Executor): F[A]
It does :)

2023-05-17 13:20 UTC, durban commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +  def evalOn[A](fa: F[A], executor: Executor): F[A]
Okay... then how is CI green? :-)

2023-05-17 13:22 UTC, armanbilge commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +  def evalOn[A](fa: F[A], executor: Executor): F[A]
It's not.
<img width="777" alt="Screen Shot 2023-05-17 at 6 21 48" src="https://github.com/typelevel/cats-effect/assets/3119428/e8e1db1b-4ae3-4018-a634-58b1b0572b82">

2023-05-17 17:22 UTC, homycdev commented on core/shared/src/main/scala/cats/effect/IO.scala
> +        .flatMap(ec => fa.evalOn(ec))
Hope, I got you right. Please, check new commit when you can.

2023-05-17 17:27 UTC, armanbilge commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +      case ec: ExecutionContextExecutor =>
It's possible it implements `ExecutionContext` without implementing `ExecutionContextExecutor`.
```suggestion
      case ec: ExecutionContext =>
```

2023-05-17 17:27 UTC, armanbilge commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +   * [[Async.evalOn]] with provided java.util.concurrent.Executor
```suggestion
   * [[Async.evalOn]] with provided [[java.util.concurrent.Executor]]
```

2023-05-17 17:27 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +
Spurious change

2023-05-17 17:27 UTC, armanbilge commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> -
Spurious change

2023-05-17 17:30 UTC, homycdev commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> -
sorry for these changes. I will fix asap

2023-05-18 11:28 UTC, homycdev commented
@armanbilge  is there everything alright? or something's missing?

2023-05-18 12:01 UTC, durban requested changes
I think what's mainly missing is the test suggested in [this comment](https://github.com/typelevel/cats-effect/pull/3637#pullrequestreview-1430640959).

(@armanbilge I've figured out what's happening with the "green" CI: in the PR list, and besides the commit there is a green checkmark. However, if I log in, I see the yellow warning at the bottom. Thsi is probably normal, just a bit strange...)

2023-05-18 12:01 UTC, durban commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
This is a strange case: if `executor` is non-`null`, `fromExecutor` is pure; however, if it's `null`, then it creates a new threadpool. I would suggest rejecting `null` here.

2023-05-18 12:34 UTC, homycdev commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
how do you see this rejection in the context of the library?

2023-05-18 13:03 UTC, homycdev commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
I can throwNPE as it is thrown in the default evalOn for example... but not sure whether this approach would be considered as good one

2023-05-18 14:02 UTC, homycdev commented on core/shared/src/main/scala/cats/effect/IO.scala
> +        .flatMap(ec => fa.evalOn(ec))
regarding tests, i have found tests only on laws for Async's methods. 
But from the comment you wrote me, i shall rather check whether the executionContext was executed through provided executor... correct me if I am wrong. 

Thank you in advance!

2023-05-18 14:14 UTC, armanbilge commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
> If null, a new Executor is created with default configuration.

What the hell ?? 😅 Good catch. Yeah, I think raising a NPE is the right thing to do. We could also no-op, but that seems arbitrary 🤔

2023-05-18 14:23 UTC, homycdev commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
> There is one thing I didn't think of, that we should add a test for: Scala has an ExecutionContextExecutor type that is both an ExecutionContext and an Executor. What happens if someone passes that to evalOn, how does it disambiguate?

@armanbilge 

regarding tests, i have found tests only on laws for Async's methods.
But from the comment you wrote me, i shall rather check whether the executionContext was executed through provided executor... correct me if I am wrong.

Thank you in advance!

2023-05-18 14:29 UTC, armanbilge commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
> i shall rather check whether the executionContext was executed through provided executor... correct me if I am wrong.

@homycdev actually, that's not what I concerned about. My concern is this. We now have methods:
```scala
def evalOn(fa: F[A], ec: ExecutionContext): F[A]
def evalOn(fa: F[A], executor: Executor): F[A]
```
so what will the compiler do if I write code like this:
```scala
def ecexec: ExecutionContextExecutor = ???
evalOn(fa, ecexec)
```
how will it choose which method to use? My guess is it won't be able to disambiguate and compilation will fail. If that's the case, we'll have to think about how to handle this.

2023-05-18 14:48 UTC, durban commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
I usually prefer an `IllegalArgumentException` (with `require`) instead of an NPE, but honestly, either one is fine.

2023-05-19 10:09 UTC, homycdev commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
> how will it choose which method to use? My guess is it won't be able to disambiguate and compilation will fail. If that's the case, we'll have to think about how to handle this.

can this approach be considered? 
```scala
def evalOn[A, Exec <: ExecutionContextExecutor](fa: F[A], exec: Exec) = {
        require(executor != null, "Cannot pass undefined Executor as an argument")
// the rest of the code 
}

```

2023-05-19 13:41 UTC, armanbilge commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
I am not sure if I understand. If the user has an ordinary `Executor` (i.e. not an `ExecutionContextExecutor`) then that method won't work.

2023-05-19 14:30 UTC, homycdev commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
I meant
```scala
def evalOn[A, Exec >: ExecutionContextExecutor](fa: F[A], exec: Exec) = {

```

but nvm, i think it is better just to change the name of the method, to avoid ambiguity 

```scala
  def evalOnExecutor[A](fa: F[A], executor: Executor): F[A] = {
    require(executor != null, "Cannot pass undefined Executor as an argument")
    executor match {
      case ec: ExecutionContext =>
        evalOn[A](fa, ec: ExecutionContext)
      case executor =>
        flatMap(executionContext) { refEc =>
          val newEc: ExecutionContext =
            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
          evalOn[A](fa, newEc)
        }
    }
  }
```

2023-05-19 15:13 UTC, armanbilge commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
> but nvm, i think it is better just to change the name of the method, to avoid ambiguity

Yeah, probably 😕 

the other option I can think of would be to have _three_ overloads since I think it will choose the most specific one, but I'm not sure if that's a good idea 😅 

```scala
 def evalOn[A](fa: F[A], ec: ExecutionContext): F[A]
 def evalOn[A](fa: F[A], exec: Executor): F[A]
 def evalOn[A](fa: F[A], ecexec: ExecutionContextExecutor): F[A]
```

2023-05-20 11:13 UTC, homycdev commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
so what shall we decide on? Keep two methods with different names, or do as you proposed with three overloads?

2023-05-20 20:48 UTC, armanbilge commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
I think Gavin has 👍 the triple-overload idea. I wonder what Daniel thinks (both of them 😉). Sorry, bike-shedding!

2023-05-23 08:09 UTC, homycdev commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
could you tag them pls?) I'd tag them myself, but not sure what their concrete gh aliases 

I am still waiting to implement final solution 😅

2023-05-23 15:07 UTC, durban commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
I see 3 options:

- Do nothing (i.e., do not add this method). I think this is an acceptable (if not particularly helpful) solution; everybody can continue to call `fromExecutor` themselves.
- Have the 3 methods, which I don't like, but it could still be the least bad solution. (Actually, I think instead of `ExecutionContextExecutor` we could have `ExecutionContext with Executor`, but that might be overdoing it.)
- Have 2 methods, with a different name. It's at least simpler than 3 methods... I also don't particularly like this one...

2023-05-24 12:30 UTC, durban commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
Okay, thought about it more, and I think calling it `evalOnExecutor` is probably best: it's a little like the `from*` methods, which have the same prefix (so autocomplete works). Three overloads could be somewhat confusing to anyone reading the source.

2023-05-29 07:59 UTC, homycdev commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
what do we do with the ExecutionContextExecutor? We ignore it? Or also do something like evalOnExecutionContextExectuor?

2023-05-29 10:05 UTC, armanbilge commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
An `ExecutionContextExecutor` is both an `ExecutionContext` and an `Executor`. So a user can pass it to either method and it will work fine :)

2023-05-29 12:29 UTC, homycdev commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
i know, but asked just in case you'd need specific method for that one too. Sorry for inconvenience

2023-05-29 12:31 UTC, armanbilge commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +            ExecutionContext.fromExecutor(executor, refEc.reportFailure)
no problem, thanks for asking!

2023-05-30 11:42 UTC, armanbilge commented on kernel/shared/src/main/scala/cats/effect/kernel/syntax/AsyncSyntax.scala
> +    Async[F].evalOnExecutor(wrapped, executor)
```suggestion
  def evalOnExecutor(executor: Executor)(implicit F: Async[F]): F[A] =
    Async[F].evalOnExecutor(wrapped, executor)
```

Would you mind also adding this method directly on `IO`? Thanks!

2023-06-06 13:35 UTC, homycdev commented on kernel/shared/src/main/scala/cats/effect/kernel/syntax/AsyncSyntax.scala
> +    Async[F].evalOnExecutor(wrapped, executor)
@armanbilge hello! Could you please check?)

2023-06-06 18:43 UTC, djspiewak approved these changes, later dismissed
I think this is good to go. @armanbilge any thoughts?

Thank you for tackling this!

2023-06-06 19:28 UTC, durban requested changes

2023-06-06 19:28 UTC, durban commented on core/shared/src/main/scala/cats/effect/IO.scala
> +      .flatMap(ec => IO(ExecutionContext.fromExecutor(executor, ec.reportFailure)))
With this, `IO#evalOnExecutor` has a different behavior from `Async#evalOnExecutor`. I think they should behave the same.

2023-06-06 19:30 UTC, armanbilge reviewed
Thanks, yes, sorry! There are a few more APIs I think it would be good to add, for consistency: `startOnExecutor`, `backgroundOnExecutor`, `evalOnExecutorK`

2023-06-06 19:30 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +import cats.effect.IO.executionContext
Instead of importing this can we call it as `IO.executionContext`? Sometimes unqualified methods can cause confusion 😅

2023-06-06 22:24 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +      .flatMap(ec => IO(ExecutionContext.fromExecutor(executor, ec.reportFailure)))
They should indeed! I missed that in my review.

2023-06-14 13:17 UTC, homycdev commented on core/shared/src/main/scala/cats/effect/IO.scala
> +      .flatMap(ec => IO(ExecutionContext.fromExecutor(executor, ec.reportFailure)))
Sorry for this. I hope, I understood you correctly now!

2023-06-14 14:27 UTC, closed without merging