evalOnExecutor
typelevel/cats-effect pull request #3691
Opened 2023-06-14 14:34 UTC by homycdev

2023-06-14 14:35 UTC, homycdev commented
@armanbilge @durban I do apologise for creating new branch. I somehow messed up the previous branch, so i decided to create new one. Hope for your understanding!

2023-06-14 15:13 UTC, durban commented
@homycdev It's not a big problem. Btw, you don't _have_ to merge _into_ your PR (I think I've seen you do that on the other one), you can just _push_ to the branch (`homycdev:evalOnExecutor` in this case). I'll re-review this when it is green (there seems to be a scalafix problem).

2023-06-14 15:17 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +   * @return
```suggestion
   * Shifts the execution of the current IO to the specified [[java.util.concurrent.Executor]].
   *
   * @see [[evalOn]]
```

2023-06-14 15:17 UTC, armanbilge commented on core/shared/src/main/scala/cats/effect/IO.scala
> +  }
Instead of duplicating the implementation :)

```suggestion
  def evalOnExecutor(executor: Executor): IO[A] =
    IO.asyncForIO.evalOnExecutor(executor)
```

2023-07-04 19:08 UTC, durban requested changes
I've left a few nitpicking comments, otherwise seems good to me.

2023-07-04 19:08 UTC, durban commented on kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
> +    require(executor != null, "Cannot pass undefined Executor as an argument")
`undefined` -> `null`

2023-07-04 19:08 UTC, durban commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    start.evalOnExecutor(executor)
This could delegate to `asyncForIO` (like `evalOnExecutor` above).

2023-07-04 19:08 UTC, durban commented on core/shared/src/main/scala/cats/effect/IO.scala
> +    Resource.make(startOnExecutor(executor))(_.cancel).map(_.join)
This could delegate to `asyncForIO` (like `evalOnExecutor` above).

2023-07-05 16:11 UTC, durban approved these changes
Thanks, LGTM!

2023-07-05 16:31 UTC, durban commented
The CI failure seems unrelated, I've restarted it.

2023-07-09 10:23 UTC, durban commented
@armanbilge Do you want to take another look at this, or should I just merge it?

2023-07-09 12:48 UTC, armanbilge approved these changes
Thanks for all your work on this!

2023-07-09 13:23 UTC, durban commented
@homycdev Thank you for your contribution!

2023-07-09 13:23 UTC, merged