Native signal handling, safe `IOApp` cancelation, and fiber dumps
typelevel/cats-effect pull request #3695
Opened 2023-06-16 21:49 UTC by armanbilge

1. Refactor `IOAppSpec` so that using it to test 3 platforms is less insane

2. Setup signal handling infrastructure with file descriptor polling and pipes

3. Add handlers/listeners to enable safe `IOApp` cancelation and fiber dumps

2023-06-16 23:45 UTC, armanbilge commented
Still diagnosing the build failures. I wonder if weak references have some issues on Scala Native so enabling fiber monitoring has compromised CI ...

2023-06-22 14:33 UTC, djspiewak requested changes

2023-06-22 14:33 UTC, djspiewak commented on build.sbt
> +lazy val ioAppTestsJVM =
Can't we shortcut a lot of this by just using `crossProject`?

2023-06-22 14:33 UTC, djspiewak commented on core/native/src/main/scala/cats/effect/Signal.scala
> +  private[this] final val SIGUSR1Mac = 30
Wouldn't it be better to do the `isMac` branching here so we could have a single `SIGUSR1` value?

2023-06-22 14:33 UTC, djspiewak commented on core/native/src/main/scala/cats/effect/unsafe/EventLoopExecutorScheduler.scala
> +  def liveTraces(): Map[IOFiber[_], Trace] = {
This reminds me that one of the important cleanup tasks for our first "Scala Native with real threads" release will need to be making sure that we've deduplicated as much as possible/relevant between JVM and Native.

2023-06-22 14:33 UTC, djspiewak commented on core/native/src/main/scala/cats/effect/unsafe/FiberMonitor.scala
> +private[effect] sealed abstract class FiberMonitor extends FiberMonitorShared {
So in the category of cross-build confusion, this is now a *third* paradigm for cross-build branching. We have `isNative`/`isJVM`/etc, we have the `*Platform` variants, and now we have `*Shared` variants. Can we at least not have that third one? ;-) Would it be possible to reorganize this to have `FiberMonitorPlatform` instead?

2023-06-22 14:35 UTC, armanbilge commented on build.sbt
> +lazy val ioAppTestsJVM =
We can't. All three of these are actually JVM projects. They just happens to be JVM projects that invoke JVMs, Node.js, or Native binaries.

2023-06-22 14:36 UTC, armanbilge commented on core/native/src/main/scala/cats/effect/Signal.scala
> +  private[this] final val SIGUSR1Mac = 30
Then it's not an inlinable constant. `final val` with a literal is treated specially by the compiler.

Ok yeah, that's a dumb reason 😂

2023-06-22 14:40 UTC, armanbilge commented on core/native/src/main/scala/cats/effect/unsafe/FiberMonitor.scala
> +private[effect] sealed abstract class FiberMonitor extends FiberMonitorShared {
Not really, no. The issue is that the _constructors_ are different, because they either take a WSTP, a BMTE, or an ELES. You can't platform a constructor.

Unless we pull out some common fiber-monitorable EC interface. Then they can all share a common constructor.

2023-06-22 14:44 UTC, armanbilge commented on core/native/src/main/scala/cats/effect/unsafe/EventLoopExecutorScheduler.scala
> +  def liveTraces(): Map[IOFiber[_], Trace] = {
I added it to the checklist in:
- https://github.com/typelevel/cats-effect/issues/3662#issue-1741007577

2023-06-22 17:52 UTC, djspiewak commented on core/native/src/main/scala/cats/effect/Signal.scala
> +  private[this] final val SIGUSR1Mac = 30
LOL. Yeah I think in this case it doesn't matter so much.

2023-06-22 17:54 UTC, djspiewak commented on core/native/src/main/scala/cats/effect/unsafe/FiberMonitor.scala
> +private[effect] sealed abstract class FiberMonitor extends FiberMonitorShared {
It might be worth pulling out the interface, if only for internal use. I feel like we need to be really relentless about trying to simplify and ensure consistency of our platform-split code, given how much of it we have.

2023-06-29 01:17 UTC, armanbilge commented on core/native/src/main/scala/cats/effect/unsafe/FiberMonitor.scala
> +private[effect] sealed abstract class FiberMonitor extends FiberMonitorShared {
I was able to make some small improvement: we can share an interface between JS and Native because they are similar, but the WSTP is too different to participate in a shared abstraction (e.g. it has a notion of thread-local weakbags for fibers).

2023-09-02 15:35 UTC, djspiewak approved these changes, later dismissed

2023-09-02 15:35 UTC, djspiewak commented
Ready to go once deconflicted

2023-09-03 21:59 UTC, merged