Add note to starvation docs re: cpus in k8s
typelevel/cats-effect pull request #3750
Opened 2023-07-14 15:30 UTC by Daenyth

This is a common "gotcha" when running in k8s.
Ideally we could automatically detect this environment in the CE runtime itself on initialization and warn the user proactively, but at least this gives people something to ctrl-f for in the doc

2023-07-14 16:06 UTC, samspills commented on docs/core/starvation-and-tuning.md
> +In many Docker clusters, it is relatively standard practice to over-provision CPU credits by some factor (even 100% over-provisioning is quite common). What this effectively means is that the contain
I don't think we want the spaces removed from `*(m * n) / (1 + k)* CPUs`, it looks like the formatting takes over the multiplication

2023-07-14 17:46 UTC, Daenyth commented on docs/core/starvation-and-tuning.md
> +In many Docker clusters, it is relatively standard practice to over-provision CPU credits by some factor (even 100% over-provisioning is quite common). What this effectively means is that the contain
oh drat, yeah I didn't even touch that - it's just the file formatting. I'll fix it

2023-07-14 17:47 UTC, Daenyth commented
Before this gets merged I want to add some wording about overriding the thread count in `IOApp` for cases where you really do want your k8s pod to have <=1 cpu

2023-08-01 15:41 UTC, armanbilge commented
drive-by-dropping a link to more material we should incorporate

https://discord.com/channels/632277896739946517/839263556754472990/1135955773613146152

2023-08-04 13:26 UTC, samspills commented
going to close and reopen b/c I think that's what's needed to get the updated CI workflows

2023-08-04 13:27 UTC, samspills commented
nope I appear to have been wrong about that _womp womp_

2023-08-04 13:32 UTC, armanbilge commented
> nope I appear to have been wrong about tha

We merged your fix to 3.5.x, but this PR is targeting 3.x. Actually this PR could target 3.5.x.

2023-08-14 09:23 UTC, TimWSpence commented
Woops just changing the target branch is not sufficient 🤦‍♂️

2023-09-02 15:48 UTC, djspiewak requested changes

2023-09-02 15:48 UTC, djspiewak commented on docs/core/starvation-and-tuning.md
> +**All cats-effect applications running in kubernetes should have either a cpu_quota configured or use the jvm `-XX:ActiveProcessorCount` argument to explicitly tell the jvm how many cores to use.**
```suggestion
**All Cats Effect applications running in kubernetes should have either a `cpu_quota` configured or use the jvm `-XX:ActiveProcessorCount` argument to explicitly tell the jvm how many cores to use.**
```

2023-09-02 15:48 UTC, djspiewak commented on docs/core/starvation-and-tuning.md
> +One cause of "not enough threads" can be that the application is running inside kubernetes with a cpu_quota not configured. When the cpu limit is not configured, the jvm detects the number of availab
```suggestion
One cause of "not enough threads" can be that the application is running inside kubernetes with a `cpu_quota` not configured. When the cpu limit is not configured, the JVM detects the number of available processors as 1, which will severely restrict what the runtime is able to do.
```

2023-09-02 15:48 UTC, djspiewak commented on docs/core/starvation-and-tuning.md
> +In many Docker clusters, it is relatively standard practice to over-provision CPU credits by some factor (even 100% over-provisioning is quite common). What this effectively means is that the contain
```suggestion
In many Docker clusters, it is relatively standard practice to over-provision CPU credits by some factor (even 100% over-provisioning is quite common). What this effectively means is that the container environment will promise (or at least *allow*) *m* applications access to *n* vCPUs each, despite only *(m * n) / (1 + k)* CPUs being physically present across the underlying hardware cluster. In this equation, *k* is the over-provisioning factor, often referred to as "burst credits".
```

2023-09-02 15:48 UTC, djspiewak commented on docs/core/starvation-and-tuning.md
> +Even if you have followed the above advice and avoided over-provisioning, the linux kernel scheduler is unfortunately not aware of the Cats Effect scheduler and will likely actively work against the
```suggestion
Even if you have followed the above advice and avoided over-provisioning, the Linux kernel scheduler is unfortunately not aware of the Cats Effect scheduler and will likely actively work against the Cats Effect scheduler by moving Cats Effect worker threads between different CPUs, thereby destroying CPU cache-locality. In certain environments we can prevent this by configuring Kubernetes to pin an application to a gviven set of CPUs:
```

Is this true? The kernel uses a work-stealing algorithm to balance tasks across compute units, so it has the same long-term convergence as Cats Effect itself: when fully loaded, threads remain where they are and affinity is maximized.

2023-11-23 14:59 UTC, djspiewak approved these changes

2023-11-23 19:06 UTC, merged