Changed tutorial so consumers are not overwhelmed by producers
typelevel/cats-effect pull request #3762
Opened 2023-07-26 18:56 UTC by lrodero

The second section of the tutorial describes how to use fibers to solve the producer-consumer problem. Thing is, as the code is now, producers outpace consumers so much that consumers seem to be 'frozen'. The explication seems to be the `Ref.modify` run by consumers is way slower than the `Ref.getAndUpdate` call run by producers. This forces consumers to retry once and again to run the `modify` call.

This PR is to add text [at the end of the first subsection](https://lrodero.github.io/cats-effect/docs/tutorial#issue-1-the-producer-outpaces-the-consumer) (the one introducing a 'naive' solution to the producers-consumers problem) to describe the problem and to propose several solutions: using a `.sleep` call (the one used in the code samples); using `AtomicCell` instead of `Ref`, or using a bounded queue (which is implemented in another section afterwards).

The new version of the tutorial can be read online [here](https://lrodero.github.io/cats-effect/docs/tutorial). All code samples are available [here](https://github.com/lrodero/cats-effect-tutorial).

Other minor changes:
* Typo as in PR #3760
* In copy file section merge `transfer` and `transmit` functions in a single one `transfer` in order to simplify code and ease understanding
* In code samples use `Sync[F].whenA` instead of `if ... else Sync[F].unit`
* Updated sbt version (1.9.3)
* Changed wrong path `catseffecttutorial.CopyFile` to correct one `catseffecttutorial.copyfile.CopyFile`

2023-09-05 11:44 UTC, durban commented on docs/tutorial.md
>  def producer[F[_]: Sync: Console](queueR: Ref[F, Queue[Int]], counter: Int): F[Unit] =
`Sync` seems unnecessarily strong here.

2023-09-05 11:44 UTC, durban commented on docs/tutorial.md
>  def consumer[F[_]: Sync: Console](queueR: Ref[F, Queue[Int]]): F[Unit] =
I also don't think we need `Sync` here.

2023-09-05 11:44 UTC, durban commented on docs/tutorial.md
> +   def producer[F[_]: Async: Console](queueR: Ref[F, Queue[Int]], counter: Int): F[Unit] =
`Async` seems unnecessarily strong for a simple `sleep`.

2023-09-05 11:44 UTC, durban commented on docs/tutorial.md
> +   as `Ref`, is a concurrent data structure to keep a reference to some data.
"as Ref" -> "like Ref"? (But I'm not sure, english is not my first language.)

2023-09-05 11:44 UTC, durban commented on docs/tutorial.md
> +   its content. Otoh `AtomicCell` is slower than `Ref`. This is because `Ref` is
"Otoh": I would recommend spelling out the abbreviation.

2023-09-05 11:44 UTC, durban commented on docs/tutorial.md
> +[here](https://github.com/lrodero/cats-effect-tutorial/blob/series/3.x/src/main/scala/catseffecttutorial/producerconsumer/InefficientProducerConsumer.scala).
This have the risk of becoming a dead link later (although I don't have better idea).

2023-09-05 11:44 UTC, durban commented on docs/tutorial.md
> +    _ <- Async[F].whenA(i % 10000 == 0)(Console[F].println(s"Consumer $id has reached $i items"))
`Async` as above.

2023-09-05 11:44 UTC, durban commented on docs/tutorial.md
> +def producer[F[_]: Async: Console](id: Int, counterR: Ref[F, Int], stateR: Ref[F, State[F,Int]]): F[Unit] = {
`Async` as above.

2023-09-05 11:44 UTC, durban commented on docs/tutorial.md
> +(be 'semantically blocked') until there is some empty bucket available to be
I think the new terminology is "fiber blocked".

2023-09-16 14:36 UTC, lrodero commented on docs/tutorial.md
>  def producer[F[_]: Sync: Console](queueR: Ref[F, Queue[Int]], counter: Int): F[Unit] =
It's not strictly required, that is true, we could just use `cats.Monad`. But I preferred to use CE type classes, as in the other code snippets that use `Sync` and `Async`. I'm ok with changing it but please let's be certain that is what we want :slightly_smiling_face: (implies changes in snippets, text and linked [repo](https://github.com/lrodero/cats-effect-tutorial)).

2023-09-16 14:44 UTC, lrodero commented on docs/tutorial.md
> +(be 'semantically blocked') until there is some empty bucket available to be
You are absolutely right, changing it :+1: .

2023-09-16 14:52 UTC, lrodero commented on docs/tutorial.md
> +[here](https://github.com/lrodero/cats-effect-tutorial/blob/series/3.x/src/main/scala/catseffecttutorial/producerconsumer/InefficientProducerConsumer.scala).
It's a repo of my own and I confirm that I intend to keep it open and cared of, but I totally understand the concern :slightly_frowning_face: . I don't mind contributing the code to the main CE repo, but I don't know if there is a proper place to fit it in. IIRC this was commented in a previous PR but no other solution was found.

2023-09-16 14:53 UTC, lrodero commented on docs/tutorial.md
> +   as `Ref`, is a concurrent data structure to keep a reference to some data.
Nor mine :sweat_smile: .  But I think you might be right and it sounds ok, changing it.

2023-09-16 14:56 UTC, lrodero commented on docs/tutorial.md
>  def producer[F[_]: Sync: Console](queueR: Ref[F, Queue[Int]], counter: Int): F[Unit] =
While a decision is taken about this I have addressed the other comments, thanks for the input!

2023-09-17 18:57 UTC, durban commented on docs/tutorial.md
> +(be 'filter blocked') until there is some empty bucket available to be
filter -> fiber?

2023-09-17 18:59 UTC, durban commented on docs/tutorial.md
>  def producer[F[_]: Sync: Console](queueR: Ref[F, Queue[Int]], counter: Int): F[Unit] =
I definitely think `Sync`/`Async` is too much here. But since it's already there, I don't think there is any need to change them _in this PR_. It's fine to leave it for a followup.

2023-09-17 19:00 UTC, durban commented on docs/tutorial.md
> +[here](https://github.com/lrodero/cats-effect-tutorial/blob/series/3.x/src/main/scala/catseffecttutorial/producerconsumer/InefficientProducerConsumer.scala).
Okay, as I've said, I don't have a better idea :man_shrugging:

2023-09-30 14:33 UTC, lrodero commented on docs/tutorial.md
> +(be 'filter blocked') until there is some empty bucket available to be
Clumsy fingers, sorry about that.

2023-11-23 15:00 UTC, djspiewak requested changes
Needs some fairly trivial conflict resolution and I think it's ready to merge! Thank you!

2023-11-26 20:20 UTC, djspiewak approved these changes

2023-11-26 20:20 UTC, merged