Print warning when we detect a non-main-thread main
typelevel/cats-effect pull request #3774
Opened 2023-08-04 20:45 UTC by Daenyth

This should help people not run facefirst into https://github.com/sbt/sbt/issues/6242
It's a frequent question for new users

2023-08-04 20:46 UTC, Daenyth commented on core/jvm/src/main/scala/cats/effect/IOApp.scala
> +  private def onNonMainThreadDetected(): Unit = {
This can probably become `protected` in the next API break, though honestly I'm skeptical that it's valuable to expose at all

2023-08-05 05:44 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/IOApp.scala
> +             |Set `Compile / run / fork := true` in this project to resolve this.
```suggestion
             |Set `Compile / run / fork := true` in this project to resolve this.
             |
             |To silence this warning set the system property:
             |`-Dcats.effect.warnOnNonMainThreadDetected=false`.
```

2023-09-02 15:39 UTC, djspiewak approved these changes

2023-09-02 15:39 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/IOApp.scala
> +  private def onNonMainThreadDetected(): Unit = {
Yeah I'd rather not expose an API like this in `IOApp`. :-) Better to keep it private.

2023-09-02 15:39 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/IOApp.scala
> +          """|Warning: IOApp `main` is running on a thread other than the main thread.
```suggestion
          """|[WARNING] IOApp `main` is running on a thread other than the main thread.
```

We use this convention in the starvation checker

2023-09-02 15:39 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/IOApp.scala
> +             |`-Dcats.effect.warnOnNonMainThreadDetected=false`.
To remain consistent, we should also (in the next minor release) add an overridable `Boolean` field in `IOApp` which controls this behavior (defaulted to read from the system property). Can you toss that in an issue so we don't forget?

2023-09-02 15:40 UTC, djspiewak requested changes
Wrong button on previous review sorry

2023-09-02 15:58 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/IOApp.scala
> +             |`-Dcats.effect.warnOnNonMainThreadDetected=false`.
- https://github.com/typelevel/cats-effect/issues/3806

2023-09-02 16:09 UTC, djspiewak approved these changes

2023-09-02 16:41 UTC, merged