Run Cirrus only for labeled PRs or tags
typelevel/cats-effect pull request #3842
Opened 2023-09-22 16:21 UTC by armanbilge

2023-09-22 17:24 UTC, samspills approved these changes
🙌

2023-09-23 01:53 UTC, djspiewak requested changes, later dismissed
Can we also make them run unconditionally for release tags? Also we should probably create the labels. :-)

2023-09-23 02:01 UTC, armanbilge commented on .cirrus.yml
> +  only_if: $CIRRUS_TAG != '' || $CIRRUS_PR != ''
@djspiewak they already run unconditionally for release tags. Unless I'm missing your point.

2023-09-23 19:22 UTC, djspiewak commented on .cirrus.yml
> +  only_if: $CIRRUS_TAG != '' || $CIRRUS_PR != ''
I misunderstood the diff. lgtm then

2023-09-23 20:00 UTC, merged