Post release to Discord in CI
typelevel/cats-effect pull request #3855
Opened 2023-09-26 19:40 UTC by armanbilge

Follow-up to https://github.com/typelevel/cats-effect/pull/3711 that uses the secret.

2023-09-26 19:40 UTC, armanbilge commented on scripts/post-release-discord.sh
> +data="{\"content\":\"https://github.com/typelevel/cats-effect/releases/tag/$1\"}"
Seems easier to just pass the tag.

2023-10-03 15:54 UTC, djspiewak commented on scripts/post-release-discord.sh
> +data="{\"content\":\"https://github.com/typelevel/cats-effect/releases/tag/$1\"}"
Well, the reason I *didn't* do it that way is because all the other scripts take a version number unprefixed by `v`, and it's going to get very confusing if we make it inconsistent.

2023-10-03 15:54 UTC, djspiewak requested changes
Definitely easier *here* to just pass tag, but it's also inconsistent with the other scripts.

2023-10-03 17:22 UTC, armanbilge commented
Presumably we eventually want to run the other scripts in CI too? We're just going to butt heads with this again. It's easier to pass a tag in GHA than it is to do string manipulation.

Meanwhile, the scripts themselves can easily strip the `v` prefix.

2023-10-03 18:27 UTC, djspiewak commented
> Presumably we eventually want to run the other scripts in CI too? We're just going to butt heads with this again. It's easier to pass a tag in GHA than it is to do string manipulation.

That's fair. Can we change the other scripts then at the same time? This is exactly the sort of stuff that gets *really* confusing if we aren't strict about it.

2023-10-03 19:12 UTC, djspiewak approved these changes

2023-10-03 19:12 UTC, djspiewak commented on scripts/make-release-prs.sh
> +new_version="${2#v}"
Oooooh, fancy.

2023-10-03 19:18 UTC, armanbilge commented on scripts/make-release-prs.sh
> +new_version="${2#v}"
Fancy? I feel dirty 😩

2023-10-04 01:05 UTC, merged