Execute `IO.blocking` on WSTP without `BlockContext` indirection
typelevel/cats-effect pull request #3903
Opened 2023-11-24 02:39 UTC by armanbilge

We already have all the fantastic machinery to execute blocking code on a `WorkerThread` and it is pointless to indirect through the `BlockContext` interface when we can just invoke this mechanism directly.

2023-11-24 02:42 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
>      pool.notifyParked(rnd)
Unrelated, but I wonder why we invoke `notifyParked()` unconditionally, even if this thread is already `blocking = true`.

2023-11-24 18:30 UTC, djspiewak requested changes

2023-11-24 18:30 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +      true
Can we move this logic up into `IOFiber` instead? I don't think there's any particular reason for it to be here, and you're making something that looks like a boolean check into a side-effecting method.

2023-11-24 18:30 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
>      pool.notifyParked(rnd)
Good question. I'm guessing there's no reason and we can probably guard that notification as you say.

2023-11-24 18:39 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +      true
Well conceptually I liked that if `canExecuteBlockingCode()` returns `true` then you _can_ run blocking code, immediately.

I do see your point. We can expose this as a separate method which `IOFiber` calls. This requires:

1. Doing the whole `Thread.currentThread()` dance a second time. How should we handle the case where the current thread is not a `WorkerThread`, or does not belong to the current pool? Do we care about those cases?

2. Expose whatever API we invent on the JS `WorkStealingThreadPool` shim. Not a big deal, just annoying.

Worth it?

2023-11-24 18:46 UTC, armanbilge commented on core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
> +      true
Oh lol, also I just realized this is bugged as-written 😅

2024-01-08 20:59 UTC, djspiewak submitted a review, later dismissed

2024-01-08 23:09 UTC, merged