Refactor `CallbackStack` based on new "pack locking" strategy
typelevel/cats-effect pull request #3943
Opened 2024-01-10 21:59 UTC by armanbilge

Fixes https://github.com/typelevel/cats-effect/issues/3940. Very fun collaboration with @samspills but credit to @mernst-github for proposing the idea of guarding `pack` in https://github.com/typelevel/cats-effect/issues/3940#issuecomment-1883123013.

The new callback stack is made up of two data types:
1. `CallbackStack.Node`, a singly-linked list of callbacks
2. `CallbackStack` itself, which holds:
    - an `AtomicReference` to the head `Node`, and
    - an `AtomicBoolean` lock, used for guarding `pack`

Pushing to the stack is a straighforward CAS of the head.

`pack` is the only method that modifies the list.
- the `AtomicBoolean` lock guarantees that only one `pack` operation is running at a time, and is also used to publish the modifications to subsequent packs
- if a call to `pack` is unable to acquire the lock, it gives up immediately

Invoking the callbacks is not guarded by the lock. This means that the modifications by `pack` may not be visible, and in fact `pack`ing can even occur concurrently while iterating over the list. This is actually okay:
- the list is only ever modified to _remove_ `Node`s, since additions happen by CASing the pointer to the head `Node`
- thus, if while iterating over the list we follow a stale pointer to a next `Node` that was actually removed, we take a "detour" but do eventually visit all the `Node`s in the list

2024-01-10 22:01 UTC, armanbilge commented on core/jvm-native/src/main/scala/cats/effect/CallbackStack.scala
> +    // TODO should we read allowedToPack for memory effect?
As explained above, it's not strictly necessary, but if we did read `allowedToPack` then at least some of the `pack`ing would be guaranteed to be visible. But I'm not sure if this additional synchronization is worth it: the modifications may already be visible fortuitously and we still need to be prepared for concurrent `pack`ing anyway.

2024-01-10 22:51 UTC, armanbilge commented on core/jvm-native/src/main/scala/cats/effect/CallbackStack.scala
> +  }
I wonder if we need to be more aggressive about iterating the list and `null`ing all the callbacks and `next`s. The concern is if someone holds onto a `Handle` for cancelation, they could actually be keeping the entire structure in memory.

2024-01-11 13:32 UTC, mernst-github reviewed
Looks great! Just a couple of thoughts:

2024-01-11 13:32 UTC, mernst-github commented on core/jvm-native/src/main/scala/cats/effect/CallbackStack.scala
>  private final class CallbackStack[A](private[this] var callback: A => Unit)
This "main" `callback` variable is somewhat of an oddball and complicates api and implementation:
- it can be installed after the fact via `unsafe...` instead of using `push`.
- it cannot be cleared
- it is only used by IOFiber and always null for IODeferred
- case in point: you don't mention it in the PR description ;-)

I'm wondering if it would balance things if it were moved into IOFiber.

2024-01-11 13:32 UTC, mernst-github commented on core/jvm-native/src/main/scala/cats/effect/CallbackStack.scala
> +    // TODO should we read allowedToPack for memory effect?
Good point, I didn't consider concurrent `pack` and `apply`. If there were any concerns regarding correctness (boils down to: is it ok for `pack` to rewrite the edges pointing to already published data without synchronization?), could even consider spinning on the `allowedToPack` lock and own the list during `apply`? That might even amortize because apply won't take the packed "detour"?

2024-01-11 13:56 UTC, armanbilge commented on core/jvm-native/src/main/scala/cats/effect/CallbackStack.scala
>  private final class CallbackStack[A](private[this] var callback: A => Unit)
> This "main" `callback` variable is somewhat of an oddball and complicates api and implementation:

Eh, you're not wrong, but it's fine. `CallbackStack` is not a general purpose data structure, it's a specialized data structure designed specifically for our needs. It's allowed to be odd.

> I'm wondering if it would balance things if it were moved into IOFiber.

This would increase the footprint of `IOFiber`, see https://github.com/typelevel/cats-effect/issues/3584.

2024-01-11 14:02 UTC, armanbilge commented on core/jvm-native/src/main/scala/cats/effect/CallbackStack.scala
> +    // TODO should we read allowedToPack for memory effect?
> could even consider spinning on the `allowedToPack` lock and own the list during `apply`

Sam and I considered this idea but decided against it. We could be spinning for an unbounded time while we wait for `pack` to complete iterating over a very long list. Or what if we lose the race and another `pack` acquires the lock? For sure, these are worst case pathologies, but since owning the lock is not required to safely iterate the list, spinning until we acquire doesn't seem worth the risk.

2024-01-13 23:09 UTC, djspiewak requested changes
Love this. Some trivial changes and a couple simple questions but otherwise this is great.

2024-01-13 23:09 UTC, djspiewak commented on core/jvm-native/src/main/scala/cats/effect/CallbackStack.scala
>  private final class CallbackStack[A](private[this] var callback: A => Unit)
For posterity's sake, we're obsessed about `IOFiber`'s memory footprint because we've discovered that this is actually one of the primary performance factors for the whole library. We create so many new fibers all of the time under perfectly normal circumstances that even a few extra bytes in the object header can have a drastic impact on the top-line numbers. In fact, as that issue notes, we're pretty sure that if we can squeeze the footprint down just a bit more, we could probably ladder up a significant step in overall performance due to cache alignment.

2024-01-13 23:09 UTC, djspiewak commented on tests/shared/src/test/scala/cats/effect/CallbackStackSpec.scala
> +        stack.pack(1) must beEqualTo(0)
Fwiw, `mustEqual` is shorter :)

2024-01-13 23:09 UTC, djspiewak commented on tests/shared/src/test/scala/cats/effect/CallbackStackSpec.scala
> +          .both(pushClearPack)
This is only a two-way race. Is it worth tossing a few thousand more fibers at this?

2024-01-13 23:09 UTC, djspiewak commented on tests/shared/src/test/scala/cats/effect/CallbackStackSpec.scala
> +          .replicateA_(1000)
```suggestion
          .parReplicateA_(1000)
```

Runs faster, particularly locally.

2024-01-13 23:09 UTC, djspiewak commented on tests/shared/src/test/scala/cats/effect/CallbackStackSpec.scala
> +      }.flatMap(stack => IO(stack.pack(1)).both(IO(stack.clear()))).replicateA_(1000).as(ok)
Same comment as above regarding parallelism factor.

```suggestion
      }.flatMap(stack => IO(stack.pack(1)).both(IO(stack.clear()))).parReplicateA_(1000).as(ok)
```

2024-01-13 23:59 UTC, durban commented on core/jvm-native/src/main/scala/cats/effect/CallbackStack.scala
> +    // TODO should we read allowedToPack for memory effect?
I'd say yes, read `allowedToPack` here, because: what will we do here? We'll call all the `cb`s in the list, right? Which are cont's `resume`s, so when we call them, each will do 1-2 CASes. If we can avoid calling some of them (the cleared ones) by doing a volatile read, that seems like a win. (Of course we might already not call them, because we might already see that they're null... so I'm not sure actually...)

2024-01-14 00:02 UTC, durban commented on core/jvm-native/src/main/scala/cats/effect/CallbackStack.scala
> +  }
I think that's a valid concern. Maybe we could do that during `apply`? It's a little strange, because `apply` and `clear` are separate, but a call to `clear` always follows `apply`, doesn't it?

2024-01-14 00:06 UTC, durban commented on core/jvm-native/src/main/scala/cats/effect/CallbackStack.scala
> +      allowedToPack.set(true)
Maybe do this in a  `finally`, since we're releasing a lock?

2024-01-14 00:08 UTC, armanbilge commented on core/jvm-native/src/main/scala/cats/effect/CallbackStack.scala
> +    // TODO should we read allowedToPack for memory effect?
That's a really interesting point :) it's essentially gambling:
- we do a volatile read now, but get a pretty good guarantee we won't do unnecessary CASes
- we take our chances and if we are lucky we got away with doing the minimum synchronization necessary

2024-01-14 00:10 UTC, armanbilge commented on core/jvm-native/src/main/scala/cats/effect/CallbackStack.scala
> +      allowedToPack.set(true)
I assume `finally` isn't free, and in theory the code between acquiring/releasing should not throw unless something fatal happened 😅

2024-01-14 00:25 UTC, armanbilge commented on tests/shared/src/test/scala/cats/effect/CallbackStackSpec.scala
> +          .replicateA_(1000)
I think I'm going to keep this one sequential. Each replicate itself now involves thousands of fibers. Also, by running sequentially we are able to use the same `CallbackStack` instance for every replicate as an additional test of robustness.

2024-01-14 00:52 UTC, armanbilge commented on core/jvm-native/src/main/scala/cats/effect/CallbackStack.scala
> +  }
> It's a little strange, because `apply` and `clear` are separate, but a call to `clear` always follows `apply`, doesn't it?

I agree. I'd be happy to see `clear` go away and we do the clearing as part of `apply`.

Having a separate `clear` seems important here. This code surprised me.

https://github.com/typelevel/cats-effect/blob/02076374689dcced923d10938117b182cf76d580/core/shared/src/main/scala/cats/effect/IOFiber.scala#L1075-L1084

I think the only callback that can throw is one installed e.g. via `IO#unsafeRunAsync`. But it seems better to `try`/`catch` where the callback is defined, and only install non-throwing callbacks in `IOFiber`. It especially strikes me as odd if the other callbacks are not evaluated, because the first one threw.

However, these changes seem involved enough to warrant their own PR ...

2024-01-14 02:01 UTC, djspiewak commented on core/jvm-native/src/main/scala/cats/effect/CallbackStack.scala
> +    // TODO should we read allowedToPack for memory effect?
The cleared ones are nulled out though, so we shouldn't have any penalty there besides the node read, or am I missing something?

2024-01-14 02:03 UTC, armanbilge commented on core/jvm-native/src/main/scala/cats/effect/CallbackStack.scala
> +    // TODO should we read allowedToPack for memory effect?
> The cleared ones are nulled out though

Yes, but currently there is no guarantee that this is published either. They are ordinary writes/reads.

2024-01-14 16:04 UTC, djspiewak commented on core/jvm-native/src/main/scala/cats/effect/CallbackStack.scala
> +      allowedToPack.set(true)
The cost of a `finally` is really small, especially since you only need one here. Agreed this shouldn't really happen, but if it happens it's going to be a hell of a bug to track down. Worth being safe imo.

2024-01-14 18:33 UTC, djspiewak commented
Looks like a perfect wash (within margin for error) in terms of performance. Good to go on that front!

## Before

```
[info] Benchmark                                             (count)  (cpuTokens)   (size)   Mode  Cnt      Score     Error    Units
[info] DeepBindBenchmark.async                                   N/A          N/A    10000  thrpt   10   2935.967 ± 102.359    ops/s
[info] DeepBindBenchmark.delay                                   N/A          N/A    10000  thrpt   10   9742.384 ±  42.545    ops/s
[info] DeepBindBenchmark.pure                                    N/A          N/A    10000  thrpt   10  11626.005 ± 170.858    ops/s
[info] DeferredBenchmark.cancel                                   10          N/A      N/A  thrpt   10    104.204 ±   0.456    ops/s
[info] DeferredBenchmark.cancel                                  100          N/A      N/A  thrpt   10     13.537 ±   0.074    ops/s
[info] DeferredBenchmark.cancel                                 1000          N/A      N/A  thrpt   10      1.312 ±   0.008    ops/s
[info] DeferredBenchmark.complete                                 10          N/A      N/A  thrpt   10    110.424 ±   0.836    ops/s
[info] DeferredBenchmark.complete                                100          N/A      N/A  thrpt   10     26.084 ±   0.109    ops/s
[info] DeferredBenchmark.complete                               1000          N/A      N/A  thrpt   10      5.073 ±   0.287    ops/s
[info] DeferredBenchmark.getAfter                                 10          N/A      N/A  thrpt   10   7059.728 ±  19.859    ops/s
[info] DeferredBenchmark.getAfter                                100          N/A      N/A  thrpt   10   2033.584 ±  10.383    ops/s
[info] DeferredBenchmark.getAfter                               1000          N/A      N/A  thrpt   10    247.342 ±   0.501    ops/s
[info] DeferredBenchmark.getBefore                                10          N/A      N/A  thrpt   10   3994.309 ±  15.618    ops/s
[info] DeferredBenchmark.getBefore                               100          N/A      N/A  thrpt   10    798.325 ±   1.832    ops/s
[info] DeferredBenchmark.getBefore                              1000          N/A      N/A  thrpt   10     81.027 ±   0.163    ops/s
[info] ParallelBenchmark.parTraverse                             N/A        10000     1000  thrpt   10    878.708 ±  25.632    ops/s
[info] ParallelBenchmark.traverse                                N/A        10000     1000  thrpt   10     70.062 ±   0.050    ops/s
[info] ShallowBindBenchmark.async                                N/A          N/A    10000  thrpt   10   2157.575 ±   3.120    ops/s
[info] ShallowBindBenchmark.delay                                N/A          N/A    10000  thrpt   10  10052.708 ±  54.888    ops/s
[info] ShallowBindBenchmark.pure                                 N/A          N/A    10000  thrpt   10  10539.875 ± 135.470    ops/s
[info] WorkStealingBenchmark.alloc                               N/A          N/A  1000000  thrpt   10     14.151 ±   0.111  ops/min
[info] WorkStealingBenchmark.manyThreadsSchedulingBenchmark      N/A          N/A  1000000  thrpt   10     50.544 ±   0.753  ops/min
[info] WorkStealingBenchmark.runnableScheduling                  N/A          N/A  1000000  thrpt   10   2958.068 ±  15.379  ops/min
[info] WorkStealingBenchmark.runnableSchedulingScalaGlobal       N/A          N/A  1000000  thrpt   10   2195.662 ±   5.718  ops/min
[info] WorkStealingBenchmark.scheduling                          N/A          N/A  1000000  thrpt   10     53.854 ±   2.195  ops/min
```

## After

```
[info] Benchmark                                             (count)  (cpuTokens)   (size)   Mode  Cnt      Score     Error    Units
[info] DeepBindBenchmark.async                                   N/A          N/A    10000  thrpt   10   3068.624 ±  16.441    ops/s
[info] DeepBindBenchmark.delay                                   N/A          N/A    10000  thrpt   10   9853.126 ± 124.913    ops/s
[info] DeepBindBenchmark.pure                                    N/A          N/A    10000  thrpt   10  11664.990 ±  94.674    ops/s
[info] DeferredBenchmark.cancel                                   10          N/A      N/A  thrpt   10    107.015 ±   0.686    ops/s
[info] DeferredBenchmark.cancel                                  100          N/A      N/A  thrpt   10     14.352 ±   0.083    ops/s
[info] DeferredBenchmark.cancel                                 1000          N/A      N/A  thrpt   10      1.326 ±   0.016    ops/s
[info] DeferredBenchmark.complete                                 10          N/A      N/A  thrpt   10    110.982 ±   1.658    ops/s
[info] DeferredBenchmark.complete                                100          N/A      N/A  thrpt   10     26.111 ±   0.183    ops/s
[info] DeferredBenchmark.complete                               1000          N/A      N/A  thrpt   10      5.129 ±   0.271    ops/s
[info] DeferredBenchmark.getAfter                                 10          N/A      N/A  thrpt   10   6990.249 ±  47.301    ops/s
[info] DeferredBenchmark.getAfter                                100          N/A      N/A  thrpt   10   2042.712 ±  21.909    ops/s
[info] DeferredBenchmark.getAfter                               1000          N/A      N/A  thrpt   10    246.581 ±   1.930    ops/s
[info] DeferredBenchmark.getBefore                                10          N/A      N/A  thrpt   10   3941.678 ±  24.476    ops/s
[info] DeferredBenchmark.getBefore                               100          N/A      N/A  thrpt   10    744.944 ±   5.293    ops/s
[info] DeferredBenchmark.getBefore                              1000          N/A      N/A  thrpt   10     80.747 ±   0.431    ops/s
[info] ParallelBenchmark.parTraverse                             N/A        10000     1000  thrpt   10    887.059 ±  23.448    ops/s
[info] ParallelBenchmark.traverse                                N/A        10000     1000  thrpt   10     69.816 ±   0.752    ops/s
[info] ShallowBindBenchmark.async                                N/A          N/A    10000  thrpt   10   2169.835 ±  22.053    ops/s
[info] ShallowBindBenchmark.delay                                N/A          N/A    10000  thrpt   10   9872.628 ± 116.515    ops/s
[info] ShallowBindBenchmark.pure                                 N/A          N/A    10000  thrpt   10  10410.052 ±  75.004    ops/s
[info] WorkStealingBenchmark.alloc                               N/A          N/A  1000000  thrpt   10     14.018 ±   0.133  ops/min
[info] WorkStealingBenchmark.manyThreadsSchedulingBenchmark      N/A          N/A  1000000  thrpt   10     48.573 ±   2.040  ops/min
[info] WorkStealingBenchmark.runnableScheduling                  N/A          N/A  1000000  thrpt   10   2997.308 ±  10.291  ops/min
[info] WorkStealingBenchmark.runnableSchedulingScalaGlobal       N/A          N/A  1000000  thrpt   10   2239.119 ±  12.325  ops/min
[info] WorkStealingBenchmark.scheduling                          N/A          N/A  1000000  thrpt   10     52.694 ±   1.716  ops/min
```

2024-01-15 18:27 UTC, djspiewak approved these changes, later dismissed
I'm still leaning toward rolling the dice on *not* fencing in `apply`. Let's see how that treats us though, and if we're seeing problems there, we'll add the fence.

2024-01-15 18:27 UTC, merged