Fix a few Supervisor bugs
typelevel/cats-effect pull request #3972
Opened 2024-01-26 01:31 UTC by durban

This PR fixes a few bugs in `Supervisor` (and creates an unknown number of new ones ;-).

Fixed bugs (at least the ones I remember spotting; I tried to write tests for them, couldn't for all of them):

- #3394
- With `checkRestart`, `cancel` allowed and didn't wait for one last restart.
- `supervise`/close race (although, due to #3394, close wasn't effective anyway).
- With `checkRestart`, if `cancel` cancelled the working fiber before it did anything, the finalizer (which removes the fiber from the map) did not run. (This was effectively a memory leak.)

2024-01-26 18:05 UTC, djspiewak requested changes
Ouch this is hairy. Nice work. :) Some minor nits.

2024-01-26 18:05 UTC, djspiewak commented on tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala
> +  sequential
Do we need this?

2024-01-26 18:05 UTC, djspiewak commented on tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala
> +  override def executionTimeout = 60.seconds
Oooof. Can we lower iteration counts instead?

2024-01-26 18:05 UTC, djspiewak commented on tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala
> +                  None
Might be a bit easier to diagnose an eventual failure here if we convert this into a side-effecting test assertion.

```suggestion
                case ex: IllegalStateException =>
                  ex.getMessage mustEqual "supervisor already shutdown"
                  None
```

2024-01-26 18:05 UTC, djspiewak commented on tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala
> +                  IO((v1: Int) mustEqual (v2: Int))
Are the type ascriptions needed?

2024-01-26 18:05 UTC, djspiewak commented on tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala
> +      tsk.parReplicateA_(if (isJVM) 10000 else 5).as(ok)
Why do we need to replicate it at all on non-JVM platforms?

Also, I'm assuming this is the test that takes most of the time?

2024-01-26 18:05 UTC, djspiewak commented on std/shared/src/main/scala/cats/effect/std/Supervisor.scala
> +          stateRef.getAndSet(null).map(_.values.toList)
So `null` is the signal that we've decided to kill ourselves? Basically, the invariant here is that `joinAll`/`cancelAll` can only be called at the end of the world, when the `Supervisor` is shutting down. Can we toss that in a comment so we don't forget it?

2024-01-27 02:28 UTC, djspiewak commented
Also it occurs to me that, with this, we might not need the double-check on closure state in #3923

2024-01-27 10:04 UTC, durban commented on tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala
> +  sequential
With lowering the iteration counts, I think we will be able to avoid this.

2024-01-27 10:05 UTC, durban commented on tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala
> +                  IO((v1: Int) mustEqual (v2: Int))
Nope, I don't even remember why I did those :slightly_smiling_face:

2024-01-27 10:08 UTC, durban commented on tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala
> +      tsk.parReplicateA_(if (isJVM) 10000 else 5).as(ok)
Good point; I think I copied the `if (isJVM) ... else 5` part from somewhere.

For me, it was usually `supervise / finalize race with checkRestart` that timed out.

2024-01-27 10:18 UTC, durban commented on std/shared/src/main/scala/cats/effect/std/Supervisor.scala
> +          stateRef.getAndSet(null).map(_.values.toList)
There is already a comment in `abstract class State` about `joinAll`/`cancelAll`, but I'll note it here too.

2024-01-27 12:10 UTC, durban commented
FTR there was a `Dispatcher` failure (https://github.com/typelevel/cats-effect/actions/runs/7678308491/job/20928046255#step:24:4779), but seemed unrelated to this PR, so I just restarted the CI jobs.

2024-01-27 15:44 UTC, djspiewak approved these changes
Awesome!

2024-01-27 15:44 UTC, merged