Improve contributor documentation
typelevel/cats-effect pull request #4038
Opened 2024-03-09 21:06 UTC by durban

Hopefully fixes #4005. I don't actually know, how releasing works, this is me trying to understand it.

2024-03-09 21:55 UTC, armanbilge commented on RELEASING.md
> +1. "Draft a new release" button in GitHub.
```suggestion
1. Press the "Draft a new release" button in GitHub.
```

2024-03-09 21:55 UTC, armanbilge commented on RELEASING.md
> +1. "Generate new release notes" button in GitHub.
```suggestion
1. Press the "Generate new release notes" button in GitHub.
```

2024-03-09 21:55 UTC, armanbilge commented on RELEASING.md
> +1. Edit manually the generated release notes:
```suggestion
1. Manually edit the generated release notes:
```

2024-03-09 21:55 UTC, armanbilge commented on CONTRIBUTING.md
> +With documentation changes (both Scaladoc and Markdown documentation in `/docs`), target the *earliest* branch to which those changes are relevant. For example, if a method already exists in `series/
Maybe we need to clarify "earliest **maintained** branch" or something e.g. do not send changes to `series/3.4.x` because our current active minor branch is `series/3.5.x`.

Honestly, we should update this contributing doc every time we release a minor. That will help stave off confusion :)

2024-03-09 22:08 UTC, durban commented on RELEASING.md
> +1. Edit manually the generated release notes:
This is what happens if a non-native speaker (me) writes documentation :rofl:

2024-03-09 22:18 UTC, durban commented on CONTRIBUTING.md
> +With documentation changes (both Scaladoc and Markdown documentation in `/docs`), target the *earliest* branch to which those changes are relevant. For example, if a method already exists in `series/
Yeah, that makes sense. I did it for the current version.

2024-03-13 14:40 UTC, djspiewak requested changes

2024-03-13 14:40 UTC, djspiewak commented on RELEASING.md
>  1. Run the following script to open two PRs to (1) update the version in the README/docs of the minor branch and then (2) merge the minor branch into the major branch. This script currently works onl
We should update this section as well since the scripts do not use the `v` prefix (e.g. `scripts/make-release-prs.sh 3.5.1 3.5.2` is correct, *not* `scripts/make-release-prs.sh v3.5.1 v3.5.2`)

2024-03-13 18:00 UTC, armanbilge commented on RELEASING.md
>  1. Run the following script to open two PRs to (1) update the version in the README/docs of the minor branch and then (2) merge the minor branch into the major branch. This script currently works onl
Nope, this is correct. The scripts do use the `v` prefix, at your request ;) see https://github.com/typelevel/cats-effect/pull/3855#issuecomment-1745503701.

2024-03-13 18:37 UTC, djspiewak commented on RELEASING.md
>  1. Run the following script to open two PRs to (1) update the version in the README/docs of the minor branch and then (2) merge the minor branch into the major branch. This script currently works onl
Ahhhhhh they actually allow for both! Rip. Okay I retract my comment.

2024-03-13 18:37 UTC, djspiewak approved these changes

2024-03-13 18:38 UTC, merged