Remove IORuntime from allRuntimes on shutdown
typelevel/cats-effect pull request #4090
Opened 2024-06-24 15:53 UTC by RafalSierkiewicz

The PR originated from question on discord https://discord.com/channels/632277896739946517/632278585700384799/1254741830042652772 

Whenever the IORuntime is created through `apply` method it is being added to the `allRuntimes` collection.
Unfortunately it seems that is not removed anywhere. 

This PR tries to remove the created `IORuntime` from `allRuntimes` collection. 
I tried to keep the api as close as it was, but as the `allRuntimes` collection require `runtime` and the `hashCode` to be supplied to remove function I struggled a bit. 

I am open for comments and suggestions. Let me know which branch I should target, not sure if change is backward and forward compatible

2024-06-25 15:57 UTC, djspiewak requested changes
I think it would make more sense to do this in the same local scope where we *add* to `allRuntimes`, both because it avoids this parameter juggle in the main class, but also because it keeps the logic a bit more localized. The forward references should be resolvable with some type ascription and strategic use of the `lazy` modifier.

2024-06-26 05:58 UTC, RafalSierkiewicz commented
> I think it would make more sense to do this in the same local scope where we _add_ to `allRuntimes`, both because it avoids this parameter juggle in the main class, but also because it keeps the logic a bit more localized. The forward references should be resolvable with some type ascription and strategic use of the `lazy` modifier.

Yes, I totally I agree. I was trying to achieve it, but somehow realized that might be hard 🙈 I changed it to use `lazy` as well as `def` and added test

2024-06-26 21:43 UTC, djspiewak requested changes

2024-06-26 21:43 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntime.scala
> +    def unregisterAndShutdown: () => Unit = () => {
Moderate pedantry:

```suggestion
    def unregisterAndShutdown(): Unit = {
```

2024-06-27 05:01 UTC, RafalSierkiewicz commented on core/shared/src/main/scala/cats/effect/unsafe/IORuntime.scala
> +    def unregisterAndShutdown: () => Unit = () => {
I had to revert the change because compilation is failing in such a solution 
`An unapplied 0-arity method was eta-expanded (due to the expected type () => Unit), rather than applied to `()`.
[error] Write unregisterAndShutdown() to invoke method unregisterAndShutdown, or change the expected type.`

2024-06-27 18:08 UTC, djspiewak approved these changes

2024-06-27 18:08 UTC, merged