Add `ownPoller`
typelevel/cats-effect pull request #4133
Opened 2024-09-10 01:13 UTC by armanbilge

This PR introduces a mechanism for checking if a given poller is "owned" by the current thread and thus is safe to interact with. This is useful primarily for cancelation, which may be requested from any thread, but can happy-path additional cleanup operations when on the owning thread.

The existing `accessPoller` and new `ownPoller` methods are now bundled up in a `PollerProvider` API.

Finally, `SelectorSystem` is improved to use `ownPoller` to attempt to remove the linked list node for a canceled selection operation, instead of simply clearing it.

Closes https://github.com/typelevel/cats-effect/issues/4009.

2024-09-23 16:21 UTC, durban submitted a review, later dismissed
LGTM

2024-10-22 18:12 UTC, djspiewak requested changes

2024-10-22 18:12 UTC, djspiewak commented on core/jvm-native/src/main/scala/cats/effect/unsafe/PollingSystem.scala
> +   * Returns `true` if it is safe to interact with this `Poller`
Can we add a note that it's always safe to return `false` here? So in other words, we tolerate false negatives, but we cannot tolerate false positives.

2024-10-22 18:12 UTC, djspiewak commented on core/jvm-native/src/main/scala/cats/effect/unsafe/PollingSystem.scala
> +  def accessPoller(cb: P => Unit): Unit
Bikeshed: remove the `Poller` suffix from both methods, since it's redundant.

2024-10-22 18:12 UTC, djspiewak commented on core/jvm/src/main/scala/cats/effect/unsafe/SelectorSystem.scala
> +  private final class Callbacks {
We've built so many of these…

2024-10-23 01:17 UTC, armanbilge commented on core/jvm-native/src/main/scala/cats/effect/unsafe/PollingSystem.scala
> +  def accessPoller(cb: P => Unit): Unit
I don't know if it's a good enough reason for you but I chose `accessPoller` so that WSTP can directly implement `PollerProvider` without a methods vaguely named `access` or `own`.

FWIW I'd rather bikeshed the name `PollerProvider`, it's possible in the future we may want to add other useful methods in here that are exposed by the WSTP to `PollingSystem` implementors.

2024-10-25 13:32 UTC, djspiewak commented on core/jvm-native/src/main/scala/cats/effect/unsafe/PollingSystem.scala
> +  def accessPoller(cb: P => Unit): Unit
Alrighty. Will ponder that one for a bit

2024-10-25 13:59 UTC, djspiewak commented on core/jvm-native/src/main/scala/cats/effect/unsafe/PollingSystem.scala
> +trait PollerProvider[P] {
What about `PollerContext` or something in that vein? Kinda sucks that everything is "poller this" and "poller that". Could also be slightly more generic like `WorkerContext` or `TLContext`. `ReferenceFrame` is not inaccurate but more obscure.

2024-10-27 19:49 UTC, armanbilge commented on core/jvm-native/src/main/scala/cats/effect/unsafe/PollingSystem.scala
> +trait PollerProvider[P] {
Renamed to `PollingContext`

2024-10-27 19:50 UTC, armanbilge commented on core/jvm-native/src/main/scala/cats/effect/unsafe/PollingSystem.scala
> +private[unsafe] trait UnsealedPollingContext[P] extends PollingContext[P]
Before you tell me that `private[unsafe]` is the same as `private` since we are already in package `unsafe`, it's not:

```
private trait UnsealedPollingContext escapes its defining scope as part of type cats.effect.unsafe.UnsealedPollingContext[P]
```

2024-10-29 14:11 UTC, djspiewak commented on core/jvm-native/src/main/scala/cats/effect/unsafe/PollingSystem.scala
> +private[unsafe] trait UnsealedPollingContext[P] extends PollingContext[P]
Thanks Scala!

2024-10-29 14:12 UTC, djspiewak submitted a review, later dismissed

2024-10-29 20:06 UTC, merged