Revise race pair
typelevel/cats-effect pull request #960
Opened 2020-07-19 00:24 UTC by RaasAhsan

- [ ] Fix laws
- [ ] Fix `Gen` instances

2020-07-19 00:28 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IO.scala
>    def both[B](that: IO[B]): IO[(A, B)] =
Seems like we could have a `bothOutcome` in a similar fashion to `raceOutcome`

2020-07-19 00:29 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IO.scala
> +          case Outcome.Canceled() => IO.canceled *> IO.never
`IO.canceled *> IO.never` can deadlock if we're masked here

2020-07-19 02:09 UTC, djspiewak requested changes
My suggestion for the laws would be to remove most of the `race` laws and talk about `racePair` with a couple new ones instead. Also, to that end, `PureConc` needs to be updated.

2020-07-19 02:09 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +          case Outcome.Completed(fa) => f.cancel *> fa.map(Left.apply)
```suggestion
          case Outcome.Completed(fa) => f.cancel *> fa.map(Left(_))
```

And analogously for the others. I think it's just a bit cleaner.

2020-07-19 02:09 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +              case Outcome.Errored(ea) => IO.raiseError(ea)
BTW this is a slightly different semantic than before, where the *first* error would be emitted. I actually think we're better off just failing the race if one errors. I haven't checked on what ce2's semantics are here, but it just seems odd to me (in retrospect) that `race(raiseError(e), never)` would be a deadlock.

2020-07-19 02:09 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +      : IO[Either[Outcome[IO, Throwable, A @uncheckedVariance], Outcome[IO, Throwable, B]]] =
Still not convinced this is actually useful. :-)

2020-07-19 02:09 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +              (Fiber[IO, Throwable, Any], Outcome[IO, Throwable, Any])]] { cb =>
We should like, make a type alias for this.

2020-07-19 02:09 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +                Some(fiberA.cancel *> fiberB.cancel)
Random thing that should probably be fixed… this should be run in parallel. We really want `IO.both(fiberA.cancel, fiberB.cancel).void`.

2020-07-19 02:09 UTC, djspiewak commented on testkit/shared/src/main/scala/cats/effect/testkit/TimeT.scala
> +  def liftK[F[_], A]: F ~> TimeT[F, *] =
`A`?

2020-07-19 02:13 UTC, RaasAhsan commented on testkit/shared/src/main/scala/cats/effect/testkit/TimeT.scala
> +  def liftK[F[_], A]: F ~> TimeT[F, *] =
I copied the type signature from `Kleisli.liftK` and didn't realize it was used 😅

2020-07-19 02:15 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +              (Fiber[IO, Throwable, Any], Outcome[IO, Throwable, Any])]] { cb =>
I was thinking about this too, maybe a specialized `Outcome` and `Fiber` for `IO` makes sense. When we're talking about either of those in the context of `IO`, `Throwable` is pretty much implied.

`IOOutcome`, `IOFiber` (this ones already taken but we can come up with better names for the implementation I think)

2020-07-19 02:17 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IO.scala
> +              case Outcome.Errored(ea) => IO.raiseError(ea)
I tried to mimic the current CE3 semantics, it seems like the second error is reported https://github.com/typelevel/cats-effect/blob/series/3.x/core/shared/src/main/scala/cats/effect/IOFiber.scala#L484

2020-07-19 02:20 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IO.scala
> +      : IO[Either[Outcome[IO, Throwable, A @uncheckedVariance], Outcome[IO, Throwable, B]]] =
I'm sure somebody could come up with a contrived example... but what do you think about `bothOutcome`?

2020-07-19 03:05 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +              case Outcome.Errored(ea) => IO.raiseError(ea)
Oh interesting! That wasn't intended. I think. I'd have to look at `PureConc`. In any case though, I think it's better to make the error report immediate; in other words, I think the old ce3 semantics are wrong.

2020-07-19 03:06 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IO.scala
> +      : IO[Either[Outcome[IO, Throwable, A @uncheckedVariance], Outcome[IO, Throwable, B]]] =
`bothOutcome` feels a bit more useful. :-) If nothing else, `both(raiseError(e1), raiseError(e2))` is inherently weird, whereas it works fine with `bothOutcome`

2020-07-20 04:29 UTC, RaasAhsan commented
@djspiewak Updated the `PureConc.racePair` implementation, let me know if it looks right :)

The law for `racePair` aren't very elegant to write because of `Outcome` :) . My first attempt was something like this, but it doesn't pass exhaustively.
```scala
def racePairNeverIdentityLeft[A](fa: F[A]) = {
    val identity = F.racePair(F.never[Unit], fa).flatMap {
      case Left(_) => F.never[Outcome[F, E, A]]
      case Right((_, oc)) => F.pure(oc)
    }

    fa.map(a => Outcome.completed[F, E, A](F.pure(a))) <-> identity
  }
```

2020-07-20 04:40 UTC, RaasAhsan commented
Ah, well the concurrent laws for `PureConc` are failing which seems to suggest that the `racePair` implementation doesn't work.

```
[error] x concurrent.uncancelable race displaces canceled
[error]  Falsified after 0 passed tests.
[error]  > Labels of failing property:Expected: "Completed(None)\u000a│\u000a├ Notify 0x37D631D2\u000a├ Notify 0x37D631D2\u000a├ Notify 0x37D631D2\u000a╰ Done"
[error]  Received: "Completed(Some(()))\u000a│\u000a├ Notify 0x22CBF51E\u000a├ Notify 0x58164174\u000a├ Fork\u000a│ ╰╮\u000a│  ├ Notify 0x58164174\u000a│  ├ Notify 0x58164174\u000a│  ╰ Done\u000a│  \u000a├ Notify 0x73D34EA4\u000a├ Fork\u000a│ ╰╮\u000a│  ├ Notify 0x73D34EA4\u000a│  ├ Notify 0x73D34EA4\u000a│  ├ Notify 0x4E172C51\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a│  ├ Await 0x7C43D089\u000a\u000a...\u000a\u000a..."
[error]  The seed is P36o_rk8LlGX5TCkjlFJepb7OtUwwbENSNvQKwGZm_D=
[info] + concurrent.uncancelable race poll canceled identity (left)
[error] x concurrent.uncancelable race poll canceled identity (right)
[error]  Falsified after 0 passed tests.
[error]  > Labels of failing property:Expected: "Completed(None)\u000a│\u000a├ Notify 0xE638D54\u000a├ Notify 0xE638D54\u000a├ Notify 0xE638D54\u000a╰ Done"
[error]  Received: "Completed(Some(Left(1299570979)))\u000a│\u000a├ Notify 0x3AE912B2\u000a├ Notify 0x165C8DD4\u000a├ Fork\u000a│ ╰╮\u000a│  ├ Notify 0x165C8DD4\u000a│  ├ Notify 0x165C8DD4\u000a│  ├ Notify 0x4534522C\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a│  ├ Await 0x57AF7EF3\u000a\u000a...\u000a\u000a..."> ARG_0: "Completed(None)\u000a│\u000a├ Notify 0x4023AF0\u000a├ Notify 0x4023AF0\u000a├ Notify 0x4023AF0\u000a╰ Done"
[error]  The seed is ZhNu4goN-9O4XlJ2JWTzFrjI09c9Ih_XDQ0umO1IbEG=
```

I'm not really sure how to debug this thing without drowning a lot of time into figuring out how it really works, so let me know if you can spot what I looked over

2020-07-20 14:37 UTC, djspiewak commented
> Ah, well the concurrent laws for PureConc are failing which seems to suggest that the racePair implementation doesn't work.

Some of the old laws need to be removed! :-) There are a bunch of laws which claim that `uncancelable` should distribute over `racePair` and such. All of those need to go.

2020-07-21 03:26 UTC, RaasAhsan commented
@djspiewak I think all the `racePair` variants are going to have to wrapped in `uncancelable`, or else we might leak resources. I want to get this branch merged as soon as fix these lingering `PureConc` issues, but I have it on my TODO to get to that afterwards. We should probably do a sweep of both `IO` and `Concurrent` machinery to see we're not missing any of these cases.

2020-07-21 07:28 UTC, RaasAhsan commented
I managed to isolate this failing `Align` test case for `PureConc`. It seems like the issue comes from either `both` or `racePair`. I've already made all the substitutions, but here's a reduced case that illustrate where things seem to go wrong:

```scala
// The following two are NOT the same
fa.align(fb.map(identity))
fa.align(fb)

// If you make the appropriate substitutions, you end up here
val a = (ParallelF.value(ParallelF(fa).map(identity)).attempt, ParallelF.value(ParallelF(fb).map(identity)).attempt)
            .parMapN((ea, eb) => catsStdInstancesForEither.alignWith(ea, eb)(identity))
            .flatMap(C.fromEither)
// `ParallelF.value(ParallelF(fb).map(identity))` is the term of interest. that map call eventually makes its way to `both` and `racePair`, so something is wrong there
```

Here are the renderings of the different effects:
```scala
// fa
Completed(Some(1))
│
├ Notify 0x2E408AB9
├ Cede
├ Notify 0x15A9C7E3
╰ Pure Completed(1)

// fb
Completed(None)
│
├ Notify 0x3641C43B
├ Notify 0x3641C43B
├ Notify 0x3641C43B
╰ Done

// ParallelF.value(ParallelF(fa).map(identity).align(ParallelF(fb)))
Completed(Some(Ior.Left(1)))
│
├ Notify 0x1C152686
├ Notify 0x13BD612B
├ Fork
│ ╰╮
│  ├ Notify 0x13BD612B
│  ├ Notify 0x13BD612B
│  ├ Notify 0x5612A9E1
│  ├ Fork
│  │ ╰╮
│  │  ├ Notify 0x5612A9E1
│  │  ├ Notify 0x5612A9E1
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53
│  │  ├ Await 0x951FB53

...

...

...

// ParallelF.value(ParallelF(fa).map(identity).align(ParallelF(fb).map(identity)))
Completed(None)
│
├ Notify 0x20A079E1
├ Notify 0xCEE2D38
├ Fork
│ ╰╮
│  ├ Notify 0xCEE2D38
│  ├ Notify 0xCEE2D38
│  ├ Notify 0x2E102352
│  ├ Fork
│  │ ╰╮
│  │  ├ Notify 0x2E102352
│  │  ├ Notify 0x2E102352
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5
│  │  ├ Await 0x229EFF5

...

...

...
```

The failing seed for the `alignHomomorphism` test is `-ETrHGyCTzib58PxGaFyumO3n6Of8RjswGuqSDhQvnN=`.

2020-07-21 20:23 UTC, djspiewak commented
So, `fa` is something like `F.cede.as(1)`, while `fb` could be either `F.canceled` or `F.never`. Really nice minimization btw! I'll take a look at it in detail as soon as I can.

2020-07-22 02:01 UTC, merged