Concurrent for OptionT and EitherT
typelevel/cats-effect pull request #996
Opened 2020-07-24 16:24 UTC by TimWSpence

2020-07-24 16:25 UTC, TimWSpence commented
Currently blocked on reformulating
```
def canceledSequencesOnCancelInOrder(fin1: F[Unit], fin2: F[Unit]) =
    F.onCancel(F.onCancel(F.canceled, fin1), fin2) <-> (F.uncancelable(_ =>
      fin1.attempt >> fin2.attempt) >> F.canceled)
```
and
```
def uncancelableCanceledAssociatesRightOverFlatMap[A](a: A, f: A => F[Unit]) =
    F.uncancelable(_ => F.canceled.as(a).flatMap(f)) <-> (F.uncancelable(_ => f(a).attempt) >> F.canceled)
```
to support short-circuiting monad

2020-08-03 21:26 UTC, djspiewak requested changes

2020-08-03 21:26 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/concurrent.scala
> +      Kleisli(r => fa.run(r).attempt >> fb.run(r))
I think this needs to be `F.forceR(fa.run(r))(fb.run(r))`, otherwise `OptionT[OptionT[F, *], A]` will have the wrong semantics w.r.t. the inner effect.

2020-08-03 21:26 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/concurrent.scala
> +        fa.run.attempt >> fb.run
Similar `forceR` issue here.

2020-08-03 21:26 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/concurrent.scala
> +        fa.value.attempt >> fb.value
…and here

2020-08-03 21:26 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/concurrent.scala
> +  trait EitherTConcurrent[F[_], E0, E] extends Concurrent[EitherT[F, E0, *], E] {
Can we make all of these traits `private[kernel]` to avoid increasing the API footprint? Also it might be more reasonable to nest them under the appropriate object (`Concurrent`, in this case).

2020-08-03 21:26 UTC, djspiewak commented on kernel/shared/src/main/scala/cats/effect/kernel/concurrent.scala
> +        fa.value.attempt >> fb.value
`forceR`

2020-08-04 07:19 UTC, TimWSpence commented on kernel/shared/src/main/scala/cats/effect/kernel/concurrent.scala
> +      Kleisli(r => fa.run(r).attempt >> fb.run(r))
Yes! Very good point!

2020-08-04 07:19 UTC, TimWSpence commented on kernel/shared/src/main/scala/cats/effect/kernel/concurrent.scala
> +  trait EitherTConcurrent[F[_], E0, E] extends Concurrent[EitherT[F, E0, *], E] {
They are nested inside `Concurrent`? But yes, making them private is a very good idea, thanks!

2020-08-04 15:13 UTC, merged