Transformer instances for temporal
typelevel/cats-effect pull request #997
Opened 2020-07-24 21:21 UTC by TimWSpence

2020-07-24 21:21 UTC, TimWSpence commented
Dependent on https://github.com/typelevel/cats-effect/pull/996 and on `TimeT` and hence the `Temporal` instance for `PureConc` being fixed

2020-08-11 22:23 UTC, djspiewak requested changes
Minor (but unfortunately, annoying) request!

2020-08-11 22:23 UTC, djspiewak commented on laws/shared/src/test/scala/cats/effect/PureConcSpec.scala
> +  )
Can we push all of these into separate files, similar to what I did for the other inductive `PureConc` specs? This might be a bit annoying given some of the implicit resolution hacks, which may have to be replicated. The reasoning behind getting all of these into their own files is that allows them to be run in parallel on ScalaJS, which drops the build times from somewhere around 30 minutes to somewhere closer to 8 minutes.

2020-08-11 22:23 UTC, djspiewak commented on laws/shared/src/test/scala/cats/effect/PureConcSpec.scala
> +trait LowPriorityInstances {
I really hate Scala 2.12… :-)

2020-08-12 07:03 UTC, TimWSpence commented on laws/shared/src/test/scala/cats/effect/PureConcSpec.scala
> +  )
😭 But yes, that is definitely worth it!

2020-08-12 08:08 UTC, TimWSpence commented on laws/shared/src/test/scala/cats/effect/PureConcSpec.scala
> +trait LowPriorityInstances {
Interestingly this was no longer necessary when I split into different files. But yes, it sucks 😆

2020-08-12 08:23 UTC, TimWSpence commented on laws/shared/src/test/scala/cats/effect/PureConcSpec.scala
> +trait LowPriorityInstances {
Oh woops. I retract this. Just forgot to test locally with 2.12 😭

2020-08-12 14:56 UTC, merged