Backpressured cancels
typelevel/cats-effect pull request #998
Opened 2020-07-25 00:20 UTC by RaasAhsan

2020-07-25 18:55 UTC, djspiewak requested changes

2020-07-25 18:55 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +  val named = name
Stray debug logic?

2020-07-25 18:55 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +              fin(Right(()))
This has a mild effect on fairness: the *first* caller of `cancel` will be continued *last*. I'm tempted to say we should invert the order of these calls.

2020-07-25 18:55 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    // conts may be null if the fiber was cancelled before it was cancelled
Actually `conts` will be `null` if the fiber was canceled before it was *started*. :-)

2020-07-25 18:55 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +//                    if (!isCanceled() || !isUnmasked()) { // double-check to see if we were canceled while suspended
Should probably clean this up.

2020-07-25 18:55 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +//                    }
Ditto here

2020-07-25 18:55 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +                // TODO: ELSE?
I guess this isn't needed? Is it worth writing a quick justification for each of our missing `else` cases?

2020-07-25 18:55 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +            }
Note that this is parsing as an `else if`. Can we stick some curly braces around this (or remove the commented code) to make it a bit more clear?

2020-07-25 18:55 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +              // indicate the presence of the cancel token by pushing Right instead of Left
BTW this "right instead of left" thing is stale and should be removed. I forgot to delete it when I added `AsyncState`.

2020-07-25 18:55 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +          runLoop(failed(result, 0), 0)
BTW I realized last night that the read barrier here is on the wrong thread: we put the barrier on the thread which *schedules* the callback with the executor, instead of putting it on the thread which owns the callback when run. We can just fix this in `execute`, but at the cost of an allocation.

2020-07-25 18:55 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +//      if (!isCanceled() || !isUnmasked()) {
More stale code

2020-07-25 18:55 UTC, djspiewak commented on core/shared/src/test/scala/cats/effect/IOSpec.scala
> +    }
I think it's worth also adding the following test case:

```scala
"never terminate when racing infinite cancels" in ticked { implicit ticker =>
  val test = IO.never.onCancel(IO.never).start flatMap { f => 
    IO.race(f.cancel, f.cancel)
  }

  test.void should nonTerminate
}
```

This gets a bit at part of what was changed, and also codifies in test-form one of the weirder consequences.

2020-07-26 01:53 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +  val named = name
yeah, couldn't access `name` before from the continuations so i used one of these

2020-07-26 01:53 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +  val named = name
i probably just needed to declare them `val` in the constructor

2020-07-26 01:55 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    // conts may be null if the fiber was cancelled before it was cancelled
mistype!

2020-07-26 01:56 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +//                    if (!isCanceled() || !isUnmasked()) { // double-check to see if we were canceled while suspended
Going to delete this because the same check is performed in `asyncContinue`

2020-07-26 01:57 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +//                    }
Bringing this one back

2020-07-26 02:04 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +          runLoop(failed(result, 0), 0)
I *think* it works because the lambda closes over a reference to `this` with respect to `IOFiber`. So if the thread running `execute` observes any changes, then it those changes should also be reflected in the reference in the lambda.

2020-07-26 02:10 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +//      if (!isCanceled() || !isUnmasked()) {
makes sense to bring this one back

2020-07-26 02:49 UTC, RaasAhsan commented on core/shared/src/test/scala/cats/effect/IOSpec.scala
> +    }
Needed to modify the test a little bit to ensure that the finalizer is registered before attempting cancellation.
```scala
 "never terminate when racing infinite cancels" in ticked { implicit ticker =>
      var started = false

      val markStarted = IO { started = true }
      lazy val cedeUntilStarted: IO[Unit] =
        IO(started).ifM(IO.unit, IO.cede >> cedeUntilStarted)

      val test = for {
        f <- (markStarted *> IO.never).onCancel(IO.never).start
        _ <- cedeUntilStarted
        _ <- IO.race(f.cancel, f.cancel)
      } yield ()

      test should nonTerminate
    }
```
I wonder if we should just use `Deferred` for asynchronous blocking

2020-07-26 02:59 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +                // TODO: ELSE?
There may a race condition here similar to what we had in `AsyncK`. In particular, if between the time we call `resume` and check `isCancelled`, the runloop is suspended while cancelled is set to true then we would be blocked.

I think it might not be an issue though, but here's my line of thinking. If `loop` can't `resume` the runloop, that means someone else owns the runloop. If the fiber gets cancelled between `resume()` and `isCancelled()`, then there are two cases:
1. Someone that isn't the canceller owns the runloop. If they happen to suspend, they will also check for cancellation via `suspendAndCheckCancellation`
2. Nobody owns the runloop, so the canceller acquires it, so they can run finalizers.

2020-07-26 04:58 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +                // TODO: ELSE?
Yeah, I'm pretty convinced that this is a non-issue. If `loop` doesn't have the runloop to begin with and it sees cancellation, it doesn't have to do anything because somebody else will probably

2020-07-26 05:18 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +          runLoop(failed(result, 0), 0)
I'm not sure I follow that logic… The reference to `this` isn't volatile and is lifted into the lambda without barriers, so the thread which resumes the continuation will get access to `this.canceled` potentially without the value ever having been published to it, no?

2020-07-26 05:19 UTC, djspiewak commented on core/shared/src/test/scala/cats/effect/IOSpec.scala
> +    }
> I wonder if we should just use Deferred for asynchronous blocking

I'm okay with that. :-) I had been using the busy-wait mostly because it reduces the surface area of problems when trying to minimize stuff, but `Deferred` is far simpler to work with in tests.

2020-07-26 05:32 UTC, djspiewak requested changes

2020-07-26 05:32 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    suspended.set(false)
`false` or `true`? Fibers start out as `suspended = true`, and we're pretty consistent about "`suspended = true` implies someone has `runLoop` somewhere".

2020-07-26 05:33 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +          runLoop(failed(result, 0), 0)
Can't we rely on the memory barriers inside the `ExecutionContext`? All the state that is visible to the thread running `ec.execute` should be visible to the thread that runs the submitted task.

It also makes sense to do the read barrier before the finalization check.

2020-07-26 05:36 UTC, RaasAhsan commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    suspended.set(false)
This is merely a write memory barrier (the comment above it is wrong) to publish the write to `mask`, the value of `suspended` doesn't change at all. I want to avoid setting it back to `true` so that no one can acquire the runloop again (see point 4 in the PR description).

2020-07-26 05:42 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +    suspended.set(false)
Ah I see! Rather than setting `suspended` to `true` when you're done with finalization, you just let it stay `false` since `outcome` is already set, so it shouldn't, ultimately, matter.

2020-07-26 05:43 UTC, djspiewak commented on core/shared/src/main/scala/cats/effect/IOFiber.scala
> +          runLoop(failed(result, 0), 0)
Oh! Right. Transitivity. Okay yeah I think this works then. :-)

2020-07-26 05:44 UTC, djspiewak approved these changes
I really like the list of invariants in the OP. I think that we should move that into `IOFiber`'s scaladoc in a follow-up PR. It provides a more structured way of thinking about these cases.

2020-07-26 05:44 UTC, merged